### ISSUE TITLE
Resize with limits

### ISSUE THREAD

**Issue by nghiado** [tiberiuzuld/angular-gridster2#10]
@tiberiuzuld  It'd be great if you can provide this option as the original plugin does http://dsmorse.github.io/gridster.js/demos/resize-limits.html

**Comment by tiberiuzuld** [comment]
Hi @nghiado setting up min and max cols/rows for each widget could be implemented and to limit the resize depending on that.

**Comment by nghiado** [comment]
thanks @tiberiuzuld 
On the other note, could you also add option resizable per widget.
There are some cases when we don't want user to resize only some specific widgets.

**Comment by tiberiuzuld** [comment]
@nghiado ok will also add a `resize` option per widget which will override the grid resize option

**Comment by tiberiuzuld** [comment]
added the option to enable/disable resize/drag per widget and will override the grid option

**Comment by tiberiuzuld** [comment]
Released in v2.2.0 the resize limits for widgets.
