### ISSUE TITLE
Add a guard to GridsterGridComponent.calculateLayout() method when the gridster element size is 0

### ISSUE THREAD

**Issue by jjpedroza** [tiberiuzuld/angular-gridster2#101]
I have an application with routing enabled. One of the components contains a gridster instance inside a resizable container.

When the routed component starts rendering, the size of the div element containing the gridster is zero until some business logic ocurrs.

When the DOM element containing the gridster is zero, an exception is thrown in GridsterGridComponent. 

![image](https://user-images.githubusercontent.com/17257131/29096938-d00ba1ac-7c5c-11e7-8869-0f1431b59934.png)

This is happening in the following lines:

`this.columns.length = Math.max(this.gridster.columns, Math.floor(this.gridster.curWidth / this.gridster.curColWidth));`
`this.rows.length = Math.max(this.gridster.rows, Math.floor(this.gridster.curHeight / this.gridster.curRowHeight));`

I think it'll be a good idea to add a guard to the GridsterGridComponent.updateGrid() when the element is zero sized (can return 0 as the calculated size if curColWidth is 0, or if curRowHeight is 0)
Somehing like this:
`this.columns.length = this.gridster.curColWidth > 0 
   ? Math.max(this.gridster.columns, Math.floor(this.gridster.curWidth / this.gridster.curColWidth)) 
   : 0;`

`this.rows.length = this.gridster.curRowHeight > 0 
   ? Math.max(this.gridster.rows, Math.floor(this.gridster.curHeight / this.gridster.curRowHeight))
   : 0;`

I created a sample application that reproduces the issue.
[gridster-test.zip](https://github.com/tiberiuzuld/angular-gridster2/files/1209699/gridster-test.zip)

**Comment by tiberiuzuld** [comment]
Hi @jjpedroza ,
Will try to have it fixed today.
Thanks

**Comment by tiberiuzuld** [comment]
Hi @jjpedroza ,
Fixed in v3.11.2

Thanks,

**Comment by jjpedroza** [comment]
Thanks @tiberiuzuld !
