### ISSUE TITLE
Question: Possible to change GridsterItemComponent Size externally?

### ISSUE THREAD

**Issue by bradtaniguchi** [tiberiuzuld/angular-gridster2#103]
Hello,

I was wondering is it **possible** in some way or form to change the rows or columns of the GridsterItem **manually**. For example, I could hit a button and change the number of rows/columns the component takes up within the grid. 

I have content that requires certain aspect ratios, and I add/subtract different amounts to protect the ratio, as such I would not allow the user to resize the component using the edges. (As in doing so would allow the user to create a square, for rectangular content)

Currently if you change the Cols, Rows of the GridsterItem's, the **values** are changed, but the component does not resize. If you move the GridsterItemComponent in the grid, the changed values revert back to the size of the GridsterItemComponent beforehand. 

Is there a "reload" or "refresh" function to call on the GridsterComponent to reinitialize all the components sizes? Or is there a cleaner way to update the GridsterItemComponent's size, without having the user drag the corners/sides?

Thank you

**Comment by tiberiuzuld** [comment]
Hi @bradtaniguchi ,
Try to call `this.options.api.optionsChanged();` after you changed the rows/cols of items

Let me know if this works for you.
Thanks,

**Comment by bradtaniguchi** [comment]
Thanks @tiberiuzuld,
Apparently I did not call the `optionsChanged();` function correctly. I was passing the gridsterComponent from the view, and trying to access its `.options.api`, which was correct. 

Using the `this.options.api.optionsChanged()` worked perfectly, thank you!
Keep up the great work!
