### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by galleonms** [tiberiuzuld/angular-gridster2#104]
Hi @tiberiuzuld ,

I have a question, how can I use this, in a asp.net core aplication to make one tab of a website a dashboard

I'm new into Angular and asp.net core and have no clue. I looked over the code and try to implement it into  my project but with no luck

Thanks.

**Comment by tiberiuzuld** [comment]
Hi @galleonms ,

I have no clue about asp.net core application :)

Look over [angular-cli](https://github.com/angular/angular-cli) integration with asp.net. 

This is my best guess on how to do it.
