### ISSUE TITLE
Shifting Items: ERROR RangeError: Maximum call stack

### ISSUE THREAD

**Issue by Konstruktour** [tiberiuzuld/angular-gridster2#105]
While shifting items around, an error occurs in the console - see seetings and behaviour @ attached gif. 

![gridster](https://user-images.githubusercontent.com/7323845/29399626-3c7f9fc2-832a-11e7-9474-a8bc961cf912.gif)

**Comment by tiberiuzuld** [comment]
Hi @Konstruktour ,
Will try to fix it as soon as possible.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @Konstruktour ,
Fixed in v3.11.4

Thanks,
