### ISSUE TITLE
How to set fixed layout for gridster?

### ISSUE THREAD

**Issue by Sandeepvedam** [tiberiuzuld/angular-gridster2#108]
Hi,

First, Thanks for very good plugin. :)

When i am dragging grid in the layout, it is dragging as much as to the bottom and right side. how to stop that and how can i drag widget only in fixed layout?

Thanks

**Comment by tiberiuzuld** [comment]
Hi @Sandeepvedam ,
You need to limit the grid `maxRows` and `maxCols`. Only then the resize and drag will stop.

Let me know if this answers your question.

Thanks

**Comment by Sandeepvedam** [comment]
Yes. Thank you very much. 

one more question please. How can i increase size of the placeholder in gridster?

**Comment by tiberiuzuld** [comment]
Hi @Sandeepvedam ,
What do you mean by placeholder(grid) ? You mean the placeholder when you resize and drag ? 
You can't that size is what gridster-item size will have when the drag event is ended.

Thanks

**Comment by Sandeepvedam** [comment]
Hi,

![image](https://user-images.githubusercontent.com/16398833/29619251-44636224-8838-11e7-8136-0673397f84f1.png)

I marked placeholder with red color. Is it possible to increase to default size?

**Comment by tiberiuzuld** [comment]
HI @Sandeepvedam ,
The size of a row or column is set depending of `gridType`.
If you set `gridType`: `fixed`
You have options `fixedRowHeight` and `fixedColWidth`.
Look at the demo settings sidenav. With all the options available for the grid.

Thanks,
