### ISSUE TITLE
Problem with emptyCellClickCallback and Firefox

### ISSUE THREAD

**Issue by josevi86** [tiberiuzuld/angular-gridster2#109]
Hi! First of all, great work! This plugin suits me perfect.

I have a little problem when i use emptyCellClickCallback with Firefox. In Chrome works fine, but with Firefox a ERROR ReferenceError: event is not defined is fired.

I have checked this at you demo (https://tiberiuzuld.github.io/angular-gridster2/angular/) and the same error is happening. When I try to click in a empty space for creating a widget, it seems that "event" has been not initializated. Searching inside the code, the problem is at gridsterEmptyCell.service.js (line 44). Here item is not defined:

![imagen](https://user-images.githubusercontent.com/9534310/29656906-32251ade-88b6-11e7-9491-0224e1339722.png)

Trace:

![imagen](https://user-images.githubusercontent.com/9534310/29656951-63a45f20-88b6-11e7-88cd-0c34a5240509.png)

Is there any workaround to avoid this? I dont need the event return at the callback, is enough with the returned gridster item.

I hope explained myself well.
Thanks in advance

**Comment by tiberiuzuld** [comment]
Hi @josevi86 ,

Will have a fix shortly.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @josevi86 ,
Fixed in v3.11.6

Thanks
