### ISSUE TITLE
Empty cell right click event context menu for new widget type selection

### ISSUE THREAD

**Issue by josevi86** [tiberiuzuld/angular-gridster2#110]
Hi!

Its possible to handle the click event with the right mouse button?

Thanks again!

**Comment by tiberiuzuld** [comment]
HI @josevi86 ,
Which click event ? and why right mouse ? 
Do you mean empty cell click to add ? 

Thanks

**Comment by josevi86** [comment]
Yes, a mean the emptyCellClickCallback but called by the right button click.

I would like to show a contextual menu when click with the right button at a widget.

Thanks!

**Comment by tiberiuzuld** [comment]
Hi @josevi86 ,
Do you want to show a context menu when right click on a widget or a empty cell ?
If is on a widget then you need to implement that yourself in your widget.

If is on a empty cell then I can add that feature, 
But you want a context menu the user to choose a type of widget to add ?
Then the empty cell right click will not add a new widget directly. 

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @josevi86 ,
Ok will implement this feature as soon as possible(most probably this week).

Thanks

**Comment by josevi86** [comment]
Many thanks!!

**Comment by tiberiuzuld** [comment]
Hi @josevi86 ,

Added in v3.12.0.

Thanks

**Comment by josevi86** [comment]
Thanks! You are amazing!
