### ISSUE TITLE
cannot call service inside gridster item callback functions (itemResize,etc)

### ISSUE THREAD

**Issue by jtushar53** [tiberiuzuld/angular-gridster2#112]
I am calling a service method from itemResize event but it is not working on aot build.
Trying to execute a method which updates the updated item information.

Getting below error in aot build, dashboardItemService is the service that we created

![image](https://user-images.githubusercontent.com/5780117/29674461-e5b82696-890f-11e7-9c85-694d12b14eb9.png)

**Comment by tiberiuzuld** [comment]
If You call from this is wrong this inside the callback is the gridster. You need to make an outside variable for this or to bind this on callback.

**Comment by WhatzzUp** [comment]
@tiberiuzuld is right, i solved it with an Output()  event syntax and it work like a charm! 🎉 

Another question:
Is it possible to display the hover drop area with an dashed frame? Like drag n drop a gridsterItem?

**Comment by tiberiuzuld** [comment]
Hi @WhatzzUp ,
Yes, but tried that when I implement drag and drop and was a bit laggy and didn't liked that.
Will try to implement it again maybe will find a better way.

Thanks

**Comment by WhatzzUp** [comment]
Hai @tiberiuzuld yeah, i tried it yesterday and it was ... very ... very laggy.
Nevertheless good job! angular-gridster2 works like a charm!

**Comment by jtushar53** [comment]
made it work using Output,

Thanks @tiberiuzuld for angular-gridster2

and thanks @WhatzzUp for pointing out @Output

**Comment by ndunas** [comment]
Could someone please post the working solution using Output?

**Comment by srivathsah** [comment]
@ndunas  and for others to refer to:

`private static changed: Subject<string> = new Subject<string>(); `

Have the above in your component or service and call next on it, then subscribe to the subject to do what you want

**Comment by the80** [comment]
@jtushar53, @srivathsah, @tiberiuzuld.  can you guys help me to understand this solution?

i declared two @Outputs:

![image](https://user-images.githubusercontent.com/35235378/34687077-d01e66ce-f494-11e7-95db-765fc0f37fc8.png)

then i set it in the template:

![image](https://user-images.githubusercontent.com/35235378/34687374-aa9a9138-f495-11e7-9c47-888e47e5856c.png)

create the funtions:
![image](https://user-images.githubusercontent.com/35235378/34687412-c84f1d8e-f495-11e7-9bc8-7fd7e54c821b.png)

and wait for it...... nothing happens! :/

**Comment by tiberiuzuld** [comment]
Hi @the80 ,
I removed the `@Output` options from gridster-item in 4.3 forgot to remove them from Readme.md
Sorry about that but there where some memory leaks with them.

You need to use the options callbacks `itemChangeCallback`, `itemResizeCallback`.

Let me know if this will be ok for you.

Thanks

**Comment by the80** [comment]
Thanks for the information @tiberiuzuld 

But I m facing the same problem as @jtushar53  posted:

![image](https://user-images.githubusercontent.com/35235378/34716685-ba630d66-f517-11e7-8858-db5622d0847d.png)

my function:
![image](https://user-images.githubusercontent.com/35235378/34716704-cba8be40-f517-11e7-95c0-8a11718b19e0.png)


Anything i use is undefined, as you said above, anything inside options is gridster...
![image](https://user-images.githubusercontent.com/35235378/34716801-15796e0c-f518-11e7-9e56-225e2f5feba9.png)

**Comment by tiberiuzuld** [comment]
Try `this.changed.bind(this)`

**Comment by the80** [comment]
@tiberiuzuld it works!

Thank you very much.

**Comment by rajesh4186** [comment]
this.changed.bind(this) shows same error , Where can i use this syntax?

**Comment by nickolind** [comment]
@rajesh4186 use the binding function inside the component, where you've defined gridster:

```
export class MyComponent {
  private itemChange (item: GridsterItem, itemComponent: GridsterItemComponentInterface) {
    console.info('itemChanged say hello: ', this.myComponentVar );
  };

  gridsterOptions: GridsterConfig;
  gridsterGrid: Array<GridsterItem> = [];

  myComponentVar = 'Hello';

  constructor() {
   this.itemChange = this.itemChange.bind(this);
  }

 // ... rest of the component ...
}
```

will result in console: 
`itemChanged say hello: Hello`
