### ISSUE TITLE
Startup issues in the demo with IE11 and Edge

### ISSUE THREAD

**Issue by rodro75** [tiberiuzuld/angular-gridster2#113]
Hi,
I was looking at the demo (AngularJS version) and it seems that it correctly initializes itself only on Chrome and Firefox. With IE and Edge the initial layout is screwed up and you have to repeatedly trigger a resize or a configuration change to get to the correct final layout. After that everything seems to work.

![immagine](https://user-images.githubusercontent.com/10122909/29712067-4757bc8a-8998-11e7-84df-e1713a447206.png)

![immagine](https://user-images.githubusercontent.com/10122909/29712096-6b9f355a-8998-11e7-95f6-8468bd1b01e6.png)

![immagine](https://user-images.githubusercontent.com/10122909/29712138-a77bf220-8998-11e7-880f-db20d23dc2be.png)

**Comment by tiberiuzuld** [comment]
Hi @rodro75 ,

Will have a fix as soon as possible.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @rodro75 ,

Fixed in v1.11.6.

Thanks
