### ISSUE TITLE
Gridster-Item resize in Material 2 Tabs

### ISSUE THREAD

**Issue by WhatzzUp** [tiberiuzuld/angular-gridster2#114]
Hallo guys,

we are using "angular-gridster2" combined with angular material 2 tabs and get a strange behavior.
Every tab has his own gridster with items to implement a multiple dashboard system for our users.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23344282/29722267-660da018-89c0-11e7-9198-cdfd0988f64e.gif)

If we change from tab 1 to tab 2 the gridster items are at one position, only after resize the window, gridster items get to the right position.

Any idea where and why this behavior comes?

Cheers

Chris

**Comment by tiberiuzuld** [comment]
Hi @WhatzzUp ,
The issue is from size transitions of content of tabs.
Try to call `options.api.resize()` for the grid to resize when animation is done.

Let me know if this helps fix your issue.

Thanks

**Comment by WhatzzUp** [comment]
Hy @tiberiuzuld 

thx for the fast reply. ☮️ 


Can you explain what do you mean with "size transition"?
Tabs content only have a "transform: translate3d(100%, 0px, 0px);" not a size (width or height) transition. 

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/23344282/29723968-f7bf71ac-89c6-11e7-8e6c-80b440e7a557.gif)

I tried your idea but without success.

**Comment by WhatzzUp** [comment]
Could be the error that I use for all grids the same options?

```javascript
<md-tab-group (selectChange)="changedDashboard($event)">
    <md-tab *ngFor="let dashboard of dashboardService.allUserDashboards">
      <unicorn-gridster [options]="options">
        <unicorn-gridster-item [item]="item" *ngFor="let item of dashboard?.userWidget">
          <unicorn-widget-standard *ngIf="item.widget === 'project-standard'" [label]="item.labelTrans|translate"
                                   [backgroundColor]="item.backgroundColor" [icon]="item.icon"
                                   [iconColor]="item.iconColor"></unicorn-widget-standard>
        </unicorn-gridster-item>
      </unicorn-gridster>
    </md-tab>
  </md-tab-group>
```

```javascript
  private options: GridsterConfig = {
    compactType: 'compactUp',
    gridType: 'scrollVertical',
    maxCols: 4,
    minCols: 4,
    itemChangeCallback: DashboardComponent.itemChange,
    itemResizeCallback: DashboardComponent.itemResize,
    draggable: {
      enabled: false, // enable/disable draggable items

    },
    resizable: {
      enabled: false, // enable/disable resizable items
    },
  };
```

**Comment by WhatzzUp** [comment]
@tiberiuzuld  solved the issue.

The problem was to use the same options for every gridster ... my bad ... 
Now i call your:
`this.options.api.resize();`

by every tab change and it work like a charm 🎉 
@tiberiuzuld thx 4 your help!

**Comment by rizwana411** [comment]
Hi @tiberiuzuld ,
   Can i load component as grid item in the gridster dynamically....? if yes plz give me example

**Comment by tiberiuzuld** [comment]
Hi @rizwana411,
Please open your own issue. 
Your questions are not related to this closed issue.
Please have a good description of what your issue is and what you want to achieve.
Please read Readme.md beforehand.
Please make sure is a library issue and not an angular or something in your app.

Thanks,

**Comment by hbthanki** [comment]
> @tiberiuzuld I solved the issue.
> 
> The problem was to use the same options for every gridster ... my bad ...
> Now i call your:
> 
> `this.options.api.resize();`
> 
> by every tab change and it work like a charm 🎉
> @tiberiuzuld thx 4 your help!

What do you mean by "same options for every gridster". I have three tabs and I use same gridster using ng-template.
My problem is the order of the gridster items are not where I am expecting.

**Comment by Abattista96** [comment]
> @tiberiuzuld I solved the issue.
> 
> The problem was to use the same options for every gridster ... my bad ...
> Now i call your:
> 
> `this.options.api.resize();`
> 
> by every tab change and it work like a charm 🎉
> @tiberiuzuld thx 4 your help!


@WhatzzUp Hi
I have similar situation, can you explain how you resolved the problem?
I can't understand what you mean with _same options for every gridster_

Thanks
