### ISSUE TITLE
 GridsterItem auto positioning even if x and y properties are assigned

### ISSUE THREAD

**Issue by StevenLiSiwei** [tiberiuzuld/angular-gridster2#115]
Dear Author,

We follows the example on the readme.md, the only difference is we use Any instead of GridsterItem to declare the array type for dashboard, but when initializing data from server, it always reset x and y values.
![](https://image.ibb.co/d2XGu5/table_position_issue.png)

**Comment by tiberiuzuld** [comment]
Hi @StevenLiSiwei ,
Do you have rows and cols on `item` ?
`x` and `y` values seem to be as given by you.

`$item` is an object used internal.
`item` is the object given by the user.

`x` and `y` on item seems to be 0

Thanks

**Comment by StevenLiSiwei** [comment]
Hi @tiberiuzuld ,
Thank you for your reply.

the first item is at location x:0, y:0, I changed first item to x:3 y:3, it is still the same. but after rendering, the items can be positioned correctly, only occurs at first data populating.

![](https://image.ibb.co/ekUPxQ/positioning_issue.png)

Thanks
Steven

**Comment by tiberiuzuld** [comment]
HI @StevenLiSiwei ,
Do you initialize the grid and the items before getting the items config from server ? 

Thanks

**Comment by StevenLiSiwei** [comment]
Hi @tiberiuzuld ,

The flow is Gridster Config is initialized first once ngOnInit triggered before Server Data result returned, but I've swapped the flow but it doesn't work either.

![](https://image.ibb.co/c2AxHQ/Data.png)

Thanks
Steven

**Comment by tiberiuzuld** [comment]
Hi @StevenLiSiwei ,

From your screenshots I cannot see the cols and rows of the items. 
So the issue maybe because of the cols/rows are saved incorrectly.

What Gridster Config you have ? 
The limits of the gridster are small `maxCols` and `maxRows` ? 

Can you reproduce the issue on the demo example ?

Thanks

**Comment by StevenLiSiwei** [comment]
Hi @tiberiuzuld 

You are right ! Massive thanks to you !
My server doesn't not supply cols and rows, which causes gridster to do auto positioning

Best Regards
Steven

**Comment by tiberiuzuld** [comment]
Hi @StevenLiSiwei ,

Great :) , good to hear the issue is not from library 👍 

Thanks

**Comment by StevenLiSiwei** [comment]
it is not library issue. thank you
