### ISSUE TITLE
Is there a way to direct the behavior of push?

### ISSUE THREAD

**Issue by loralyn** [tiberiuzuld/angular-gridster2#116]
I would like to have the gridster items push south always.  Is there a way to access that behavior?

**Comment by tiberiuzuld** [comment]
Hi @loralyn ,

There is no way right now to configure push direction.

A bit complicated to make it configurable, but will think about it.
Will try to add it as soon as possible.

Thanks

**Comment by loralyn** [comment]
Thank you!

**Comment by tiberiuzuld** [comment]
Hi @loralyn ,

Added in v3.14.0

Thanks,
