### ISSUE TITLE
Is there any event which tells the dashboard is rendered?

### ISSUE THREAD

**Issue by RavalikaP** [tiberiuzuld/angular-gridster2#117]
I want to render dynamic component inside each widget for that rendering I need height and width of the widget.

**Comment by tiberiuzuld** [comment]
Hi @RavalikaP ,
You have https://github.com/tiberiuzuld/angular-gridster2#gridster-item-options `initCallback` for each item.
Events for each item https://github.com/tiberiuzuld/angular-gridster2#events
And global callbacks https://github.com/tiberiuzuld/angular-gridster2#default-grid-options in gridster options.

Thanks

**Comment by RavalikaP** [comment]
Hi @tiberiuzuld,

initCallback is called before the dashboard is rendered but I need a event which will trigger after the whole dashboard renders

Thanks

**Comment by tiberiuzuld** [comment]
Hi @RavalikaP ,
I listed more options than `initCallback` in readme.md
Probably you need `itemResizeCallback`.

Thanks
