### ISSUE TITLE
Swap on drag, push on resize

### ISSUE THREAD

**Issue by FrozenGenis** [tiberiuzuld/angular-gridster2#119]
Hello,

Is it possible to configure Gridster to behave as follows:
- Swap on drag (swap: true)
- No push on drag (pushItems: false), but push on resize only

Cheers

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,

Right now is not possible. 
Will need to add a new option.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,

Added in v3.14.0

Thanks,
