### ISSUE TITLE
Cannot scroll vertically for long dashboard under edit mode (Drag & drop and resize) on mobile

### ISSUE THREAD

**Issue by nvphuc1989** [tiberiuzuld/angular-gridster2#120]
Hi All,

I'm developing a dashboard has many widget and user need to scroll vertically to reach the items in the bottom in mobile view. The issue is every time user sweep to scroll, the event makes widgets resize or change position.
Please advise if the gridster library can be configured to resize/drag&drop with long touch only (not sweep to scroll)? Or any other solutions. Thanks.

![screenshot_98](https://user-images.githubusercontent.com/11606840/30130305-eb516ec4-9372-11e7-9849-315f9fcb19e1.png)

**Comment by tiberiuzuld** [comment]
Hi @nvphuc1989 ,

Right now any touch event is handled as a normal mousedown event.

Will have to improve on touch events as soon as possible.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @nvphuc1989 .
Fixed in 3.13.0

Thanks,

**Comment by nvphuc1989** [comment]
Thanks teberiuzuld,

I'm still using the 1.x branch (AngularJs 1). Could you please apply the fix to that branch?

**Comment by tiberiuzuld** [comment]
Hi @nvphuc1989 ,
Ok will try to migrate the changes to 1.x branch.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @nvphuc1989 ,
Migrated changes in v1.15.0.
You can configure the delay for start drag/resize `delayStart` option.
By default is set to 0.
Let me know if it is ok for you.

Thanks,

**Comment by nvphuc1989** [comment]
Perfect @tiberiuzuld 
Thank you!

**Comment by dharmarajan** [comment]
I'm also facing the same problem. Is there any clue?
