### ISSUE TITLE
Handle different number of columns in desktop and mobile

### ISSUE THREAD

**Issue by nvphuc1989** [tiberiuzuld/angular-gridster2#121]
Hi All,

I'm designing a dashboard which support different screens size of devices using angular-gridsters.
On desktop I set the option **minCols = maxCols = 8** and for mobile, dynamically change, the number of columns reduced: **minCols = maxCols = 2**.
I arrange 8 items horizontally in the dashboard in desktop (1 item/column) then I view the dashboard in mobile.
I expect 2 items in each row for mobile but the layout still the same with desktop (still 8 items/row with the items's size is smaller).

Please advise what is the option to make 2 items/row arranged automatically.
Please note all items under resize and drag mode.

**Comment by tiberiuzuld** [comment]
HI @nvphuc1989 ,

The items positions and size are meant to be saved in a DB not to be changed on different sizes of screen.
The main concept here is to have the same layout in any screen size.
For really small screens you have the option `mobileBreakpoint` so you can have items one after the other.

But in that mode you cannot edit your dashboard.

One option is to add a option to have 2 mobile breakpoints, one with 2 columns and one with one column like now.

Let me know if this will help your use case.

Thanks,

**Comment by kamilbrk** [comment]
I have a similar project going on, actually.

Grid is set to have a fixed number of columns (`minCols` & `maxCols`), e.g. `20` by default. We have some items drawn on the grid, some of them are on the far right. All good.

Now, we change the number of columns during the runtime, from `20` to `10` (and call the `.optionsChanged()` method). The grid setting itself is updated fine, but all the items that were on the grid are still in the same position. You can try to drag them around which does only work when you drag it across to the left - within the `10` column limit.

I would like to ask what can we do force all items to move within column boundaries. I can see some `.autoPositionItem()` stuff but I am yet to play around with all that.

Right now a nasty workaround is to completely get rid of and render the entire grid again.

See the screencast for the explanation (47s, YouTube): 
[![angular-gridster2 dynamic columns](http://img.youtube.com/vi/dj_6Zh0OypM/0.jpg)](http://www.youtube.com/watch?v=dj_6Zh0OypM "angular-gridster2 dynamic columns")

**Comment by kamilbrk** [comment]
Thanks a lot for the tip! I realise that our use case is far different from the original assumptions of the library, it is entirely on us to attempt to make it work, hence my question was just to give us an idea where to start. Cheers! :thumbsup:

**Comment by tiberiuzuld** [comment]
Hi @kamilbrk and @nvphuc1989 ,
If you want to have grids with flexible size maybe try [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) .

Thanks,
