### ISSUE TITLE
Working version for angular 2

### ISSUE THREAD

**Issue by michael-gasser** [tiberiuzuld/angular-gridster2#122]
Hi,
I could not found any working version for angular 2.
In the README is written that branch 2.4.x is for angular 2. But versions 2.4.1-3 are not working and in version 2.4.4 the GridsterResizableService has a bug. (`e.srcElement is undefined. srcElement -> currentTarget`)
And after 2.4.4 all versions require angular 4. 

Would it be possible to release a new version for angular 2 were the resize bug is fixed?

**Comment by tiberiuzuld** [comment]
Hi @michael-gasser ,

The version 2.4.x for angular 2 was not maintained lately since I hoped people migrated to version 4 already.

Let me know if you still want to use this version and will make a backport of fixes to it. 

Thanks,

**Comment by michael-gasser** [comment]
That would be great.
In our project we have some legacy code and therefore we cannot upgrade fast.

**Comment by tiberiuzuld** [comment]
Hi @michael-gasser ,

Made the migration from v3.14.0 to v2.4.11 and should work with angular2.
Didn't test it to much, the demo seems  to work.
Let me know if works for you.

Thanks,
