### ISSUE TITLE
Any way to make removed widgets shift left instead of up?

### ISSUE THREAD

**Issue by williamzhao87** [tiberiuzuld/angular-gridster2#123]
When I delete a widget from gridster, all the widgets in the same column below it shift up instead of widgets to the right shifting left.  Is there any way to change this behaviour?  

Or at least, can I make it redraw so that the order of widgets (from left to right) is correct after deletion?

**Comment by tiberiuzuld** [comment]
Hi @williamzhao87 ,
Yes `compactType: 'none', // compact items: 'none' | 'compactUp' | 'compactLeft' | 'compactUp&Left' | 'compactLeft&Up'`

Try those options.

Thanks,
