### ISSUE TITLE
Is there any way to drag or swap the items in mobile view.

### ISSUE THREAD

**Issue by RaviSambaraju** [tiberiuzuld/angular-gridster2#124]
Hi,

I configured my mobileBreakpoint as ==>**{ mobileBreakpoint:350 }**, 
If my screen is not wider than this, It removes the grid layout and stack the items one by one.
At this time is there any way to drag or swap items in mobile view.

Thanks in Advance.

**Comment by tiberiuzuld** [comment]
Hi @RaviSambaraju ,

No is not possible in mobile mode to edit the grid. 
Size and position of items is meant to be saved in DB. In mobile mode the items in grid have total different positions and sizes.

Thanks,
