### ISSUE TITLE
[Question] Divide the grid in to x number of cols in any screen size ?

### ISSUE THREAD

**Issue by mcshiva** [tiberiuzuld/angular-gridster2#126]
Is there any configuration available for setting grid to x rows and y columns, so that screen width divide by y and height divide by x. 

Currently I have used  gridType:'fixed', fixedColWidth: 200, fixedRowHeight: 200.
The problem using this is if I add 3 widgets next to next in bigger screen. on smaller screen getting horizontal scroll bar. instead I wanted the grid  to adjust cell width and height as per screen width and height. in-turn widgets gets adjusted automatically without scroll.

**Comment by celloman** [comment]
I think you can use the gridType: 'fit' and give the grid the same width and height as your screen

**Comment by tiberiuzuld** [comment]
Hi @mcshiva ,

Yes @celloman is right you may want to use `gridType: 'fit'` for your use case.

Thanks,
