### ISSUE TITLE
Scroll screen when dragging

### ISSUE THREAD

**Issue by celloman** [tiberiuzuld/angular-gridster2#129]
The grid scrolls when dragging a tile past existing rows/columns (which is great), but would it be possible to have an option to have the browser window scroll when dragging near the bottom/top of the screen on a long layout?

I am resizing my grid's height based on the number of rows (4 fixed columns), so I never have to deal with the grid having a scrollbar, but it would be pretty slick if there was a setting for the window to scroll vertically while moving an item up/down.

I was able to implement this as follows, do you see any problems with this approach? The one thing that concerns me with  this approach is that I am altering the diffTop of the dragged element to cause the element to track with the mouse (I save a reference to the dragged element with the options drag.start callback and remove with the drag.stop callback). This seems to work fine, but I don't know enough about gridster's internals to know if changing the diffTop could screw anything else up.

```
@HostListener('mousemove', ['$event'])
  autoScroll(event: MouseEvent) {
    if (this.gridster && this.gridster.dragInProgress) {
      const down = (window.innerHeight - event.clientY) < 100;
      const up = event.clientY < 100;
      if (up || down) {
        const baseIncrement = 20;
        const increment = (up ? -baseIncrement : baseIncrement);
        document.scrollingElement.scrollTop = document.scrollingElement.scrollTop + increment;
        this.draggingItem.drag.diffTop -= increment; // compensate element position for scroll
      }
    }
  }

**Comment by tiberiuzuld** [comment]
Hi @celloman ,

If in your modification don't see any immediate issues when dragging then is working fine.
The `diffTop` is used so if the gridster is in a scrolled container the drag will be moved/drop correctly.

The problem with having the grid making the scroll of a parent container as is when the grid has scroll is that the user can have multiple scrollable parents and not necessary the window. 

Maybe by using the browser api [scrollIntoView](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) will simplify things. Need to try it to see.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @celloman ,
Looked into adding scrollIntoView , current implementation in browser is not enough for what is needed.
Is needed to scroll only if item is not completely into view, and scroll only enough to get into view.
Browsers currently don't support that.

So will remain like is now.

Thanks,
