### ISSUE TITLE
some widgets are not showing up if given settings are not correct

### ISSUE THREAD

**Issue by nghiado** [tiberiuzuld/angular-gridster2#13]
When playing with the lib, if I put wrong/duplicated values for { cols, rows, x, y} to the list of widgets, they just disappear and no error thrown.
Expected behavior is when there are collisions in the settings, we should throw warning/error in the console to let user know which one is not correct if possible

**Comment by tiberiuzuld** [comment]
Hi @nghiado ,
In v1.x had the $log.warn but since angular2 doesn't has a default logger I no longer added it.
Will add a console.warn in.

**Comment by tiberiuzuld** [comment]
Fixed in v2.0.8
