### ISSUE TITLE
Grid collision checking not always working properly after removing items

### ISSUE THREAD

**Issue by celloman** [tiberiuzuld/angular-gridster2#130]
After removing tiles (using the gridster.removeItem function in conjunction with removing the item from the array that is bound to the template *ngFor of gridster-items), sometimes gridster seems to still have 'phantom' tiles that prevent the grid from compacting properly, as well as sometimes allows components to end up stacked on top of each other (i.e. the collision check fails). I would be glad to talk this through and try to diagnose the issue, as everything else works great!

**Comment by tiberiuzuld** [comment]
Hi @celloman ,
To remove and item you only need to remove it from you array no need to call gridster methods.
Thats why you get ghosting I think.

Will look again over the code anyway to check if is possible for the item to remain in the internal array.

Thanks,

**Comment by celloman** [comment]
Ok, I'll give it a shot. Thanks!

**Comment by celloman** [comment]
On initial testing of this, the ghosting behavior appears to be gone, but I will keep an eye out for it in the future and let you know if I find any edge cases. Great work on this by the way! =)

**Comment by tiberiuzuld** [comment]
Hi @celloman ,

With the current version only a setTimeout will help you or something similar from angular.

Will try to add a `itemRemovedCallback` as soon as possible.

Thanks,

**Comment by celloman** [comment]
Ok, I'll try that for now. I agree that an itemRemovedCallback would make sense as a counterpart to the itemInitCallback. Thanks again!

**Comment by tiberiuzuld** [comment]
Hi @celloman ,

Added in 3.13.0

Thanks,
