### ISSUE TITLE
Can I get the latest version to support for angular 1.4?

### ISSUE THREAD

**Issue by kvsskk** [tiberiuzuld/angular-gridster2#132]
Hi, I would really like to work on this angular gridster 2,but there is no support for angular1.4 version, can you release any version that support angular1.4, help is greatly appreciated

**Comment by tiberiuzuld** [comment]
Hi @kvsskk ,
The last version which works with angular 1.4 is `v1.3.0`.

Sorry but will not do any work to migrate all the new features for versions older than angular 1.5

If you want to make the migration/changes to that version will accept any PRs and publish the versions in v1.3.x

Thanks,

**Comment by kvsskk** [comment]
Thanks @tiberiuzuld for responding quickly. I am unable to find `v1.3.0` on the `angular-gridster**2**` repository. 
Also, the latest on `angular-gridster` repository is `0.13.x`. Which one are you referring to? Also to be specific, **we need support for `angular 1.4.8`**. Which version (that I can download) do you advise, please?

If you have a general list of "new features" in `angular-gridster2` - after upgrade to `angular >=1.5`, that will be of great help. We have specifically tried successfully gridlines, pinning the parts, fixing the layout to the window horizontally, resizable-draggable etc. in the `angular-gridster2`, BUT the requirement is to use `angular 1.4.8`. Any link to such a list will also be helpful. 

Many thanks!

**Comment by kvsskk** [comment]
Part of my question is answered. I found the v1.3.0 release here: [v1.3.0](https://github.com/tiberiuzuld/angular-gridster2/releases/tag/v1.3.0). 

Sorry, but the features that we need, I am not sure how to implement backwards?

**Comment by kvsskk** [comment]
Well, OK. I got the list of breaking changes and updates here: [changes from 1.4.0 (backwards migrated from 3.4.0)](https://github.com/tiberiuzuld/angular-gridster2/releases/tag/v1.4.0).
Supports angular v1.5 components but recommends angular js v1.6.
[updated readme for 1.x](https://github.com/tiberiuzuld/angular-gridster2/blob/1.x/README.md)
[the backporting issue and conversation](https://github.com/tiberiuzuld/angular-gridster2/issues/39)

**Comment by kvsskk** [comment]
Hi tiberiu,
Nice to hear back and im in a need of grid layout in angular gridster. Can
you please provide any of your gridster which supports grid layout along
with layout.
Regards

**Comment by tiberiuzuld** [comment]
HI @kvsskk ,
What to provide ?  This [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) ?

I cannot provide something totally different than what the library already supports.
