### ISSUE TITLE
Grid is not visible using angular 1.4

### ISSUE THREAD

**Issue by swarajm** [tiberiuzuld/angular-gridster2#133]
Following is the code that I have added in my existing controller
$scope.options = {
               gridType: 'fit',
               fixedColWidth: 250, // fixed col width for gridType: 'fixed'
               fixedRowHeight: 250, // fixed row height for gridType: 'fixed'
               itemChangeCallback: undefined,
               margin: 10,
               outerMargin: true,
               draggable: {
                 enabled: true,
                 stop: undefined
               },
               resizable: {
                 enabled: true,
                 stop: undefined
               }
             };
            
            $scope.options.dashboard = [
              {cols: 2, rows: 1, y: 0, x: 0},
              {cols: 2, rows: 2, y: 0, x: 2}
            ];
Below is the code that i am using in HTML Template

<gridster options="options">
                    <gridster-item item="item" ng-repeat="item in options.dashboard">
                    </gridster-item>
            </gridster>

Can you guys help me out ??

**Comment by tiberiuzuld** [comment]
Hi @swarajm ,
For angular 1.4 check this issue #132.

And make sure the grid parent has height.

Thanks,

**Comment by swarajm** [comment]
Stil not working :(... 
can you please provide me a fiddle that will be the great help for me

**Comment by tiberiuzuld** [comment]
Hi @swarajm ,
You can look at readme.md for the 1.3 [here](https://github.com/tiberiuzuld/angular-gridster2/tree/v1.3.0)

You can install like this: `npm install --save angular-gridster2@1.3.0`. 

Follow the steps from readme.md and will work.

Thanks,
