### ISSUE TITLE
Remove/disable extra half column?

### ISSUE THREAD

**Issue by casni14** [tiberiuzuld/angular-gridster2#134]
I'm trying to make a Gridster view with only one column, where only vertical dragging is possible. To do this I sat maxCols to 1. But somehow, when I try to drag items, it seems like there is an extra half column to the right which messes up the view (as can be seen in the picture below).    
![gridsterdragissue](https://user-images.githubusercontent.com/12065417/31218940-1ad2d2c8-a9bc-11e7-984e-ccd6bf286671.png)
Is there some way to disable this behaviour, or am I doing something wrong?
Thanks

**Comment by tiberiuzuld** [comment]
Hi @casni14 ,
The drag behavior detects next cell movement when the element exceeds half of column width.
Only way to disable this is to disable dragging.

This behavior is needed so the user gets best experience while dragging items around.

Thanks,

**Comment by casni14** [comment]
That's a shame. Gridster seemed to be the perfect library for my needs with resizeability and dragability. But I guess I gotta find another library which suits my needs.
Anyway, thanks for the quick response 👍

**Comment by casni14** [comment]
Is it the offsetLeft variable which produces this behaviour?  If not, can you point me to where in the source this is defined?

**Comment by tiberiuzuld** [comment]
Hi @casni14 ,
No is not that simple.
[Here](https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridsterDraggable.service.ts#L167) , probably if you change to `Math.ceil` will get you what you want. 
And possibly you also need to stop lateral scroll from gridsterScroll.

Will accept PR for adding that option to change the limit the drag.

Unfortunately I am a bit busy lately to work on this now.

Thanks,

**Comment by casni14** [comment]
Very nice @tiberiuzuld ! 
`Math.ceil`, worked.
I will look into making a PR

Thank you!
