### ISSUE TITLE
How to store coodinates of gridster item in database

### ISSUE THREAD

**Issue by swarajm** [tiberiuzuld/angular-gridster2#136]
How to store coodinates of gridster item in database and retrive and plot it

**Comment by tiberiuzuld** [comment]
Hi @swarajm ,
I am not sure how to answer this question.
You need to save `x,y, rows,cols` properties in your db.
On init you fetch all the items which have `x,y,rows, cols` and you give the array to the gridster.

I hope this answers your question.

Thanks,
