### ISSUE TITLE
3.14.0 - Can't find angular-gridster2 module

### ISSUE THREAD

**Issue by dec0y** [tiberiuzuld/angular-gridster2#137]
Testing out the new features but unable to get the project started. Looking into the node_modules folder the dist folder has a .tmp in side of it which is holding all the files. The package.json states it should go to dist/index.ts. 

Thank you!
![image](https://user-images.githubusercontent.com/495170/31311230-b082cd4a-ab75-11e7-8358-579551fef093.png)

**Comment by dec0y** [comment]
Moved it back to 3.12.0 and still see it. Might be a me thing, sorry for the troubles. Closing for now.

**Comment by kkeltner** [comment]
Just tried pulling down 3.14.0 to check out angular-gridster2 for first time and having similar problems.. seeing same structure as pointed by dec0y.  Pulled 3.11.0.. no .tmp inner directory and can import the module.

**Comment by tiberiuzuld** [comment]
Hi @dec0y , @kkeltner ,
Yes seems to be a problem with the build for npm.
Will try to fix it right a way and make a new version.
Till then I think you can import from /.tmp folder seems to have the necessary files, or use 3.12.0

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @dec0y , @kkeltner ,
Try v3.14.1 should work now.

Thanks,

**Comment by kkeltner** [comment]
Thanks for the quick response / commit.  However, blew away node_modules and grabbed the 3.14.1 with a new npm install - now getting the following on build: ERROR in Metadata version mismatch for module D:/code/web/wt-ymir/trunk/node_modules/angular-gridster2/dist/index.d.ts, found version 4, expected 3.

Rolled back to 3.12.0 and no issue.

--Kris

**Comment by dec0y** [comment]
I am experiencing the same issue kkeltner reported above. Thank you for still looking into this!

**Comment by dec0y** [comment]
I can see in a lot of the .map files there are things pointed to a "./tmp/Component" etc.

**Comment by tiberiuzuld** [comment]
Oh crap, will look into it,
Seems they changed how tsconfig compiles things....

**Comment by tiberiuzuld** [comment]
Hi @dec0y and @kkeltner ,

I think I fixed this time from what I tested in version v3.14.2
Seems that "@angular/compiler-cli": "5.0.0-beta.4" dosen't want to compile the library correctly.
Had to revert to `beta.3`.

Let me know if works for you.

Thanks,

**Comment by dec0y** [comment]
Works for me now!

Thank you

**Comment by kkeltner** [comment]
Right on - works for me as well.  Thanks!

--Kris
