### ISSUE TITLE
resizable/draggable.stop callback should be able cancellable

### ISSUE THREAD

**Issue by nghiado** [tiberiuzuld/angular-gridster2#14]
Can you support promise/cancellable for the stop callback?
A simple use case is users want to rearrange the widget position but we want their confirmation(via  popup dialog) before apply new position.

**Comment by tiberiuzuld** [comment]
Hi @nghiado, 
It is possible, will implement it this week.

**Comment by tiberiuzuld** [comment]
Hi @nghiado ,
Implemented this in v2.4.0

**Comment by nghiado** [comment]
Thanks @tiberiuzuld, will try this weekend.

**Comment by PeterSeifert** [comment]
Can you please provide an example on how this callback should look like with the posibility to cancel it?

**Comment by tiberiuzuld** [comment]
Hi @PeterSeifert ,
You need to return a promise from the callback like:

```javascript
vm.options.draggable.stop = areYouSureCallback;

function areYouSureCallback(item, itemComponent, event){
     return new Promise(function(resolve, reject){
        /// do your stuff here
    });
}

```

**Comment by PeterSeifert** [comment]
Thank you, @tiberiuzuld. This helped me.
