### ISSUE TITLE
scroll vertical firefox

### ISSUE THREAD

**Issue by estevanjantsk** [tiberiuzuld/angular-gridster2#140]
On firefox, the last item isn't applying the margin-bottom, as you can see in the image bellow:

![image](https://user-images.githubusercontent.com/461342/31355932-853ed81a-ad12-11e7-8e46-49d1e812caf5.png)

**Comment by tiberiuzuld** [comment]
Hi @estevanjantsk ,
This is a bug in Firefox there is nothing I can do, is issue with how the calculation for the box model is done in Firefox.

This is the [spec for collapsing-margins](https://www.w3.org/TR/CSS21/box.html#collapsing-margins)

This is the snippet which fails in Firefox:
`Margins of absolutely positioned boxes do not collapse (not even with their in-flow children).`

You can file a bug to Firefox at https://bugzilla.mozilla.org/

Two already existing bugs there: [1](https://bugzilla.mozilla.org/show_bug.cgi?id=1253721), [2](https://bugzilla.mozilla.org/show_bug.cgi?id=940439)

Thanks,

**Comment by estevanjantsk** [comment]
@tiberiuzuld thanks for the answer. =)
