### ISSUE TITLE
"Fit to screen" option doesn't fill the entire screen

### ISSUE THREAD

**Issue by marcingold** [tiberiuzuld/angular-gridster2#141]
On the right side is still some empty space:
![gridster-bug-16x9](https://user-images.githubusercontent.com/17317156/31567488-039797dc-b070-11e7-9278-6139395b22df.PNG)

I changed 4 lines of code in the <b>gridster.component.ts</b> file. 
```javascript
if (this.$options.outerMargin) {
      this.curColWidth = (this.curWidth - this.$options.margin) / this.columns;
      this.curRowHeight = (this.curHeight - this.$options.margin) / this.rows;
} else {
      this.curColWidth = (this.curWidth + this.$options.margin) / this.columns;
      this.curRowHeight = (this.curHeight + this.$options.margin) / this.rows;
}
```

Now it works and looks like this: 
![gridster-bug-16x9-fixed](https://user-images.githubusercontent.com/17317156/31567660-e651a586-b070-11e7-9374-68c71f2a7ebf.PNG)

I dont know if this affects any other feature in the gridster module.

**Comment by tiberiuzuld** [comment]
Hi @marcingold ,
I think you chosen fixed option not fit.
At least seems that way from the screenshot.

I am not able to reproduce what you are showing in the screenshot only on fixed grid type.

Thanks,

**Comment by tiberiuzuld** [comment]
Close for inactivity.

**Comment by marcingold** [comment]
I'm back ;-)
These are the options I used, so hopefully u can reproduce the bug. 
![options](https://user-images.githubusercontent.com/17317156/34051940-a2ffe596-e1c0-11e7-8038-80d5cc4f967a.PNG)

The important part is that u set the min / max grid rows / cols to the aspect ration of ur screen. 
Example: 1920x1080p like my screen -> Max/Min cols = 16 and Max/Min rows = 9
So the result is:
![bug](https://user-images.githubusercontent.com/17317156/34052143-72ae4012-e1c1-11e7-9d03-164320f7db50.PNG)

If u multipli these 4 options by 2, 3, 4 etc. it's even more visible.
![image](https://user-images.githubusercontent.com/17317156/34052266-ec7a9170-e1c1-11e7-8e20-494b6da8ec1c.png)

If u can reproduce this bug, the fix in my first comment should still work

PS: Sorry for open this thread again  ;)

**Comment by tiberiuzuld** [comment]
Hi @marcingold,
Ok now I understand what you mean.
Will look into it this weekend.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @marcingold ,

Fixed the issue in v4.3.0

Let me know if works ok now.

Thanks

**Comment by tauchmi** [comment]
Would you mind by any chance to release this for angular 4 lts too?

**Comment by tiberiuzuld** [comment]
Hi @tauchmi ,
It is released for angular4 https://github.com/tiberiuzuld/angular-gridster2/blob/4.x/src/lib/gridster.component.ts#L203

In version 3.18.0
Does the package released on npm does not contain it ?

Thanks

**Comment by tauchmi** [comment]
D'oh, yes you are right. Thank you for this great Module!

**Comment by marcingold** [comment]
It's working 👍  thx :)

**Comment by tiberiuzuld** [comment]
Great!

Thanks for feedback and solution for fix.
