### ISSUE TITLE
WARNING in ... Cannot find source file '...'

### ISSUE THREAD

**Issue by thechausenone** [tiberiuzuld/angular-gridster2#142]
I seem to be getting multiple instances (i.e., different affected files) of these warnings after trying to run my application. 
<img width="803" alt="2017-10-14 18_26_07-package json - workspace - visual studio code" src="https://user-images.githubusercontent.com/9039337/31579847-52ba866a-b10d-11e7-9a34-5b24289245fc.png">

Any help would be appreciated.

**Comment by tiberiuzuld** [comment]
Hi @thechausenone ,

Fixed in 3.15.1

Let me know it works now.

Thanks,

**Comment by thechausenone** [comment]
The warnings are gone now, thanks for the quick fix.
