### ISSUE TITLE
Problem with resizable stop

### ISSUE THREAD

**Issue by josevi86** [tiberiuzuld/angular-gridster2#143]
Hi,

When I use the resizable event stop, the event is capturing the coordinates of the exactly moment when stop pushing the left mouse button, but later, the target is resizing to the next grid separator.

What i really need is the coordinates after this resizing. Could be possible to get them?
![card-resizing](https://user-images.githubusercontent.com/9534310/31717548-b02f3e7e-b40c-11e7-83b1-fecebbba8782.png)

Thanks!

**Comment by tiberiuzuld** [comment]
Hi @josevi86 ,
You could use a setTimeout to get the size of element after resize,
Or use the callback ` itemResizeCallback` which is triggered after the element resized in final position.

Let me know if this fixes your use case. 

Thanks,

**Comment by tiberiuzuld** [comment]
Close for inactivity.

**Comment by viethien** [comment]
@josevi86 have you fixed this issue yet?

**Comment by viethien** [comment]
I add setTimeout to resize function, it worked now. Thanks
