### ISSUE TITLE
Items overlap when pushItems and swap are both set to true

### ISSUE THREAD

**Issue by anatel** [tiberiuzuld/angular-gridster2#145]
Hi,
I created a dashboard with the following settings:
```
        this.options = {
            maxCols: 16,
            maxRows: 16,
            draggable: {
                enabled: true
            },
            resizable: {
                enabled: true
            },
            pushResizeItems: true,
            displayGrid: 'none',
            swap: true,
            outerMargin: false,
            pushItems: true
        };
```
```
        this.dashboard = [
            {cols: 6, rows: 8, y: 0, x: 0, minItemCols: 2, minItemRows: 2},
            {cols: 6, rows: 8, y: 0, x: 6, minItemCols: 2, minItemRows: 2},
            {cols: 6, rows: 8, y: 8, x: 0, minItemCols: 2, minItemRows: 2},
            {cols: 6, rows: 8, y: 8, x: 6, minItemCols: 2, minItemRows: 2},
            {cols: 4, rows: 16, y: 0, x: 12, minItemCols: 2, minItemRows: 2}
        ];
```
But when dragging the right block to the leftmost side and then move it a little to the right without releasing the mouse (as you can see in the below gif), the block is ending up overlapping blocks under it.

I also reproduced it in the gridster demo:
![awesomescreenshot-2017-10-19t13-28-00-051z 1](https://user-images.githubusercontent.com/5842641/31774633-edeac192-b4ee-11e7-9c6c-cde129eb0a36.gif)

Using the following settings:
![gridster settings](https://user-images.githubusercontent.com/5842641/31773878-c9679216-b4ec-11e7-9d80-599e0bdb5b5b.png)

Thanks!

**Comment by tiberiuzuld** [comment]
Hi @anatel ,
Will check it out and will try to fix it as soon as possible.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @anatel ,

Fixed in v3.15.2.

Thanks,

**Comment by anatel** [comment]
@tiberiuzuld Thanks!

**Comment by yvahava** [comment]
is there a way to force overlapping to happen ?
