### ISSUE TITLE
getNextPossiblePosition returns true when there is no room on the dashboard

### ISSUE THREAD

**Issue by sheldonyss** [tiberiuzuld/angular-gridster2#146]
I use below method to determine if I can still add an item to the dashboard.
```
private emptyCellClick(event, item) {
        if (this.gridster.options.api.getNextPossiblePosition(item)) {
            this.tiles.push(this.getDefaultTile());
            this.outputLayoutDto();
        } else {
            console.log('No room for new item');
        }

    }
```

When there are already 4 items on the dashboard and I right click to add another one, the `getNextPossiblePosition` method still returns true and console window prints `gridster.component.js:306 Can't be placed in the bounds of the dashboard!/n{"cols":8,"rows":4,"x":0,"y":0}`
And all items became smaller. The 5th item is in the DOM set to hidden and the item has a property `notPlaced:true`.

![image](https://user-images.githubusercontent.com/15058152/31814356-f5275e7a-b5bb-11e7-86c8-77e963145108.png)
![image](https://user-images.githubusercontent.com/15058152/31814621-ccd2f780-b5bc-11e7-85da-e55e0bae7b17.png)

Below is my gridster config:
```
         gridType: 'fit',
            compactType: 'none',
            margin: 5,
            outerMargin: true,
            mobileBreakpoint: 640,
            minCols: 16,
            maxCols: 16,
            minRows: 9,
            maxRows: 9,
            maxItemCols: 16,
            minItemCols: 1,
            maxItemRows: 9,
            minItemRows: 1,
            maxItemArea: 144,
            // minItemArea: 1,
            defaultItemCols: 1,
            defaultItemRows: 1,
            fixedColWidth: 105,
            fixedRowHeight: 105,
```
All items are:
```
rows: 4,
cols: 8,
```

What's going wrong here? Thanks.

**Comment by tiberiuzuld** [comment]
Hi @sheldonyss ,
Tried to replicate your issue and was not able.

On the demo app did:
```
  addItem() {
    const newItem = {x: 0, y: 0, rows: 4, cols: 8};
    console.log(this.options.api.getNextPossiblePosition(newItem));
    console.log(newItem);
  }
    this.dashboard = [
      {cols: 8, rows: 4, y: 0, x: 0},
      {cols: 8, rows: 4, y: 0, x: 8},
      {cols: 8, rows: 4, y: 4, x: 0},
      {cols: 8, rows: 4, y: 4, x: 8},
    ];
     
     //options
      minCols: 16,
      maxCols: 16,
      minRows: 9,
      maxRows: 9,
      maxItemCols: 16,
      minItemCols: 1,
      maxItemRows: 9,
      minItemRows: 1,
      maxItemArea: 144,
```

And in console I get: 
```
false
app.component.ts:141 {x: 15, y: 8, rows: 4, cols: 8}
```


Thanks,

**Comment by sheldonyss** [comment]
Hi @tiberiuzuld , I published a reproduce here. https://github.com/sheldonyss/gridster-test

As shown below, I have 4 items already added to a dashboard. I expect no more item can be added when I right click the empty space. But instead, 
![image](https://user-images.githubusercontent.com/15058152/31869251-51fc7670-b7d9-11e7-881c-b3f6541d8547.png)

the 5th item is added to the dom
![image](https://user-images.githubusercontent.com/15058152/31869272-7be4c280-b7d9-11e7-91f3-92ee36160a3b.png)
![image](https://user-images.githubusercontent.com/15058152/31869308-b35761a0-b7d9-11e7-8522-9c1c303bac1d.png)

**Comment by tiberiuzuld** [comment]
Hi @sheldonyss ,
I see only one commit on the repo, no gridster integration.

Thanks

**Comment by sheldonyss** [comment]
Hi @tiberiuzuld sorry my mistake. I just committed the gridster integration code. Please check it again.

**Comment by tiberiuzuld** [comment]
Hi @sheldonyss ,
So the changes I made and works:
```
// app.component.ts
...
// line 32,33 change the defaultItem sizes
defaultItemCols: 8,
defaultItemRows: 4,
...
 this.tiles = [ // line 87 added existing 4 tiles
      {x: 0, y: 0, rows: 4, cols: 8},
      {x: 8, y: 0, rows: 4, cols: 8},
      {x: 0, y: 4, rows: 4, cols: 8},
      {x: 8, y: 4, rows: 4, cols: 8},
    ];
...
// line 95 changed the emptyCellClick callback
  private emptyCellClick(event, item) {
    this.tiles.push(item);
  }
// The callback is called only if the defaultItem has room.
// The new item from callback already has x,y,cols,rows set.

```

Let me know if your use case is correct this way.

Thanks,

**Comment by sheldonyss** [comment]
it works by chaing defaultItemCols/Rows. Thanks.

**Comment by nguyenviethien** [comment]
Hello @tiberiuzuld 
When I use getNextPossiblePosition to check postion for new component.
It is successfull, but new component always jump to (0,0) or top of dashboard postion.
How can I avoid this issue?
Thanks
