### ISSUE TITLE
Problem with position element when i try set max cols

### ISSUE THREAD

**Issue by Rambuto** [tiberiuzuld/angular-gridster2#147]
I have new problem, when I set maxCols 4 and maxItemCols 4 and do drag, gridster add new cols (5) and pose some item (not which one I try to move) to this cols.

Sorry for my bad english

**Comment by tiberiuzuld** [comment]
Hi @Rambuto ,
Please post a config options sample, list of items and maybe a GIF if is a gesture issue.

Possible related to #134

Thanks,

**Comment by tiberiuzuld** [comment]
Close for inactivity.
