### ISSUE TITLE
/deep/ is deprecated

### ISSUE THREAD

**Issue by dzhavat** [tiberiuzuld/angular-gridster2#148]
I just came across this [article from Google](https://developers.google.com/web/updates/2017/10/remove-shadow-piercing) where it says that starting in Chrome 63 `/deep/` will be removed. There's also a [commit to Angular](https://github.com/angular/angular/commit/b754e60) from June, which also discourages the use of `/deep/`. 

The reason I'm opening this issue is that I can see you use the selector in a [couple of places](https://github.com/tiberiuzuld/angular-gridster2/search?q=deep&type=Code&utf8=%E2%9C%93). I don't know if this is going to break gridster in any way but it might be a good idea to update the implementation.

Thanks and keep up the good work!

**Comment by tiberiuzuld** [comment]
Hi @dzhavat,
Will try to find a way to replace it.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,

Fixed in v3.15.3.

Thanks,
