### ISSUE TITLE
Drag Not working when gridtype is fixed, working when it is fit

### ISSUE THREAD

**Issue by swarajm** [tiberiuzuld/angular-gridster2#149]
$scope.gridsterOpts = {
                    gridType: 'fixed', // 'fit' will fit the items in the container without scroll;
                    fixedColWidth: 250, // fixed col width for gridType: 'fixed'
                    fixedRowHeight: 250,
                    //compactType: 'none',
                    margins: 20,
                    //displayGrid: 'onDrag&Resize',
                    //disableWindowResize:false,
                    itemChangeCallback: itemChange,
                    //columns: ,
                    //colWidth: 'auto',
                    // minRows: 2,
                    defaultSizeX: 1,
                    defaultSizeY: 1,
                    minCols: 12,
                    maxCols: 12,
                    minRows: 10,
                    maxRows: 10,
                    maxItemCols: 100,
                    minItemCols: 1,
                    maxItemRows: 100,
                    minItemRows: 1,
                    maxItemArea: 100,
                    minItemArea: 1,
                    defaultItemCols: 4,
                    defaultItemRows: 4,
                   // fixedColWidth: 105,
                   // fixedRowHeight: 105,
                    outerMargin: true,
                    // pushItems:true,
                    // pushResizeItems:false,
                    // maxRows: 3,
                    // rows:3,
                    //  swap: true,
                    //  compactType: 'none',
                    //   rowHeight: 287,
                    //  pushing: false,
                    //  floating: false,
                    //   swapping: false,
                    draggable: {
                        enabled: true,
                        stop: eventStop
                    },
                    resizable: {
                        enabled: true,
                        handles: ['s', 'e', 'n', 'w', 'se', 'ne', 'sw', 'nw'],
                        stop: eventStop
                    },
                };

This is my configuration

**Comment by tiberiuzuld** [comment]
Hi @swarajm ,
Your config is wrong for resizable.
```
      resizable: {
        enabled: true,
        handles: {
          s: true,
          e: true,
          n: true,
          w: true,
          se: true,
          ne: true,
          sw: true,
          nw: true
        },
        stop: AppComponent.eventStop
```

With your correct config it works to drag on the demo app.

Thanks,

**Comment by swarajm** [comment]
Still drag not working 
Resize is working

**Comment by tiberiuzuld** [comment]
Hi @swarajm ,
Can you reproduce it on the demo app ?

Thanks,

**Comment by swarajm** [comment]
No

**Comment by swarajm** [comment]
can you help it?

**Comment by swarajm** [comment]
on click of button i am giving x,y,rows,cols value

**Comment by tiberiuzuld** [comment]
Hi @swarajm ,
There is little to go on here please provide all the code and some gif and the exact use case you want to achieve.

Thanks

**Comment by tiberiuzuld** [comment]
Close for inactivity.
