### ISSUE TITLE
Increasing item rows not resizing / laying out correctly - Compacting fine.

### ISSUE THREAD

**Issue by sgmccli** [tiberiuzuld/angular-gridster2#150]
Hi,

I have an issue whilst implementing angular-gridster2 where I click an icon inside a nested component that changes the row number of the item to a 1 or a 2 to be expanded or collapsed. 

When the content expands out the grid does not reflow correctly. It appears to expand fully underneath the item directly below it. If I manually move an item on the grid you can see it is fully expanded. When I collapse the component using the same approach the grid compacts perfectly fine as expected

I have attached a gif of the behaviour below.

![angular-gridster-issue](https://user-images.githubusercontent.com/1972162/32123980-2ae09e62-bb5e-11e7-973c-41be15964044.gif)

My options are set out below
```
    this.options = {
      itemChangeCallback: this.itemChange,
      itemResizeCallback: this.itemResize,
      gridType: 'scrollVertical',
      compactType: 'compactUp&Left',
      resizable: {
        enabled: true,
      },
      draggable: {
        enabled: true,
      },
      pushItems: true,
      pushResizeItems: false,
      minCols: 3,
      maxCols: 3,
      swap: true,
    };
```

My event handler for the expansion and collapse is here

```
  itemExpanded(item) {
    if (item.expanded) {
      item.list.rows = 2;
    } else {
      item.list.rows = 1;
    }
    this.options.api.optionsChanged();
  }
```

I am hoping I am just doing something wrong here but I can't seem to get it to work as desired on expansion.

Any thoughts or suggestions would be appreciated.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @sgmccli ,
In your expand handler you need to find the items below and move them on row down manually.
There is no push action when the change is made dynamic, with no user interaction like drag/resize.
Maybe I should expose the API for push.

Let me know if works.

Thanks

**Comment by sgmccli** [comment]
Hi @tiberiuzuld,

Thanks for the quick response, that works fine.

As you figured out from my question - I did intuitively expect the grid to reflow itself on expansion as it does when dragged or resized. I think exposing this behaviour would be worthwhile for the benefit of others.

Appreciate your work on this repo 👍 

 I am doing the following in case anyone else has the same question.

```
  itemExpanded(item, itemComponent) {
    if (item.expanded) {
      item.list.rows = 2;
    } else {
      item.list.rows = 1;
    }
    this.rearrangeGrid(item);
  }

  rearrangeGrid(item) {
    this.listCollection.map(list => {
      if (list.x === item.list.x && !isEqual(listCollection, item.list)) {
        item.expanded ? list.y++ : list.y--;
      }
    });

    this.changedOptions();
  }
```

Thanks again!

**Comment by tiberiuzuld** [comment]
Hi @sgmccli ,
Nice, 
Will make a separate issue for exposing the push api.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @sgmccli .
Added in v3.16.0 [read here on how to use](https://github.com/tiberiuzuld/angular-gridster2/tree/v3.16.0#gridster-options-api)

**Comment by sgmccli** [comment]
Hey @tiberiuzuld,

Thanks for turning this around so quickly.

The documentation looks good. I'll have a play with the API on Monday 👍
