### ISSUE TITLE
Can we do nesting of gridster with-in a "gridster-item" ? 

### ISSUE THREAD

**Issue by sreekumarp** [tiberiuzuld/angular-gridster2#152]
Similar to angularjs 1.x implementation shown here ?
https://codepen.io/narigua/pen/rOeWrV

**Comment by tiberiuzuld** [comment]
Hi @sreekumarp ,
You can try, let me know if it works. 
Never tried it, and I don't see a use case for it.

Thanks

**Comment by sreekumarp** [comment]
I already tried actually, its not working. May be because of the CSS styling. Its based on tag names...right

**Comment by tiberiuzuld** [comment]
Hi @sreekumarp ,
The link works now.
Probably it should work, don't see why not, you should check your sizes and that the config is right, since is a bit different than the library you use in the codepen.

Thanks

**Comment by sreekumarp** [comment]
This doesnot seems to be working, can you look into the below trail I made,

https://stackblitz.com/edit/angular-gridster-f4wvyc?file=app%2Fhello.component.ts

**Comment by tiberiuzuld** [comment]
Hi @sreekumarp ,

Works here: https://stackblitz.com/edit/angular-gridster-oqsngm

Thanks,

**Comment by sreekumarp** [comment]
this worked !! thanks, let me chk for the changes you made

**Comment by yvahava** [comment]
I'm having the same issue as above.  Would you be able to tell me what change made it work ?
