### ISSUE TITLE
Expression changed after it was checked in `updateGrid()`

### ISSUE THREAD

**Issue by NoMercy235** [tiberiuzuld/angular-gridster2#153]
Hello Tiberiu! With the latest update on Angular, there has been an issue that I can reproduce only on the project that I'm working on. 

I have stumbled across the `Expression changed after it was checked` error and, after some debugging, I found out that the cause was the `updateGrid()` method found in `GridsterGridComponent`, more exactly, the issue seems to happen only when assigning to the `this.columnsHeight` property. The way I see it, this is the cause:

- The component is created along with its properties. At this point, `this.columnsHeight`'s value is `undefined`.
- The constructor is executed and at this point `this.columnsHeight` has a value of 0.
- `ngAfterViewInit()` is ran due to the Angular component's lifecycle (this is ran inside a change detection cycle)

This is the call stack after a debugger inside `updateGrid()`:

```
  | GridsterGridComponent.updateGrid | @ | gridsterGrid.component.js?58a4:37
  | GridsterComponent.calculateLayout | @ | gridster.component.js?8b9f:212
  | GridsterComponent.optionsChanged | @ | gridster.component.js?8b9f:91
  | DashboardComponent.onResize | @ | dashboard.component.ts?fca9:231
  | DashboardComponent.ngAfterViewInit | @ | dashboard.component.ts?fca9:176
  | callProviderLifecycles | @ | core.es5.js?de3d:11176
```
- Inside `updateGrid()`, the following line is what causes the error:
`this.columnsHeight = this.gridster.curRowHeight * this.rows.length;`
```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '0'. Current value: '200'.
```

I do not know why this only happens for `this.columnsHeight` (I presume it's because it is used like this in the template `[style.height.px]="columnsHeight"`, but this means it should also happen for `rowsWidth` and it doesn't) but something that seemed to fix the problem for me was changing the `this.cd.markForCheck()` method call to `this.cd.detectChanges()`.

However, after reading [this](https://stackoverflow.com/a/41364469), it looks to me like `this.cd.markForCheck()` is the right approach (it also works on your example) but for some reason, it does not work for me. Do you have any idea what else could be the cause for this?

LATER EDIT:
Relevant npm packages:
```
    "@angular/common": "^4.4.6",
    "@angular/compiler": "^4.4.6",
    "@angular/core": "^4.4.6",
    "@angular/forms": "^4.4.6",
    "@angular/http": "^4.4.6",
    "@angular/platform-browser": "^4.4.6",
    "@angular/platform-browser-dynamic": "^4.4.6",
    "@angular/router": "^4.4.6",
    "angular-gridster2": "^3.15.3",
    "zone.js": "^0.8.18",
```

**Comment by tiberiuzuld** [comment]
Hi @NoMercy235 ,

I have no idea why this happens maybe they changed something in the latest versions.

Probably `rowWidth` will fail also if the `columnHeight` row is commented.

Will check out the angular 5 how it works and will make a new release. 
Maybe will fix your issue if you are on angular 5 now.

Interesting issue, will have to investigate this week.

Thanks

**Comment by NoMercy235** [comment]
Indeed, commenting the said line triggered the error on the next one, but fortunately, I saw where the error was. 

For some reason, I was convinced that `DashboardComponent.onResize` was not a function of my project, when in fact it was. It is responsible for computing the `height` of the gridster container and guess what... it was called from `ngAfterViewInit()`. :laughing: This is what was causing the issue and it seems like it was there all along, but earlier versions of Angular (4.4.1 to be precise) let it slide off.

So, as advice for the next person, don't call `gridsterOptions.api.optionsChanged();` inside a change detection.

I'll close this since it was only an error on my side. Thanks again for the package and keep up the great work! :+1:
