### ISSUE TITLE
Taking a snapshot while dragging causes error

### ISSUE THREAD

**Issue by julsette** [tiberiuzuld/angular-gridster2#156]
Hi, I am using Microsoft's Snipping Tool to take snapshots of the dashboard and I've tried taking a snapshot of your demo while dragging an item, as displayed here:

![image](https://user-images.githubusercontent.com/22366536/32616145-e6824acc-c571-11e7-8bf2-751baa572e67.png)

When I do so, take the snapshot and then go back to the page, the item continues to be in a state of dragging, following the mouse. This causes multiple errors and the page to stop working.

![image](https://user-images.githubusercontent.com/22366536/32616577-ee88e6e4-c572-11e7-848e-09f2fa31c46f.png)

Thank you and keep up with your awesome work! :sparkles:

**Comment by tiberiuzuld** [comment]
Hi @julsette ,

For some reason the browser/os doesn't trigger mouse up on the window and the element remains in a state of dragging.

I will investigate more this week and see if I find any solution.

But in any case this bug can be reproduce only when the user does special things like snipping or puts a breakpoint in drag move method.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @julsette ,
Found a way to fix it.
Fixed in v4.0.1

Thanks,
