### ISSUE TITLE
Tiles not movable on initial page load

### ISSUE THREAD

**Issue by karanaditya993** [tiberiuzuld/angular-gridster2#157]
I'm seeing something very strange on my end regarding tile movement. This might be a browser cache issue because it's completely resolved when you do a hard refresh of the page, BUT, on initial page load, sometimes the tiles in my dashboard are not able to be moved. Has anyone else experienced this? Thanks in advance.

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
I couldn't reproduce the issue.
Yes something is very strange.

Let me know if you find the issue in your app or in the library.
And if someone sees this issue also please do tell.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
Do you init the library before the request from server with options arrives?
Try init the gridster after.
Or use the API to update the options after request arrived.
Or loading items before the final options arrives.

Just a thought I had.

Thanks,

**Comment by karanaditya993** [comment]
Solved. Forgot to add the enabled property (true) on draggable for the gridster-item. Very clumsy of me. Thanks for the help and appreciate your time.
