### ISSUE TITLE
has no exported member 'Renderer2'.

### ISSUE THREAD

**Issue by awaisaltaf** [tiberiuzuld/angular-gridster2#158]
Hi guys,
i just started to work with it, it installed correctly but when i try to include in module it is giving error.
i am attaching a screenshot 
![gridster](https://user-images.githubusercontent.com/10347603/32649274-4bbc5e92-c61b-11e7-9a59-e27743380fcd.png)

**Comment by tiberiuzuld** [comment]
Hi @awaisaltaf ,
You need angular 4 or newer to have Renderer2.
You need to use the 2.4.x branch for angular2.

Thanks

**Comment by awaisaltaf** [comment]
Hi @tiberiuzuld ,
Right now i am have angular version 2.4.10

How can i specify version while installing it through npm ???
npm install angular-gridster2 --save

**Comment by tiberiuzuld** [comment]
Hi @awaisaltaf ,
In package.json file you can set at `angular-gridster2` the value to `2.4.16` .
Then run `npm install` again.

Thanks

**Comment by awaisaltaf** [comment]
Thanks @tiberiuzuld now working fine :+1:

**Comment by CyberVik** [comment]
Changing to 2.4.16 helped me as well. 2.4.20 throws error on build about missing definitions for GridsterItem Component
