### ISSUE TITLE
Gridster item visible on smartphone only

### ISSUE THREAD

**Issue by AlMuIssues** [tiberiuzuld/angular-gridster2#16]
Hello,
I created a new angular project. I've tried your sample code:
app.component.ts:
this.options = {
      gridType: 'fit',
      compactUp: false,
      compactLeft: false,
      itemChangeCallback: AppComponent.itemChange,
      itemResizeCallback: AppComponent.itemResize,
      margin: 10,
      outerMargin: true,
      maxItemCols: 50,
      minItemCols: 1,
      maxItemRows: 50,
      minItemRows: 1,
      defaultItemCols: 1,
      defaultItemRows: 1,
      fixedColWidth: 250,
      fixedRowHeight: 250,
      draggable: {
        enabled: true,
        stop: AppComponent.eventStop
      },
      resizable: {
        enabled: true,
        stop: AppComponent.eventStop
      },
      swap: false
    };
    this.dashboard = [
      { cols: 2, rows: 1, y: 0, x: 0 }];

app.component.html:
<gridster [options]="options">
  <gridster-item [item]="item" *ngFor="let item of dashboard">
    <p>Hello</p>
  </gridster-item>
</gridster>

I see one gridster item on devices with max-width 655px only. On smartphone is visible, on tablet and pc not. My css-file is empty. Here my project info:

@angular/cli: 1.0.0
node: 6.9.5
os: linux x64
@angular/common: 4.0.0
@angular/compiler: 4.0.0
@angular/core: 4.0.0
@angular/forms: 4.0.0
@angular/http: 4.0.0
@angular/platform-browser: 4.0.0
@angular/platform-browser-dynamic: 4.0.0
@angular/router: 4.0.0
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.0

**Comment by tiberiuzuld** [comment]
Hi @AlMuIssues ,
Was not able to reproduce the issue with only one widget.
What I think it happens:
* The parent of the `<gridster>` is not having width/height and so the space to render is 0 and will not render. In mobile size the `<gridster>` has different css. In mobile is `display: block;` and above is `display: flex;`

Let me know if this help you, if not please provide a codepen/plunker so I can reproduce this issue.

**Comment by AlMuIssues** [comment]
If I set height of parent than works fine.
Thanks.
