### ISSUE TITLE
Textarea not editable in  <gridster-item>

### ISSUE THREAD

**Issue by awaisaltaf** [tiberiuzuld/angular-gridster2#160]
Hi guys i am not able to edit textarea placed in gridster-item tag. Can anyone please help me to sort out this problem.I would be very thankful.
```
 <gridster-item  [item]="itemsPosition[0]">
        <h6>Description</h6>
        <hr>
        <textarea  [(ngModel)]="metadata.description"  id="metaDescription">{{metadata.description}}</textarea>
    </gridster-item>
```

**Comment by tiberiuzuld** [comment]
Hi @awaisaltaf ,
Read [here](https://github.com/tiberiuzuld/angular-gridster2#interact-with-content-without-dragging)
For you the option 2 should be the desired way.

Please read the entire readme.md before opening issues which already have implementation done.

Thanks

**Comment by awaisaltaf** [comment]
Thanks @tiberiuzuld, I am very sorry i was searching for it in options, i didn't notice. 
By the way you people are doing great job :+1:
