### ISSUE TITLE
How to keep grid size of same size when we drag

### ISSUE THREAD

**Issue by swarajm** [tiberiuzuld/angular-gridster2#161]
when grid type is "fit to screen". I don't want scroll bar

**Comment by tiberiuzuld** [comment]
Hi @swarajm ,
Well you shouldn't have a scrollbar if grid type is "fit".
When you drag beyond the edges of the screen a scrollbar will appear probably just when dragging. 
When you release the item it will resize all items to fit the screen.

Thanks,
