### ISSUE TITLE
keepFixedHeightInMobile differs by margin

### ISSUE THREAD

**Issue by Zaixer** [tiberiuzuld/angular-gridster2#162]
If you for example use fixedRowHeight=200 and margin=10 then the gridster-item height will be 190px on desktop and 200px on mobile. I assume they are supposed to be the same.

**Comment by tiberiuzuld** [comment]
Hi @zaxier,
Yes will try to have it fixed this week.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @Zaixer ,
Fixed in v4.0.2

Thanks,

**Comment by Zaixer** [comment]
thanks
