### ISSUE TITLE
How to load new component on adding new gridster item

### ISSUE THREAD

**Issue by rizwana411** [tiberiuzuld/angular-gridster2#163]
Hi @tiberiuzuld ,
   I am designing a dashboard where i can add different widgets in the gridster dynamically... here i am using dynamic component load part to load the component.
but the issue is i want the component to be a grisdster item so that i can drag n resize that accordingly.
but it is not acheived.

**Comment by tiberiuzuld** [comment]
Hi @rizwana411 ,
Your dynamic component needs to be inside the gridster-item component.

Thanks

**Comment by rizwana411** [comment]
ya how can i add any template programatically in a gridster- item component,
bcoz to add gridster-item i just have to add {} object to dashboard.

**Comment by tiberiuzuld** [comment]
Read [here](https://github.com/tiberiuzuld/angular-gridster2#load-dynamic-components-inside-the-gridster-item)

**Comment by rizwana411** [comment]
I  have used this sir, bt the issue is i have to mention the tag <ndc-dynamic> in gridster-item, which i have to do static,as i have to make it dynamic i.e when i click on any of the item this tag should be appended to gridster item. then the component will be loaded.

**Comment by tiberiuzuld** [comment]
Well then you should read [here](https://angular.io/guide/dynamic-component-loader), [here](https://angular.io/guide/structural-directives#templateref-and-viewcontainerref), []

Google is your friend.
This is an Angular question.
Please address Angular repo on how to load dynamic content.
I don't know how to solve your problem.

**Comment by rizwana411** [comment]
ok thank you for ur help.

**Comment by rizwana411** [comment]
Can u tell me how to get the gridster item on its click.
i.e which method is used to get the item clicked.

**Comment by tiberiuzuld** [comment]
None. Put (click) on your content.
