### ISSUE TITLE
CompactType not none and fixed position

### ISSUE THREAD

**Issue by Konstruktour** [tiberiuzuld/angular-gridster2#165]
Multiple gridster items are placed in a gridster container and the setting 'compactType' is set to 'compactLeft'. As expected every item moves to the left, when e.g. an item is removed. So far so good.
An additional wished behaviour would be that the position of some items should to be fixed. So they are excluded from the 'compactLeft' and therefore don't move to the left automatically. 
Is this behaviour already possible through a special configuration?

**Comment by tiberiuzuld** [comment]
Hi @Konstruktour ,
No there is no config to exclude an item from compacting.

Will have to add one.
But other items to the left of it will not compact over the excluded item.

Will try to add the feature this week.

Thanks,

**Comment by Konstruktour** [comment]
Would be great :-)
thx in advance!

**Comment by tiberiuzuld** [comment]
Hi @Konstruktour ,

Added in v4.1.0

Thanks
