### ISSUE TITLE
Grouping Elements

### ISSUE THREAD

**Issue by vgiattino** [tiberiuzuld/angular-gridster2#167]
Do you have any plans on providing the ability to nest grids? User should be able to create a Group container to place widgets within. This container would be treated as a grid within a grid. Widgets inside container would adhere to that container break-point point for stacking.

Would also need the ability to:

- Add/Remove Widgets 
- Drag widgets in and out of group conatiners
-etc...

**Comment by tiberiuzuld** [comment]
Hi @vgiattino ,

1. Nesting is already possible read #152

2. Add remove widgets already works like for a normal grid.

3. Breakpoints for mobile/stacking works on window level only, right now, can be changed or added a separate option easily.

4. Drag widgets in and out of different grids. Very hard and complex to implement with current system to drag and push. With push on will never be possible. With push off maybe.

5. What other features ? 

6. Why do you need this? Can you give me the use case for this? 

Thanks

**Comment by tiberiuzuld** [comment]
Close for inactivity.
