### ISSUE TITLE
Interop with Angular Material

### ISSUE THREAD

**Issue by bajzat** [tiberiuzuld/angular-gridster2#168]
Hi,

First of all, this is a great library I'm trying to use the Gridster with Angular Material 2.0.0 beta-12 (Angular 4.4.6) and everything went well until I've started to use the MatDialog component. My problem is that, if the Gridster is on the page then I am not able to close the dialog windows with the dialogref.close() method or the MatDialog.closeAll() method.

I've tried to disable the resize and dragging options, but it didn't help. I'm new in the Angular world, Is that possible, the Gridster suppress an event or prevent the rerendering?

Thanks

Tamas

**Comment by tiberiuzuld** [comment]
Hi @bajzat ,
That is strange it shouldn't interfere with anything external.
The gridster only suppresses events inside the grid-item for drag or resize purpose.
You can read about it [here](https://github.com/tiberiuzuld/angular-gridster2#interact-with-content-without-dragging) how to get around it.
But the dialog is opened over the grid not inside. So it shouldn't be any interference.
You will have to debug in your application to see what is going on.

Thanks

**Comment by bajzat** [comment]
Thanks for the quick answer. You were right, one of the components in the Gridster item caused the issue. I forgot to remove that before I tested the solution without the Gridster.

**Comment by szechyjs** [comment]
I have a similar issue with PrimeNG. A component within a `gridster-item` has a `p-dialog` component. When activated it should display above the grid, however when activated it does not display.  If the `gridster-item` is removed it works just fine.

**Comment by MuthuD** [comment]
@szechyjs,  

I'm also facing this issue, did you find any solution for this?
