### ISSUE TITLE
Item creation at mobile/tablet design

### ISSUE THREAD

**Issue by josevi86** [tiberiuzuld/angular-gridster2#169]
When i try to create an item with drag and drop at an empty cell, with chrome tools for mobile, it seems that the events enableEmptyCellDrop or enableEmptyCellDrag are not firing. EnableToDrag is working on your demo (without mobile tools) with this option:

![enable-to-drag](https://user-images.githubusercontent.com/9534310/33199428-a9d1e012-d0f0-11e7-872c-191ae2587a87.png)

It allows me to swap and move items, but not the creation of new ones from empty cells with dragging. I have try at your demo (https://tiberiuzuld.github.io/angular-gridster2/angular/), just to make sure that is not my configuration, and is working in the same way.
![screenshot](https://user-images.githubusercontent.com/9534310/33183485-53a8d89e-d078-11e7-801f-7c4976226396.jpg)

Thanks!

**Comment by tiberiuzuld** [comment]
Hi @josevi86 ,
Yes I was able to reproduce the issue.
I will try to have it fix as soon as possible.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @josevi86 ,
Fixed in v4.1.0

Thanks
