### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'gridster'

### ISSUE THREAD

**Issue by dhaniksahni** [tiberiuzuld/angular-gridster2#170]
**Getting below error when tried to add angular-gridster2. Used sample which is provided in example. If i will add NO_ERRORS_SCHEMA in schemas, then it will not show error but there will be no output. Any help regarding this.**

compiler.js:466 Uncaught Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'gridster'. ("<h1>PTS Program</h1>
<gridster [ERROR ->][options]="options">
  <gridster-item [item]="item" *ngFor="let item of dashboard">
    <!-- your c"): ng:///DashboardModule/DashboardComponent.html@1:10
'gridster' is not a known element:
1. If 'gridster' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<h1>PAP Program</h1>
[ERROR ->]<gridster [options]="options">
  <gridster-item [item]="item" *ngFor="let item of dashboard">
    <"): ng:///DashboardModule/DashboardComponent.html@1:0
    at syntaxError (compiler.js:466)
    at TemplateParser.parse (compiler.js:24329)
    at JitCompiler._parseTemplate (compiler.js:33716)
    at JitCompiler._compileTemplate (compiler.js:33691)
    at eval (compiler.js:33593)
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:33593)
    at eval (compiler.js:33463)
    at Object.then (compiler.js:455)
    at JitCompiler._compileModuleAndComponents (compiler.js:33462)

**Comment by tiberiuzuld** [comment]
Hi @dhaniksahni ,
Seems you didn't imported the module.
Hint: `1. If 'gridster' is an Angular component, then verify that it is part of this module.`

Please add:
```
import { GridsterModule } from 'angular-gridster2';

@NgModule({
  imports: [ GridsterModule ],
  ...
})
```

Thanks

**Comment by dhaniksahni** [comment]
I have already imported in app.module.ts but still giving that error. I have resolved that issue by using component instead of module.

**Comment by danday74** [comment]
Getting this too on v6.0.4
 importing GridsterModule.forRoot() in my imports array in correct module
Still getting 'gridster' is not a known element

**Comment by ahmedmohyeldean** [comment]
if use "Lazy load" or use module for every page  ,, you can make import in Page.module.ts

**Comment by harounchebbi** [comment]
Having the same issue with Angular 11.2.1. 
I imported the module as mentioned but the error still persists.
