### ISSUE TITLE
Order of items when mobileBreakpoint is applied

### ISSUE THREAD

**Issue by Zaixer** [tiberiuzuld/angular-gridster2#172]
It seems that the stacked items are ordered by index in the list. Intuitively one would like for the items to be first ordered by Y and then by X when stacked.

**Comment by tiberiuzuld** [comment]
Hi @Zaixer ,
The `ngFor` is in your code you can apply your own pipe to order it how you want.
`item of items | orderBy:'x,y'`

Thanks

**Comment by Zaixer** [comment]
Ah, didn't think about that. Thanks!
