### ISSUE TITLE
Possible memory leaks from angular-gridster2

### ISSUE THREAD

**Issue by StevenLiSiwei** [tiberiuzuld/angular-gridster2#176]
Dear author,

It seems that our project has been buggy due to memory leaks, we narrowed down all and patched for all unsubscribe observeables and impure pipes, but chrome memory profiling still gives us a memory leaks chart with every peak blue bar whenever system enters a page component which uses gridster2 module. 

![](https://image.ibb.co/cVLBNw/Memory_Leakage.png)

![](https://image.ibb.co/cK9MNw/mem_leaks_2.png)

Please help.

**Comment by tiberiuzuld** [comment]
Hi @StevenLiSiwei ,
Will try to have fixed all the memory leaks this weekend.

Thanks

**Comment by StevenLiSiwei** [comment]
Thank you, looking forward to the update

**Comment by tiberiuzuld** [comment]
Hi @StevenLiSiwei ,
Fixed some of the issues I found in v4.2.0

Let me know if you still are able to pinpoint the leaks to the library.

Thanks

**Comment by StevenLiSiwei** [comment]
Many thanks @tiberiuzuld . 
I will update you when I found any issue.
Is there any breaking API change from 3.17.0 to 4.2.0 ?

Thanks

**Comment by tiberiuzuld** [comment]
The only breaking change is that requires angular 5

**Comment by StevenLiSiwei** [comment]
The issue is we are using ionic, it is currently doesn't support angular 5. And our project is for production, we are in dilemma now.

**Comment by tiberiuzuld** [comment]
Ok will migrate the changes to angular 4 branch also.
Found out that Angular now has LTS for v4 ... so will need to support it also.

Will make a release soon.

**Comment by StevenLiSiwei** [comment]
Thank you very much. May I know roughly when it can be released, we are considering moving to muuri since we have no choice here. And my company can make donation to your project if you can release earlier.

**Comment by tiberiuzuld** [comment]
Will make the release soon in a couple of minutes.
Already started working on merging on that branch.
Just made the 4.3.0 release for angular 5.

**Comment by StevenLiSiwei** [comment]
Massive Thanks !!!!!!!

**Comment by tiberiuzuld** [comment]
Hey released `v3.18.0`
Let me know if works ok for you and the memory leaks are gone.

Thanks
