### ISSUE TITLE
Not able to drag element to downwards

### ISSUE THREAD

**Issue by swarajm** [tiberiuzuld/angular-gridster2#179]
I am using gridtype = "scrollVertical", I don't want to use scrollbar to scroll down the element. I want to drag an element to downwards, but it is getting stuck at bottom of the viewport.

**Comment by swarajm** [comment]
I found that in angular 2 demo it is working fine but not in angular 1.5 gridster demo

**Comment by tiberiuzuld** [comment]
Hi @swarajm ,
Ok will have a look this weekend.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @swarajm ,
Fixed in 1.18.0

Thanks
