### ISSUE TITLE
When dragging element down the screen, focus does not shift (movement of element is not visible)

### ISSUE THREAD

**Issue by abhishekpathak2017** [tiberiuzuld/angular-gridster2#180]
Hi,

When I am dragging element down the screen, focus does not shift (movement of element is not visible). 
This is working in Angular 2 and Angular 4 Demo URLs, but not in Angular 1.x Demo URL.
Can you please fix this, or suggest a workaround?
![error](https://user-images.githubusercontent.com/34339176/33712449-858de0f2-db6d-11e7-9c13-5435ac568e02.png)

**Comment by tiberiuzuld** [comment]
Hi @abhishekpathak2017 ,

Will have a look to fix it as soon as possible.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @abhishekpathak2017 ,
Fixed in 1.18.0

Thanks
