### ISSUE TITLE
Adding new widgets by dragging from outside the dashboard

### ISSUE THREAD

**Issue by nareshkore** [tiberiuzuld/angular-gridster2#181]
When we drag an element from outside of the dashboard, is there any event to highlight the empty cells just like emptyCellDragHover or any alternative to achieve this functionality.

If yes, then how can we highlight maximum no.of empty cells which are side by side.

Thanks in advance..

**Comment by tiberiuzuld** [comment]
Hi @nareshkore ,
Look over:
`emptyCellDropCallback: undefined, // empty cell drag drop callback. HTML5 Drag & Drop`
and
`enableEmptyCellDrop: false, // enable empty cell drop events`

I don't understand what you mean by highlight maximum?

Thanks
