### ISSUE TITLE
displayGrid options 'allTheTime'

### ISSUE THREAD

**Issue by HoplaGeiss** [tiberiuzuld/angular-gridster2#183]
I would like to permanently display the grid of the dashboard. At the moment the only option seems to be 
 displayGrid: 'onDrag&Resize', would it be possible to add 'allTheTime' as an option ?

**Comment by tiberiuzuld** [comment]
Hi @HoplaGeiss ,
It already exists: `always` and `none`.
The readme.md does not specify it the but the demo option has it in the dropdown.
Will add it in doc also now.

Thanks

**Comment by HoplaGeiss** [comment]
thnaks mate
