### ISSUE TITLE
Revert to initial grid.

### ISSUE THREAD

**Issue by Kalemstorm94** [tiberiuzuld/angular-gridster2#184]
Hello! 

I'm trying to apply some changes to each GridsterItem (x, y, cols, rows). Afterthat, I've added a button to discard those changes on click, so I can return to the initial state, but I'm able to do this only if i delete the current grid. After that, I'm  repopulating the list and it seems to work fine.

I'm trying to make it work without deleting the grid, but something like `gridsterItemComponent.$item.rows += 1` does not redraw the grid. I've checked the $item in the console and the changes are right there, but the html page remains the same. 

Could you please tell me if I'm doing something wrong? I've tried your example, but I don't think that's what I need to solve this problem.

**Comment by tiberiuzuld** [comment]
Hi @Kalemstorm94 ,

Please make the changes on your items not on internal `$item` from your controller.
After you make the changes call `this.options.api.optionsChanged();`

This way you can change the options from outside the grid and the grid will update with the new values.

Let me know if this fixes your problem.

Thanks

**Comment by Kalemstorm94** [comment]
Thank you! This really helped me. There is still one issue here, because for the initial positions I make a request to the database to get all the positions. If I try to duplicate the `dashboard: Array<GridsterItem>` to another auxiliary variable, when I change a position, both of them updates.

The problem is that if I make some changes and save them to the database, then I start again to make some other changes, and after that I try to discard them, if I want to get my last saved configuration, I need to make another call to the database, because my Auxiliary variable will always be updated, even though in the HTML template I'm using only the dashboard array. , `<gridster-item [item]="item" *ngFor="let item of dashboard">`

**Comment by tiberiuzuld** [comment]
Well when you make your copy don't get the reference of the object take the value.
```

var item = {x: 5, y: 4};

// not like this
var copy = item;
item.x = 4;

// like this
var copyX = item.x;
var copyY = item.Y;
item.x = 4;

function revert(){
     item.x = copyX;
     item.y = copyY;
}


```
OR if you have lodash in your project use clone https://lodash.com/docs/4.17.4#clone

**Comment by Kalemstorm94** [comment]
This solved my problem. Thank you very much!
