### ISSUE TITLE
Items swap position after mobile breakpoint

### ISSUE THREAD

**Issue by julsette** [tiberiuzuld/angular-gridster2#186]
Hi,
I was testing my dashboard and I found out an issue while resizing the window from desktop to mobile mode.
I reproduced this in your demo.
I'm using the default options, I set minCols=5 and minRows=5 and left two widgets like so:
![image](https://user-images.githubusercontent.com/22366536/33876471-effba710-df25-11e7-945b-1af3ef6f584e.png)

When I go beyond the mobile breakpoint, the items swap:
![image](https://user-images.githubusercontent.com/22366536/33876546-25149c18-df26-11e7-9c5b-1d5d37dc703a.png)

Thank you!

**Comment by tiberiuzuld** [comment]
Hi @julsette ,
You need to do order by x and y in your code *ngFor

**Comment by julsette** [comment]
Okay, I thought that was somehow managed internally by gridster2. Thanks for the fast reply.
