### ISSUE TITLE
Start events

### ISSUE THREAD

**Issue by Kalemstorm94** [tiberiuzuld/angular-gridster2#187]
Hello again! On `ngOnInit()` I have the following setting of GridsterConfiguration variable: 

` this.options = {
      draggable: {
        enabled: true,
        start: this.openEditMode}} `

where the function is `public openEditMode() {
    this.editMode = true;
  }` and the `editMode` variable is `public editMode: boolean = false`
When I start dragging it enters the function but it doesn't make any changes on  `editMode`. I'm using this variable inside the template with `*ngIf="editMode"`. 

Is there a way so that I can access my variable from there without static functions?

**Comment by tiberiuzuld** [comment]
Hi @Kalemstorm94 ,
Try start: this.openEditMode.bind(this)

Thanks

**Comment by Kalemstorm94** [comment]
It works. 

Thank you!
