### ISSUE TITLE
ZoneAwareError- Expected 'styles' to be an array of strings. at assertArrayOfStrings (Webpack)

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [tiberiuzuld/angular-gridster2#19]
Hi,
i am getting "Expected 'styles' to be an array of strings. at assertArrayOfStrings" when i included "angular-gridster2" in my project which uses webpack. Got this link to solve this error (http://javaee.ch/2017/02/21/angular-how-to-import-your-css-file-with-webpack-without-errors/). Two things mentioned in the link
1) Use Webpack v2 - my project webpack is v2
2) Call the CSS file this way and correct loaders.
@Component({
    selector: 'cv-experience',
    templateUrl:'cv-experience.html',
    styles:[require('./cv.css').toString()]
})

You have two CSS file references inside gridster.component.ts & gridsterItem.component.ts. In those files styles files referred as  styles: [require('./gridsterItem.css')]. Do you think this is  causing the webpack css packaging issue?

**Comment by tiberiuzuld** [comment]
Hi @rajeshmuraleedharan , 
Added `.toString()` in v.2.4.1
Let me know if this fixed your problem.

**Comment by rajeshmuraleedharan** [comment]
Hi, 
"ZoneAwareError- Expected 'styles' to be an array of strings. at assertArrayOfStrings to ZoneAwareError- Expected 'styles' to be an array of strings. at assertArrayOfStrings (Webpack) " resolved. But Can't resolve few components. 

Check below build errors
 ERROR in ./~/angular-gridster2/dist/gridster.module.js
Module not found: Error: Can't resolve './gridster.component' in 'C:\git1\project\node_modules\angular-gridster2\dist'
 @ ./~/angular-gridster2/dist/gridster.module.js 5:27-58
 @ ./src/app/app.module.ts
 @ ./src/main.ts
ERROR in ./~/angular-gridster2/dist/gridster.module.js
Module not found: Error: Can't resolve './gridsterItem.component' in 'C:\git1\optionstrading\UX\Options.Trading.TitanUI\node_modules\angular-gridster2\dist'
 @ ./~/angular-gridster2/dist/gridster.module.js 6:31-66
 @ ./src/app/app.module.ts
 @ ./src/main.ts
ERROR in ./~/angular-gridster2/dist/gridster.module.js
Module not found: Error: Can't resolve './gridsterPreview.component' in 'C:\git1\project\node_modules\angular-gridster2\dist'
 @ ./~/angular-gridster2/dist/gridster.module.js 7:34-72
 @ ./src/app/app.module.ts
 @ ./src/main.ts
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] (webpack)/buildin/global.js 509 bytes {0} [built]
       [2] (webpack)/buildin/module.js 517 bytes {0} [built]
       [3] ./~/html-webpack-plugin/lib/loader.js!./src/public/index.html 660 bytes {0} [built]

**Comment by tiberiuzuld** [comment]
Pushed another release v2.4.3.
Added a index.js which exports the components.
Let me know if this fixes your issues.

**Comment by rajeshmuraleedharan** [comment]
all build issues fixed. but i can't see any widgets on my screen. using same code from your demo app,  browser console shows log when i add new widget. No run-time errors. Look like i am missing few css/styles. Please let me know the styles i need to include.

**Comment by tiberiuzuld** [comment]
the parent of the gridster needs to have width and height. 
Please have a look at this issue: https://github.com/tiberiuzuld/angular-gridster2/issues/16

**Comment by rajeshmuraleedharan** [comment]
Added width and height but still I am not able to see widget properly.


[cid:image002.jpg@01D2ABB6.072134E0]

Thanks,
Rajesh Muraleedharan
SR APPLICATION DEVELOPER
•  (Wk)  (515) 342 3371
• RMuraleedharanNair@athene.com<mailto:RMuraleedharanNair@athene.com>

**Comment by tiberiuzuld** [comment]
From the image it seems that the styles from the components are not applied.
Will look into it tomorrow(monday).

Try to check if you can use the lib/* folders where are the ts files. Maybe this will help you solve the issues temporarily while I make the fix for the .js files

**Comment by rajeshmuraleedharan** [comment]
tried lib/* folder, still style issue is there.

**Comment by tiberiuzuld** [comment]
Hi @rajeshmuraleedharan ,
I inlined the styles and templates now.
Let me know if this fixed your issue.

**Comment by rajeshmuraleedharan** [comment]
Still same issue. 

<img width="770" alt="capture" src="https://cloud.githubusercontent.com/assets/16232384/24625355/61ff112c-1874-11e7-9f75-f0279fcd06e9.PNG">

Chome Dev tool Inspect screenshots 
<img width="946" alt="capture" src="https://cloud.githubusercontent.com/assets/16232384/24625465/b13ea48c-1874-11e7-87b6-c5fdaeab89ae.PNG">
<img width="950" alt="capture1" src="https://cloud.githubusercontent.com/assets/16232384/24625471/b66e99bc-1874-11e7-90ab-e67cf078c86e.PNG">

**Comment by tiberiuzuld** [comment]
Can you show me the applied styles on the `<gridster>` element.
I think you miss the styles there, and those styles are included in the file.
The `<gridster-item>` seems to have the styles applied.
The only styles that are provided from the library are for `<gridster>` & `<gridster-item>` elements

**Comment by rajeshmuraleedharan** [comment]
Please check this.
<img width="833" alt="capture" src="https://cloud.githubusercontent.com/assets/16232384/24627703/77bdb6ba-187b-11e7-9689-96d3be348e5e.PNG">

**Comment by rajeshmuraleedharan** [comment]
Please check this
<img width="828" alt="capture" src="https://cloud.githubusercontent.com/assets/16232384/24628093/b00e4458-187b-11e7-985e-2996fa3816d6.PNG">

**Comment by rajeshmuraleedharan** [comment]
i can able to to see "gridster.css" style included. not sure is this something to do with ":host" Pseudo-class.

**Comment by tiberiuzuld** [comment]
I just made a local new test angular-cli app and all works fine for me.
I don't know how to help you.
 I think is from the stack you are using that the styles are not added.

**Comment by rajeshmuraleedharan** [comment]
Hi,
Please close this issue. Working fine after i deleted my node modules and reinstalled. Not sure what was causing. Thank you for the quick support on this.

**Comment by Maseeharazzack** [comment]
@rajeshmuraleedharan rajeshmuraleedharan Even after deleting node module am getting same issue
