### ISSUE TITLE
Unable to prerender: No provider for GridsterComponent! 

### ISSUE THREAD

**Issue by chrisvfabio** [tiberiuzuld/angular-gridster2#192]
I'm unable to render the gridster via server-side in Angular 5. It worked previously in Angular 4.

Getting this error:
```
ERROR { Error: StaticInjectorError[GridsterComponent]:
  StaticInjectorError[GridsterComponent]:
    NullInjectorError: No provider for GridsterComponent!
....
  ngTokenPath:
   [ { [Function: GridsterComponent]
       checkCollisionTwoItems: [Function],
       decorators: [Array],
       ctorParameters: [Function],
       propDecorators: [Object] } ] }
```

Perhaps it's related to the AngularCompilerPlugin using AOT? 

checkCollisionTwoItems is referencing the GridsterComponent statically, so maybe this is causing the error? 
https://github.com/tiberiuzuld/angular-gridster2/blob/eddf26e236f2da78f7436baa77596c5735d3c928/src/lib/gridster.component.ts#L330

Here is my template: 
```html
 <gridster [options]="gridConfig">
    <gridster-item [item]="item" *ngFor="let item of items">

      <div class="gridster-item-content">
        <ndc-dynamic [ndcDynamicComponent]="item.component" [ndcDynamicInputs]="item.componentInputs"></ndc-dynamic>
      </div>

      <div class="item-overlay" >
        <div class="action-buttons">
          <button mat-icon-button mat-raised-button (mousedown)="itemSelect($event, item)" (touchstart)="itemSelect($event, item)" matTooltip="Remove">
            <mat-icon>clear</mat-icon>
          </button>
        </div>

        <button mat-icon-button class="drag-handler">
          <mat-icon>open_with</mat-icon>
        </button>
      </div>
    </gridster-item>
  </gridster>
```

Thanks.

**Comment by tiberiuzuld** [comment]
Hi @chrisvfabio ,
I have no clue why is not working in angular5 anymore.
I used AOT compile on demo page since angular4 and in angular5 still works.
But yes I don't do server side rendering.

Will have to look at this, maybe they introduced some change in changelog which I missed.

Thanks
