### ISSUE TITLE
Return statements in functions of gridsterCompact.service.ts is not used in calling function

### ISSUE THREAD

**Issue by yugi03** [tiberiuzuld/angular-gridster2#194]
https://github.com/tiberiuzuld/angular-gridster2/blob/836f04b2b19ed6dbf3066e3bda850d892eaade2a/src/lib/gridsterCompact.service.ts#L50

**checkCompactUp()** and **checkCompactLeft()** is returning boolean values, which is not used in the function which is calling above function. Should I create a PR to remove that?

**Comment by tiberiuzuld** [comment]
Hi @yugi03 ,
Yes please :)

Thanks
