### ISSUE TITLE
Cannot set property 'movingItem' of undefined

### ISSUE THREAD

**Issue by ceejeeb** [tiberiuzuld/angular-gridster2#199]
Since the destroy method was added in `src/lib/gridsterDraggable.service.ts`
This results in a error being thrown at line 105:
```
     setTimeout(function () {
            this.gridster.movingItem = null;    <---------------
            this.gridster.previewStyle();
        }.bind(this));
```

because this.gridster is now undefined.

**Comment by tiberiuzuld** [comment]
Hi @ceejeeb ,
Can you tell me what action you do for that error to appear ?
On the demo page I cannot reproduce it.

Thanks

**Comment by ceejeeb** [comment]
Hi,
in my code i have a model which contains a list of elements, each of these elements generates an item fo r the dashboard, when a tile is moved i have a callback to trigger an action to update my model with the new location which then in-turn forces the dashboard to re render . 

I assume because the dashboard is re rendering that destroy method is firing before the timeout. I might be wrong though.

**Comment by tiberiuzuld** [comment]
Hmm... ok will look into it.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @ceejeeb ,
Didn't test it but it should be fixed now in v4.3.2

Please let me know if it fixes your issue.

Thanks

**Comment by ceejeeb** [comment]
Hi @tiberiuzuld 
So the error no longer is thrown but there is a visual bug that the drop shadow style remain visible if you have dragged a tile to a new location that has caused the grid to resize (i.e. a new lower column).
I assume that the line this.gridster.previewStyle(); needs to fire.

**Comment by tiberiuzuld** [comment]
Ok try v4.3.3 should be fixed now.

Thanks

**Comment by ceejeeb** [comment]
Thanks, i am using the angular 4.x (v3.x) branch so once merged ill test it.

**Comment by tiberiuzuld** [comment]
Ok v3.8.2 is up.

**Comment by ceejeeb** [comment]
Seems to all be fixed now.
Thanks
