### ISSUE TITLE
any plans on re-writing this library in typescript for angular2?

### ISSUE THREAD

**Issue by rajesh-kanakabandi** [tiberiuzuld/angular-gridster2#2]

**Comment by tiberiuzuld** [comment]
Hi,

Yes, soon, hopping to have some time this weekend to do it. 
If not for sure this month.

Thanks,

**Comment by rajesh-kanakabandi** [comment]
@tiberiuzuld great work man. Appreciate the work.

**Comment by roeeovadia** [comment]
@tiberiuzuld 
can you please write some instructions? I cant import it to my projects
Roee

**Comment by tiberiuzuld** [comment]
Hi @roeeovadia migration to angular2 is not complete, and such I didn't build and deployed the application.
Will be done this week.

**Comment by dedalusmax** [comment]
based on what we've seen on the demo, it is what we would need for our app.
so, please make this for ng2 + ts + webpack. we are eagerly waiting... :)

**Comment by tiberiuzuld** [comment]
Will do

**Comment by tiberiuzuld** [comment]
Hi,
Finally managed to release v2.0.0. as angular2 implementation of the library.
Let me know if you find any issues.
