### ISSUE TITLE
Can we have min-width and min-height?

### ISSUE THREAD

**Issue by swaraj-mahajan** [tiberiuzuld/angular-gridster2#202]
I need to have min-width and min-height for gridster element so they cannot resize if that width or height is reached

**Comment by tiberiuzuld** [comment]
Hi @swaraj-mahajan ,
You can try to add your css with `min-height` and `min-width`.
Not sure if it will work.
If not the only solution is to set min cols and min rows properties.

There is no pixels option.

Thanks

**Comment by tiberiuzuld** [comment]
Close for inactivity,

**Comment by ShaileshInfyom** [comment]
@swaraj-mahajan  any solution?

**Comment by ShaileshInfyom** [comment]
@tiberiuzuld any update for min-height?

**Comment by tiberiuzuld** [comment]
If you mean min-heigth/min-width in px then no.
There is no solution.

**Comment by tiberiuzuld** [comment]
#228

**Comment by ShaileshInfyom** [comment]
Thanks for response.
