### ISSUE TITLE
columns length changes when i reinit my content 

### ISSUE THREAD

**Issue by icepoint0** [tiberiuzuld/angular-gridster2#203]
after save the contents such as {x: "1", y: "0", cols: "1", rows: "2"}{x: "1", y: "1", cols: "1", rows: "2"}{x: "1", y: "4", cols: "1", rows: "2"}

columns were changed

before: 3 columns

after: 5 or more.

**Comment by tiberiuzuld** [comment]
Hi @icepoint0 ,
Strange, please explain in more detail what you do...

But from what I understand most likely your are doing something wrong when you save/reload your content.

Thanks

**Comment by icepoint0** [comment]
yeah, for example :
before i saved the two grids ,

 {x: "1", y: "0", cols: "1", rows: "2"}
{x: "1", y: "1", cols: "1", rows: "2"}
{x: "1", y: "4", cols: "1", rows: "2"}

the column number is  3,

it looks very well,

but when i  reload these content after saving, 

the   column number will be  5 or more,

why? the content data is  same.

**Comment by tiberiuzuld** [comment]
why do you reload it ?
probably the issue is from *ngFor, is removing the old items after inserts the new items.

**Comment by icepoint0** [comment]
i have fixed this by jquery-gridster , thank u .

**Comment by tiberiuzuld** [comment]
Ok...
