### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by klemenoslaj** [tiberiuzuld/angular-gridster2#204]
Are there any plans to extend the library a bit, to support custom themes, without overwriting hardcoded styles in library source?

First example that comes to my mind is gray background hardcoded in styles of `gridster` component. Rarely someone will use it out of the box.

**Comment by tiberiuzuld** [comment]
Hi @klemenoslaj,
Adding predefined themes don't see the benefit of it since you don't have same control as just by setting styles from css.

What is the problem with overwriting css in gridster ?

Will it help if gridster and its components will have `encapsulation: ViewEncapsulation.None` ?

Thanks

**Comment by klemenoslaj** [comment]
Hi @tiberiuzuld,

thanks for your quick reply.
Actually now that I am thinking about it, there is no need really, sorry.

What probably makes sense is only to remove all opinionated styles out of the default components styling. Here I mean explicitly -> gray background.

ql product otherwise, great job 👍 thanks

**Comment by tiberiuzuld** [comment]
I understand you don't like the gray background :D (You can suggest another color if you like)

I am not forcing anyone to use the colors I choose :D (even I don't use them in my project :D )
Is there just so I don't get issues like: "Is not rendering / is empty kinda of stuff."

Removed encapsulation so it is easier to override styles and colors. https://github.com/tiberiuzuld/angular-gridster2/commit/7d343be66324b0596bde66de5ee14f01b14cd04f

Will have a release soon with it.

Thanks

**Comment by klemenoslaj** [comment]
Ok ql, you're the boss ;)

Thanks a lot!

**Comment by AkashJain21** [comment]
Hi, Is there any way to overwrite the column and row` border-color` as per min theming?
