### ISSUE TITLE
Recursion and returning from moveUpTillCollision method of gridsterCompactService

### ISSUE THREAD

**Issue by yugi03** [tiberiuzuld/angular-gridster2#206]
https://github.com/tiberiuzuld/angular-gridster2/blob/7d343be66324b0596bde66de5ee14f01b14cd04f/src/lib/gridsterCompact.service.ts#L58

I was going through the code, but above line of code was not clear to me. We are doing recursion in moveUpTillCollision method and the next line we are returning also. Why we doing like this? 

P.S: This question came when I was writing test case for this method and I was not able to test that recursion part as it was executing again and again for me.

**Comment by tiberiuzuld** [comment]
Hi @yugi03 ,
Well the recursion will stop when the item collides with another item or reaches grid border in this case row 0.

```javascript
  if (this.gridster.checkCollision(itemComponent.$item)) {
```

**Comment by yugi03** [comment]
Hello @tiberiuzuld,
I understood that part. But my doubt is that `moveUpTillCollision` is returning `boolean value at each iteration of its recursion` which should not happen.


    moveUpTillCollision(itemComponent: GridsterItemComponent): boolean {
        itemComponent.$item.y -= 1;
        if (this.gridster.checkCollision(itemComponent.$item)) {
            itemComponent.$item.y += 1;
            return false;
        } else {
            this.moveUpTillCollision(itemComponent);
            return true;
        }
    }

As you can see in the above method, when `this.gridster.checkCollision(itemComponent.$item)` returns false, then `moveUpTillCollision method` will recursively call itself again, but it returns true also each time, which I think should not happen. It should return only once.

One solution for this I can think of is by making below changes:

    moveUpTillCollision(itemComponent: GridsterItemComponent, isMovedUp: boolean): boolean {
        itemComponent.$item.y -= 1;
        if (this.gridster.checkCollision(itemComponent.$item)) {
            itemComponent.$item.y += 1;
            if (isMovedUp) {
                return true;
            } else {
                return false;
            }
        } else {
            isMovedUp = true;
            if (this.moveUpTillCollision(itemComponent, isMovedUp)) {
                return true;
            } else {
                return false;
            }
        }
    }

We can call this method as:

`moved = this.moveUpTillCollision(widget, false);`

Above function change will make sure that it will return only once when a widget is completely moved up.

What's your view on this? I was thinking to have your view on this before making PR for the same.

**Comment by tiberiuzuld** [comment]
Hmm... don't think your changes are necessary.
In the current code:
Only the first call of `this.moveUpTillCollision` matters since if the item is moved once the grid needs to be checked again. 
All future calls to the method don't matter if they return false or true because the return value is ignored.

In the changes you propose:
The recursion calls return value will not matter either since if the item was moved once you will return true anyway, even if the item is moved again or not.

So this changes only adds 2 more if statements and complicates the code, it will not change the end result.

Btw added a comment to your PR why you are getting infinite loop.
https://github.com/tiberiuzuld/angular-gridster2/pull/205

**Comment by yugi03** [comment]
@tiberiuzuld : I was just focussing on returning only once from `this.moveUpTillCollision`. That's why I came up with this idea. But I think you are right, this will overall not change the end result of it.

I saw your comment on PR, will resolve it soon and update it.

I am closing this issue.
Thanks!
