### ISSUE TITLE
Gridster config enums

### ISSUE THREAD

**Issue by klemenoslaj** [tiberiuzuld/angular-gridster2#207]
### Explanation
Whenever I play around with gridster I find myself struggling and searching for those strings that you have defined for different behaviors, like `compactUp&Left`.

### Suggestion
I would recommend to create `const enum` for `GridType`, `displayGrid` and `compactType` which would be publicly available.

### Example
```
const enum GridType {
    Fixed = 'fixed',
    ScrollVertical = 'scrollVertical',
    ...
}

const enum DisplayGrid { ... }

const enum CompactType { ... }

this.gridOptions = {
    gridType: GridType.Fixed,
    displayGrid: DisplayGrid.OnDragAndResize,
    compactType: CompactType.None,
};
```

**Comment by tiberiuzuld** [comment]
Hi @klemenoslaj ,
Thanks for the suggestion will do.

Thanks

**Comment by klemenoslaj** [comment]
Great, thanks! 👍

**Comment by tiberiuzuld** [comment]
Added in 4.4.0
