### ISSUE TITLE
Resizable stop even hook get's old data

### ISSUE THREAD

**Issue by klemenoslaj** [tiberiuzuld/angular-gridster2#209]
### Explanation
On `resizable.stop` event callback we receive `GridsterItem` as a first argument, however data is outdated.
Is that perhaps by design?

### Steps to reproduce
1. Assign callback to `resizable.stop`
2. Resize any `GridsterItem`
2.1. First argument in assigned callback is instance of `GridsterItem`
3. Observe resized dimension(s) and notice, that old values are provided

**Comment by tiberiuzuld** [comment]
Hi @klemenoslaj ,
Second argument `gridsterItem.$item` has the new values.
The first argument still has the old values because in stop you can cancel the resize.

**Comment by klemenoslaj** [comment]
Hi @tiberiuzuld,

thanks for the quick answer.
I could have looked a little bit better and see that `GridsterItemComponent` indeed have public `item` :( sorry.

Maybe small suggestion then:
Does it makes sense to add more strict function types to `GridBase` in `gridsterConfig.interface.d.ts`?

e.g. `start?(item: GridsterItem, itemComponent: GridsterItemComponent, event: MouseEvent): void;`

**Comment by tiberiuzuld** [comment]
Added in 4.4.0
