### ISSUE TITLE
drag handle

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [tiberiuzuld/angular-gridster2#21]
Is there any way i can add drag handle css? I have a bootstrap panel inside the widget and i want to move the widget using panel header only. Other thing is if i want to select a label text from a widget, due to the drag handle i can't select the text.

**Comment by tiberiuzuld** [comment]
Hi @rajeshmuraleedharan ,
You can have the inside content stop propagating the mouse events and have a div with position absolute which will propagate the mouse events.
```html
<gridster-item>
   <div class="content "(mousedown)="$event.stopPropagation()" 
                       "(touchstart)="$event.stopPropagation()">
     <-- your widget content !--> 
   </div>
   <div class="drag handle"></div>
</gridster-item>
```

**Comment by rajeshmuraleedharan** [comment]
yes, above worked to set drag handle. But still i can't select content div label text with mouse. can you please help.

**Comment by tiberiuzuld** [comment]
Will implement something soon.

**Comment by tiberiuzuld** [comment]
Hmm good question.
Well one option is to create a config mode for your dashboard where the user cannot interact with the content and can drag and resize widgets. And the normal mode where the dashboard is fixed and the user can interact only with the content.

A second option implemented now in v2.7.0 where the content has a class and what mouse events come from that element children and itself will be ignored by the widget drag event.

Please have a look in README.md and release notes on how to use.

**Comment by rajeshmuraleedharan** [comment]
Now i am getting this when i compile my app.
ERROR in [at-loader] ./node_modules/angular-gridster2/dist/gridster.component.d.ts:1:41 
has no exported member 'Renderer2'.

in "gridster.component.d.ts", "gridsterItem.component.d.ts" files. misspelled Renderer  as Renderer2.
![image](https://cloud.githubusercontent.com/assets/16232384/24821410/01b37bee-1bb4-11e7-9dd4-e3932c532ddb.png)

**Comment by tiberiuzuld** [comment]
Renderer2 is only available in angular 4. So you need to have angular 4.
