### ISSUE TITLE
Gridster items failing in iframes

### ISSUE THREAD

**Issue by swaraj-mahajan** [tiberiuzuld/angular-gridster2#210]
Gridster items failing in iframes getting error

Uncaught TypeError: Cannot read property 'x' of undefined
    at Object.d.calculateItemPosition (gridster.js?build-ver=1515511197215:formatted:1325)
    at Object.d.calculateItemPositionFromMousePosition (gridster.js?build-ver=1515511197215:formatted:1266)
    at Object.d.dragMove (gridster.js?build-ver=1515511197215:formatted:1257)

 at Object.d.makeDrag (gridster.js?build-ver=1515511197215:formatted:1308)
    at Object.d.dragStop (gridster.js?build-ver=1515511197215:formatted:1286)

**Comment by tiberiuzuld** [comment]
Hi @swaraj-mahajan ,
Are you sure is because of the iFrame ?
Doesn't look like an error from an iFrame.
Will test the demo in an iFrame and see.

**Comment by tiberiuzuld** [comment]
Hi @swaraj-mahajan ,
Just tested inside an iframe works perfectly.

```html
<iframe style="width:100%; height:100%;" src="https://tiberiuzuld.github.io/angular-gridster2/angular/"></iframe>
```

Please put in an example, codePen etc. 


Thanks

**Comment by mconner** [comment]
I'm getting the same issue, though only in IE11, so far (Chrome and Edge work properly, but unfortunately, we still support IE11).   I am able to duplicate this using the [w3schools editor](https://www.w3schools.com/code/tryit.asp?filename=GKSYCGRFZ8KJ) (IE11 no longer supported in codepen).   Run it, then drag a widget out of the iframe, then go back and click,  the widget will continue to follow (sort of), and no amount of clicking will reset it.  You can get a similar problem if you drag the resize handle off the iframe.   Looks like there may be a workaround based on [this comment](https://github.com/tiberiuzuld/angular-gridster2/issues/401#issuecomment-417716735).
