### ISSUE TITLE
Execute DOM events outside Angular zones

### ISSUE THREAD

**Issue by klemenoslaj** [tiberiuzuld/angular-gridster2#212]
I would strongly encourage to trigger all DOM events outside the zone in order to get additional performance out of gridster2.

I am currently implementing gridster2 into existing project, where each `GridItem` contains one pretty expensive component, and I can totally feel the problem.
Another scenario where this can cause problems are applications in migration from AngularJS to Angular by using ngUpgrade, since there `$digest` is triggered in addition.

#### On your demo app

**Inside angular**
![screen shot 2018-01-11 at 14 53 47](https://user-images.githubusercontent.com/7548247/34828945-721fe10e-f6df-11e7-8fcb-9b759d41f11f.png)

**Outside angular**
![screen shot 2018-01-11 at 14 52 25](https://user-images.githubusercontent.com/7548247/34828966-830076be-f6df-11e7-8e50-219bc48c037e.png)

**Comment by tiberiuzuld** [comment]
Ok, will do.
After I fix the bug with PushService.

**Comment by klemenoslaj** [comment]
Hi @tiberiuzuld, yes, the `PushService` issue is more important for sure.

Thanks for the great work!

**Comment by tiberiuzuld** [comment]
Implemented in v5.0 for drag move and resize move events
