### ISSUE TITLE
Cards' content get selected unexpectedly in Firefox

### ISSUE THREAD

**Issue by hngdev** [tiberiuzuld/angular-gridster2#213]
I tried to run the demo in Firefox and by clicking into the background as shown below, the content in the cards gets selected and can't be unselected.
![capture](https://user-images.githubusercontent.com/35343373/34837597-4af6cdc4-f6c9-11e7-81c9-1de8ffa5837b.PNG)

**Comment by tiberiuzuld** [comment]
Hi @hngdev ,
Ok strange, will have it fixed.


Thanks

**Comment by hngdev** [comment]
Thanks @tiberiuzuld,
May I ask when the fix will be rolled out?

**Comment by tiberiuzuld** [comment]
As soon as possible, probably this weekend.

**Comment by tiberiuzuld** [comment]
Fixed in 4.4.0
