### ISSUE TITLE
Callback event that fires constantly during resizing

### ISSUE THREAD

**Issue by oachkazlschwoaf** [tiberiuzuld/angular-gridster2#216]
Hi!
I have a chart inside a GridsterItem and want to resize it constantly during resizing the GridsterItem (not only when the resize is done) ... for better usability.

I couldn't find a callback to achieve this - is there one, or any other options i could use?

thx for your help!

**Comment by tiberiuzuld** [comment]
Hi @oachkazlschwoaf ,
No there is none because it will kill performance.
You can try the angular `ngDoCheck()` from https://angular.io/guide/lifecycle-hooks for now.
It will not work forever because https://github.com/tiberiuzuld/angular-gridster2/issues/212

**Comment by oachkazlschwoaf** [comment]
OK - I understand ... thx for your help
