### ISSUE TITLE
logic behind the calculation of the grids layout

### ISSUE THREAD

**Issue by naveenamruth** [tiberiuzuld/angular-gridster2#217]
Hi,

We couldn't able to understand the logic behind the grids layout designing.

could you please help us to understand how to calculate the number of cols, rows, x, and y to achieve below design?

Please suggest the best configuration where it will be suitable for my design
Note: - We played around and came up with below number for each widget but not sure how these are calculated internally :(

        //  Widgets
        this.disWidget1 = { cols: 6, rows: 1, y: 0, x: 0 }; // ?? 
        this.disWidget2 = { cols: 4, rows: 2, y: 0, x: 1 };
        this.disWidget3 = { cols: 2, rows: 2, y: 1, x: 1 };
        this.disWidget4 = { cols: 2, rows: 2, y: 0, x: 2 };
        this.disWidget5 = { cols: 2, rows: 2, y: 1, x: 2 };
        this.disWidget6 = { cols: 2, rows: 2, y: 2, x: 2 };
        this.disWidget7 = { cols: 2, rows: 2, y: 0, x: 3 };
        this.disWidget8 = { cols: 2, rows: 2, y: 1, x: 3 };
        this.disWidget9 = { cols: 2, rows: 2, y: 2, x: 3 };
      
![image](https://user-images.githubusercontent.com/8732898/34958875-c80d7a2a-fa01-11e7-8dc4-4483d67c4762.png)

**Comment by tiberiuzuld** [comment]
Hi @naveenamruth ,
Short answer: https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridster.component.ts

Long answer: 
X is horizontal 
Y is vertical
Cols is how many X position occupies/spreads starting from X
Rows is how many Y position occupies/spreads starting from Y

Depending of the GridType each X and Y takes the available space of px or the space specified in options.

For GridType: `fit`.
So if the entire grid width is 500px and you have 5 columns total. 
Then each column will have 100px (without margins options).
Then if you have an item with 3 columns then that item will have 300px width.
If the item has X of 1 then it will start from left side 100px.
Same applies for rows and height.

I hope this clarifies everything.

If you don't need Drag and Resize then please use https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout
FYI functions on pretty much the same principle.

**Comment by naveenamruth** [comment]
Awesome!!!

Such a great response in minutes :) ... I appreciate, Thank you.

I will look into this and let you know if I have any more questions.

**Comment by naveenamruth** [comment]
@tiberiuzuld ,

I think, the logic to build the grids is very tuff or am I missing something,

So, here is my understanding of logic to constructs rows and cols. It'd be great if you could help me out to explain. 

![image](https://user-images.githubusercontent.com/8732898/35066670-721ffc06-fb9f-11e7-9f9a-261f176043d0.png)

**Comment by tiberiuzuld** [comment]
The 0, 0 is at top left corner
Cols go from 0 to N from left to right
Rows go from 0 to N from top to bottom
Widgets cannot go bellow 0
Widgets can go to +infinity with the correct config.
