### ISSUE TITLE
How do I mange responsiveness for different device sizes (xl, lg, md, sm, xs) ?

### ISSUE THREAD

**Issue by shivam25** [tiberiuzuld/angular-gridster2#218]
Hello @tiberiuzuld ,

The responsiveness support I can see as of now is for single breakpoint, and reaching there all widgets are re-arranged in a single lane in a stacked layout. Is there any way, I can define multiple breakpoints like below:
xl breakpoint - 8 columns
lg breakpoint - 6 columns
---- likewise.

Please help.

**Comment by tiberiuzuld** [comment]
Hi @shivam25 ,
Yes you can with [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) and `@media-queries`
You can override the css `gridster.mobile` with your own and you can define your own columns.
You will not be able to drag and resize.

There is no way for the grid to work with drag and resize when you move the widgets depending of the size.

**Comment by gs-vappannagari** [comment]
Hi @tiberiuzuld 
Do we have a codepen demonstrating multiple breakpoints?
It will be a great help for us

Thanks
