### ISSUE TITLE
Drag does not work on firefox

### ISSUE THREAD

**Issue by red-0ne** [tiberiuzuld/angular-gridster2#22]
Drag event does not seem to be handled on firefox. Even the online demo does not work.

**Comment by tiberiuzuld** [comment]
Hi @red-0ne ,
Thank you for reporting this issue.
Fixed in v2.7.2 , I used by mystake a experimental feature only available in chrome. [here](https://developer.mozilla.org/en-US/docs/Web/API/Event/deepPath)

Thanks,

**Comment by red-0ne** [comment]
Excellent. Any chance to get this release on npm?

**Comment by tiberiuzuld** [comment]
Ops , will do it now.

**Comment by tiberiuzuld** [comment]
Done

**Comment by red-0ne** [comment]
Thank you.
