### ISSUE TITLE
CSS conflict with Bootstrap

### ISSUE THREAD

**Issue by MelissaVanDijk** [tiberiuzuld/angular-gridster2#220]
Hi @tiberiuzuld,

We'd like to use your grid but at the moment the CSS is conflicting with Bootstrap in our project.
Bootstrap uses class "row" and when we put your grid in any of the Bootstrap rows, the Bootstrap rows get a white border and the width is put to 100%.
Can you make your CSS local to the < gridster-grid > tag? 
Thanks in advance!

Melissa van Dijk

**Comment by tiberiuzuld** [comment]
Hi @MelissaVanDijk ,

Yes will try to make it today.

Thanks

**Comment by tiberiuzuld** [comment]
Ok now it should be fixed in v4.4.2

Thanks again, this slipped when I removed encapsulation in v4.4.0

**Comment by MelissaVanDijk** [comment]
Yes it is fixed now! Thank you very much for the -VERY- quick reply. :-)

**Comment by dennisfleischmann** [comment]
Hi together. We are trying to use your drag and drop library and tried to use it with bootstrap, without success. Can you please give us an example how to use it or even better to provide an documentation. Thank you very much! BTW awesome framework

**Comment by tiberiuzuld** [comment]
Hi @dennisfleischmann ,
Documentation is directly on [Readme.md](https://github.com/tiberiuzuld/angular-gridster2)
Demo app: https://tiberiuzuld.github.io/angular-gridster2/angular/
Source code for demo app: https://github.com/tiberiuzuld/angular-gridster2/tree/master/src/app

There shouldn't be any issues with the bootstrap.
In this issue there was a css class conflict.
