### ISSUE TITLE
drag one item on top of another

### ISSUE THREAD

**Issue by olivaresdeveloper** [tiberiuzuld/angular-gridster2#221]
I have a component or a specific section of a design. I want to drag one element to another (on top of it) in the design and modify it with the characteristics of the library, this library can fulfill what is desired or there is a function that was not added.

**Comment by tiberiuzuld** [comment]
Hi @olivaresdeveloper,
You cannot drag items over another item in this library.

**Comment by maheshchari** [comment]
It is great library , i love it, but i suggest if we can have overlap element on top of other it will fit like layout component , can you suggest if you have any future road map for this?

**Comment by tiberiuzuld** [comment]
Can you show me a mock design so I get what you want please.
For this to work most probably will have to have disable for push.

**Comment by jayaseshuq** [comment]
I need a Layout with option to overlap a widget on another. Will it be possible?

**Comment by maheshchari** [comment]
![image](https://user-images.githubusercontent.com/503005/36726455-d83b5d90-1bdf-11e8-84e7-3c41d7af49d8.png)

Please find attached image where one element can be placed over another .

**Comment by tiberiuzuld** [comment]
Ok
Questions: 
1. You want a callback when the item is droped ? With arguments source and target items.
2. The droped item should be removed from the grid by the library ?
3. The `gridster-preview` should display as in image or not render if this option is enabled?

**Comment by maheshchari** [comment]
Following exactly my requirements

-  Disable auto align (PUSH) elements  to grid completely 
-  Every element should be movable freely over a bounding box 
-  Every element should be resizable freely without auto align (PUSH) of other elements

**Comment by tiberiuzuld** [comment]
What you said is already possible.
You can disable push option.

Still not answering my questions ...

**Comment by maheshchari** [comment]
Please find my comments
- You want a callback when the item is droped ? With arguments source and target items. Yes, 
- The droped item should be removed from the grid by the library ? No
- The gridster-preview should display as in image or not render if this option is enabled? when an item is over another item. Yes

**Comment by tiberiuzuld** [comment]
Most probably will implement it in 5.x currently focused on finishing the changes for 5.0.0

**Comment by RajVrach** [comment]
Hi..like to know how we can do as shown in attached image.
how we add multiple items in 1 grid cell
before:
![2_items_in_2](https://user-images.githubusercontent.com/14893895/36865604-f5a6ff9a-1d5d-11e8-99bb-e6e7ac5ba7cc.png)

after:
![2_items_in_1](https://user-images.githubusercontent.com/14893895/36865618-0260cb80-1d5e-11e8-86b1-5694bc810616.png)

can you point out in code where it could be possible..we can submit update if we are able to make it work.
this will make your library better to support all the Calendar/Scheduler tools people want to make along with us :) 

PS: also the original question of how to lay one on top of other is important too as both could happen.
 
Thanks
Raj

**Comment by tiberiuzuld** [comment]
Hi @RajVrach ,
Please don't use this library for a calendar/schedule
This library is not made to work for a calendar.
This library will never support multiple items in one cell.
One cell can only be occupied by one item.

Please use a calendar library.

Thanks

**Comment by RajVrach** [comment]
@tiberiuzuld.. ok
Thanks..

**Comment by MarcoAbi** [comment]
I would be glad to support you with testing of the "overlap" feature.

Thanks for this great piece of work!!

**Comment by tiberiuzuld** [comment]
Added in v5.1.0
