### ISSUE TITLE
GridsterPush doesn't work with collision detection

### ISSUE THREAD

**Issue by VirsaeAllenZhang** [tiberiuzuld/angular-gridster2#223]
When I resize from code, collision detection works fine when item size is 1, 1.
But when item size is 2, 2, and there are multiple items next to each other, the resize action doesn't push other items.
As shown here:
https://stackblitz.com/edit/angular-gridster-8nvsmm?file=app%2Fhello.component.ts
when I hit the button to resize the top left item, it doesn't push other items. 
It works fine when the item size is changed to 1,1

**Comment by tiberiuzuld** [comment]
Hi @VirsaeAllenZhang ,
Yes there is some issues there.
The documentation is a bit wrong.
The `pushItems` method should return a boolean. So if push is not successful to be able to revert.
And the push is not working with +1. Really strange.

Will try to have a fix this week.

```javascript
 const pushResize = new GridsterPush(itemConponent);
          itemConponent.$item.cols += 1;
          itemConponent.$item.rows += 1;
          pushResize.pushItems(pushResize.fromNorth)
          pushResize.pushItems(pushResize.fromWest)
             pushResize.checkPushBack();
             itemConponent.setSize(true);  
             itemConponent.checkItemChanges(itemConponent.$item, itemConponent.item);
             pushResize.setPushedItems();
             pushResize.destroy();
```

Thanks,

**Comment by VirsaeAllenZhang** [comment]
Thanks for the fast response. Looking forward to the fix.

**Comment by tiberiuzuld** [comment]
Hi @VirsaeAllenZhang ,
Changed a bit the api so you get boolean if push was successful or not.
Managed to make it work with the following code:
```javascript
    // this.dashboard.splice(this.dashboard.indexOf(item), 1);
    const push = new GridsterPush(this.itemComponent); // init the service
    this.itemComponent.$item.rows += 1; // move/resize your item
    if (push.pushItems(push.fromNorth)) { // push items from a direction
      push.checkPushBack(); // check for items can restore to original position
      push.setPushedItems(); // save the items pushed
      this.itemComponent.setSize(true);
      this.itemComponent.checkItemChanges(this.itemComponent.$item, this.itemComponent.item);
    } else {
      this.itemComponent.$item.rows -= 1;
      push.restoreItems(); // restore to initial state the pushed items
    }
    this.itemComponent.$item.cols += 1;
    if (push.pushItems(push.fromWest)) { // push items from a direction
      push.checkPushBack(); // check for items can restore to original position
      push.setPushedItems(); // save the items pushed
      this.itemComponent.setSize(true);
      this.itemComponent.checkItemChanges(this.itemComponent.$item, this.itemComponent.item);
    } else {
      this.itemComponent.$item.cols -= 1;
      push.restoreItems(); // restore to initial state the pushed items
    }
    push.destroy(); // destroy push instance
```

Sometimes the push will not work because of this issue https://github.com/tiberiuzuld/angular-gridster2/issues/208

The changes to the api will be in the next release.

**Comment by tiberiuzuld** [comment]
Fixed in v4.6.0

**Comment by VirsaeAllenZhang** [comment]
Hi Tiberiu,

Really appreciated the fix.
I tried it and it works fine.

However, the v4.6.0 version only work with angular 5. But we’re on angular 4 and not quite ready to upgrade to 5, yet.

Can you kindly merge this fix to the 3.x.x branch for angular 4, please?

Regards,
Allen

**Comment by tiberiuzuld** [comment]
Will try this week.

**Comment by VirsaeAllenZhang** [comment]
@tiberiuzuld , thanks a lot. really appreciated.
