### ISSUE TITLE
resize grip (handler-se) not positioned correctly when scrolling

### ISSUE THREAD

**Issue by MelissaVanDijk** [tiberiuzuld/angular-gridster2#225]
Hi Tiberiu,

For using the grid on a rather small screen, we added auto-scrollbars to the gridster-items by setting the following css:
gridster-item { overflow: auto!important; }

When hovering, the handler-se is nicely placed in the right bottom corner with position:absolute :
![image](https://user-images.githubusercontent.com/29451068/35243393-f5fed30a-ffbc-11e7-98cc-6113a272f684.png)

But when scrolling to the right, the handler-se moves to the left along with the content of the gridster-item:
![image](https://user-images.githubusercontent.com/29451068/35243249-77a4f124-ffbc-11e7-9a51-2b82435feea8.png)

Can you fix this or help me with some external styling how to set this right?

Thanks in advance!
Melissa

**Comment by tiberiuzuld** [comment]
Hi @MelissaVanDijk ,
Try adding the scrollbars to some div inside the gridster-item.
 ```html
<gridster-item>
  <div class="gridster-item-content">
      Some content to select and click without dragging the widget
  </div>
</gridster-item>
```
On gridster-item-content for example.

**Comment by MelissaVanDijk** [comment]
Thank you! That works. Solved :-)
