### ISSUE TITLE
Add Change log

### ISSUE THREAD

**Issue by rajesh-kanakabandi** [tiberiuzuld/angular-gridster2#23]
please provide a change log between releases so users are aware of breaking changes on new releases.

**Comment by tiberiuzuld** [comment]
The changelog is here in releases https://github.com/tiberiuzuld/angular-gridster2/releases

**Comment by rajesh-kanakabandi** [comment]
@tiberiuzuld the url that you shared is to the releases page. 
here is an example change log.
https://github.com/valor-software/ng2-charts/blob/master/CHANGELOG.md

which has a more detailed description of changes and breaking changes between releases.

**Comment by tiberiuzuld** [comment]
Ok @rajesh-kanakabandi  added better styling for release notes
This is ok if I maintain this style of release notes for the next releases ?

**Comment by rajesh-kanakabandi** [comment]
@tiberiuzuld this should be sufficient. it will also be a good idea to include breaking changes when applicable.
thank you very much for all the work.
