### ISSUE TITLE
Drag&Drop shadow at wrong position

### ISSUE THREAD

**Issue by BrummbQ** [tiberiuzuld/angular-gridster2#234]
Hi,
When setting compactType to compactUp or compactLeft, items are pulled correctly towards the "gravity". But the drag&drop shadow doesn't reflect this behaviour. Instead it indicates a valid drop position i.e. at the bottom, but when releasing the tile jumps to the top.

**Comment by tiberiuzuld** [comment]
Hi @BrummbQ ,
Yes that is correct.
The shadow position is not reflecting the correct position when the item will drop.

Will try to have a fix this week.

Thanks

**Comment by tiberiuzuld** [comment]
It was interfering with the Push.
The compact had to run only for the item which is dragged.
Changed a bit the GridsterCompact and made it work.
Also was creating weird issue on Resize so made it to check for compact only when dragging.

**Comment by tiberiuzuld** [comment]
Released v4.6.1 with the fix.

**Comment by BrummbQ** [comment]
Great! Thank you
