### ISSUE TITLE
Is it possible to load widget positions from server 

### ISSUE THREAD

**Issue by shootermv** [tiberiuzuld/angular-gridster2#236]
Hi, in my scenario user should be able to save widgets positions, after that - positions must persist.
I managed to make the initial positions to change after response came from server :
([stackblitz demo](https://stackblitz.com/edit/loadin-gridster-positions?file=app%2Fapp.component.ts))
Only by hide the gridster with *ngIf until data loaded...
Is this the only way to achieve this?
Thanks

**Comment by tiberiuzuld** [comment]
Hi @shootermv ,
Yes you can.
You need to save on server {x, y, cols, rows} and an extra id if you need it.
You don't init the grid till the list of widgets are retrieved from server.
Using the callback from `gridOptions.itemChangeCallback(widget)`
You can save each time there is a change.

 Let me know if this clarifies the things.

**Comment by shootermv** [comment]
Thank u very much for quick response, But what exactly you mean by "You don't init the grid till the list of widgets are retrieved from server"? 
Thanks

**Comment by tiberiuzuld** [comment]
You can put one *ngIf on the gridster element and when the items come from server then you make true the *ngIf
Or you init the grid but your list of widgets is empty.
When the request from server arrives you set that variable with your list from server.

**Comment by galvakojis** [comment]
Is it possible to do the same if gridster item is FormGroup.
I get warning 

> : TS2339: Property 'cols' does not exist on type 'FormGroup'
