### ISSUE TITLE
Output to bootstrap grid HTML 

### ISSUE THREAD

**Issue by toregua** [tiberiuzuld/angular-gridster2#237]
First thanks for your really great component.

I need to export my gridster grid to a static HTML bootstrap grid (with nested rows if gridster rows > 1) Do you have any ideas how to do that ? 

I don't know how to start... first i was thinking to start by browsing x coordonnate but i don't know how to convert/export data in this way.

Any help will be really appreciate.

**Comment by tiberiuzuld** [comment]
Hi @toregua ,
Well maybe just convert the widget `{x, y, rows, cols}` in appropriate classes for bootstrap.
And you generate the HTML with the appropriate html for each widget.
Didn't worked with bootstrap in years so don't know exactly what classes they use now.

**Comment by toregua** [comment]
Hi @tiberiuzuld thank you for helping me. It is not so easy (or maybe I missing something). 
If i allow only one row max for a widget it is simple and its works well by creating a simple bootstrap row containing x col-md classes for each widget but when i try to allow a widget to be on multiple rows it become really difficult beceause with bootstrap in order to do that i need to create nested rows : [nested grid with bootstrap 4](https://v4-alpha.getbootstrap.com/layout/grid/)

Is there that i have lot of difficulties to convert gridster grid system {x, y, rows, cols}

I try to explain with an example : 
[Schema from my gridster](http://nsa39.casimages.com/img/2018/02/02/180202093617712364.jpg)

With bootstrap to do the same grid i need to generate : 

`<div class="row">
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-6">
				<div style="width:100%;background-color:#000;height:100px;">1</div>
			</div>
			<div class="col-md-6">
				<div class="row">
					<div class="col-md-12">
						<div style="width:100%;background-color:#000;height:100px;">2</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<div style="width:100%;background-color:#000;height:100px;">4</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div style="width:100%;background-color:#000;height:100px;">5</div>
			</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="row">
			<div class="col-md-12">
				<div style="width:100%;background-color:#000;height:100px;">3</div>
			</div>
		</div>
	</div>
</div>`

**Comment by tiberiuzuld** [comment]
Well what can I say, that's why didn't made the gridster in boostrap.
I don't think with bootstrap you can have items which intersects on multiple rows with other items which start on different row.
Maybe try to export to [CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)

**Comment by toregua** [comment]
It is true that's why I use this options in order to be close to bootstrap behavior : 

```
        this.options = {
            gridType: 'verticalFixed',
            minCols: 4,
            maxCols: 4,
            minRows: 1,
            maxRows: this.nombreLignesMax ? parseInt(this.nombreLignesMax) : 50,
            displayGrid: 'always',
            pushItems: true,
            fixedRowHeight: 300, // fixed row height for gridType: 'fixed'
            compactType: 'compactLeft',
            scrollToNewItems: true,
            enableEmptyCellDrag: true,
            emptyCellDragMaxCols: 4,
            emptyCellDragMaxRows: 1,
            emptyCellDragCallback: this.ajouterElement.bind(this),

        };
```

I don't have the choice, i need to use bootstrap.
I see only two options for me:
- I found a solution to convert {x, y, rows, cols} to row and col-md bootstrap classes
- I force one row in gridster max for each widget and i use a workaround by addind inside a widget another gridster by zooming system
