### ISSUE TITLE
First dashboard item

### ISSUE THREAD

**Issue by Kalemstorm94** [tiberiuzuld/angular-gridster2#239]
Hello again!
 I have an app-component template that contains the gridster. Inside the gridster, I try to dynamically add other components (maybe some of them multiple times). Inside my app.modules `@NgModule`, if I have ` bootstrap: [AppComponent]` everything works well. If I have  `entryComponents: [AppComponent, ...,OtherComponents, ...]` the gridster will load the data for all the components, but it will not render the template for the first one. If I try to make a clone of the first one, and then delete the original, the same thing will happen with the second component. 

Do you have any idea about this behaviour? I know that with entryComponents, the AppComponent is not treated as a root component, but as a simple parent. Still I don't understand why it has this problem.

**Comment by tiberiuzuld** [comment]
HI @Kalemstorm94 ,
I have no idea, probably has to do with the template and entryComponents, try adding the template separate of the gridster. See if that works.

**Comment by Kalemstorm94** [comment]
If I try to load the other components separate from the gridster, it will work, all of them will be rendered.  With the gridster, the data is brought correctly for each component, but the first one will always remain blank.

**Comment by tiberiuzuld** [comment]
Strange maybe when the template is rendered for the first time it has height and width 0.
Try using ngIf with itemInitCallback or try a setTimeout with some update to size in the template.

**Comment by Kalemstorm94** [comment]
I've tried this, but no success. I'll let you know if I'll resolve this issue.

**Comment by tiberiuzuld** [comment]
Close for inactivity.
