### ISSUE TITLE
Division by zero when testing with phantomJS

### ISSUE THREAD

**Issue by MelissaVanDijk** [tiberiuzuld/angular-gridster2#240]
Hi Tiberiu,

For our project that uses the grid, we added Karma test cases. A grid is created with 4 grid components in it.
When using "ng test" this works fine, but when testing in 'silent' mode, with "browser=phantomJS" we get errors, always on line 38 of gridsterGrid.component.js:

this.columns.length = Math.max(this.gridster.columns, Math.floor(this.gridster.curWidth / this.gridster.curColWidth)) || 0;

Logging the variables says that this.gridster.curColWidth is 0, so a division by zero takes place. 
The curColWidth is Probably zero because using phantomJS the dimensions cannot be calculated correctly.

For now we workaround this (dirty) by setting the option "margin" to a negative number (for example -20). 
This works because then we get a positive number in the method "calculateLayout":
this.curColWidth = (this.curWidth - this.$options.margin) / this.columns;

Do you have any suggestions how we should test with phantomJS so the tests won't fail?
Our test command is:
ng test --watch=false --single-run=true --reporters=junit,progress --browsers=PhantomJS --progress=false

Thanks in advance!

**Comment by tiberiuzuld** [comment]
Hi @MelissaVanDijk ,
Just tested my code there:
```javascript
Math.max(10, Math.floor(0/0)) || 0
```
Works perfectly fine without an error.
It will set the grid columns to 0. 
If you don't test the grid lines then it should be fine.

Maybe try to run the unit tests in [chrome headless](https://github.com/karma-runner/karma-chrome-launcher)
It should render the grid correctly and run faster.

Let me know if this fixes your issue.

Thanks

**Comment by tiberiuzuld** [comment]
Close for inactivity.
