### ISSUE TITLE
Get position base on mouse events

### ISSUE THREAD

**Issue by IThordGray** [tiberiuzuld/angular-gridster2#241]
Hi there, 

I've got a situation where I want to get the position of the GridsterItem in relation to the mouse.

So basically when I drop something, I want to manually get the position of where I ended the drop.
Possibly exposing the 'getValidItemFromEvent' method? Maybe this is something that can be looked at?

Regards

**Comment by tiberiuzuld** [comment]
Hi @IThordGray ,
Will look into it to add the original event to the callbacks from drag and resize.

Thanks

**Comment by IThordGray** [comment]
Thanks for the quick response.

Appreciate it

**Comment by tiberiuzuld** [comment]
Hi @IThordGray ,
Initially look a bit fast over the issue and forgot that there is already options to get hold of the mouse event:

```
emptyCellClickCallback
emptyCellContextMenuCallback
emptyCellDropCallback
emptyCellDragCallback
draggable.start
draggable.stop
resizable.start
resizable.stop
```
I don't get it what exactly you want from:

> So basically when I drop something, I want to manually get the position of where I ended the drop.

**Comment by IThordGray** [comment]
Hi again,

I am using the callbacks where applicable. Internally though they seem to use 'getValidItemFromEvent' in order to give you the gridster-item. In my use case, I would like access to this/ or a similar method to manually, without the callback, find the item based on a mouse event that I'll be passing through as a parameter.

**Comment by tiberiuzuld** [comment]
You should be able to do something like this:
```
import GridsterEmptyCell from 'angular-gridster2/lib'
...

this.options.initCallback = this.onGridInit.bind(this);

onGridInit(gridster){
 this.emptyCell = new GridsterEmptyCell(gridster); 
}

myEvent(event){
 const item = this.emptyCell.getValidItemFromEvent(event);
 if(item){
  // do stuff
 }
}

onDestroy(){
  this.emptyCell.destroy();
}

```

Let me know if this will solve your use case.

Thanks

**Comment by IThordGray** [comment]
Hi there,

Sorry for not getting back to you sooner. This seems to do the trick. Thank you for the assistance!

**Comment by viethien** [comment]
I use import GridsterEmptyCell from 'angular-gridster2/lib'
It show: **error TS2307: Cannot find module 'angular-gridster2/lib'.**

**Comment by viethien** [comment]
I can get position of item by emptyCellDropCallback, but this event called twice. 

Can you explain why? Thanks
