### ISSUE TITLE
Show/ expose GridPreview for custom use

### ISSUE THREAD

**Issue by IThordGray** [tiberiuzuld/angular-gridster2#242]
Hi there.

I want to be able to drag something onto the grid, but if it has 'rows' and 'cols', I'd like to be able to show the preview during the drag event. (this is when dragging anything, not an item on the grid). 

Is this possible?

Regards

**Comment by tiberiuzuld** [comment]
Hi @IThordGray ,
At first I created it with a preview but was really slow the callback for drag over so I had to remove it.

**Comment by IThordGray** [comment]
I really didn't expect such a quick response. 
Thanks!

It would make sense that it would slow things down quite a bit. 
Thanks for that
