### ISSUE TITLE
Is there any way to call specific method after arranging all the widget in dashboard?

### ISSUE THREAD

**Issue by kaushikgotefode** [tiberiuzuld/angular-gridster2#243]
Hi,
Is there any way to call specific method after arranging all the widget in dashboard?

now I am calling **itemChangeCallback** method, but this callback triggering multiple time on drag-and-drop of widget as widgets are more than one.

So I want to know that is there any way to call method after re-arranging all the widget on drag-and-drop, so that I can update the position of these widget at a time by calling sever API.

**Comment by tiberiuzuld** [comment]
Hi @kaushikgotefode ,
You don't need to call `itemChangeCallback`. The library calls your method set on the option `itemChangeCallback`.
Its up to you what you do in that callback.
You can do a debounce or have a separate save button, and send all the changes when the user has finished.
The library doesn't know when the user has finished.

**Comment by kaushikgotefode** [comment]
@tiberiuzuld 
we don't have any other action options on the page, other than this drag-and-drop .
anyway Thanks for your quick reply.
