### ISSUE TITLE
itemChangeCallback vs itemResizeCallback

### ISSUE THREAD

**Issue by brianpkelley** [tiberiuzuld/angular-gridster2#249]
I noticed that the item change and resize callbacks are called with different values for the item.

Noticeable in this stackblitz.  It looks like the item size is adjusted after the resize callback is fired.

https://stackblitz.com/edit/angular-ex5mkg

**Comment by tiberiuzuld** [comment]
Hi @brianpkelley ,
Yes seems the the resize callback is called before the changes are applied to the item.
Will try to have it fixed this week.

Thanks

**Comment by tiberiuzuld** [comment]
Fixed in v4.6.2
Now the callbacks are called in reversed order but with the correct info.

Thanks
