### ISSUE TITLE
create a fixed 2 column with vertical scroll

### ISSUE THREAD

**Issue by jtushar53** [tiberiuzuld/angular-gridster2#25]
Hi,

how to get setting 2 column width with vertical scroll grid.

whenever i add 5th item the grid gets converted to 3 column grid and i've also tried setting maxcolumn to 2 and also tried with fixed grid still no luck.

**Comment by tiberiuzuld** [comment]
Hi,
Yes seems like a bug, will fix it today

**Comment by tiberiuzuld** [comment]
Hi @jtushar53 ,
I looked over the issue you are having and for me it seems to be working as intended.
So if you set  `gridType: 'scrollVertical';` and `maxCols:2` you should be able to have the effect you want.

I updated the demo to have min/max rows/cols options so now you can test this directly on the demo.
![image](https://cloud.githubusercontent.com/assets/15310395/24993971/6c0f10da-2031-11e7-864a-196dd6d04465.png)

If maxCols option is set after widgets that conflict are placed, the widgets will not be re-positioned. 
But for example if you have a widget with conflict to the grid maxCols/maxRows and is placed after the grid options are set then the widget will be re-positioned.

So delete/drag all widgets that conflict then set Max Grid Cols to 2.
Now you can keep adding widgets without the grid expanding the number of columns.

Let me know if you have any more issues.

**Comment by jtushar53** [comment]
Hi @tiberiuzuld ,

thanks its working now.
