### ISSUE TITLE
Code for the demo

### ISSUE THREAD

**Issue by xbotuk** [tiberiuzuld/angular-gridster2#250]
Where can we download the code for the demo of
http://tiberiuzuld.github.io/angular-gridster2/angular
please?

**Comment by mhartkorn** [comment]
[In this very repo.](https://github.com/tiberiuzuld/angular-gridster2/tree/master/src)

**Comment by xbotuk** [comment]
Thanks mhartkorn.

Is there an example what has gridster with ng-dynamic-component library?

**Comment by tiberiuzuld** [comment]
https://github.com/tiberiuzuld/angular-gridster2/issues/51
