### ISSUE TITLE
Disable logging

### ISSUE THREAD

**Issue by xbotuk** [tiberiuzuld/angular-gridster2#253]
How can I disable the console logging for gridster components?
I have added disableWarnings: true
however still getting logs.

**Comment by tiberiuzuld** [comment]
Hi @xbotuk ,
There are only 2 warning logs in the library. 
Both of them are conditioned if the option `disableWarnings` is set to true.
What other logs you have ?

**Comment by xbotuk** [comment]
Its not an issue. It was me overlooking the logging done by static functions in the sample codebase:

   https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/app/app.component.ts
