### ISSUE TITLE
Conflicts in dragging of GridsterItem

### ISSUE THREAD

**Issue by xbotuk** [tiberiuzuld/angular-gridster2#255]
I have a gridsteritem (as ng-dynamic-component) that has dragging enabled for some smaller parts of section. Is it possible to do either of the following?

- change priority order so that the gridsteritem gets lower priority for dragging
- change priority order so that the relevant content of the component gets higher priority for dragging
- allow dragging on parts of the gridster item, i.e. on the header/footer/sides (upto configured pixels i.e. 30px from edges)

**Comment by tiberiuzuld** [comment]
Hi @xbotuk ,
In readme.md https://github.com/tiberiuzuld/angular-gridster2#interact-with-content-without-dragging

There is no priority option.
If you have content which you want to drag then you need to `event.stopPropagation()`
