### ISSUE TITLE
Fill all spaces during resize in "Fit to Screen" grid type

### ISSUE THREAD

**Issue by sriksp001** [tiberiuzuld/angular-gridster2#256]
Hi,
While resizing an item in "Fit to Screen" grid type, is there any way make all the other items push to fill the empty areas ?

Thanks for the nice work.

![image](https://user-images.githubusercontent.com/34489892/36627615-096501d4-18fa-11e8-986c-226df0cd7a61.png)

**Comment by tiberiuzuld** [comment]
HI @sriksp001 ,
No there is no way.
Push is done to push items in a certain directions depending from what direction you drag.

Thanks
