### ISSUE TITLE
Accessing component instance methods

### ISSUE THREAD

**Issue by xbotuk** [tiberiuzuld/angular-gridster2#257]
<gridster [options]="options" *ngIf="!remove" style="background-color:#f5f5f5">
    <gridster-item [item]="item" *ngFor="let item of dashboard">
        <ndc-dynamic [ndcDynamicComponent]="item.component" [ndcDynamicInjector]="_vcr.parentInjector" [ndcDynamicInputs]="item.inputs"></ndc-dynamic>
    </gridster-item>
  </gridster>

I have a Gridster dashboard defined with the above template and I would like to be able to access the component that renders when items are resized. However is unable to access it. 

I tried this:
    itemComponent.item.component.prototype.XX()

which seems to call the function XX() of the generic component, not the actual object instance that renders the actual gridsteritem.

I would really appreciate your help. Thanks

**Comment by tiberiuzuld** [comment]
Hi @xbotuk ,
I don't get it what component you want to access ?
Your component or the gridsterItemComponent.
Why do you need to access it?
If you want to access your component ask at https://www.npmjs.com/package/ng-dynamic-component
