### ISSUE TITLE
Issue with SVG elements

### ISSUE THREAD

**Issue by bajzat** [tiberiuzuld/angular-gridster2#258]
HI,

We are using SVG elements inside the grid-item component to show charts and we are facing an issue when the dragging enabled (the drag handler has been specified) in the gridster settings. When we click on the SVG element the following exception has been thrown by the gridster only in IE11:

Unable to get property 'contains' of undefined or null reference: TypeError: Unable to get property 'contains' of undefined or null reference at GridsterDraggable.prototype.dragStartDelay (eval code:203:9) at Anonymous function (eval code:2680:9) at ZoneDelegate.prototype.invokeTask (eval code:419:13) at onInvokeTask (eval code:4939:17) at ZoneDelegate.prototype.invokeTask (eval code:419:13) at Zone.prototype.runTask (eval code:188:21) at ZoneTask.invokeTask (eval code:496:17) at invokeTask (eval code:1517:9) at globalZoneAwareCallback (eval code:1543:17)

I've found the issue in the gridsterDraggable.service.ts (dragStartDelay function), it tries to get the classlist from the target element but it is not supported on SVG elements.

https://developer.mozilla.org/en-US/docs/Web/API/Element/classList

Best Regards

Tamas

**Comment by tiberiuzuld** [comment]
Hi @bajzat,
Will try to have a fix today.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @bajzat ,
Fixed in v4.6.3

Thanks

**Comment by bajzat** [comment]
Thanks for the quick response and fix! Really appreciate it!
