### ISSUE TITLE
itemResize, itemChange not getting fired 

### ISSUE THREAD

**Issue by rishi-ios** [tiberiuzuld/angular-gridster2#26]
Hello,

I am integrating your component in my Angular 4 project. I have created a simple grid by following sample code, its running fine and I am able to see a widget in dashboard. But I am not getting any itemResize or itemChange events when I resize grid item.

I am also attaching code files for your reference(Please remove trailing .txt extension from files). 

Please check and let me know if I am missing anything at my end.

Browser : Chrome

Project Config :

 `"@angular/animations": "^4.0.2",
    "@angular/common": "^4.0.2",
    "@angular/compiler": "^4.0.2",
    "@angular/core": "^4.0.2",
    "@angular/flex-layout": "^2.0.0-beta.7",
    "@angular/forms": "^4.0.2",
    "@angular/http": "^4.0.2",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.2",
    "@angular/platform-browser-dynamic": "^4.0.2",
    "@angular/router": "^4.0.2",
    "angular-gridster2": "^2.7.4",`

Thanks 

[app.component.ts.txt](https://github.com/tiberiuzuld/angular-gridster2/files/919234/app.component.ts.txt)
[app.component.html.txt](https://github.com/tiberiuzuld/angular-gridster2/files/919233/app.component.html.txt)

**Comment by tiberiuzuld** [comment]
Hi @rishi-ios ,
Yes it seems that the events are not fired. Will have it fixed today.
Thank you for reporting this.

**Comment by tiberiuzuld** [comment]
Hi @rishi-ios ,
Fixed in v2.7.6
Let me know if you find any more issues.

**Comment by rishi-ios** [comment]
Thanks @tiberiuzuld 

Really appreciate your quick fix 👍 .

Also I have one more query, right now I am using grid item with vertical scroll with max columns 2.
By default on inserting any new record it goes through at the end of all grid items(on bottom). 
But what I want is that if a new item is added to the grid it should come at first place(on top).

I tried with following code to use array `unshift` in place of `push` but it didn't worked.

`        this.dashboard.unshift ({
            cols: 1,
            rows: 1,
            minItemRows: 2,
            minItemCols: 2,
            label: 'move to first place',
            dragEnabled: true,
            resizeEnabled: true
        });`

Can you please let me know how to insert grid item from top.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @rishi-ios 
The position in array doesn't matter you need to modify to set `y = 0` and `x= 0 or 1` and move all other widgets to `y +=1` .

The lib code on new item will do this.
```javascript
if (item.x === undefined || item.y === undefined) {
      this.autoPositionItem(item);
    } else if (this.checkCollision(item)) {
      console.warn('Can\'t be placed in the bounds of the dashboard, trying to auto position!/n' +
        JSON.stringify(item, ['cols', 'rows', 'x', 'y']));
      item.x = undefined;
      item.y = undefined;
      this.autoPositionItem(item);
    }
```

1. So first move all widgets on the first column (`x == 0`) you have to  `y +=1` .
2. Call grid `this.options.optionsChanged();` to know that options changed externally
3. Then push the new widget `this.dashboard.push({ cols: 1, rows: 1, x: 0, y: 0, label: 'move to first place', dragEnabled: true, resizeEnabled: true });`

Let me know if this works. Didn't test it.

**Comment by rishi-ios** [comment]
Thanks @tiberiuzuld 

I checked it and its working right as you mentioned 👍
