### ISSUE TITLE
Grid Settings drawer unusable in IE

### ISSUE THREAD

**Issue by adamlubek** [tiberiuzuld/angular-gridster2#260]
hey, first of all amazing package! Unfortunately though, grid settings drawer isn't usable in IE:

![2018-02-26 14_26_11-](https://user-images.githubusercontent.com/8349742/36675606-661c1634-1b01-11e8-99e7-8978b46df093.png)

**Comment by tiberiuzuld** [comment]
Hi @adamlubek ,
Will try to have it fixed soon.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @adamlubek ,
The issue happens because IE11 doesn't support CSS grid auto placement.
Since this affects only the demo page will not fix it, since requires to change to a float or display: flex layout.

In version 6 the grid will also be rendered with display: grid.
I am not sure that the library will work from that version on IE11.
https://github.com/tiberiuzuld/angular-gridster2/issues/230


Thanks

**Comment by adamlubek** [comment]
as FYI, this doesn't work in edge too. I think this discourages potential users.

**Comment by tiberiuzuld** [comment]
Tested in Edge 16 and works 
![image](https://user-images.githubusercontent.com/15310395/36722625-ac7fcebc-1bb6-11e8-8ad0-2f43b6972e77.png)

**Comment by adamlubek** [comment]
ver 16 is 3 years old. it doesn't in newer ones, here's result for ver 40:

![2018-02-27 11_10_17-gridster2 - microsoft edge](https://user-images.githubusercontent.com/8349742/36725687-fff4596c-1bae-11e8-933d-4ecfabdf7cd0.png)

**Comment by tiberiuzuld** [comment]
I am referring to version 16 of EdgeHTML
![image](https://user-images.githubusercontent.com/15310395/36726050-0d1faada-1bc1-11e8-88bd-5db2b9432045.png)

**Comment by tiberiuzuld** [comment]
All tools out there are referring to that version to be the version of the browser.
https://caniuse.com/#feat=css-grid
Even the `navigator.userAgent` says so:
`"Mozilla/5.0 (Windows NT 10.0; Win64; x64; ServiceUI 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299"`

**Comment by adamlubek** [comment]
sorry, misunderstood, all good then :)
