### ISSUE TITLE
Show gridster item full screen ?

### ISSUE THREAD

**Issue by MelissaVanDijk** [tiberiuzuld/angular-gridster2#264]
Hi there,

We love the grid! We have a question (which was adressed earlier about zooming in). It would be really great if we could temporarly show one item in the grid full screen temporarily, and then switch back to show all items. Is this already possible in some way? And if not, would it be a lot of work to build in?

Thanks in advance!

**Comment by tiberiuzuld** [comment]
Hi @MelissaVanDijk ,
There is no built in solution.

Do you need actual browser fullscreen? then look over https://github.com/sindresorhus/screenfull.js/

If you mean just as showing the widget in a state where is covering 100% of the page?
Then you can look over this https://github.com/tiberiuzuld/angular-gridster2/issues/38

Or you can do a separate state in your app where the widget is the only one rendered.
This is what I use currently.

Thanks

**Comment by MelissaVanDijk** [comment]
Thank you, we want one widget to take over the entire grid (maximize), and then scale it back to see all widgets again. 
I will take a look at #38, and try the CSS solution there.

**Comment by manvfx** [comment]
please help me with example code

**Comment by Pradeepg21** [comment]
Hi,

On each widget I want maximize and minimize button.
Do you have any working example for the same.

Thanks,

**Comment by manvfx** [comment]
@Pradeepg21 
please help me
I want example code

**Comment by hardfi** [comment]
Should anyone be still looking, just add custom class to gridster-item that's supposed to be maximized:

.custom-class {
      height: calc(100% - 20px) !important;
      width: calc(100% - 20px) !important;
      top: 0 !important;
      left: 0 !important;
      z-index: 999;
    }

Works perfect for us, especially that build in resize animations still work while resizing.

**Comment by gary-holland** [comment]
@hardfi .  Thanks for tip.  I also needed to add a transform to get objects positioned thoughout the grid to maximize properly.

```
.maximize {
    height: calc(100%) !important;
    width: calc(100%) !important;
    top: 0 !important;
    left: 0 !important;
    transform: translate3d(0, 0px, 0px) !important;
    z-index: 999;
  }
```

**Comment by mbshingala28** [comment]
Hello,
Does anyone provide demo full example of maximizing grid item?
