### ISSUE TITLE
Data loaded with HTTP appears only after a click

### ISSUE THREAD

**Issue by petarGitNik** [tiberiuzuld/angular-gridster2#269]
I have to fetch data over HTTP and load it into a cell. However, when my service finishes loading the data, data in cell is displayed only if I click/drag the cell, or click/drag/resize/delete any other cell.

Here is a demonstration on [stackblitz](https://stackblitz.com/edit/angular-gridster2-loading-data-with-http) (the cell which should display dynamically fetched data is yellow).

In the demo my service is injected in the constructor of `app.component.ts`, and data is stored in the variable `users`. Then, in the template, the content is shown only if `users` variable has some value i.e.

```html
          <div class="dynamic-users" *ngIf="users">
            Dynamic users are: <span *ngFor="let user of users">{{user.name}} </span>
          </div>
```

All relevant code is commented in `app.component.ts` and `app.component.html`. My question is, is this expected behavior of gridster, and/or should I "refresh" the grid somehow after loading data from an external API?

**Comment by tiberiuzuld** [comment]
Hi @petarGitNik ,
Your component has:
```javascript
 changeDetection: ChangeDetectionStrategy.OnPush
```
Add:
```javascript
constructor(private ps: ProviderService, private ref: ChangeDetectorRef) { }
    this.ps.getHeroes().subscribe((users) => { this.users = users; this.ref.markForCheck() });
```

More info about how ChangeDetection works here: https://angular.io/api/core/ChangeDetectorRef

**Comment by petarGitNik** [comment]
Thank you @tiberiuzuld ! I thought it was a bug. Thank you very much for help and gridster :)

**Comment by darrenst** [comment]
Thanks that did it.

If you are not following the Angular Heroes Tut, the bits you needs are:
ChangeDetectorRef } from '@angular/core'  in import
private ref: ChangeDetectorRef in constructor

then turn your subscribe lambda into an object and call:
this.ref.markForCheck();

thanks tiberiuzuld
