### ISSUE TITLE
is there a way to get the updated changed dashboard list

### ISSUE THREAD

**Issue by rajesh-kanakabandi** [tiberiuzuld/angular-gridster2#27]
@tiberiuzuld 
when the user drags, removes or resizes an item, is there a way to get the updated dashboard list?

I need it so, I can save it a users saved config for his dashboard.

**Comment by tiberiuzuld** [comment]
Hi @rajesh-kanakabandi ,
When an item is changed , the change will be made on the original item from the list you provide
```html
<gridster [options]="options">
  <gridster-item [item]="item" *ngFor="let item of dashboard">
    <!-- your content here -->
  </gridster-item>
</gridster>
```
So in the `itemChangeCallback: AppComponent.itemChange` you will get the original object from that list.
The updated list of items is the original list.
I hope this answers your question.

**Comment by rajesh-kanakabandi** [comment]
thank you very much.
