### ISSUE TITLE
Call method on viewChildren(gridItemComponent) init

### ISSUE THREAD

**Issue by pionierx** [tiberiuzuld/angular-gridster2#270]
Could you add possibility to define method that will be called after grid item components initialization?

I want to set height of container for gridster, but InitCallback is called before gridster has initialized elements and curRowHeight is 0.

edit: Ok, I realized that solution for my case is putting logic in debounced itemInitCallback ;)

**Comment by tiberiuzuld** [comment]
Hi @pionierx ,
Currently thats the only way this will work because of how angular works especially `ngFor`

I assume this issue is resolved.
