### ISSUE TITLE
Add donations link to the project

### ISSUE THREAD

**Issue by matpag** [tiberiuzuld/angular-gridster2#271]
This project is awesome.
I would be really glad to donate you a couple of beers 👍 

Please add a donations link.

**Comment by matpag** [comment]
I've found now that there is a badge for donations in the README (sorry but it isn't much visible).
I will donate to you ASAP ;)

**Comment by tiberiuzuld** [comment]
Thank you!

**Comment by matpag** [comment]
@tiberiuzuld Sorry for the delay :)

**Comment by tiberiuzuld** [comment]
@matpag thank you ❤️ , will have a couple of 🍻

**Comment by matpag** [comment]
@tiberiuzuld Thank you for the mention in the supporter section 😊
