### ISSUE TITLE
angular-gridster2 items set in local storage

### ISSUE THREAD

**Issue by dejan10** [tiberiuzuld/angular-gridster2#273]
Hi.
How to set gridster items in localstorage? I get changed position of only one item on call 

```
> static itemChange(item: GridsterItem, itemComponent: GridsterItemComponentInterface) {
>     console.info('itemChanged', item, itemComponent);
> }
```

But how to get the positions of all the items? Is it possible?
Thanks

**Comment by tiberiuzuld** [comment]
Hi @dejan10 ,

The position of all items is the array you first give to the gridster.

Thanks

**Comment by dejan10** [comment]
Ok, and when I change position one or two items, how to set that new positions in localstorage?

Thanks

**Comment by dejan10** [comment]
I found solution.
Thanks a lot.
