### ISSUE TITLE
How to restrict widgets drag beyond the width of browser

### ISSUE THREAD

**Issue by kksevta** [tiberiuzuld/angular-gridster2#274]
Hi
Please let me know what should be gridster configuration for having following layout
[http://dsmorse.github.io/gridster.js/demos/responsive.html](http://dsmorse.github.io/gridster.js/demos/responsive.html)
As we can see, widgets cannot be extended beyond the browser width. I need to have same layout using angular-gridster2.

**Comment by kksevta** [comment]
thanks @tiberiuzuld this option will work perfectly 👍 
Actually I am having one scenario where user will have a blank container to add widget in container dynamically.
I am using gridtype as 'Fit', so that container adjust its width according to browser width.
But as soon as user adds a new widget dynamically, the newly added widget takes all the available space in container. But the expected behavior of widget should be to take defined size only.

Kindly let me know solution to handle this.

**Comment by tiberiuzuld** [comment]
Try `gridType: 'fixed'` if you want that the items don't take all available space.
