### ISSUE TITLE
Resize elements from component

### ISSUE THREAD

**Issue by BraneMKD** [tiberiuzuld/angular-gridster2#275]
Is it possible to resize grid element from component ? 

For example i have two grid elements with cols = 5. I want if possible to change first element cols = 10 and the second one to move to the next available spot.

**Comment by tiberiuzuld** [comment]
Hi @BraneMKD ,
If you mean to change from component code the position/size of elements, then yes.
```js
  itemA.cols = 5;
  itemB.y = 10;
  this.options.optionsChanged();
```

**Comment by BraneMKD** [comment]
Ty for the fast response. 
I played around and found this option, but i want if possible to auto position next element or to get (x, y) for next element. 
`getNextPossiblePosition()` 
is boolean.

**Comment by tiberiuzuld** [comment]
That function will modify the item you give and return boolean if a position is found as valid.
You can use  `this.options.api.getFirstPossiblePosition(item: GridsterItem); ` to get a new item.

**Comment by BraneMKD** [comment]
Great, i will try tomorrow and see what i can do. 
Thank you again.
