### ISSUE TITLE
emptyCellClickCallback: information about the grid instance

### ISSUE THREAD

**Issue by AndrewK15** [tiberiuzuld/angular-gridster2#277]
I'm using several gridster components on one page. I'm trying to use the option `emptyCellClickCallback` to add a new item, but I have to know from which grid instance the event came from. Is this possible in current implementation?

**Comment by tiberiuzuld** [comment]
Hi @AndrewK15 ,
You can do a bind in your callback:
`emptyCellClickCallback.bind(this, this.options)`

**Comment by AndrewK15** [comment]
Thanks for the quick answer! It seems kind of hacky, but well, if it works, I don't mind for know.
