### ISSUE TITLE
Grid Bounds checking on load

### ISSUE THREAD

**Issue by celloman** [tiberiuzuld/angular-gridster2#278]
@tiberiuzuld one more for you here.

I am seeing a warning that elements are being auto-positioned when loading a dashboard where the elements already have an x/y (and width/height) (Can't be placed in the bounds of the dashboard, trying to auto position!/n{"cols":1,"rows":1,"x":0,"y":0}).

My grid is set up to have 4 columns (minCols and maxCols both set to 4), and I have not specified a min/max number of rows (so I suppose that is using the defaults of 1/100). Why would an element at 0,0 with a width/height of 1 be considered to be outside of the grid? Based on the saved positions of all the elements, they should all fit on the grid (since they have the same height/width and position that was set by dragging them around the grid)... The only thing I could think of is maybe they are considered outside the bounds since there aren't any rows in the grid yet. Is it possible to have rows be auto-created up to the maximum when generating elements on a grid?

Note: these elements are generated with the gridster-item component like this
`<gridster-item *ngFor="let widget of widgets; let idx = index;"
            [item]="widget.item">[widget content here]</gridster-item>`

The end result of this behavior is that when trying to re-create a saved dashboard configuration, some of the widgets tend to auto-position themselves to random spots where they fit (and I don't think this happened in old versions).

Using Gridster 4.4.2 and Angular 5.2.1

Again, thanks for being awesome!

**Comment by tiberiuzuld** [comment]
Hi @celloman ,
The grid internal rows and columns are calculated based on the items positions and dimensions. They are not checked when placing an item.
The things that are checked on placing an item is collision with other items and grid boundaries maxRows, maxCols, -1, -1 
Code here: https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridster.component.ts#L289

Maybe try to update to latest version maybe is a bug in that version...
Or you have some item which is placed first at 0,0, which is not saved/loaded correctly.

Thanks,

**Comment by celloman** [comment]
Upon some further digging, I think this is on our end. I think when leaving the page with the dashboard, items are being destroyed which is triggering us to save the new auto-calculated positions as other items are shifted, resulting in conflicts (so the findItemWithItem check is failing)

Thanks again!

**Comment by celloman** [comment]
I guess, is there a way to determine that grid items are changing/being removed due to gridster being destroyed? It would be nice to have some way of determining that, so we can skip any updates to saved widget positions

**Comment by tiberiuzuld** [comment]
There is `itemRemovedCallback` and `destroyCallback` but the items shouldn't change when the grid is destroyed ...

**Comment by tiberiuzuld** [comment]
You can test here https://tiberiuzuld.github.io/angular-gridster2/angular/ on the demo there is the top right corner button which destroy the grid and not item change is called.

**Comment by celloman** [comment]
Ah, I was using the itemRemovedCallback to re-calculate the grid height, which was in turn causing a bunch of itemChange callbacks, which was in turn triggering a layout save... Now I am only paying attention to that callback when the user explicitly removes a widget.

Thanks again!
