### ISSUE TITLE
drag enable and disable not working for me

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [tiberiuzuld/angular-gridster2#28]
i have a check box to enable/ disable options.draggable.enabled. But it's not working, i can see options.draggable.enabled value getting changed to true/ false. Still widgets is draggable all the time. Your demo app works fine, i have checked that. 

I am calling optionsChanged() method after the options change but not working. Could you please check and let me know.
![image](https://cloud.githubusercontent.com/assets/16232384/25154022/741c91a4-2454-11e7-8371-609af536adfa.png)

**Comment by tiberiuzuld** [comment]
Hi @rajeshmuraleedharan ,
I didn't test it but if the demo works than is something wrong in your code. 
Will have time to investigate only later today.

**Comment by tiberiuzuld** [comment]
Hi @rajeshmuraleedharan ,
I just tested on master and on 2.4.x branch and drag/resize enable/disable works.
Something is wrong in your code.

**Comment by rajeshmuraleedharan** [comment]
Hi,
Working now, i was setting drag and resize enable/ disable values for individual widgets, then the global setting were getting ignored. Now i am not setting drag and resize enable/ disable values for individual widgets, just using the global gridster options. If needed i can set individual widgets options but for me it's not needed now.

Thanks
Rajesh
