### ISSUE TITLE
Accessing methods from dynamically added components

### ISSUE THREAD

**Issue by Kalemstorm94** [tiberiuzuld/angular-gridster2#280]
Hello @tiberiuzuld ! 
I have the following configuration:

```
<gridster-item [item]="item" *ngFor="let item of dashboard"
        <div class="gridster-item-content">
          <ndc-dynamic class="gridster-item-content" [ndcDynamicComponent]="item.Selector" [ndcDynamicInputs]="item" [ndcDynamicOutputs]="outputs"></ndc-dynamic>
        </div>
      </gridster-item>
```
Is there a way to access a dynamically added component method, when the itemChange event is triggered?
I have some dropdowns inside my component which I want to close when I start dragging or resizing the gridster item. 

Thank you!

**Comment by tiberiuzuld** [comment]
Hi @Kalemstorm94 ,
If possible to hide your stuff from css you can use the drag/resize class on gridster-item when resize or drag is happening.

If not you can check the library https://www.npmjs.com/package/ng-dynamic-component on how to pass inputs to your component like a boolean hideStuff and change it when drag/resize start/end

Also `itemChange` is called only after drag/resize ends and only if a changed occured.

Thanks

**Comment by Kalemstorm94** [comment]
I've pased the properties of the item (x, y, height, width) as Inputs to my component, and now I close those Inputs from the ngOnChange function. 
I believe there might be a more efficient way to do this, but right now I think it's all right, because I want to close the inputs, only after the changes are made.
