### ISSUE TITLE
Fixed number of columns and rows count and beyond the limit showing of scroll

### ISSUE THREAD

**Issue by RavalikaP** [tiberiuzuld/angular-gridster2#283]
Hi, 

I want to show fixed number of rows and columns in the first view and if we dragging the report beyond this fixed number of rows/columns we need to show that excess columns/rows with scroll bar.

Kindly let me know if there is any possible way to achieve this.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @RavalikaP ,
There is options `minCols` and `minRows`.
But there is no built in way to set that any extra columns/rows to be shown with a scroll bar.
You can go for gridType `fixed` and calculate at run time the row height and column width depending on your space available so you have similar to gridType `fit` and if there are some extra columns/rows the scrollbar will appear.
