### ISSUE TITLE
Is there any event to find gridster item is selected?

### ISSUE THREAD

**Issue by RavalikaP** [tiberiuzuld/angular-gridster2#285]
Is there any event to know that gridster item is selected?

Thanks

**Comment by tiberiuzuld** [comment]
Hi @RavalikaP ,

There is no feature yet to select items implemented in the library.
There is feature issue to implement this. https://github.com/tiberiuzuld/angular-gridster2/issues/267
You can implement this feature outside of the library if you need it right now.
