### ISSUE TITLE
Fix outerMargins

### ISSUE THREAD

**Issue by tiberiuzuld** [tiberiuzuld/angular-gridster2#286]
https://github.com/tiberiuzuld/angular-gridster2/issues/222

> Steps to reproduce:
> 
> Set gridType to GridType.Fixed
> Set outerMargin to true
> Set outerMarginBottom to 100
> Scroll down, and 100px space is not visible
> Or even simpler:
> 
> Go to demo page and set gridType to Fixed
> Add more gridster items to the bottom so that you get big height
> Inspect <gridster> element
> Change padding from 10px to 10px 10px 100px 10px
> Scroll down, and 100px space is not visible

**Comment by tiberiuzuld** [comment]
fixed in 5.0.1

**Comment by klemenoslaj** [comment]
Thanks for fast fix!
