### ISSUE TITLE
Can I have multiples intances of gridster on the same view or page?

### ISSUE THREAD

**Issue by fernandojne20** [tiberiuzuld/angular-gridster2#287]
Hello, I'm having an issue, when I try to have two instances of gridster, in different divs but on the same page, the gridster is not working, I was searching this problem on internet, an looks like there are a solution, using differents id's and namespaces for the root element of gridster, but this approach is for the JQuery version, Any suggestion about how can I implement this using the Gridster Component?. 

Thank you!

**Comment by tiberiuzuld** [comment]
Hi @fernandojne20,
It should work with no issues, you just need to have 2 sets of options and widgets list.
Maybe also have it inside 2 different div. Since the grid will take 100% of the parent element.

**Comment by andrei-tatar** [comment]
Hi, great job on the lib. 
If you have multiple gridster components visible at the same time, is there any way to drag items from one to the other?

**Comment by tiberiuzuld** [comment]
Hi @andrei-tatar ,
There is an open issue on this. https://github.com/tiberiuzuld/angular-gridster2/issues/245
Working on it, hoping for this month release of it.

**Comment by vahidx4876** [comment]
Hi,
I want to have one gridster per tab in mat-tab-group,  or multi instance gridstr but unfortunately I can't
Is issue closed on Apr 9, 2018
This issue is resolved or still exists
Thank you very much for your guidance
