### ISSUE TITLE
Preview of element is still showing after element was dropped

### ISSUE THREAD

**Issue by chrstnbrn** [tiberiuzuld/angular-gridster2#288]
I think I discovered a bug in the preview feature when enabling drop to add. If an element is dragged over an empty grid cell but is dropped outside of the grid the preview is still showing.

In this example I dropped the element to the left of the highlighted cell:

![image](https://user-images.githubusercontent.com/11138584/38354188-fbf4eb66-38b8-11e8-9c26-6de3ece05a40.png)

**Comment by tiberiuzuld** [comment]
Hi @chrstnbrn ,
Ok will try to have it fixed this week.

Thanks

**Comment by tiberiuzuld** [comment]
Fixed in v5.2.0

**Comment by chrstnbrn** [comment]
Thank you for fixing this so quickly!
