### ISSUE TITLE
Feature Request: Add flag to disable auto-position in case of conflicting items

### ISSUE THREAD

**Issue by matpag** [tiberiuzuld/angular-gridster2#289]
Hi, I've found a case where the ability to switch off the autoposition when there are items in the same positions is really useful.

For example in my project I'm listening for items changed events, and when there are conflicts (because we generate conflicts manually for testing purposes) we don't want the conflicting items to be pushed around to fit in the grid at all costs. Because with the current behaviour I don't know if the item has been changed by the user or changed by the autoposition function [here](https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridster.component.ts#L371).

The problem is here probably (and in the autoPositionItem function):
https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridster.component.ts#L300-L308

A small flag enabling/disabling this behaviour should be enough.

I've a simple PR for that, can you check that it doesn't break anything?
Thank you.

**Comment by tiberiuzuld** [comment]
PR looks ok, any problem if the check is placed on line 308 since there is the auto position if there is a conflict. https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridster.component.ts#L308

**Comment by matpag** [comment]
No problem, will update after dinner 😁

**Comment by tiberiuzuld** [comment]
Will do the update since I want to make a small release 👍

**Comment by tiberiuzuld** [comment]
Added in v5.2.0

**Comment by matpag** [comment]
Thank you 😊
