### ISSUE TITLE
Unable to Reorder grid item in mobile state

### ISSUE THREAD

**Issue by rishi-ios** [tiberiuzuld/angular-gridster2#29]
Hey @tiberiuzuld 

I am using this grid control on both iPad and iPhone. On iPad the items in the grid are resizable and swap enabled. On iPhone it enters in mobile state as expected and grid items are shown in one after another in vertical order. 

In mobile state all these items are not resizable, draggable and swap enabled .

Please let me know how to achieve all same features in mobile state also.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @rishi-ios 

You can't , in mobile state all widgets are displayed one after another as is in the list.
The mobile state is not made to be able to drag /resize and edit the position only to view.

If you still want to be able to edit then reduce the `mobileBreakpoint` option.
