### ISSUE TITLE
add a validation callback on item/grid to be called inside checkColission

### ISSUE THREAD

**Issue by Chibas** [tiberiuzuld/angular-gridster2#293]
Hello. Is there a way to keep aspect ratio of my grid items?
I've tried something like 

`static itemResize(item: GridsterItem, itemComponent: GridsterItemComponentInterface) {

        let deltaOld = item.minItemCols - item.minItemRows;
        let deltaNew =  item.cols - item.rows;
        if (deltaNew !== deltaOld) {
             deltaNew > 0 ? item.cols += deltaNew : item.rows += deltaNew;
        }

}`

But that did not affect anything at all. Can i directly set resizable item dimensions on the go?

**Comment by tiberiuzuld** [comment]
Hi @Chibas ,
You can set minItemRows/minItemCols/minItemArea.
Or you can use the push API to resize a item from code.
I think is up to the user to set his widgets how he thinks he is ok with.

About aspect ratio:
It is relative to the screen size / available space for the grid and gridType.
If you choose for example the gridType vertical scroll, then the widgets will be square.

**Comment by GMacAussie** [comment]
We have a similar situation where we have dial graph widgets in the mix that should only be square.

We did the following to the code (sorry) - this is for AngularJS:

1. Added an `aspectRatio` variable to the `vm.$item` initialisation:

`      aspectRatio: undefined`

2. Modified `vm.checkGridCollision` to enforce aspect ratio. NOTE! We only need 1:1 so this is not generalised - it suited our purpose however:

```
  vm.checkGridCollision = function checkGridCollision(item) {
      // handle locked aspect ratio. 1 to 1 only at the moment
      if (item.aspectRatio) {
        if ((item.rows != item.rowsA) && (item.cols != item.colsA)) {
            item.cols = item.rows;
        } else if (item.rows != item.rowsA) {
            item.cols = item.rows;
        } else if (item.cols != item.colsA) {
            item.rows = item.cols;
        }

        item.rowsA = item.rows;
        item.colsA = item.cols;
      }
```

I am not sure this is the best way but it got us over non-square dial graphs.

**Comment by tiberiuzuld** [comment]
Hmm, interesting, maybe is better to add a validation callback on item/grid to be called inside checkColission.

**Comment by tiberiuzuld** [comment]
Added in v5.3.0
