### ISSUE TITLE
Autopositioning item causes grid resize when it doesn't fit

### ISSUE THREAD

**Issue by dnbo** [tiberiuzuld/angular-gridster2#296]
**Issue**:
When you add an item programmatically to a gridster area that doesn't fit the available space, the area will be incorrectly resized, thus overriding set min/max rows/cols.

**Steps to reproduce**:
[StackBlitz example](https://stackblitz.com/edit/gridster-resize-issue)

**Image example:**
![image](https://i.imgur.com/tQXgNBB.gif)

**Version used:**
4.7.2 (Not possible to upgrade right now)
Unsure if it affects latest version.

**Comment by matpag** [comment]
Stackblitz link is broken

**Comment by dnbo** [comment]
Fixed! Sorry about that!

**Comment by tiberiuzuld** [comment]
Hi @dnbo ,
Was able to reproduce it in the latest version also.

Will have a fix soon.

Thanks you

**Comment by tiberiuzuld** [comment]
Fixed in v5.2.1

Thanks
