### ISSUE TITLE
Expose current grid dimension

### ISSUE THREAD

**Issue by macftw** [tiberiuzuld/angular-gridster2#298]
Is it possible to expose the current with and height of the grid as reflected in the .gridster-column elements? Preferably by an event that fires whenever the grid dimension changes (during drag, deletion, insertion, etc.).

I am currently trying a workaround by watching the gridster-column element with an MutationObserver which seems like a hacky solution (and also doesn't work as expected).

I also tried to check the dimension onDragStop which doesn't quite work either since it fires immediately while the grid is still animating.

I'm thinking of a gridSizeChanged callback in the options which fires whenever rows or columns are added/removed. Or is this already possible and I'm missing something?
Thank you for your help!

**Comment by macftw** [comment]
Thank you @tiberiuzuld for the quick reply.
I already tried using the existing callbacks but they don't provide a callback when the grid size changes during dragging. 

Also the `itemRemovedCallback` immediately fires while the grid is still shrinking, so I can't read the correct grid size there.

I think a `gridSizeChanged` callback would be useful.

**Comment by tiberiuzuld** [comment]
Ok will add a `gridSizeChangedCallback` as soon as possible.

**Comment by tiberiuzuld** [comment]
Added in v5.3.0

**Comment by viethien** [comment]
Hello @tiberiuzuld 

I tried to use gridSizeChangedCallback, but it has never fired.
this.options = {
			gridType: this.gridType,
			enableEmptyCellDrop: true,
			emptyCellDropCallback: this.onDrop.bind(this),
			gridSizeChangedCallback: this.gridSizeChanged.bind(this),

...
}

How can I trigged gridSizeChangedCallback when grid size change in this case?
