### ISSUE TITLE
Question - Routes within a grid item

### ISSUE THREAD

**Issue by jdell64** [tiberiuzuld/angular-gridster2#299]
Hey, had a quick question... not sure if its a feature request.

How would you implement routes with ids as separate grid items?

example:

- User picture with an id
- a search pane
- a saved items list with an id

Would this be able to use an app-routing module with lazyloading and guards? or is it more of a flat structure?

**Comment by tiberiuzuld** [comment]
Hi @jdell64 ,

From a list of ids you can give it to the `gridster` to auto position them.
Inside each item you can load your image based on the id.
The search you can implement outside the library even using the `ngFor` and a filter.
Don't see why the routing will not work... the library doesn't make use of routing.

If you don't need drag and resize there are many other choices out there to position items in 2 dimensions, like css flexbox with wrap, or css grid.

Not sure if understood correctly what you need from this library ...
