### ISSUE TITLE
apply packing algorithm when items are changed or removed.

### ISSUE THREAD

**Issue by rajesh-kanakabandi** [tiberiuzuld/angular-gridster2#3]
when an Item is added, it gets placed at at the top most empty position as expected. 
it would also be cool if the empty spaces be removed by cascading the items to top and left when and item is removed.

**Comment by tiberiuzuld** [comment]
Will see if I can make a config option for this.

**Comment by tiberiuzuld** [comment]
Hi added the compact Up and Left in version 1.2.0
