### ISSUE TITLE
is there a way to trigger redraw the dashboard on a certain event?

### ISSUE THREAD

**Issue by rajesh-kanakabandi** [tiberiuzuld/angular-gridster2#30]
I would like to be able to call a function or so to make the redraw the whole dashboard.

I tried calling 
`this.options.optionsChanged();`

but I end up with a error 

`this.options.optionsChanged is not a function`

**Comment by tiberiuzuld** [comment]
Hi @rajesh-kanakabandi ,
You end up with an error because the dashboard is not initialized yet.
The optionsChanged function is triggering a redraw.

**Comment by rajesh-kanakabandi** [comment]
@tiberiuzuld thank you for the response. it is working as designed. it was failing on load when the dashboard is still not initialized.
