### ISSUE TITLE
mobileBreakpoint is not applied if a parent element is resized

### ISSUE THREAD

**Issue by Zaixer** [tiberiuzuld/angular-gridster2#300]
It looks like the code listens to the window resize event, but doesn't detect other size changes.

Is this a bug and is there some kind of workaround that can be applied?

**Comment by tiberiuzuld** [comment]
Hi Zaxier,
The library only listens after window resize if a parent changes the size you need to call `this.options.api.resize()`.

Thanks

**Comment by Zaixer** [comment]
If I call this.options.api.resize() it doesn't update the IsMobile variable.

**Comment by Zaixer** [comment]
So what I would like to do is call the resize method and have the grid switch to stacked items if the container have now become narrow and have the grid switch to columns if the container have now become wide.

**Comment by Zaixer** [comment]
Hmm I tested some simpler code now and it seemed to work. Maybe it's just me that messed something up...

**Comment by Zaixer** [comment]
Yeah I messed something up. Sorry for wasting your time.
