### ISSUE TITLE
Question: how to maximize a gridster item using button on gridster item header?

### ISSUE THREAD

**Issue by BansalPooja** [tiberiuzuld/angular-gridster2#302]

**Comment by tiberiuzuld** [comment]
Hi @BansalPooja ,
See #264 .

Thanks

**Comment by BansalPooja** [comment]
Hi @tiberiuzuld 

Thanks for your quick response, but it seems like you are suggesting that we need to maximize out of gridster adn there is no feasible way in gridster to maximize and resize other items in gridster.

**Comment by BansalPooja** [comment]
Also, I am using gridster 4.6.3 for angular 5 version and have tried using this.optionsChanged() but it does'nt resize all other items.

**Comment by tiberiuzuld** [comment]
What do you mean by is not resizing all other items ?
If you mean that it should push other items then you need to look at https://github.com/tiberiuzuld/angular-gridster2/issues/307
