### ISSUE TITLE
dashboard resizes after adding a new item

### ISSUE THREAD

**Issue by w-veltman** [tiberiuzuld/angular-gridster2#304]
I have an issue with the resize that gets triggered in the following situation:

My options and empty dashboard:
    this.options = {
      gridType: GridType.ScrollVertical,
      displayGrid: DisplayGrid.None,
      pushItems: true,
      maxCols: 8,
      draggable: {
        enabled: true,
        ignoreContent: true,
        dragHandleClass: 'drag-item',
      },
      resizable: {
        enabled: true,
        stop: this.eventStop.bind(this),
      },
      swap: true,
      compactType: CompactType.None,
    };
    this.dashboard = [];

the thing is, I add a gridsterItem with a dynamically generated component inside of it with 4 rows and columns. Then I add another with the same cols and rows. and when I add a third with the same number of rows and cols it will be placed next to the first one added, which is logical. 

But which event gets fired when this happens, because both gridsterItems get resized in height and width?

I ask this, because  I'm having trouble with getting it right for the resizing of my dynamic compoennt inside the gridster item.

I know itemResizeCallback gets callled, but when i put some code in it to resize my dynamically generated component, that code doesnt fire or does not fire correctly.

Can you help me?

**Comment by tiberiuzuld** [comment]
Hi @w-veltman ,
All 3 items should get item resize event when adding the third one.
Will have a look at the resize events if they fire correctly this week.

Thanks

**Comment by w-veltman** [comment]
Thank you, I'll be patiently waiting for your answer. 

Great widget by the way!

**Comment by tiberiuzuld** [comment]
Item resize event works as expected.
Is called for each item which changes the size when a new item is added to a new column/row.

**Comment by w-veltman** [comment]
Okay then it's probably my code that doesnt run as expected. Thank you for testing!

**Comment by w-veltman** [comment]
I think the itemResizeCallback from the options menu is called when there is an item added to an empty dashboard. In my code it is even called twice. Can you take look at this?

Options:
    _this.options = {
      gridType: GridType.ScrollVertical,
      displayGrid: DisplayGrid.None,
      pushItems: true,
      maxCols: 8,
      draggable: {
        enabled: true,
        ignoreContent: true,
        dragHandleClass: 'drag-handler',
      },
      resizable: {
        enabled: true,
        stop: this.eventStop.bind(this),
      },
      swap: true,
      compactType: CompactType.None,
      itemResizeCallback: this.dashResized.bind(this),
      itemInitCallback: this.dashInit.bind(this)
    };
    this.dashboard = [];_

Functions:

  _dashInit(item: GridsterItem, itemComponent: GridsterComponentInterface){
    console.log('Init')
  }

  dashResized(item: GridsterItem, itemComponent: GridsterComponentInterface){
    console.log('resize')
}

  addItem(value) {
    this.dashboard.push({})
  }_

Console output:

![image](https://user-images.githubusercontent.com/29980599/39119478-41f704c8-46ec-11e8-92bd-b664e4172760.png)

**Comment by tiberiuzuld** [comment]
Yes it is possible for the resize to be called twice for the same item.

**Comment by w-veltman** [comment]
Okay, but why is called even after the initialisation of the item? I havent performed any form of a resize and still it gets called.

**Comment by w-veltman** [comment]
Okay thanks for the explanation! If i find a solution i'll be sure to pass it along to you
