### ISSUE TITLE
resize a widget using a button

### ISSUE THREAD

**Issue by viksakshum** [tiberiuzuld/angular-gridster2#307]
i have the gridster item as below 
```
<gridster-item [item]="myAptInfolet" class="shadow">
                               <app-my-appointments-infolet></app-my-appointments-infolet>
                        </gridster-item> 
```

**.ts**
`this.myAptInfolet = {cols: 1, rows: 2, y: 0, x: 4}`

the resize function is like
```
test(){
    this.myAptInfolet.cols = 2
    this.options.api.resize()

   }
```
but nothing happens. no error in console. please advise

**Comment by viksakshum** [comment]
sorry bit new on gridster as well as your amazing work. can u point me to an example plz

**Comment by tiberiuzuld** [comment]
https://tiberiuzuld.github.io/angular-gridster2/api
https://github.com/tiberiuzuld/angular-gridster2/tree/master/src/app/sections/api

**Comment by viksakshum** [comment]
I looked at it but there is still some trouble. 

what is the purpose of chageDetection policy  in the above code?   also do i need to call changeOptions api explicitly after changing cols?
