### ISSUE TITLE
Minimum / maximum size of items stopped working

### ISSUE THREAD

**Issue by pawlik92** [tiberiuzuld/angular-gridster2#31]
Hi @tiberiuzuld 

After upgrading from version 2.4.6 to 2.4.9 min/max ItemRows and min/max ItemCols stopped working.
They are not taken into account and item can be freely resize to any size.
This bug also occurs on the angular-gridster2 demo.

**Comment by tiberiuzuld** [comment]
Hi @pawlik92 
Thank you for reporting this issue, will have it fixed today.

**Comment by tiberiuzuld** [comment]
Hi @pawlik92 ,
Fixed in v2.4.10 and v2.7.7
Thanks
