### ISSUE TITLE
document "dragend" EventListeners never removed

### ISSUE THREAD

**Issue by iteufel** [tiberiuzuld/angular-gridster2#311]
The document "dragend" EventListeners won't bee removed after destroy.
https://github.com/tiberiuzuld/angular-gridster2/blob/9632cfca64d6db6dc36b99d58e8956e73d27a83e/src/lib/gridsterEmptyCell.service.ts#L57

**Comment by tiberiuzuld** [comment]
Hi @iteufel ,
Fixed in v5.3.2

Thank you!
