### ISSUE TITLE
Question: Prepending the grid

### ISSUE THREAD

**Issue by jdell64** [tiberiuzuld/angular-gridster2#312]
Sorry if this isn't the place to ask this, but I had a question.

If I wanted to put a new item in the grid, but I wanted it to be at (0,0) and push all other items; is this possible? My current settings don't seem to allow this.

Also, is there a way to get the current size of the grid?

**Comment by tiberiuzuld** [comment]
Hi @jdell64 ,
You need to use the PUSH API: https://tiberiuzuld.github.io/angular-gridster2/api

**Comment by jdell64** [comment]
@tiberiuzuld I do have that enabled. If I want my special component to always start at (0,0); should I just load it last?

**Comment by jdell64** [comment]
I am not sure I was clear enough on this one... I'll give it some more thought and reopen if I can come up with better information. I will also look into "anchoring" a single item to a spot as a possible solution.
