### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by princevg** [tiberiuzuld/angular-gridster2#314]

**Comment by princevg** [comment]
Hi 
I have facing one issue on the gridster. For my requirement I don't want to scroll beyond the screen size and not to shrink the ui to accommodate another item. The UI should remains as the same. Is there any way to do that. I am staying on that 3 days. Please help if anyone has some ideas
![capture](https://user-images.githubusercontent.com/1523806/39344018-a6c7cc70-49fd-11e8-8dfb-5cefe32f0783.PNG)

**Comment by tiberiuzuld** [comment]
Hi @princevg ,
The only thing you can do is set `maxRows` and `maxCols`.
You can set `gridType: 'fit'` if you don't want a scroll.

The items added after `maxRows` and `maxCols` will not be displayed.

You cannot limit the screen size of the user.
In `gridType: 'fit'` the items will have different size depending on the users screen size.

From your requirements seems that you want to change how the web works.
This library is not about that is about having a responsive dashboard depending on the space available.
