### ISSUE TITLE
Is there any event or callback to know after all the gridster items rendered

### ISSUE THREAD

**Issue by RavalikaP** [tiberiuzuld/angular-gridster2#316]
Hi,

Is there any callback to know after all the gridster items are rendered?

Thanks

**Comment by tiberiuzuld** [comment]
Hi @RavalikaP ,
No there is not.
You can use itemInitCallback with a debounce to know when all are rendered and with size.

Thanks

**Comment by RavalikaP** [comment]
Hi @tiberiuzuld ,

I will see for work around.

Can you please me in more scenario?
Is there any way of adding a gridster item based on the available Rows/Columns dynamically on the click of any button?

Thanks

**Comment by tiberiuzuld** [comment]
Yes you can, see `getNextPossiblePosition` https://tiberiuzuld.github.io/angular-gridster2/api

**Comment by RavalikaP** [comment]
Hi @tiberiuzuld ,

For getNextPossiblePosition function we need to send the item. But for my case I have to push the empty rows and cols size as item.

Thanks

**Comment by tiberiuzuld** [comment]
There is no callback to get the empty rows/cols.
You can get the current rows/cols number from gridsterComponent from initCallback or by doing the calculation yourself, e.g. for on items array and determine the current rows/cols
