### ISSUE TITLE
New element positioning

### ISSUE THREAD

**Issue by dcp3450** [tiberiuzuld/angular-gridster2#318]
I'm adding an item using the following notation:

`this.elements.push({cols: 2, rows: 2, y: 0, x: 0});`

However it adds the element at the "next available slot" is it possible to specify the location of a new element?

**Comment by tiberiuzuld** [comment]
Hi @dcp3450 ,
You need to use the PUSH api if you want to set an item where there is already a item.
https://tiberiuzuld.github.io/angular-gridster2/api

If a position is already occupied the grid will try to auto position the item.

**Comment by dcp3450** [comment]
@tiberiuzuld I looks like this part of the API pertains to items after they are added. However, I'd like to add an item at specific col / row.

**Comment by tiberiuzuld** [comment]
Not possible at the moment.

**Comment by dcp3450** [comment]
Ok, thanks!

**Comment by tiberiuzuld** [comment]
Made a improvement issue for this.
Will close this now.

Thanks

**Comment by akash1525** [comment]
Hey @tiberiuzuld this is a great library indeed!. Do you plan on adding pushing an element to a specific cell feature ? That would be a great feature to have.
