### ISSUE TITLE
Element starts "flying" when dragged out of the gridster area

### ISSUE THREAD

**Issue by pawlik92** [tiberiuzuld/angular-gridster2#32]
Hi @tiberiuzuld again

I found a strange bug (on Chrome 57 & 58).
When dragging an item out of the gridster area, drop it there and try again to drag it, then item starts "flying" with cursor. You can not put it anywhere anymore.
I attached a screencast with this problem.

![bug_gridster](https://cloud.githubusercontent.com/assets/9088664/25229200/b0b8b5f8-25cf-11e7-800e-da43e49ff7d0.gif)

**Comment by tiberiuzuld** [comment]
Hi @pawlik92 ,
Will look at it today.
Thanks

**Comment by tiberiuzuld** [comment]
Hi @pawlik92 ,
Fixed in v2.4.10 and v2.7.7
Thanks
