### ISSUE TITLE
How to drag two separate events in single grid?

### ISSUE THREAD

**Issue by Sandeepvedam** [tiberiuzuld/angular-gridster2#320]
Hi,

Thank you for great library. It has many features :)

I have requirement to draw arrows between grids. So that i have to handle two separate drags from single grid. For ex: I have grid with single marker. Marker to drag and draw arrow to other grid. Grid should be separate drag event to place anywhere in the panel.

For this requirement, I am trying to draw svg line to other grid but both draggable events are same.

Is it possible to drag separate events from single grid?

please find the attached image for reference,

![image](https://user-images.githubusercontent.com/16398833/39666888-8ce5e5cc-50c8-11e8-8d51-ff268da4784a.png)

**Comment by tiberiuzuld** [comment]
Hi @Sandeepvedam ,
You need to look over the options https://tiberiuzuld.github.io/angular-gridster2/drag especially the `ignoreContentClass` and `ignoreContent`.
That way you can have a button from which to drag the arrows without triggering the item drag.
