### ISSUE TITLE
Overlap function doesn't work 

### ISSUE THREAD

**Issue by Steven-ZhouMeng** [tiberiuzuld/angular-gridster2#322]
**Dear tiberiuzuld,**
Currently I am using angular-gridster2 and found an issue regarding the overlap function.
As you described on the [drag demo page](https://tiberiuzuld.github.io/angular-gridster2/drag), we can set draggable.dropOverItems option to support the overlap function. But it doesn't work during my research.

The init code of the grid is simple as below:

ngOnInit() {
            this.options = {
            itemChangeCallback: AppComponent.itemChange,
            itemResizeCallback: AppComponent.itemResize,
            gridType: 'fit',
            displayGrid: "always",
            pushItems: false,           
            swap: false,
            draggable: { enabled: true, dropOverItems: true, dropOverItemsCallback: AppComponent.overlapEvent },
            minCols: 10, 
            maxCols: 100, 
            minRows: 10, 
            maxRows: 100
        };
this.dashboard = [
            { cols: 3, rows: 3, y: 1, x: 1 },
            { cols: 2, rows: 2, y: 3, x: 4 }
        ];
    }

As you can see, I disable swap and pushItems, enable dropOverItems and create callback method accordingly. During the testing I have found that the overlap function never works.

I have debugged the code and found that there will be error occurred "ERROR TypeError: Cannot read property '$item' of undefined" when I click the item. The issue occurred on the makeDrag method in [gridsterDraggable.service.ts](https://github.com/tiberiuzuld/angular-gridster2/blob/master/projects/angular-gridster2/src/lib/gridsterDraggable.service.ts) file.  The collision object is undefined so that this.collision.$item will throw the error. I have confirmed that the issue exist on the [drag demo page](https://tiberiuzuld.github.io/angular-gridster2/drag) too if you uncheck 'Push Items' and 'check Allow Drop Over Items', then click the item.

I have checked the source code that the collision object will be always true or false which is returned by checkCollision method in [gridster.component.ts](https://github.com/tiberiuzuld/angular-gridster2/blob/master/projects/angular-gridster2/src/lib/gridster.component.ts). 

Since the collision object will be always true or false, calculateItemPosition method in [gridsterDraggable.service.ts](https://github.com/tiberiuzuld/angular-gridster2/blob/master/projects/angular-gridster2/src/lib/gridsterDraggable.service.ts) will return to the original location if the item was dropped over on top of another item. 

Based on above research and testing, it seems that current latest version of angular-gridster2 doesn't support overlap function due to the issue. Please kindly help confirm it, thanks a lot.

**Comment by tiberiuzuld** [comment]
Hi @Steven-ZhouMeng ,
Fixed in v6.0.1

Thanks

**Comment by Steven-ZhouMeng** [comment]
Hi @tiberiuzuld, thanks a lot for your quick response. The error was fixed and the dropOverItemsCallback can be called correctly now, but the overlay function still doesn't work. I have created another issue regarding this. Here is the link for your reference.
