### ISSUE TITLE
Multiply ignoreContentClass

### ISSUE THREAD

**Issue by galvakojis** [tiberiuzuld/angular-gridster2#323]
is it possible to add multi classes to ignoreContentClass?
To do something like this:
`ignoreContentClass: 'panel-label', 'panel-otptions'`

or this:
`ignoreContentClass: ['panel-label', 'panel-otptions']`

**Comment by tiberiuzuld** [comment]
Hi @galvakojis ,

It is possible but why not you set a single class instead of the library doing for loops.
You already control the content in the item you can add just one class to the elements you don't want drag to occur from.

**Comment by galvakojis** [comment]
Thank you for help, i just changed my layout, so one class is enough at the moment
