### ISSUE TITLE
Overlap function still doesn't work with v6.0.1

### ISSUE THREAD

**Issue by Steven-ZhouMeng** [tiberiuzuld/angular-gridster2#325]
Hi @tiberiuzuld,
After you fixed Issue #322, the error disappeared but the overlay function still doesn't work. 

The init code of the grid is simple as below:

ngOnInit() {
this.options = {
itemChangeCallback: AppComponent.itemChange,
itemResizeCallback: AppComponent.itemResize,
gridType: 'fit',
displayGrid: "always",
pushItems: false,
swap: false,
draggable: { enabled: true, dropOverItems: true, dropOverItemsCallback: AppComponent.overlapEvent },
minCols: 10,
maxCols: 100,
minRows: 10,
maxRows: 100
};
this.dashboard = [
{ cols: 3, rows: 3, y: 1, x: 1 },
{ cols: 2, rows: 2, y: 3, x: 4 }
];
}

As you can see, I disable swap and pushItems, enable dropOverItems and create callback method accordingly. During the testing I have found that the overlap function never works. Also you can reproduce the issue on [drag demo page](https://tiberiuzuld.github.io/angular-gridster2/drag) if you uncheck 'Push Items' and 'check Allow Drop Over Items', then drop one item on top of another one. 

The overlay function never works. The item which was dropped over on top of another item will return to its original location. Please kindly help confirm if it's a bug or an enhancement. Thanks a lot.

**Comment by Steven-ZhouMeng** [comment]
Hi @tiberiuzuld, 
Thanks a lot for your feedback. I just want to confirm with you about the overlap function. Currently we want to put one item on top of another item which means "overlay". That means two items are in the same location, one is on top of another one. 

I have added some code in the callback method of dropOverItems to implement the overlay function, but the code after the callback in Gridster was executed to return the drag item back to original location.

Please kindly help confirm if it's possible to support overlay function now? Thanks a lot.

**Comment by tiberiuzuld** [comment]
It is not possible to have two items at the same location.
This overlap function is just to know when an item is dropped over the other.
Is not to place two items over the others as an overley.

**Comment by Steven-ZhouMeng** [comment]
Hi @tiberiuzuld,
Here is a question which need your help. I don't want  execute the code in Gridster after the dropOverItems callback method. Currently I just throw an error so that the gridster will not execute the following code after the dropOverItems callback method. But obviously it's not a good way. Do you have any suggestion on it? Thanks in advance.

**Comment by nayfin** [comment]
@tiberiuzuld I was hoping to use this library to build a game. It has so many great features and would be perfect except that I need to allow players to lay pieces over other pieces. Would you be open to taking pull requests to enable something like this? I'm happy to dig in if you're open to the feature.

**Comment by Mayurdoshi** [comment]
Hi @tiberiuzuld , I have a requirement of placing an gridster-item one above another, any plans to add feature ?
