### ISSUE TITLE
Tiles not auto resize, it overlaps over other tiles when rows are increased programmatically

### ISSUE THREAD

**Issue by shyambhiogade** [tiberiuzuld/angular-gridster2#327]
hi @tiberiuzuld ,  
i am using gridster to display tiles and when it loads first time it will not have the its data and will be of smaller size as below
![image](https://user-images.githubusercontent.com/10468130/39789631-ec5544b6-52e5-11e8-8450-cfe589b19eca.png)

but as each tiles gets the data, i increase the size of tile by updating no of gridster rows, but it overlaps, how to fix this, i want to maintain the order of the tiles in which it was added, 

this is how it looks  
![image](https://user-images.githubusercontent.com/10468130/39789694-4ee212ee-52e6-11e8-8edc-c053879de298.png)

how to make tiles adjust to new rows without overlapping ? i tried pushitem, but it only works if there is no item below or one row item. if i use getNextPossiblePosition, it may place it somewhere, i want to maintain the oder of tile left to right

my gridster style is compactLeft, verticalScroll 

i think this should be a very standard behavior where people must be updating tiles rows programatically, for now i remove everything from collection and place it again in zero timeout.

**Comment by shyambhiogade** [comment]
please find the attached sample application,
[sample app.zip](https://github.com/tiberiuzuld/angular-gridster2/files/1986099/sample.app.zip)

keep clicking additem untile it creates 3 rows and then click on push item button, it does nothing.

**Comment by tiberiuzuld** [comment]
Hi @shyambhiogade ,
The only option is to use the push api as in this example https://tiberiuzuld.github.io/angular-gridster2/api

**Comment by shyambhiogade** [comment]
Hi @tiberiuzuld , but push api is not working if there is two more item row below

**Comment by tiberiuzuld** [comment]
Related to this issue https://github.com/tiberiuzuld/angular-gridster2/issues/281
Don't have a fix for it yet.

**Comment by shyambhiogade** [comment]
@tiberiuzuld Yes, if i make compactType equal to none then it works, but if compact type is compactLeft or there its not working. any suggestion you would like to give on how to handle this situation. i tried setting compact type to none and after a second setting it to compact left, but that also didnt work.

**Comment by CollinGraf314** [comment]
It may be difficult to do, but your best bet might be to programatically reset the Y properties to take into account the higher row counts of the above tiles.

**Comment by shyambhiogade** [comment]
@tiberiuzuld  i noticed that now push api doesnt work even when size of each item is same, sometime it works even in the demo application, can you please check, my item is going to be of same size initially, please find the recording

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10468130/40989862-f74f8452-68a3-11e8-84d2-830b798439f8.gif)

**Comment by me2mitesh** [comment]
Hi @tiberiuzuld, 

I am facing the similar issue, the data in the content is dynamic and the length of the data changes.
However, the gridster item overlaps. I have a use case where there are multiple items one below the other. They just overlaps instead of pushing the gridster item down. 

Any idea how we can achieve this ?

using version angular-gridster2 - 8.2.0

Thanks
