### ISSUE TITLE
Enable drop to add in demo is not working in Firefox

### ISSUE THREAD

**Issue by chrstnbrn** [tiberiuzuld/angular-gridster2#329]
If I go to https://tiberiuzuld.github.io/angular-gridster2/emptyCell and enable drop to add I am not able to drag the "Drag me!" text. It is working in Chrome and Edge but not in Firefox (59.0.3). If I select the text first however dragging works fine.

In my application that uses angular-gridster2 in version 5.3.3 I have a similar issue. I think the bug in the demo might be related.

**Comment by tiberiuzuld** [comment]
Hi @chrstnbrn ,
Fixed the issue. Apparently Firefox needs also `ondragstart` handle to make the element `draggable`.
Was only on the demo side no need to make a new lib version.

Thank you
