### ISSUE TITLE
Can't resize items on Firefox

### ISSUE THREAD

**Issue by pawlik92** [tiberiuzuld/angular-gridster2#33]
It is impossible to resize items on a firefox. I tested on the latest Firefox (53.0).
Resize also does not work on angular-gridster2 demo.

**Comment by tiberiuzuld** [comment]
HI @pawlik92 ,
Will look at it today.
Thanks

**Comment by tiberiuzuld** [comment]
Hi @pawlik92 ,
Fixed in v2.4.10 and v2.7.7
Thanks
