### ISSUE TITLE
Is there any way I can undo/restore to original state of grid

### ISSUE THREAD

**Issue by shyambhiogade** [tiberiuzuld/angular-gridster2#330]
Hi @tiberiuzuld, 
I am planning to add edit mode feature in my dashboard which uses gridster. When in edit mode, user can drag, resize the tiles/grid items but if he click on discard change button, he should able to restore to it's original state. How this can be achieved. i tried to keep the copy of dashboard in separate variable and on click of discard change button, i assigned that to actual array variable, it works in the sample application but not in my original application which is in angularjs, i am using hybrid application, also i think that will force complete refresh, is this the best way or is there is better optimize way. Thanks

**Comment by tiberiuzuld** [comment]
HI @shyambhiogade ,
Yes you clone the items array before edit mode, and if reset button is pressed you replace the current one with the clone.
