### ISSUE TITLE
Is there any easy way to get the new order of tiles in gridster

### ISSUE THREAD

**Issue by shyambhiogade** [tiberiuzuld/angular-gridster2#332]
hi @tiberiuzuld , 
is there any easy way to get the new order of tiles in the gridster after reodering.

**Comment by tiberiuzuld** [comment]
Hi @shyambhiogade ,
Your array has the new order and you are notified with the `itemChangeCallback`

**Comment by shyambhiogade** [comment]
@tiberiuzuld  , my array still contains the old order. any other suggestion

**Comment by shyambhiogade** [comment]
@tiberiuzuld , i dont see my array is getting new order, i think if you could expose a property telling about the new order, that would be helpful, right now i am managing with x and y position but i dont want to save x and y position in my database.

**Comment by shyambhiogade** [comment]
@tiberiuzuld  can you help on this, there is no new order of tiles in array.

**Comment by katye610** [comment]
Does itemChangeCallback only accept as arguments (and give you access to) the item that has changed? I'm trying to persist the coordinates and cols/rows of every item in the grid, but I can only get access to the changed itemComponent, not any of the other items in the grid. How can I do that?
