### ISSUE TITLE
Is there any way I can restrict the size of cell in the grid

### ISSUE THREAD

**Issue by shyambhiogade** [tiberiuzuld/angular-gridster2#333]
Hi @tiberiuzuld, 
Is there any way I can restrict grid from resizing.
My tile on the grid has minimum width and height, but when browser is resized, grid cell also resized, because of this tile is overlapping over each other

**Comment by tiberiuzuld** [comment]
Hi @shyambhiogade ,
No you cannot restrict the size of a cell in the `gridType: 'fit'`.
You can use `gridType: 'fixed'` to set a certain size for a cell.
