### ISSUE TITLE
is there any way to keep the minimum size of the widgets/tiles in vertical scroll grid type

### ISSUE THREAD

**Issue by shyambhiogade** [tiberiuzuld/angular-gridster2#335]
hi, 
i am using gridster with vertical scroll and compact left,
is there any way i can keep the minimum size of widget, i tried to give min-height and min-width, but other  tiles are getting overlapped over it. please see the below recording
![zoom_1](https://user-images.githubusercontent.com/10468130/39950943-27e0644c-553a-11e8-81cd-1f05b6d7abc5.gif)

**Comment by tiberiuzuld** [comment]
Hi @shyambhiogade ,
No is not possible to give min width and height in px, the only option is `minItemCols` and `minItemRows`.
See https://github.com/tiberiuzuld/angular-gridster2/issues/228
