### ISSUE TITLE
Touch events help 

### ISSUE THREAD

**Issue by PeterDjukic** [tiberiuzuld/angular-gridster2#336]
Hi 

I have one question regarding touchevents. How do I get the content of the component inside gridsteritem to scroll on touch mobile. It works if the component is in seperet view. But when loaded in gridster nothing happens when intry to scroll. 

Thank you I have been killing myself over this

**Comment by tiberiuzuld** [comment]
Hi @PeterDjukic ,
Try to add the class `gridster-item-content` on the content element which has the scroll.

**Comment by PeterDjukic** [comment]
@tiberiuzuld  thank you 

But i have gridster-item-content. And i have now came to see that touch does work, but not all the time !? It starts working when i change mobile breakpoint option. But then it stops working.
I did not figure out when exactly it does and does not work. 

I'm sorry I can not post plunker of the problem.

Do you have any advice where to look ?

thanks

**Comment by tiberiuzuld** [comment]
Most probably in the gridsterDraggable.service where the drag start is, most probably the issue is there.

**Comment by PeterDjukic** [comment]
thanks i will take  a look
