### ISSUE TITLE
Dynamically loading content for each grid-item

### ISSUE THREAD

**Issue by dcp3450** [tiberiuzuld/angular-gridster2#338]
The documentation says to use `ng-dynamic-component` to dynamically load content into a grid item when it's added to the grid. Is there an example of this anywhere?

**Comment by tiberiuzuld** [comment]
Hi @dcp3450 ,
There are examples on the library page, https://www.npmjs.com/package/ng-dynamic-component
And probably there are examples also in some closed issues.
