### ISSUE TITLE
How to add new widgets from widget list if the gridster or dashboard has no room

### ISSUE THREAD

**Issue by vikasnawal** [tiberiuzuld/angular-gridster2#339]
Hi @tiberiuzuld ,

I am developing a customize dashboard where user have options to drag and drop the widgets from the widget list on left side. For  drag and drop i have used HTML 5 library, which is working properly and dashboard is also working properly. Thanks for this nice library...
I have been using angualar 2 along with angular-gridster2@2.4.20 library.

Below are my gridster configurations 

this.gridsterOpts = {
       girdType:'fit'       
       maxCol: 3,
       mincol : 3,
        minItemArea : 1,
        maxItemArea : 1,
        minRows: 3, // maximum amount of rows in the grid
        margins: [10, 10],
        draggable:{
                  enabled:true,
                   ignoreContent:true,
                  dragHandleClass:'handle-drag'
           },
   fixedRowHeight: 284,
emptyCellDropCallBack : emptyCellDropCallBack 
    };

I have fixed column size 3 and min rows size 3 and fixed container size. The issue is that I am not able to drag and drop more widgets in the container if there is no room inside dashboard container.I can only drop 9 widgets inside that container. So it is possible to add more widgets if there is no more space available in the container or container full.(3X3) I think there should be some scroll visible when there is no room in the grid.

Thanks in advance.

**Comment by tiberiuzuld** [comment]
Hi @vikasnawal ,
Yes hoping to fix this issue with the new dragging  #245
Closing this issue to have only one issue with the drag feature.
Thank you

**Comment by anji405** [comment]
Hi vikasnawal,
Could you share me the snippet on drag from sidebar drop on to angular-gridster2 , new dashboard widgets
