### ISSUE TITLE
allow floating of items

### ISSUE THREAD

**Issue by Hintalo** [tiberiuzuld/angular-gridster2#340]
Hi,

I would like to ask if a support for "floating" feature is planned. Floating means that at dragging away or resizing (reducing size) of one particular grid-item, the resulting empty space (if big enough) will be occupied by other grid-items automatically, so that they float up / left, consuming the available empty space.
We are currently using ["angular-gridster"](https://github.com/ManifestWebDesign/angular-gridster) in a NG1/NG6 hybrid app and we would like to migrate to the new Angular completely. Therefore we are searching for an alternative to "angular-gridster" that is an NG1 library.
I think, one of the most important features of such a grid-component is the automatic floating feature and "angular-gridster" supports this very well.
There is another Gridster implementation that is available for Angular2+ (named "[angular2gridster](https://github.com/swiety85/angular2gridster)") and this has some support for floating, but is not so flexible as the old NG1-library.
I think, your Gridster library is a good alternative to replace the old angular-gridster, because there are a lot of nice features, and I would very appreciate if the floating-feature would be also available.

Thanks.

**Comment by tiberiuzuld** [comment]
Hi @Hintalo ,
There is a "compact" feature which is similar to what you describe.
https://tiberiuzuld.github.io/angular-gridster2/compact

Take a look and tell me if it satisfies your needs.

Thank you

**Comment by Hintalo** [comment]
Yes, thank you for the info, this is very cool, actually I didn't recognised this feature in the demo earlier.
I think this is exactly that what we wanted. We will have a try.

**Comment by HCenggel** [comment]
Mash sain
Excellent
