### ISSUE TITLE
Cannot read property 'setPushedItems' of undefined when put gridster into IFrame

### ISSUE THREAD

**Issue by fienol** [tiberiuzuld/angular-gridster2#345]
Hi, GridSter is amazing, but when I put gridster2 into IFrame and did following steps, I get some errors:
1. drag item out of IFrame
item is still in Iframe while mouse is out of it. 
![image](https://user-images.githubusercontent.com/10250705/40352013-0eb739f8-5d6b-11e8-90d3-8f13b2b7517d.png)
"+" is my mouse
2. drop (mouse up)
at this time, nothing happens
3. move mouse back to IFrame and click, error comes
![image](https://user-images.githubusercontent.com/10250705/40352484-28df1840-5d6c-11e8-9b0a-38fe4efba9c6.png)

I did some research. The key point is platform-browser.js. When we drop out of IFrame, the code below is not executed, but this[symbolName] is added.
var globalListener = function (event) {
    var symbolName = symbolNames[event.type];
    if (!symbolName) {
        return;
    }
    var taskDatas = this[symbolName];

So when we click in the IFrame again, there are two values in the this[symbolName] which are both for mouseup, so we will delete this.push twice.

Can you confirm it is the reason and how can resolve it? Thanks.

**Comment by fienol** [comment]
I think the key point is why nothing happens in step 2. In the zoom.js
![image](https://user-images.githubusercontent.com/10250705/40401917-348a0fde-5e06-11e8-8647-e9f1fcb06e27.png)
when drop, we hope document can get this event, but for IFrame, when we drop out of IFrame, document in IFrame cannot get this event now.

**Comment by fienol** [comment]
Sorry, it not zoom.js, it is zone.js
![image](https://user-images.githubusercontent.com/10250705/40401997-915a41de-5e06-11e8-84bf-92323309ee1e.png)

**Comment by tiberiuzuld** [comment]
Hi @fienol ,

Possible to be related to this issue https://github.com/tiberiuzuld/angular-gridster2/issues/233

Please have a look and tell me if it fixes your issue.

Thanks

**Comment by fienol** [comment]
Hi @tiberiuzuld 
I went through that thread before I raised the issue. They are different. I had a workaround for this. I will capture the mouseup event when drop out of the IFrame, and dispatchEvent on the document in the IFrame, right now it works.
