### ISSUE TITLE
Drag issue of Gridster

### ISSUE THREAD

**Issue by Steven-ZhouMeng** [tiberiuzuld/angular-gridster2#348]
**Dear tiberiuzuld,**
I have found an issue about drag function when I use Gridster. Could you please help check it? Please refer to the detail as below:

**Issue Description:** 
Part of the gridster item was shown outside of the grid.

**Reproduce Steps:**
1. Access [drag page](https://tiberiuzuld.github.io/angular-gridster2/drag) of gridster demo.
2. Check "Allow Drop Over Items".
3. Drag the first item toward top left corner so that part of the item was not shown in the grid and drop the mouse. Then issue occurred, part of the item will not be shown in the grid anymore.

![image](https://user-images.githubusercontent.com/17919938/40411227-668c48a2-5ea2-11e8-8365-a82417834a4f.png)

**Comment by tiberiuzuld** [comment]
Hi @Steven-ZhouMeng ,
Thank you for reporting this.
Can confirm I was able to reproduce it.

Will try to have a fix for it this week but not promising.

Thank you

**Comment by tiberiuzuld** [comment]
Hi @Steven-ZhouMeng ,
Fixed in v6.0.5

Thanks
