### ISSUE TITLE
'$item' is undefined when click item with checking allow drop over items

### ISSUE THREAD

**Issue by Steven-ZhouMeng** [tiberiuzuld/angular-gridster2#350]
**Dear tiberiuzuld,**
I have found an issue related with allow drop over items function when I use Gridster. Could you please help check it? Please refer to the detail as below:

**Issue Description:** 
Cannot read property '$item' of undefined error occurred in console when click item with checking allow drop over items.

**Reproduce Steps:**
1. Access [drag page](https://tiberiuzuld.github.io/angular-gridster2/drag) of gridster demo.
2. Check "Allow Drop Over Items".
3. Just click on the Gridster item but do not click on the delete button.

![image](https://user-images.githubusercontent.com/17919938/40471625-cd96ff8e-5f69-11e8-8f91-a9c74f00392e.png)

**Comment by tiberiuzuld** [comment]
Hi @Steven-ZhouMeng ,
Is the same issue as https://github.com/tiberiuzuld/angular-gridster2/issues/348
Will try to have it fix today or tomorrow.

**Comment by Steven-ZhouMeng** [comment]
Hi @tiberiuzuld,
Yes, both issues have this error in the console. Please kindly let me know when you fixed it. I will verify it after your fix. Thanks a lot.
