### ISSUE TITLE
is there api to get itemComponent to be used later in any other function, 

### ISSUE THREAD

**Issue by shyambhiogade** [tiberiuzuld/angular-gridster2#352]
hi @tiberiuzuld , 
is there any function which will give me itemComponent object, 
to be able to use pushItem api i need itemComponent, but i found that only in initItem callback function, itemComponent is available, so i save the itemComponent is item as below to be used later. 

`
    initItem(item, itemComponent) {
        item["itemComponent"] = itemComponent;
    }`

but i think its not good way, as item has itemComponent, and itemComponent has item, 

i am using gridster from angularjs as our application is not yet into angular, 

can you suggest me on how to get itemComponent directly.

**Comment by CollinGraf314** [comment]
I'm not entirely sure if this will help, but you might want to give it a try. 
```
public myItem: itemComponent;
constructor(){
     this.options = {
             itemInitCallback: this.itemInit.bind(this)
     }
}
public itemInit(item: gridsterItem, itemComponent: gridsterItemComponent){
     this.myItem = itemComponent;
}
```

**Comment by shyambhiogade** [comment]
myItem at a time will have just one component which was initialized last, if i want to get any other item, i dont have a way. what i am doing is 
item.myItem = itemComponent;

**Comment by CollinGraf314** [comment]
public myItem: GridsterItemComponent;
constructor(){
     this.options = {
             itemInitCallback: this.itemInit.bind(this)
     }
}
public itemInit(item: GridsterItem, itemComponent: GridsterItemComponent){
     this.myItem = itemComponent;
}```

**Comment by CollinGraf314** [comment]
```
public myItems: GridsterItemComponent[];
constructor(){
     this.myItems = [];
     this.options = {
             itemInitCallback: this.itemInit.bind(this)
     }
}
public itemInit(item: GridsterItem, itemComponent: GridsterItemComponent){
     this.myItems.push(itemComponent);
}
```

**Comment by shyambhiogade** [comment]
yes, this is one way, but every time, it will have to iterate through all items, i would prefer if there is any optimized way/api of getting itemComponent, @tiberiuzuld  do you have any suggestion.

**Comment by shyambhiogade** [comment]
@tiberiuzuld can you please help
