### ISSUE TITLE
Saving grid state on itemChange can access only static functions, services

### ISSUE THREAD

**Issue by kunal105** [tiberiuzuld/angular-gridster2#353]
itemChange callback function cannot access local class variables, function or injected services. It can only access static methods and variables. I am injecting a service  in my class which has a post api call to save grid state to database. I cannot call an instance of this service ex this.mydbservice inside the itemChange callback function. Is there a non static way to save the state of grid on every item change

some relevant code below.... 

 constructor(private userService: UserService, private router: Router, private route: ActivatedRoute)
  {
}
itemChange(item: GridsterItem, itemComponent: GridsterItemComponentInterface) {
     console.info('itemChanged', item, itemComponent);
   savetoDb(item,itemComponent) //cannot call this function here 
  }

savetoDb(item,itemComponent )
{
call injected service savetoDb function here
   this.userService.saveTodb...............
}

**Comment by CollinGraf314** [comment]
try using this:
```
 this.options = {
         itemResizeCallback: this.itemResize.bind(this)
 }
```

**Comment by kunal105** [comment]
thanks that worked. closing this
