### ISSUE TITLE
Leaflet map is not loading propery inside a gridster item

### ISSUE THREAD

**Issue by ganigapeta** [tiberiuzuld/angular-gridster2#355]
Hi,

I am trying to load leaflet map inside a gridster item, but it is not loading properly please see the attached screenshot. 

![capture](https://user-images.githubusercontent.com/5964992/40702061-0f1cd71a-63fe-11e8-95cf-b87ac76e0955.PNG)

but out side the gridster it is working perfectly.

**Comment by CollinGraf314** [comment]
Children of gridsterItems cannot read the dimensions of their container. This issue might be very similar to issue #308 where people were having trouble putting highcharts charts inside gridsterItems. Here is a stackblitz that shows how to tell inside component what dimensions it should be: https://stackblitz.com/edit/angular-xjdard
https://angular-xjdard.stackblitz.io

**Comment by ganigapeta** [comment]
@CollinGraf314 Thanks for the quick suggestion will check and let you know.

**Comment by smoore2386** [comment]
@ganigapet This might be related to the leaflet css. We have it currently working well in our app. This is just offhand will check back later 
`
<div *ngIf="mapId" id="{{mapId}}" [class]="stylingClass"></div>
  .map-widget {
    height: 24em;
    width:100%;
    margin-left: .45em;
  }
`

**Comment by davidcunningham** [comment]
@ganigapeta - I'm experiencing the same issue and have tried both CSS changes and passing height/width from gridster to the leaflet div and I'm having the same issue as your screenshot. Were you able to resolve this?
