### ISSUE TITLE
Changing gridster.css file

### ISSUE THREAD

**Issue by sonulchoi217** [tiberiuzuld/angular-gridster2#361]
I would like to make some styling changes, but I am having trouble finding gridster.css file when I install the package through "npm install angular-grister2 --save" command.  It seems like the gridster.css file gets incorporated into somewhere in the bundle. Which file do I need to open in the angular-gridster2 library to apply changes in gridster.css file? Thank you so much!

**Comment by CollinGraf314** [comment]
The angular-gridster2 module does not have any style sheets available for you to modify. Any styling you want to do should be done within the style sheets in your application.
