### ISSUE TITLE
Export gridster component as "Angular Element"

### ISSUE THREAD

**Issue by bitflower** [tiberiuzuld/angular-gridster2#369]
Hi, before trying this out I thought it might be worth to ask if you as the developer of the package think its possible to do and worth the work?

I want to use this in a non-angular (StencilJS) app.

Thanks!

**Comment by CollinGraf314** [comment]
I believe that this functionality is not possible. A non-angular compiler will not be able to read/understand any angular elements. If you were to create an iframe or something that runs your angular code and then nest that into your non-angular project, then that would work, just know that the two projects would be more or less completely separate
