### ISSUE TITLE
Grid stylesheet

### ISSUE THREAD

**Issue by ruffiem** [tiberiuzuld/angular-gridster2#37]
The gridster element is deep-styled, would it be possible to add an option to support styling ? Or just not use the :host style binding property ? Thanks.

**Comment by tiberiuzuld** [comment]
Hi @ruffiem ,
You mean you cannot override the default style ? 
for me this works:
```javascript
gridster {
  background: red;
}
// or
gridster:hover gridster-item {
  background: red;
}
```

If you have other issue please give me an exact example of what style you cannot override.

**Comment by ruffiem** [comment]
I can override the style using the !important flag in my SASS. Otherwise, it takes the default background. 

Without important
![screen shot 2017-05-09 at 09 21 13](https://cloud.githubusercontent.com/assets/1785492/25839720/3625eaf8-3499-11e7-9984-8897ba6bae8b.png)

Thank you @tiberiuzuld

**Comment by tiberiuzuld** [comment]
Hi @ruffiem .

For me this worked:
```
:host gridster /deep/ gridster-preview {
  background: red;
}
```
Let me know if this works for you

**Comment by ruffiem** [comment]
Hi @tiberiuzuld,

Thanks for the answer again 😃 .

The Gridster default style is set directly on the `:host` which add styles to the component on the lowest possible level. 

If you don't style the component directly on the `:host` (eg. your example), Angular will not listen to styles coming from a higher level - which is an acceptable behaviour.

Let's take the case you're using Angular material and use its [practice recommendations](https://material.angular.io/guide/theming-your-components) to style custom components. You don't access `:host` since you style the target element because you don't have access to `:host`. It means that if you're not styling the component directly in the component stylesheet, you must add `!important` flags on every CSS property you want to override which is not defined as a good practice.

A good alternative would be to use classes to give a default style to Gridster instead of using `:host` which is too low and not easily accessible. It will not affect the code much and it would be easier for developers to add custom style to the component.

What do you think ?

**Comment by tiberiuzuld** [comment]
Hi @ruffiem 

So I move the gridster-preview css to it's own css file. Added class `gridster-preview` to the 
`gridster-preview` 

Now this css will override the background
```
gridster /deep/ .gridster-preview{
  background: red;
}
```

You can test this on v2.9.2

**Comment by ruffiem** [comment]
Yes, it works like that, thank you @tiberiuzuld

**Comment by tiberiuzuld** [comment]
@ruffiem 👍

**Comment by swapnil-proctur** [comment]
@idreeshaddad 
:host gridster{
  background: red;
}
