### ISSUE TITLE
Is it possible to customize border styles on rows and columns.

### ISSUE THREAD

**Issue by daveladouceur** [tiberiuzuld/angular-gridster2#370]
Is it possible to do the following.
Every 4 column set that represents 15 minute increment.
There is a dark column border on the hours and a light border on the 1/2 hours and no border on the 15 minute increments.

**Comment by CollinGraf314** [comment]
This can be achieved using the gridster-item::nth-child() {} css rule.

**Comment by daveladouceur** [comment]
THANKS! You have a resume?

**Comment by CollinGraf314** [comment]
I have one better, I have a job ;)
