### ISSUE TITLE
Preview not showing when resizing

### ISSUE THREAD

**Issue by ImDarrenParker** [tiberiuzuld/angular-gridster2#373]
Hi @tiberiuzuld,

We currently have an issue where the preview that displays when resizing is not showing or tracking the item we are interacting with however, when dragging it works perfectly.

We have an edit button that enables both the resizable and draggable options, then displays a "plus" item for adding another widget. This appears in the form of another item in the dashboard.

Using the start and stop callbacks of both resizing and dragging the "plus" item is removed when the interaction has started and re-added when stopped.

For dragging, previewing works perfectly fine but resizing does not.

It may be too brief a description but have you had any other similar implementations where this has been a known issue?

Thanks!

![preview](https://user-images.githubusercontent.com/32125286/41855426-8e58a86a-788a-11e8-9fad-28dd596c8361.gif)

**Comment by tiberiuzuld** [comment]
This should have been fixed now.
