### ISSUE TITLE
Set the height of the component div same as item height

### ISSUE THREAD

**Issue by kunal105** [tiberiuzuld/angular-gridster2#379]
I am able to get the height of the item on the itemResize event as below. I am not sure how I can resize the div inside the ng dynamic component. the component has change detection and I pass the height to inputs param. It can detect the change. However my div has a JS chart and height of the div has to change and JS chart has to refresh. Is there a way to rebind/readd/update the item widget on resize? I tried explicitly removing and adding the widget back inside the resize but that had undesired behavior like going into infinite loop. Below is relevant code. I have been struggling on this for last few days

   itemResize(item: GridsterItem, itemComponent: GridsterItemComponentInterface) {
     console.info('itemResized', item, itemComponent);
     const compWidth = itemComponent.el.style.width;
     const compHeight = itemComponent.el.style.height;

     if (item.inputs.widgetData != null) {
       let data = item.inputs.widgetData;
       item.inputs.widgetData.height = compHeight
     }

 <div class="gridster-item-content" >

      <div class="row" style="margin-top:3px;margin-left:1px;margin-right:1px">
        <div class="col-12 text-muted" style="height:100%;">

          <ndc-dynamic *ngIf="item.component != null" [ndcDynamicComponent]="item.component" [ndcDynamicInputs]="item.inputs"></ndc-dynamic>

        </div>
      </div>
    </div>
  </gridster-item>

Component html. 
The div below loads chart for JS function which is called in the ts file. This works on adding the widget first time. on resizing, i need to be able to change the height.
<div class="tradingview-widget-container" *ngIf="widgetKey == 'trading-view-advance-chart' ">
  <div [id]="tradingViewId" style="height:1000px;"></div>

</div>

component ts

ngAfterViewInit() {

          let s = this._renderer2.createElement('script');
          s.type = this.widgetData.widgetSetting.type;
          s.src = this.widgetData.widgetSetting.src;
          //if (this.widgetData.height != null && this.widgetData.height != "")
          //  s.text = JSON.stringify(this.widgetData.height);
          s.text = JSON.stringify(this.widgetData.widgetSetting.data);
          this._renderer2.appendChild(this.tradingViewContainer.nativeElement, s);
          break;
             

      this.ref.markForCheck();
    }

      

   
  }

**Comment by CollinGraf314** [comment]
If you are using highcharts or something similar, this stackblitz might help: https://stackblitz.com/edit/angular-xjdard

**Comment by inorganik** [comment]
You can simply apply these styles to the root element of the component loaded inside the gridster item:

```css
.fill-height {
  display: flex;
  align-items: stretch;
  height: 100%;
  min-height: 100px;
}
```

**Comment by kunal105** [comment]
Thanks, I was able to get this to work

**Comment by gethari** [comment]
@inorganik can you please check this out ? I got it working with a plugin called fitty, but could'nt get it working on my application. Is there a better alternative or solution to simulate this ?

https://stackblitz.com/edit/tiberiuzuld-angular-gridster2-kdnkbt
