### ISSUE TITLE
Option to disable scroll when drag/resize

### ISSUE THREAD

**Issue by andrei-tatar** [tiberiuzuld/angular-gridster2#382]
Hello,

I'm running gridster in a configuration where I have a fixed number of columns with fixed widths (same for rows). I would like to be able to disable the scroll when dragging items around or resizing them.
I tried setting the following, in the config object:
```
scrollSpeed: 0,
scrollSensitivity: Number.MAX_SAFE_INTEGER,
```
The problem is that there are a lot of jump arounds and jitter whem I drag an item.

I tried commenting out the scroll function from the gridsterScroll.service.ts and it works just fine, however I am not able to change the way it works since it isn't exposed in any way.

Thanks!

**Comment by PartyArk** [comment]
This worked for me - it's a bit of a hack but the `dragMove `function is exposed so you can overwrite it without messing around with the original code. I've taken out the `checkTouchEvent `(because is causes a lot of jerkiness) and the window scrolling. Add this to the options you pass in.

```
        // this is a bit of a hack by disabling the checkTouchEvent and the window scrolling
        // we stop all sorts of unpleaseant scrolly behaviour. compare with original code.
        options.itemInitCallback = (_: GridsterItem, b: GridsterItemComponentInterface) => {

            b.drag.dragMove = function (e: any): void {
                e.stopPropagation();
                e.preventDefault();
                this.offsetLeft = this.gridster.el.scrollLeft - this.gridster.el.offsetLeft;
                this.offsetTop = this.gridster.el.scrollTop - this.gridster.el.offsetTop;
                this.calculateItemPositionFromMousePosition(e);
            };
        };
```

**Comment by andrei-tatar** [comment]
@PartyArk Thanks for the solution, works great!
