### ISSUE TITLE
ItemResize getting triggered on constructor and ngOnInit()

### ISSUE THREAD

**Issue by ballySingh** [tiberiuzuld/angular-gridster2#386]
Hi,

What I'm doing is storing my items in the localstorage. How I am doing this?  obvious, every time a change or size happens. No problem we got itemResizeCallback & itemInitCallback. 

So  logic is when a change/itemInit occurs add it to local storage i.e localStorage.setItem(key, xxxx).  Works perfect, I see that it's being store.

But the issue occurs when I want to use what's been set in the local storage. I want to use me localstorage value and set it in to my this.dashboard[] array, to display when a user refreshes or open the page in the future.

What I see happening is when I add each object to the dashboard array in the constructor or onIinit.
The  itemResizeCallback & itemInitCallback is excuted and the bit of code which adds to the local storage is adding the same object again.

I was wondering is there a flag/indication to know when a item is set from the constructor or is there a way to prevent the functions from be used i.e  itemResizeCallback & itemInitCallback? 

Hope this makes sense :)

Thanks

**Comment by CollinGraf314** [comment]
Item resize getting triggered when the item is initialized in the grid is desirable behavior. Here is a stackblitz with an example of how to set your own flag so that you only run some code on each resize after the initial resize: https://stackblitz.com/edit/angular-xjdard. I hope this helps you.

**Comment by ballySingh** [comment]
Many Thanks this has helped me with this issue and enlighten me on something else ;)
