### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by MaiGhoneem** [tiberiuzuld/angular-gridster2#388]
Hello,
I need to ask if there is any plan to support rtl or not? and if it is not, can you please help me to guide me how to start implement this part?

**Comment by demirmusa** [comment]
Are you planning to make this enhancement soon?
We also use that in ASP.NET Zero, we would be appreciated if this enhancement is done.

**Comment by demirmusa** [comment]
Hi @tiberiuzuld 
Is there any update?
