### ISSUE TITLE
Back porting features to 1.x version

### ISSUE THREAD

**Issue by karanaditya993** [tiberiuzuld/angular-gridster2#39]
Hey @tiberiuzuld 

Was drag-handler ever implemented to this version (angular 1 version)? If not, I can spin something up and contribute if you'd like. Thanks.

**Comment by karanaditya993** [comment]
@tiberiuzuld quick update on this, I've managed to get a drag handler working for angular 1 version. I'm now working on implementing gridsterPush for angular 1. Will submit a PR with **both** these features when finished.

**Comment by karanaditya993** [comment]
gridsterPush has proven to be much more difficult...challenge accepted

**Comment by tiberiuzuld** [comment]
@karanaditya993  good to know :) yes gridsterPush took me a week to make it work :D good luck :)

**Comment by karanaditya993** [comment]
@tiberiuzuld I got push to work with the widgets/tiles, which is great. However, I now seem to be experiencing issues with the persistence of the tile placement...not sure if this is because of the push function or because of the drag function. Have you experienced these errors in console before:

Can't be placed in the bounds of the dashboard, trying to auto position! Object {cols: 1, rows: 1, x: undefined, y: undefined, initCallback: undefined…}

Looks like the x and y positions are undefined therefore the gridster is autopositioning them. This is causing their placement to change on refresh/reload.

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
You need to use initCallback when adding a new widget to save it in your DB with the x an y auto filled by the Gridster. So on refresh you will have the position correct. 
And for update use the callbacks from drag and resize.

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,

After `v2.10.0` I think is more easy to back port the whole library code to `v1.x` instead of back porting the each feature that is not in `v1.x`

So what I have in mind is to copy the `lib` folder to `v1.x` branch, remove the `types`, replace angular2 code with angular1 and then change the demo.  

I don't know when I will have time for this since this will take a while to make.

**Comment by karanaditya993** [comment]
@tiberiuzuld that would be great. I've modified a lot of the code on my end to support v1, but once you've completed the back porting, I'll just switch over to yours completely. Thanks very much.

**Comment by karanaditya993** [comment]
@tiberiuzuld wondering if you've made any progress on this and whether or not you have an ETA? thanks very much.

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
Unfortunately didn't had any time to make it happen.
And in the near future don't have time for it. 
Only after the first week of July will hopefully have time for it.

**Comment by karanaditya993** [comment]
@tiberiuzuld sounds good, whenever you get to it please let me know. Thanks again.

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
A small update to the status of the migration.

Migrated most of the code backwards to angularjs 1.6.x
Still have some things left to do:
* make build work with the components html files
* update readme.md
* update demo
* test all the features
* make release

Probably will finish this week.

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
Managed to finish the the migration released in v1.4.0
Watch out for the breaking changes.

**Comment by karanaditya993** [comment]
@tiberiuzuld Thanks so much for doing this, really. Did you mean that you backported the features to AngularJS 1.4.0?

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
To AngularJS v1.5 is the minimum that it can work. Since I used components.

Thanks,

**Comment by karanaditya993** [comment]
Beautiful, I'm migrating the application I'm working on to Angular 1.5, so will see how implementing your gridster will work with these once I've done so. Thanks again for all your help!
