### ISSUE TITLE
Can GridsterItemComponent detect ngClass changes?

### ISSUE THREAD

**Issue by apcrash** [tiberiuzuld/angular-gridster2#391]
Hi,

We are currently using your awesome library in our project and we implemented a fit to screen full-screen method based on #38 solution thru ngClass. The solution works for the gridster item size, (we can maximize the item) but the content widget is not resizing according to the new gridster size provided by the ngClass because as I checked the itemComponent values in itemResizeCallback, it still has the original width and height values.

Is there a way for itemComponent to detect or update itself when a class changes its size?

Thanks!

**Comment by CollinGraf314** [comment]
Actually, re-reading your question it sounds like you are simply using CSS to expand the GridsterItem to fill the whole screen. While this works, you should avoid it as for all intents and purposes the grid will still think the GridsterItem's size is its number or rows * grid row height by its number of columns  * grid column width. This means that the content inside the GridsterItem is restricted to what the grid thinks the GridsterItem's dimensions are. 

You could try handling this differently by actually setting the GridsterItem's dimensions to be { x: 0, y: 0, rows: maxrows, cols: maxcols }, where maxrows and maxcols are just the number of rows/cols currently in the grid. Just make sure to save the old dimensions somewhere to collapse the GridsterItem back to its original size/location when the time comes.

**Comment by apcrash** [comment]
Thank you for the reply. I will try this approach. I'll comment back if this solves it.

**Comment by CollinGraf314** [comment]
That functionality is nearly impossible to get with this repository. Think of the following case:

Given: gridsterItems must fill exactly one or more grid cells, columns cannot change width mid-way through the column, and rows cannot change height mid-way through the row. 
You have two gridsterItems, one has content of size of 200px by 200px and one has content size of 181px by 181px.
It is now impossible for these two gridsterItems to be adjacent to each other unless each row and column had a height/width of 1px. 

For now obvious reasons this functionality is not included in the repository, however, given a few conditions you can still add this functionality yourself. If you know for a fact that all of your content for each gridsterItem is going to have the same dimensions, then if you can find a way to calculate the height/width of that content, you can then set the fixedRowHeight or fixedColumnWidth properties on the gridster configuration object and run `this.options.api.optionsChanged();` where this.options is your gridster configuration object. You could even go one further and calculate the total height/width of your grid, and then set minRows/maxRows minCols/maxCols to be the grid-height/row-height and grid-width/col-width rounded down. You also have the option to simply limit yourself to a single item on your grid, or to make the grid's row height and column width to each be 1px, but defeats most of the purpose of using angular-gridster 2 in the first place.

**Comment by apcrash** [comment]
Hi,

I was able to find a workaround by adding a (transitionend) on the gridster item and it works. I no longer need to modify the cols, rows, x and y.

My only issue right now is the performance bottleneck on the gridsterOptions.api.resize() method as it fires all items' itemResizeCallback. Is there a way to trigger only the modified item's itemResizeCallback without triggering the others?

**Comment by CollinGraf314** [comment]
Sadly no. The simplest work around would be to store some sort of identifier or a boolean flag on the item that is only true if it is the item that has been modified, then wrap the content of the itemResizeCallback in an if-statement.

Also, I think I've run into this issue before where itemResizeCallback fires much more often than it's supposed to (only once after a resize has completed). When I ran into the issue it was a very strange bug specific to Chrome where having a css border-top rule caused the resize event to fire many times while dragging the gridsterItem around. If that is your problem, than I just recommend some good old debugging because the issue is likely project specific.
