### ISSUE TITLE
Setting gridster-item size on initialization of grid?

### ISSUE THREAD

**Issue by katye610** [tiberiuzuld/angular-gridster2#393]
Looking to persist (and later recreate) the exact layout of a grid, so that the user can resize and/or drag items around and then have the grid show up the same way the next time they log in.

Obviously, the location of the items can be set with their x and y coordinates, but how can I create an item at a specific height and width? I can see the height and width properties on the itemComponent object that is passed into the resizeable.stop callback function, I just don't know how to pass them into items. Appreciate any help!

**Comment by CollinGraf314** [comment]
Each item has object is as follows: ```
{
x: number, 
y: number, 
rows: number, 
cols: number
}```. 
An item's height is the same as the 'rows' property and an items width is the same as the 'cols' property, so simply saving an array of these items should save the layout of your dashboard. Note that there is no good way to store pixel heights/widths unless you feel like writing some custom code in your application to do it.
