### ISSUE TITLE
Can't bind to 'options' since it isn't a known property of 'gridster'

### ISSUE THREAD

**Issue by xif3681** [tiberiuzuld/angular-gridster2#397]
<gridster [options]="options">
      <gridster-item [item]="item" *ngFor="let item of dashboard">
        
      </gridster-item>
    </gridster>

**Comment by CollinGraf314** [comment]
This sounds like it's a problem with your imports. Also make sure that you in your component you are creating an object called 'options' of type GridsterConfig. If this still doesn't fix your problem, here is a quick stackblitz that you might be able to use to debug what your doing.
https://stackblitz.com/edit/angular-fphqah
