### ISSUE TITLE
Check if the grid area is fully occupied or a Notifying/Alerting mechanism for the user if the gridster item doesn't fit within the grid area

### ISSUE THREAD

**Issue by arjun-varrier** [tiberiuzuld/angular-gridster2#403]
Hi @tiberiuzuld,

I am implementing a cockpit page and the size of the cockpit is 3x3. The widgets which can be added to the cockpit has different sizes varying from 1x1, 2x1 to 3x3. 
Currently, whenever I add a widget which cannot be placed within the cockpit, 
(Eg - The 1st row of the grid is occupied and then I choose a 3x3 widget) I see a warning in the console which says "Can't be placed in the bounds of the dashboard" and the gridster item is not added to the grid area.
So I wanted to know is there api/property to figure out if the grid area is fully occupied or which tells that the added gridster item won't fit in the grid area? 
This would be helpful for me to alert the user accordingly.

Thank You.

**Comment by CollinGraf314** [comment]
Very similar to #360. I do not currently have an answer for this. If anyone else has a solution I'd appreciate the hearing it.

**Comment by tiberiuzuld** [comment]
Will be covered by  #360

**Comment by er-shrey** [comment]
In case of gridster does not have enough space to add any new item, it will still add it and will not add any key like x,y,cols,rows and if it's already there it will make all to undefined.

You will just need to loop it over the grid-items after a timeout of say 500, to check if the values x,y,cols and rows are there or not... It not then it means the gridster is fully occupied and hence you can through an event or call a function as per required.

**Comment by develop-akumar** [comment]
There is  a property **"notPlaced"** by which we can find out wether the gridster is occupied or not. when we try to add a item in gridster, there is a event "itemInitCallback" fires. 

![image](https://github.com/tiberiuzuld/angular-gridster2/assets/100281934/42e52db3-d350-4053-a1bb-2309dcc6a0ba)

**Sample link** - https://tiberiuzuld.github.io/angular-gridster2/gridEvents

**Gridster events .ts file link** - https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/app/sections/gridEvents/gridEvents.component.ts

Steps to achieve
1. Register event in gridster config
 this.options = {
      gridType: GridType.Fit,
      displayGrid: DisplayGrid.Always,
      initCallback: GridEventsComponent.gridInit,
      destroyCallback: GridEventsComponent.gridDestroy,
      gridSizeChangedCallback: GridEventsComponent.gridSizeChanged,
      itemChangeCallback: GridEventsComponent.itemChange,
      itemResizeCallback: GridEventsComponent.itemResize,
      
      **itemInitCallback: GridEventsComponent.itemInit,**
     
      pushItems: true,
}

2. write callback function for itemInitCallback event

itemInit = (
    item: GridsterItem,
    itemComponent: GridsterItemComponentInterface
  ): void => {

    if (itemComponent.notPlaced == true) {
     // gridster is full, there is no space for new item
    } else {
     // Gridster has space for new item
    }

  }
  
  // itemComponent.notPlaced will be true if gridster has no empty space for new item
      
I hope this will help you as this helped me a lot and worked in my case.
