### ISSUE TITLE
Push items in occupied space when dragging in a new dashboard item

### ISSUE THREAD

**Issue by mbizzle** [tiberiuzuld/angular-gridster2#406]
I'm currently trying to pull in items from a control panel and it works when adding items to an empty space. What I need to do is be able to add more items and push items from occupied space when dragging in items from the same control panel. Is that something that can be done?

**Comment by CollinGraf314** [comment]
Look at #245. Currently I do not believe this is something that is possible, however this is something that this library will hopefully support in the future.

**Comment by tiberiuzuld** [comment]
Will be covered by https://github.com/tiberiuzuld/angular-gridster2/issues/399

**Comment by mpotter-modus** [comment]
@tiberiuzuld #399 Look like it only allowed for dropping into an empty space. Is there a way to drop onto an _occupied_ space and have the existing contents shift around?

**Comment by mpotter-modus** [comment]
I've created a PR #540 to address my previous comment.
