### ISSUE TITLE
Grid not rendering

### ISSUE THREAD

**Issue by mervindsouza** [tiberiuzuld/angular-gridster2#410]
I am new to Angular and TS, I was trying gridster2 and for some reason even after trying the examples given on the website, the grid renders as a single row as shown below. 

<img width="1644" alt="screen shot 2018-08-20 at 2 40 26 pm" src="https://user-images.githubusercontent.com/10725440/44362584-0c60a280-a487-11e8-95db-2b818a8faed6.png">

Please help.
Thank you.

**Comment by CollinGraf314** [comment]
Unless you use the setGridSize property (set's size of parent gridster element based of child gridsterItem elements), the parent gridster element has a very small default height, so you must overwrite it with CSS. Example: The following will set the height of the parent gridster element to 50% of the screen.
```
gridster {
    height: 50vh;
} ```

**Comment by mervindsouza** [comment]
That worked. Thanks @CollinGraf314
