### ISSUE TITLE
Cascading push does not work

### ISSUE THREAD

**Issue by munga73** [tiberiuzuld/angular-gridster2#411]
When I have a gridster item with just one item directly below and I resize the top one downward, the resize works.  

When I have a stack of gridster items (i.e. an item with more than one item, directly below) and I resize the top one downward, the resize fails.  It appears that the push on the first item, directly beneath, does not cascade to the item beneath that.

Any ideas?

**Comment by CollinGraf314** [comment]
The push api for this library is not perfect, see #281 and #363. In fact we are asking for help in developing it, so if you have any ideas for algorithms that would improve the api, please help out by sharing your knowledge here or creating a pull request.

Thank you!
