### ISSUE TITLE
current Demo Flickering in Chrome

### ISSUE THREAD

**Issue by Logic-Bits** [tiberiuzuld/angular-gridster2#413]
Hello,

just wanted to let you know that the current Demo flickers alot while moving items around:

https://tiberiuzuld.github.io/angular-gridster2/compact

Best!

**Comment by CollinGraf314** [comment]
Hmmm... I see the problem and I will look into it. Thanks for bringing this to my attention.

**Comment by saif0724** [comment]
Hello

i also facing same issue in angular-gridster2 7.0.1 version. please give solution for that.
