### ISSUE TITLE
How to Add widgets to a better place/ view

### ISSUE THREAD

**Issue by gethari** [tiberiuzuld/angular-gridster2#427]
I add this widget dynamically. I don't specify any size in that. The widget just contains the data to display. It is automatically displaying too small. How can i make it better ? Sorry can't seem to find some documentation on this

![image](https://user-images.githubusercontent.com/20477956/47198436-c3937000-d389-11e8-8c5f-4d088069a526.png)

Maybe make it look like this or better ?
![image](https://user-images.githubusercontent.com/20477956/47198486-1836eb00-d38a-11e8-9d7a-3bc56281f2a4.png)

**Comment by equero** [comment]
Could you please give us more information about your problem.

What could i understand is, that you need to set a initial size depends of the content inside.

The only way i can imagine is with a parameter in your object with a minimum size

**Comment by petarGitNik** [comment]
Which chart library are you using? It seems that the plot is not responsive relative to the size of the grid item.

**Comment by hariharan618** [comment]
> Could you please give us more information about your problem.
> 
> What could i understand is, that you need to set a initial size depends of the content inside.
> 
> The only way i can imagine is with a parameter in your object with a minimum size
> 
> @hariharan618 btw, did you look at the new version of angular (7.0.1) Solves your problem
> 
> ![asdasdasd](https://user-images.githubusercontent.com/7300634/47443369-6a29a780-d7b4-11e8-9e2f-7f35a1c7fa97.gif)
> 
> [Blog post](https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c) speaking about the new drag&drop implemented and [documentation link](https://material.angular.io/cdk/drag-drop/overview)

Thanks for the reply. I am taking a look the the Angular 7's native drag and drop. Can we have the card size dynamically based on the content inside the card ?

**Comment by tiberiuzuld** [comment]
Maybe do a calculation before adding the widget on how big the grid is and it's size and determine what size the widget should have.
PS: Yes I saw the new drag functionality considering if the library is still needed. Or migrate to use that drag functionality.

**Comment by mujahid-akbar** [comment]
> Could you please give us more information about your problem.
> 
> What could i understand is, that you need to set a initial size depends of the content inside.
> 
> The only way i can imagine is with a parameter in your object with a minimum size
> 
> @hariharan618 btw, did you look at the new version of angular (7.0.1) Solves your problem
> 
> ![asdasdasd](https://user-images.githubusercontent.com/7300634/47443369-6a29a780-d7b4-11e8-9e2f-7f35a1c7fa97.gif)
> 
> [Blog post](https://blog.angular.io/version-7-of-angular-cli-prompts-virtual-scroll-drag-and-drop-and-more-c594e22e7b8c) speaking about the new drag&drop implemented and [documentation link](https://material.angular.io/cdk/drag-drop/overview)

@equero the layout in picture is achieved using gridster or angular drag and drop?
