### ISSUE TITLE
Browser support docs missing

### ISSUE THREAD

**Issue by jtushar53** [tiberiuzuld/angular-gridster2#43]

**Comment by tiberiuzuld** [comment]
What angular4 supports

**Comment by tiberiuzuld** [comment]
I tested the v2.x only on latest Chrome and Firefox.
If you find bugs in other browser make an issue or a PR.
Currently on my project I still use the v1.x , made the v2.x because people wanted it.

**Comment by jtushar53** [comment]
Oh missed that out. thanks for pointing out. 
I am having some issue on IE 11 with angular 4 , checking
