### ISSUE TITLE
Not able to resize Diagonally when there is item aside

### ISSUE THREAD

**Issue by gauravoodles** [tiberiuzuld/angular-gridster2#435]
Hi @tiberiuzuld , I'm facing an issue while resizing the item diagonally, when there is gridster-item aside.
Aside item is not moving downward, Is there any way to overcome this ?

Thanks

**Comment by tiberiuzuld** [comment]
Hi @gauravoodles ,
There is a current limitation the PUSH algorithm.
https://github.com/tiberiuzuld/angular-gridster2/issues/281
Any help is welcomed.
