### ISSUE TITLE
Drag & drop gridster-item between different gridster 

### ISSUE THREAD

**Issue by jewway** [tiberiuzuld/angular-gridster2#437]
Hi, @tiberiuzuld 

Have any way to DND item between different gridster for nested case ?

Thanks a lot for your work.

**Comment by CollinGraf314** [comment]
related: #245 #357 #399

This is currently unsupported, but may be supported in the future.

**Comment by tiberiuzuld** [comment]
@CollinGraf314 is right is a feature requested a lot, with current implementation is kinda hard to work, a refactoring of the library and API is needed.

**Comment by andreElrico** [comment]
Is there any updates regarding "exchange elements between gridster"?

**Comment by CyberV** [comment]
@tiberiuzuld Any update on this feature?
