### ISSUE TITLE
Need some help cell drop if cell is not empty In Gridster 2 demo like drag me

### ISSUE THREAD

**Issue by hamzash750** [tiberiuzuld/angular-gridster2#438]
Hye Tiberiu Zuld i need some help from the empty cell drop function like when we drop on gridster2 demo page drag me on empty cell they work fine but i need to help how can we drop on if cell is not empty and add the the current item in current cell other item will move  i have add two gif image for understanding what i need one image in gridster site other is my work that i have done

**Comment by hamzash750** [comment]
![gridstersite](https://user-images.githubusercontent.com/22794155/48547764-304c4c80-e8ed-11e8-9f6d-601a6c1394a9.gif)
![gridstersitedashboard](https://user-images.githubusercontent.com/22794155/48547765-30e4e300-e8ed-11e8-9bc7-ee2594d0a9f6.gif)

**Comment by tiberiuzuld** [comment]
Hi @hamzash750 ,
This issue is related to https://github.com/tiberiuzuld/angular-gridster2/issues/399
Currently there is no solution for this.
Any PR adding this functionality is welcomed.

**Comment by vguleaev** [comment]
Any progress on it?

**Comment by viethien** [comment]
@hamzash750 can you share your dashboard in stackbliz, It is nice, i want to refer your dashboard. Thanks

**Comment by hamzash750** [comment]
okay i will done soon in stackbliz and than share link with you...
