### ISSUE TITLE
GridsterComponent  ngOnChanges performance

### ISSUE THREAD

**Issue by laserus** [tiberiuzuld/angular-gridster2#439]
I have a performance related question on following. I was testing the component in "dev" mode with `ng serve` without `aot` flag and found that it is extremely slow in my browser and makes a lot of updates per second. Then  I checked the code and found that a lot of time happens options update event (and all event firing related to that) 
```
ngOnChanges(changes: SimpleChanges) {
    if (changes.options) {
      this.setOptions();
      this.options.api = {
        optionsChanged: this.optionsChanged.bind(this),
        resize: this.onResize.bind(this),
        getNextPossiblePosition: this.getNextPossiblePosition.bind(this),
        getFirstPossiblePosition: this.getFirstPossiblePosition.bind(this),
        getLastPossiblePosition: this.getLastPossiblePosition.bind(this),
      };
      this.columns = this.$options.minCols;
      this.rows = this.$options.minRows;
      this.setGridSize();
      this.calculateLayout();
    }
  }
```

The question is why do you need the piece above inside update, and not to move inside corresponding `@Input()`?:
```
_options: GridsterConfig;
 @Input() set options(value: GridsterConfig) {
    this._options = value;
    if (value) {
      this.setOptions();
      this.options.api = {
        optionsChanged: this.optionsChanged.bind(this),
        resize: this.onResize.bind(this),
        getNextPossiblePosition: this.getNextPossiblePosition.bind(this),
        getFirstPossiblePosition: this.getFirstPossiblePosition.bind(this),
        getLastPossiblePosition: this.getLastPossiblePosition.bind(this),
      };
      this.columns = this.$options.minCols;
      this.rows = this.$options.minRows;
      this.setGridSize();
      this.calculateLayout();
    }
}
```

**Comment by laserus** [comment]
Ok, I have found why demo is working blazing fast (although it has same problem hidden). It uses:
```
	changeDetection : ChangeDetectionStrategy.OnPush,
```

To avoid updates too often. 
What I see here as conceptual problem is that you want to update options each update, even when options reference did not change (probably you looking for changes in nested properties???). But it makes the whole thing very slow (as there many heavy operations on options update and they run each angular update iteration. To order to avoid that you make components that use this library with strategy `OnPush`, thus trying to avoid `ngOnChanges` to run too often (and now it reacts only to internal events-- which are unnecessary and to `options` variable reference change (which can be done with simple `@Input()`). 

Things to think about: what part of `ngOnChanges` we should move to `@Input() set options`.

Meanwhile, a hack for everyone who has performance problem, use `OnPush`.

**Comment by tiberiuzuld** [comment]
Hi @laserus ,
Yes for the grid to have performance when there is a lot of content the changeDetection needs to be OnPush, is the only way because of how angular works.

**Comment by laserus** [comment]
@tiberiuzuld but the whole point of this issue that gridster could benefit from removing heavy computation and update unnecessary of all observables from ngOnChanges. This is simple move of all code related to that to corresponding Input. This is way how to make Angular work much better. =)

**Comment by tiberiuzuld** [comment]
As per angular documentation https://angular.io/api/core/OnChanges
On changes is called when the input has been changed, not on every run.
There is no performance improvement here.

**Comment by laserus** [comment]
@tiberiuzuld no, that is not correct. 
It says:
> A lifecycle hook that is called when any data-bound property of a directive changes

Each time `ngOnChanges` run it changes a lot of parameters (unnecessary). Part of which are data-bound properties and directive becomes re-rendered and a new `ngOnChanges`. You can check it easily: add `console.log('ngOnChanges');` and remove OnPush from any component that uses gridster. It will spam console continuously.

**Comment by tiberiuzuld** [comment]
It referees only to the inputs of the component not all components in the application that will not make sense at all.

> A callback method that is invoked immediately after the default change detector has checked data-bound properties if at least one has changed, and before the view and content children are checked.

You can also read:
https://angular.io/guide/lifecycle-hooks#onchanges

Probably your are confusing onChanges with doCheck https://angular.io/api/core/DoCheck

And just spend 10 min and tested how you said on home section of the demo, and onChanges is called only once event if I press buttons, change inputs, drag/resize widgets etc.
