### ISSUE TITLE
Gridster Options: dragAndDrop is breaking the app

### ISSUE THREAD

**Issue by GabrielGamy** [tiberiuzuld/angular-gridster2#44]
I set the dragAndDrop option to false, and when I navigate to a new page my app breaks.

gridsterOptions:IGridsterOptions = { 
  lanes: 5,  
  direction: "vertical", 
  dragAndDrop: false 
}

I found this into the gridster-item.component.ts class:

this.dragSubscription is undefined but into the ngOnDestroy(), you try to unsubscribe on it

    ngOnInit() {
        this.gridster.registerItem(this);

        if(this.gridster.options.dragAndDrop) {
            this.createMouseDrag(this.$element);
            this.createTouchDrag(this.$element);

            // Update position
            this.dragSubscription = this.dragging.subscribe((pos) => {
                if(!this.pin){
                    this.$element.style.top = (pos.top - this.gridster.$element.offsetTop) + 'px';
                    this.$element.style.left = (pos.left - this.gridster.$element.offsetLeft) + 'px';
                }           
            });
        }
    }
    ngOnDestroy() {
        let index = this.gridster.items.findIndex((z) => z == this);
        if(index){
            this.gridster.items.splice(index,1);
        }
        this.dragSubscription.unsubscribe();
    }

**Comment by tiberiuzuld** [comment]
Hi @GabrielGamy ,
I think you mistaken the library this is not the library with those options.

**Comment by GabrielGamy** [comment]
Oh yeah :) I'm sorry.
Thank you
