### ISSUE TITLE
Dragged GridsterItem should stay in grid bounds

### ISSUE THREAD

**Issue by fjauer** [tiberiuzuld/angular-gridster2#448]
Hi!
I'm searching for an option that all dragged GridsterItem can't be moved over the green borders visible in the screenshot.
thx!

![widget](https://user-images.githubusercontent.com/19175201/49944478-c83c5680-feea-11e8-8a93-b33e10ba0af0.png)

**Comment by fjauer** [comment]
Hi that is excatly what it want. Below you could see my original dashboard with max 4 cols and max 2 rows. The user should only be able to drag in the green arrow directions. 
![bildschirmfoto 2018-12-19 um 09 58 09](https://user-images.githubusercontent.com/19175201/50210669-0d430b80-0377-11e9-95fe-982101f2528a.png)

**Comment by wiltzius** [comment]
I'm attempting to do something similar. The idea is to just allow placement within a grid of a fixed width (always 3 columns, in my case), not allow the user to grow the grid arbitrarily sideways.

By setting both minCols and maxCols to 4 and both minRows and maxRows to 2 in the example @fjauer gave you can _effectively_ prevent the grid from resizing, but the UI effect is a little janky. It allows you to drag as far as you want to the bottom and to the right, but then everything "snaps back" to the closest allowed position.

Here are some screenshots of the example UI with settings that illustrate what I'm trying to get at:

Setting min/max rows/cols to the same values and remove all items:

<img width="1680" alt="screen shot 2018-12-26 at 4 02 09 pm" src="https://user-images.githubusercontent.com/245229/50460148-02b0e500-0928-11e9-88c6-bf46993b76a1.png">

Then add an item:

<img width="1680" alt="screen shot 2018-12-26 at 4 02 35 pm" src="https://user-images.githubusercontent.com/245229/50460156-11979780-0928-11e9-9c33-151e0b411e35.png">

All good, except you can drag very far away:

<img width="1680" alt="screen shot 2018-12-26 at 4 02 57 pm" src="https://user-images.githubusercontent.com/245229/50460163-2e33cf80-0928-11e9-81e6-35cc4329a48d.png">


For my use case I never want the user to be able to change the dimensions of the grid horizontally, it's always 3 columns, so it's strange UX when they can drag/scroll off the screen like this.

Any ideas on how we might accomplish something like this? Gridstack, the gridster successor, can operate in a similar mode (see their first example here: http://gridstackjs.com/ ), but I like the great Angular integration that angular-gridster2 provides -- thank you for all the work on it, it's very easy to use.

**Comment by METACEO** [comment]
Is there anything new to this request?.. as I'm working within a fixed height / width, this is the only feature I'd like to configure off or disable. This does feel like a bug as it's quite counter-intuitive when I have my "grid type" to "fixed" but items still seem to disregard the rule.

**Comment by METACEO** [comment]
> disableScrollHorizontal?
> https://tiberiuzuld.github.io/angular-gridster2/drag

Disabling vertical and horizontal scrolling gets me close but (using the link you provided) I can still take a larger element and drag and drop it into the bottom right-hand corner and it creates a new column/row.

**Comment by nickbullock** [comment]
@METACEO 
I created https://stackblitz.com/edit/angular-gridster-static, please check gridster configuration and behavior. Is it what you want to achieve?
Width and height are fixed, both axis scrolling disabled, no way to add new items, swap is working, but you can disable if you want

**Comment by METACEO** [comment]
@nickbullock this is certainly almost there for me, this configuration looks a lot better. I do however see the below, still. Could this be a simple `overflow: hidden;` around the container - mainly for the user's sake, because it does not look to actually affect anything (it transitions back into place when you let it go.)

Thanks for the new demo!

![image](https://user-images.githubusercontent.com/13586713/65377287-c5d40d80-dc6f-11e9-8f1a-3618f1c75a60.png)

**Comment by polhek** [comment]
Hey all. Is there something new with this implementation? The old Gridster for angularJS had this implemented, so by default, you couldn't drag out of gridster. I want to limit the movement, so that widget is always visible and you cannot move it out. 

![image](https://user-images.githubusercontent.com/32010556/148534529-0f78739e-6c07-415a-a313-84f19a44937c.png)

**Comment by tiberiuzuld** [comment]
Hello,
New option `enableBoundaryControl` that will solve this issue released in [v13.3.0](https://github.com/tiberiuzuld/angular-gridster2/releases/tag/v13.3.0) 
Can be tested here: https://tiberiuzuld.github.io/angular-gridster2/drag
Thank you for the work @dogukan10
