### ISSUE TITLE
Unrestricted/Unlimited "maxRows"

### ISSUE THREAD

**Issue by alexcoroza** [tiberiuzuld/angular-gridster2#455]
Question. Is it possible to set "maxRows" into unlimited? I have a widget and it is impossible to drag a widget "far down" as it is stucked at 100th row(since maxRows default value is 100).  Well I can a high value for maxRows but Im wondering if theres another option for this.

**Comment by petarGitNik** [comment]
Have you tried using [`Infinity`][1] for max rows?

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity

**Comment by alexcoroza** [comment]
@petarGitNik Ive been doing web development for some years but this is the first time I heard about that **Infinity** haha. I tried it just now and its working exactly what I wanted. Thanks.
