### ISSUE TITLE
keepFixedHeightInMobile smaller by margin (V7.1.0)

### ISSUE THREAD

**Issue by tmtron** [tiberiuzuld/angular-gridster2#456]
it is related to #162, but happens for items that span more than one row

e.g. in the [GridTypes demo](https://tiberiuzuld.github.io/angular-gridster2/gridTypes)

- set  `GridType=Vertical Fixed`  and `FixedRowHeight=200`
- check `Keep Fixed Height In Mobile`
- resize the first tile to span 2 rows: now the tile is 410px high: 2x200 + 10px (margin)
- now resize the browser to activate the mobile layout: the tile is now only 400 high, because the margin is not taken into account

**Comment by HCenggel** [comment]
Is this problem okay?

**Comment by tiberiuzuld** [comment]
fix released in v12.1.1
