### ISSUE TITLE
How can i initialize an empty dashboard? 

### ISSUE THREAD

**Issue by parijatsharma93** [tiberiuzuld/angular-gridster2#459]

**Comment by petarGitNik** [comment]
@parijatsharma93 What do you mean by empty? I've tried `this.dashboard = []` and it works fine. Do you get any warning or error? As a disclaimer, I'm not associated in any way with this project, I'm just a user of this library.

**Comment by parijatsharma93** [comment]
@petarGitNik Yes i was getting an error and it there was some problem which i have managed to resolve.As you are a user of gridster2 i would again ask you some questions.
1.Can we have a gridster inside a gridster?As in one of my widgets will also be another gridster.
2.Is it possible to create an item and then display it on a position which is already occupied?(Something like we push the present item somewhere else when a new item with the same position is pushed.
3.I am unable to achieve view-port breakdown at 640 as mentioned in the options object.

Can you please help me in this?

**Comment by parijatsharma93** [comment]
@petarGitNik Thanks for your response,i have been able to solve all the problems except the 2 point.When i try to push an item into a position already occupied it gives a warning and auto-positions it by itself.I want to be able to place an item to an already filled space.Can you please share some demo how the push api can be used in this case
