### ISSUE TITLE
Textbox is not editable inside gridster item

### ISSUE THREAD

**Issue by prateikjaiswal** [tiberiuzuld/angular-gridster2#46]
` <gridster-item [item]="item" *ngFor="let item of dashboard">
      <input type="text" value="Cannot Edit"/>
  </gridster-item>`

The textbox is not editable in the above code.

**Comment by tiberiuzuld** [comment]
Hi @prateikjaiswal ,
You need to look here https://github.com/tiberiuzuld/angular-gridster2#interact-with-content-without-dragging

**Comment by prateikjaiswal** [comment]
@tiberiuzuld  Thanks!!
