### ISSUE TITLE
gridType: "fixed" dragging widget to edge of screen hides gridsterGrid

### ISSUE THREAD

**Issue by Kzamikaze** [tiberiuzuld/angular-gridster2#47]
I believe the issue comes from `GridsterComponent.prototype.calculateLayout()` where `this.gridLines.updateGrid();`is called without the `true` argument, causing the gridsterGrid component to hide itself.

You can reproduce this bug using the demo, set the grid type to fixed and drag any widget to the edge of the screen.

**Comment by tiberiuzuld** [comment]
Hi @Kzamikaze .
Thank you for reporting this issue.
You where right the `updateGrid()` from `calculateLayout()` was the issue.
Fixed in v2.10.1

Cheers,
