### ISSUE TITLE
[BUG] Unable to resize in some cases

### ISSUE THREAD

**Issue by felipeinfantino** [tiberiuzuld/angular-gridster2#475]
Hi, in some situations I am not able to resize the grid items. 

Please see the gif. 

I thought it was because of the configurations of the options but I change a lot of things and it didnt work.

    this.options = {
      gridType: GridType.Fixed,
      compactType: CompactType.None,
      margin: 10,
      outerMargin: true,
      outerMarginTop: null,
      outerMarginRight: null,
      outerMarginBottom: null,
      outerMarginLeft: null,
      useTransformPositioning: false,
      mobileBreakpoint: 0,
      minCols: 1,
      maxCols: 6,
      minRows: 1,
      maxRows: 14,
      maxItemCols: 6,
      minItemCols: 1,
      maxItemRows: 6,
      minItemRows: 1,
      maxItemArea: 2500,
      minItemArea: 1,
      defaultItemCols: 6,
      defaultItemRows: 1,
      fixedColWidth: 60,
      fixedRowHeight: 60,
      keepFixedHeightInMobile: false,
      keepFixedWidthInMobile: false,
      scrollSensitivity: 0,
      scrollSpeed: 0,
      enableEmptyCellClick: false,
      enableEmptyCellContextMenu: false,
      enableEmptyCellDrop: false,
      enableEmptyCellDrag: false,
      emptyCellDragMaxCols: 50,
      emptyCellDragMaxRows: 50,
      ignoreMarginInRow: false,
      draggable: {
        enabled: true
      },
      resizable: {
        enabled: true
      },
      swap: true,
      pushItems: true,
      disablePushOnDrag: false,
      disablePushOnResize: false,
      pushDirections: { north: true, east: true, south: true, west: true },
      pushResizeItems: true,
      displayGrid: DisplayGrid.Always,
      disableWindowResize: true,
      disableWarnings: false,
      scrollToNewItems: false
    };
![bugangulargridster](https://user-images.githubusercontent.com/34038087/53034689-05d1d880-3474-11e9-8c54-974adcf59565.gif)

**Comment by nghiado** [comment]
I have the same issue. Is there anyway to workaround that?
Maybe on resize, just push everything below it down one row to create more space?

**Comment by felipeinfantino** [comment]
@nghiado Did you find a workaround ? I would like to fix that or at least understand what is happening to make a pull request and try to fix it ? @tiberiuzuld maybe you know what it could be ?

**Comment by felipeinfantino** [comment]
Should be fixed with this pr #538 @nghiado @tiberiuzuld

**Comment by tiberiuzuld** [comment]
Deployed in v8.1.0
