### ISSUE TITLE
dynamic grid with different rows & cols

### ISSUE THREAD

**Issue by kirtiesl** [tiberiuzuld/angular-gridster2#48]
Hello, 
I am having dynamically generated grid-items. each grid-item has different charts like bar-chart, gauge etc.
I want to set different rows and cols for bar-chart  and different for gauge dynamically.

**Comment by kirtiesl** [comment]
any update??

**Comment by tiberiuzuld** [comment]
Hi @kirtiesl ,
Well when you create the widget depending on type you can put different cols and rows on the grid item.
So you can have dynamic width and height.
Have a look at the gridster item options [here](https://github.com/tiberiuzuld/angular-gridster2#gridster-item-options)

**Comment by kirtiesl** [comment]
Thanks.
But i am generating grid item on page load of size cols-1 and rows-1 and after that binding charts to grid-item. so depending on chart i am want resizise the grid-item. is there any grid-item.refresh function??

**Comment by tiberiuzuld** [comment]
After you change the `gridster-item` options you need to call ` this.options.optionsChanged();`
`this.options` being the options object you gave to the grid.

Be careful that like this your items may overlap or not be display anymore.

I suggest inserting the `items` when you know what type of chart you have and you set the dimensions.

**Comment by kirtiesl** [comment]
exactly after calling this.options.optionsChanged(); my gridster-item are overlaping. is there any solution to rearrange?? and actually setting dimensions previously wont be possible as chart sequence is not fix it has random order.

**Comment by tiberiuzuld** [comment]
When you set dimensions also set `x` and `y` to `undefined`. 
Not sure if it will work. 
If this doesn't work the only solution is to populate the grid after you know the dimensions.

**Comment by kirtiesl** [comment]
populating grid after setting dimensions worked for me.
thanks a lot.

**Comment by tiberiuzuld** [comment]
Great :)
