### ISSUE TITLE
Does not work when used in components other than app.component

### ISSUE THREAD

**Issue by tauseef-kazi** [tiberiuzuld/angular-gridster2#49]
Hi,

I tried this awesome module. I have used this under app.component and it works as expect. However when I use it under sub components it does not work.

**Comment by tiberiuzuld** [comment]
Hi @tauseef-kazi,
Strange, true never tested like this but it should work.
Can you provide a code sample please ?

**Comment by tiberiuzuld** [comment]
Hi @tauseef-kazi,
Just tested and form me it worked. 
You only need to make sure that your components have height and width, 
since the gridster has width and height: 100%

**Comment by tauseef-kazi** [comment]
Thanks @tiberiuzuld,

Your recommendation worked !
