### ISSUE TITLE
itemResizeCallback, itemChangeCallback, new itemMoveCallback

### ISSUE THREAD

**Issue by benneq** [tiberiuzuld/angular-gridster2#494]
I have an issue with monitoring gridster item changes. 

What I'm trying to achieve:
The user should be able to rearrange and resize the grid items. And when he's done, he clicks "save". And at this point I need the current grid layout data.
Though I tried to simply keep track of all changes, but that's not as easy as I thought...

Here are my findings:
1. `itemResizeCallback` get's called on init. That's **no** issue.
2. `itemChangeCallback` does not get called when moving / resizing an item to its initial position.
3. There's no `itemMoveCallback` or `itemDropCallback`.

To keep track of everything I have to use `itemChangeCallback`. But if the user moves an item from `x: 1` to `x: 2` and then decides to move it back to `x: 1` I can't update my grid layout state, because `itemChangeCallback` doesn't get called.

And in order to not change the existing behavior of `itemChangeCallback`, I came up with the idea to introduce a new method: Some kind of `itemMoveCallback` or `itemDropCallback`, which behaves the same as `itemResizeCallback`, but gets called when moving items instead of resizing.

Or is there an easier way to get the current grid layout state on demand?

**Comment by tiberiuzuld** [comment]
Hi @benneq ,
That's strange since item change should be called each time the widget position is changed.
https://github.com/tiberiuzuld/angular-gridster2/blob/master/projects/angular-gridster2/src/lib/gridsterItem.component.ts#L116

Just tried it on the demo page and is executing each time.
https://tiberiuzuld.github.io/angular-gridster2/gridEvents

**Comment by benneq** [comment]
That's really strange. Indeed it works on the demo page.

I've modified some angular-gridster2 example on StackBlitz. And there my problem appears again.

Here's the App: https://my-angular-gridster2-uwekdi.stackblitz.io
And here's the editor: https://stackblitz.com/edit/my-angular-gridster2-uwekdi

I found the code causing the issue: It's the `getGridsterItem` method within the `DashboardComponent`. It does a mapping from my application widget representation to gridster item.
When you replace it with a simple `return widget.layout` then it works as expected.

But I'm still not sure why this happens. Maybe you have an answer.

**Comment by tiberiuzuld** [comment]
Well is because of JS references how it works https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference
If you map something it loses the reference.

**Comment by benneq** [comment]
That doesn't explain why it only fails when moving the item back to its original place.

**Comment by tiberiuzuld** [comment]
Yes indeed, what can I say is that is not from the library :D

The library updates the config given when drag/resize happens and calls the callbacks.
It's up to the user what to do with it.

Maybe your mapping function is called multiple times and changes the config given to the grid.

**Comment by benneq** [comment]
I just checked it. The mapping functions is getting called for **every** pixel i move the gridster item. (about 1000 times a second)

I thought that maybe this is the problem: https://github.com/tiberiuzuld/angular-gridster2/blob/master/projects/angular-gridster2/src/lib/gridsterItem.component.ts#L116
the first if-statement in this method. Because old and new item have the same data when you move it back to its original position.

**Comment by tiberiuzuld** [comment]
Well the mapping function should be called only once per widget initially.

**Comment by benneq** [comment]
Okay, now I know where to look for changes.
Thank you 👍
