### ISSUE TITLE
Moving between GridTypes while approximately maintaining tile proportions

### ISSUE THREAD

**Issue by iturn** [tiberiuzuld/angular-gridster2#499]
Is there a way to change the gridtype without manually resizing all tiles? 

I would like to move from GridType.Fit to GridType.VerticalFixed. But when i do this all tiles become severely disproportioned, which requires manual resizing of the tiles, and there are hundreds of grids made by users.

**Comment by tiberiuzuld** [comment]
Hi @iturn ,
`GridType.Fit` is made to scale to user resolution or the given container of the grid if the container has a fixed size. This makes it that the widgets will not be the same ratio for all users, with variable width/height.
`GridType.VerticalFixed` is made to have a variable width for each column and a fixed height of the rows.

Given this facts you seem to have to determine an appropriated value for `fixedRowHeight` or/and modify the number of rows each widget spans.

This will not be easy or possible if you don't have a fixed height for the container where you display the widgets if you want to keep exactly the same ratio for all users.

Most probably each user configured they're widgets to look ok for them.

**Comment by iturn** [comment]
Thanks for the reply,

Do i understand correctly then that `fixedRowHeight` would be applied in `GridType.VerticalFixed`? Thought that would only be in Fixed.

I would be able to filter out problematic grids based on row count, and fix other dashboard automatically with some math and going with a fullHD screenres as reference.

**Comment by tiberiuzuld** [comment]
Yes it is. Yes that will be your best option.

**Comment by iturn** [comment]
Great thanks for you reply and help
