### ISSUE TITLE
module.id is is null

### ISSUE THREAD

**Issue by roeeovadia** [tiberiuzuld/angular-gridster2#5]

**Comment by tiberiuzuld** [comment]
Hi @roeeovadia 
Made a new release with a try to fix the issue you experience.
From what I read
[Here](https://blog.thoughtram.io/angular/2016/06/08/component-relative-paths-in-angular-2.html)
and
[Here](http://stackoverflow.com/questions/37178192/angular2-what-is-the-meanings-of-module-id-in-component)
The library should already work.
Let me know if you still have issues.

**Comment by tiberiuzuld** [comment]
Removed the moduleId should not cause any more problems from now on.

**Comment by roeeovadia** [comment]
@tiberiuzuld cool!
I make some updates for you code. i will create a merge request later on this week

**Comment by tiberiuzuld** [comment]
@roeeovadia ok, thank you!
