### ISSUE TITLE
Does this work for Angular 4?

### ISSUE THREAD

**Issue by broodjetom** [tiberiuzuld/angular-gridster2#50]
I was wondering if this completely works and if it doesn't give any break. I have put this module into my project that was initialized with Angular-CLI, and thus Angular 4.1.3. This works, but I don't know if it could give any breaks afterwards when I start developing.

**Comment by tiberiuzuld** [comment]
Hi @broodjetom ,
Yes this works with angular4.

**Comment by tiberiuzuld** [comment]
Hi @broodjetom ,
Updated info on [Readme.md](https://github.com/tiberiuzuld/angular-gridster2/blob/master/README.md)
Hoping now is more clear.
