### ISSUE TITLE
i am trying to open a customized contextmenu on a datagrid it is not aligning properly

### ISSUE THREAD

**Issue by niranjansooda** [tiberiuzuld/angular-gridster2#502]
I am trying to create a context menu.I have a datagrid when user right clicks on a row in a datagrid i take the co-ordinates of that point and position the context-menu exactly at that point. when i used gridster it is not aligning properly at that clicked point.

steps to reproduce:
click on any row of the datagrid.you can see customized context-menu aligning away from the clicked point if i use gridster.

click the "open in new tab" in top right corner of stackblitz to see more clearly.

with gridster it is not aligning properly:
https://stackblitz.com/edit/with-gridster?file=src/app/app.component.ts

without using gridster it is aligning properly:
https://stackblitz.com/edit/without-gridster?file=src/app/app.component.ts

please suggest any workarounds if this is related to gridster.

**Comment by CollinGraf314** [comment]
This not directly related to gridster2. So what is happening is that you are getting the x and y coordinates of the click on your screen, then using that to set the `top` and `left` css attributes on the menu, which has position set to `absolute`. If you look up `position: absolute` you will find that it sets the position relative to the closest positioned parent element (by positioned I mean any element with `position` set to something other than `static` which is the default). The gridster element has a position set on it, so your menu goes from being set relative to your screen to being set relative to the grid. 

I know this answer is a bit late, but I hope it helps.

**Comment by niranjansooda** [comment]
hi @CollinGraf314 

i tried with position :fixed but not able to fix it. can you please try with the above stackblitz code i gave? 
 and give the work around in stackblitz.Thanks.

**Comment by CollinGraf314** [comment]
Currently your stackblitz is broken (throwing an error on load). If you could revert it back to how it was I could be of more use. 

I think the easiest way to do this (though its not entirely dynamic) would be to keep the `.contextMenuState{ position: absolute; }` then set the contextMenuState's `left` value to be `calc(contextMenuPositionX- 10rem)` and its `top` value to be `calc(contextMenuPositionY- 2.5rem)` as `10rem` is the width of your sidebar and `2.5rem` is the height of your topbar, thus accounting for the offset of your gridster's position.
