### ISSUE TITLE
How to dynamically add a component to this gridster?

### ISSUE THREAD

**Issue by broodjetom** [tiberiuzuld/angular-gridster2#51]
I am making a extensible dashboard. Depending on the data that I receive from the server, there need to be tiles created with different components in it. Because it is extensible, we cannot make a simple factory for this. An independent person needs to be able to make its own tilewidget, and be able to render that tile in the gridster by sending the right data to it.

**Comment by tiberiuzuld** [comment]
Hi @broodjetom ,
You need to use something from angular4 to dynamic init a component
Try [this](https://angular.io/docs/ts/latest/api/common/index/NgComponentOutlet-directive.html)

**Comment by tiberiuzuld** [comment]
Hi @broodjetom ,
Did the info helped ? made it work ?

**Comment by broodjetom** [comment]
Hi,

I tried this, but this won't work since this will add another dependency to the dashboard, where people have to manually add the components that they make to the entryComponents of the main component. This probably won't work for my implementation. Also we are receiving JSON data as a string, so how would we be able to load a component to a string without using a factory?

But I am still interested in how this works. Do you know how to pass data to the component that you load in the ngComponentOutlet? I am using microservices so I only need to pass an URL.

**Comment by tiberiuzuld** [comment]
Hi @broodjetom ,

Try [this](https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html)
Should resolve your issue to load component based by a string saved in db.

**Comment by broodjetom** [comment]
Hi @tiberiuzuld 

`ComponentFactoryResolver` is deprecated. I have found a way to dynamically render components with the `ngComponentOutlet` as follows:

`<ng-container *ngComponentOutlet="getComponent(item.tag)"></ng-container>`

I only have one issue with this solution. I am unable to input data into the loaded component. I have looked on the documentation but there seems to be a mistake there ([#16373](https://github.com/angular/angular/issues/16373)). I have looked into the source code and they are right about there not being a property to input an object into the loaded component.

I think you have been working with this for a while now. Do you know a solution for this? I also read about someone that setup a `injector` with `providers` but in that case the loaded component doesn't know what its provider is

**Comment by tiberiuzuld** [comment]
Hi @broodjetom ,

I didn't tried to load dynamic components in angular2 or greater.
Found [this](https://www.npmjs.com/package/ng-dynamic-component) maybe it will help you.
From what I read seems to work with inputs.

**Comment by Onyphlax** [comment]
Hi @tiberiuzuld,
To answer you with my issue, it's working but not really dynamically. In fact i juste have a ngSwitch inside the `gridster-item` and check what string i have so i can call different components.
I'll try the `ng-dynamic-component` tomorrow and give you a feedback.

**Comment by Onyphlax** [comment]
Hi @tiberiuzuld,

I manage to make it work with `ng-dynamic-component`, thanks again for your help.

**Comment by tiberiuzuld** [comment]
Hi @Onyphlax ,
Good to know that is working will add in Readme.md the info

**Comment by tiberiuzuld** [comment]
Added [here](https://github.com/tiberiuzuld/angular-gridster2/blob/master/README.md#load-dynamic-components-inside-the-gridster-item).

**Comment by broodjetom** [comment]
I made a possible solution as well.
http://blog.tomscholten.nl/dynamically-load-components-with-data-in-angular/
Sorry for this late addition, you can close this issue now.
I hope this issue will help other people as well.

**Comment by adrianromanko** [comment]
Loading components dynamically is not an issue. Does anyone have a sample of dynamically creating a 'gridster-item' attaching it to 'gridster' programmatically?

The current design will not allow GridsterItems component selector 'gridster-item' to be held in a separate template without 'gridster' GridsterComponent being its parent. The angular template parser will throw an error.

I would get rid of @Host and refactor it a bit to decouple Grid from GridItem and turn GridsterItemComponent to be a Directive allowing you to attach behavior anywhere. The GridsterItem directive constructor should inject Gridster.

**Comment by tiberiuzuld** [comment]
Hi @adrianromanko ,
Why would you need that ?

Thanks

**Comment by adrianromanko** [comment]
I have a dashboard use case where I need to split up the gridster and grid-item into separate components. grid-item will be dynamically added using resolveComponentFactory().

dashboard.ts
```
<dashboard>
<gridster [options]="options">
   <ng-template dashboard-host></ng-template>
</gridster>
</dashboard>
```
dynamicWidget.ts
```
<widget>
<gridster-item [item]="item">
  </gridster-item>
</widget>
```

**Comment by pbackx** [comment]
@adrianromanko I made that work using the [ng-dynamic-component](https://www.npmjs.com/package/ng-dynamic-component )mentioned above.

It's messy, but it works. The template of your dynamicWidget.ts should look something like this:
```
    <ndc-dynamic [ndcDynamicComponent]="gridsterItem" [ndcDynamicInputs]="gridsterItemConfig">
      <your content
    </ndc-dynamic>
```

And the variables:
```
  gridsterItem = GridsterItemComponent;
  gridsterItemConfig = {item: {x: 2, y: 0, cols: 2, rows: 1}};
```

**Comment by ndce06** [comment]
@pbackx - can u please share working code. I tried the same way but it's throwing error - No provider for GridsterComponent....

**Comment by pbackx** [comment]
@ndce06 you still need a GridsterComponent somewhere in the hierarchy. In my case, this was split over two nested templates. Lets call them parent and child. The parent had the GridsterComponent defined the regular way. The child has the dynamic code I show in my example.

**Comment by mkgn** [comment]
I managed to get the basics of the gridster. I can add dummy widgets and play around with them. However I am stuck when trying to load different components as widgets dynamically.

What I have done up-to now is

1) I have a WidgetModule that imports all WidgetComponents such as;

```
    @NgModule({
    declarations: [],
    imports: [
        DynamicModule.withComponents([TicketWidgetComponent, UsageWidgetComponent])
    ],
    providers: []
    })
    export class WidgetsModule { }
```

2) The component that should return widgets dynamically are defined as;
```
@Component({
    selector: 'my-component',
    template: `<ndc-dynamic [ndcDynamicComponent]="component" [ndcDynamicInputs]="gridsterItemConfig"></ndc-dynamic>`
})
class DynamicLoaderComponent {
    gridsterItemConfig = { item: { x: 0, y: 0, cols: 1, rows: 1 } };

    //i need a click event or something that checks some input and return widgets
    component = Math.random() > 0.5 ? TicketWidgetComponent : UsageWidgetComponent;
}
```

3) Each widget component is defined as(these will in turn register with the above module. so all widgets are controlled by the widget Module);
```
    @Component({
        templateUrl: './tickets.widget.component.html'
    })

    export class TicketWidgetComponent extends AppComponentBase {}
```

4) The template file for above component 
```
<gridster-item [item]="item">
content here
</gridster-item>
```

5) My dashboard is like;
```
<div> 
other stuff
<gridster class="gridster" [options]="options">
<my-component></my-component>
</gridster>
</div>
```

From here i am stuck Because;

1) I only need to add the widget selected by the user (Example, user want to show the [ticket count] widget). I am not sure how I should wire that up with what i have done. Ultimately we should add something to the dashboard array.

2) in the widget host <gridster/> each <gridster-item/> is taken from the dashboard array. So with dynamic loading of other components how this will work?

I would like to see a working dynamic grid. The code at #250 doesn't use [ng-dyamic-component](https://github.com/gund/ng-dynamic-component). A sample simulating how different widgets can be added dynamically would be great since it'll be very useful for those who are building dashboards

**Comment by NastyZ98** [comment]
@mkgn Hi, have you solved your problem ? I'm facing the same issue. 

Thank you

**Comment by hariharan618** [comment]
> @adrianromanko I made that work using the [ng-dynamic-component](https://www.npmjs.com/package/ng-dynamic-component)mentioned above.
> 
> It's messy, but it works. The template of your dynamicWidget.ts should look something like this:
> 
> ```
>     <div style="display:none"><span #myContent><your content here></span></div>
>     <ndc-dynamic [ndcDynamicComponent]="gridsterItem" [ndcDynamicInputs]="gridsterItemConfig" [ndcDynamicContent]="[[myContent]]">
>     </ndc-dynamic>
> ```
> And the variables:
> 
> ```
>   gridsterItem = GridsterItemComponent;
>   gridsterItemConfig = {item: {x: 2, y: 0, cols: 2, rows: 1}};
> ```

Hi is it possible to share your code in stackblitz or JSFiddle ? Thanks

**Comment by n8patty** [comment]
@mkgn @NastyZ98 Hi, have you been able to find the solution to your problem? I'm having the same issues.

**Comment by NastyZ98** [comment]
Hello @n8patty it has been a long while I didn't worked with Gridster but I succeed to did what I wanted.

Can you describe your problem ? 

What I can do is to dynamically generate components from an API using a component library (components are generated as a JS Bundle and I simply interpreting the JS file in Angular).
I can also contextualize components services and behaviours using providers if I have multiple instances of Gridster.

If your problem is related to one of the topics I listed above I may can help you!

Cordially.
Nathan.

**Comment by eapatel** [comment]
Hi @n8patty , I'm also facing the same issue. Have you found any solution?
