### ISSUE TITLE
Implementing Angular-Gridster2 Drag feature : not able to see complete grid

### ISSUE THREAD

**Issue by NidhiBisaria** [tiberiuzuld/angular-gridster2#519]
Reproduction
Steps to reproduce:
Used StackBlitz to reproduce my issue: https://stackblitz.com/edit/angular-it2vl4

Expected Behavior
What behavior were you expecting to see?
Want to see complete grid.

Actual Behavior
What behavior did you actually see?
Complete Grid is not showing

Environment
Angular: angular 8
CDK/Material: Material
Browser(s): Chrome
Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by CollinGraf314** [comment]
This works as expected.

By default, the grid adds rows/columns to itself based on its height/width, so it would cause a circular dependency if it tried to set it's height/width based on content size. In order to change this behavior take a look at the `setGridSize` property.
