### ISSUE TITLE
Gridster resizable limit

### ISSUE THREAD

**Issue by karanaditya993** [tiberiuzuld/angular-gridster2#52]
Hi @tiberiuzuld ... I know that i've asked for backporting to 1.x version which i truly appreciate. I'm wondering whether or not as part of that feature, you plan on implementing a limit on the amount a tile can be resized. This use case is because i don't want someone using the dashboard to be able to resize the tile to an enormous size. Is there a feature like this in the 2.x version? Thanks so much

**Comment by tiberiuzuld** [comment]
Hi @karanaditya993 ,
Yes there is look [here](https://github.com/tiberiuzuld/angular-gridster2#gridster-item-options)
