### ISSUE TITLE
Grid re-sizing after drag, not initialize.

### ISSUE THREAD

**Issue by Estevete** [tiberiuzuld/angular-gridster2#523]
I have 6 col grid and X rows , But, when I refresh the browser, it does not resize correctly. After I drag an item, it resizes correctly. I add two pictures so you can see the difference.

![image](https://user-images.githubusercontent.com/19273351/60661827-1a2ed480-9e5b-11e9-858c-8d7a42af834c.png)

This is when I first get into the grid view

![image](https://user-images.githubusercontent.com/19273351/60661864-3468b280-9e5b-11e9-906d-e54d1827f720.png)

This is how it looks like after dragging an item. You can see the first image the last item gets 'cut'. Can u help me?

_Originally posted by @Estevete in https://github.com/tiberiuzuld/angular-gridster2/issues/493#issuecomment-508440288_

**Comment by CollinGraf314** [comment]
I kind of doubt this is an issue with this library, and sadly there is no way to really figure it out unless you are able to provide us with a minimum reproduction. If you can find the time to duplicate this behavior in a smaller https://stackblitz.com/ application and post the link I can certainly help you debug the issue.

**Comment by Estevete** [comment]
You were right. I've fixed it already.
