### ISSUE TITLE
While resizing the gridster item some gray color portion is visible in background

### ISSUE THREAD

**Issue by anushamramyam** [tiberiuzuld/angular-gridster2#526]
Hi,

 While resizing the gridster item some gray color portion is visible in background and it is availing some height, remaining gridster item will align after this. 

My gridster options: 
 GridsterConfig = {
	gridType: GridType.ScrollVertical,
	compactType: 'compactUp&Left',
	displayGrid: 'onDrag&Resize',
	margin: 5,
	pushItems: true,
	draggable: {
		enabled: true
	},
	resizable: {
		enabled: true
	},
	minCols: 30,
	minRows: 40,
	maxCols: 30,
	maxRows: 5000,
	mobileBreakpoint: 640,
	swap: false,
	outerMargin: true
};
I have attached the screen shot. PFA.

![image](https://user-images.githubusercontent.com/31650367/60894543-8c028600-a280-11e9-8b76-2a68f1aee93a.png)

**Comment by anushamramyam** [comment]
I resolved myself. It was css issue.

**Comment by saidAdservio** [comment]
hi, how did u resolve this issue exaclty?

**Comment by Kendsar** [comment]
> hi, how did u resolve this issue exaclty?

gridster {
background: transparent;
}
