### ISSUE TITLE
Input textbox not working !

### ISSUE THREAD

**Issue by zinkalthakker** [tiberiuzuld/angular-gridster2#527]
I am trying input text box inside the gridster. It is working when first clicked by right click of mouse but not working when clicked by left click of the mouse. Focus is not set.and it is highlighting the grid until it is clicked by right click of mouse.Same issue with kendo-numerictextbox. I am attaching stackblitz url with the issue. Please revert asap.

Stackblitz demo :
https://stackblitz.com/edit/angular-nkgvdk

**Comment by alexjmason** [comment]
@zinkalthakker Place the input into a "gridster-item-content" class div like so:

`        <div class="gridster-item-content">
            <input type="text">
        </div>`

**Comment by zinkalthakker** [comment]
It's working !!! Thanks @alexjmason .
