### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by 4kochi** [tiberiuzuld/angular-gridster2#529]
Hello,

we sometimes get the Error `ERROR RangeError: Invalid array length` in our prod system. Sadly we could not reproduce it locally on our dev machine. 

The code the produces the error is this line:

`gridster.component.ts`

```ts
updateGrid(): void {
    if (this.$options.displayGrid === 'always' && !this.mobile) {
      this.renderer.addClass(this.el, 'display-grid');
    } else if (this.$options.displayGrid === 'onDrag&Resize' && this.dragInProgress) {
      this.renderer.addClass(this.el, 'display-grid');
    } else if (this.$options.displayGrid === 'none' || !this.dragInProgress || this.mobile) {
      this.renderer.removeClass(this.el, 'display-grid');
    }
    this.setGridDimensions();
    // error comes from next line
    this.gridColumns.length = Math.max(this.columns, Math.floor(this.curWidth / this.curColWidth)) || 0;
    this.gridRows.length = Math.max(this.rows, Math.floor(this.curHeight / this.curRowHeight)) || 0;
    this.cdRef.markForCheck();
  }
```

Maybe you can add some extra checks to prevent the array length to be invalid.

**Comment by tiberiuzuld** [comment]
Deployed in v8.1.0

**Comment by 4kochi** [comment]
Hi @tiberiuzuld ,

thanks for the fix, but we still get the error sometimes. 

According to the stack trace the problem is still this line:

```
 this.gridColumns.length = Math.max(this.columns, Math.floor(this.curWidth / this.curColWidth)) || 0;
```

Probably the next line too because it's kind of a similar logic.

So i tested a bit around and the only case where i can produce the error is when the `Math.max()` expression returns a negative number, since this is not allowed as a length of an array.

So i could imagine that maybe in some case `this.columns` and `this.curWidth` or ` this.curColWidth` are negative. Maybe you can add an additional check to make sure the result of the assignment is always >= 0
