### ISSUE TITLE
Not Working on safari

### ISSUE THREAD

**Issue by peio72** [tiberiuzuld/angular-gridster2#53]
The demo is broken in Safari Mac and iOS.

https://tiberiuzuld.github.io/angular-gridster2/angularjs/

**Comment by tiberiuzuld** [comment]
Hi @peio72 ,
Can you please provide a screenshot/log of what is broken ? 
Don't have Safari and all other major browsers(Chrome, Edge, Firefox) work

**Comment by peio72** [comment]
![safari](https://cloud.githubusercontent.com/assets/13556248/26558047/2f34339a-44a6-11e7-982c-4a5df203de3c.png)

**Comment by tiberiuzuld** [comment]
Hi @peio72 ,
So from the screenshot it can be 2 things : 
1. Some Javascript error , which seems less likely
2. Is a css `flex-box` problem. On `<div gridster="main.options" class="fit"></div>` check the height element and try to add `flex` class to it from the inspector. 

Let me know if this works.

**Comment by tiberiuzuld** [comment]
Fixed the demo now on Safari
