### ISSUE TITLE
Add event listeners conditionally on gridster item init.

### ISSUE THREAD

**Issue by artu-ole** [tiberiuzuld/angular-gridster2#537]
I'm using this amazing library for a hefty grid of >80 items which sadly results in poor init performance due to gridster adding event listeners for resize handles for each of the item even with restrictive options such as
```js
resizable:
    {
        enabled: false,
        handles: { s: false, e: false, n: false, w: false, se: false, ne: false, sw: false, nw: false }
    }
```
![image](https://user-images.githubusercontent.com/15938416/62547155-6c558200-b86d-11e9-8c24-e78212f67e43.png)

Am I missing an already existing configuration to skip resize event listeners (and add them on the fly when/if resizable becomes true) or could this be an enhancement worthy of looking into?

**Comment by tiberiuzuld** [comment]
Hi @artu-ole ,
There is no option currently to skip the event listeners at init.
You can have a look at https://github.com/tiberiuzuld/angular-gridster2/blob/master/projects/angular-gridster2/src/lib/gridsterItem.html
Currently they are added by angular. 
Maybe as a perf improvement they should be added by ts when resize is enabled.

**Comment by tiberiuzuld** [comment]
Changed the resize elements to be displayed with and `*ngIf` instead of `[hidden]` attribute.
Let me know if it is a improvement for you, or we need to change to dynamic in ts.

**Comment by tiberiuzuld** [comment]
Deployed in v8.1.0

**Comment by artu-ole** [comment]
Thank you!
It greatly improves time to first meaningful paint!
There's a trade off, however, that every time resizable option would be toggled - event listeners take time to attach, rather than once. It is not a huge deal for me, as such edit mode toggling is supposed to be rarely used just to set things up, but it could be considered regression by people who have a need for rapid resizable/non-resizable toggles. 

Keeping both hidden and ngIf attributes and bypassing ngIf with a flag variable(either per handle or for all at once) would fix this, though I will be first to admit that this is far from elegant solution and as mentioned - it is a non-issue for me.
```html
<div (mousedown)="resize.dragStartDelay($event)" (touchstart)="resize.dragStartDelay($event)"
     [hidden]="!gridster.$options.resizable.handles.w || !resize.resizeEnabled"
     *ngIf="gridster.$options.resizable.handles.w && resize.resizeEnabled || resize.initialized"
     class="gridster-item-resizable-handler handle-w"></div>
```

**Comment by artu-ole** [comment]
Oh, I've completely overlooked your comment about just adding them in the code, which would be better solution of course.

**Comment by tiberiuzuld** [comment]
Glad to hear it improved.
Will move them inside the code during the refactoring which I keep delaying ...
