### ISSUE TITLE
Element superposition when dragging outside grid

### ISSUE THREAD

**Issue by Onyphlax** [tiberiuzuld/angular-gridster2#54]
Hi @tiberiuzuld,

I found a little bug on the demo. When i've a fulfilled row and drag outside the grid on the same row with pushItems at false and swap at true, the element is overlapping  the last element on the row.
Here is an example :
![gridster](https://cloud.githubusercontent.com/assets/22189792/26622239/0719d6ea-45ea-11e7-9184-c5fa2bab37b4.gif)

Moreover i'd like to know if it is possible to disable the possibility to drag an element outside of the grid

**Comment by tiberiuzuld** [comment]
Hi @Onyphlax ,

Interesting bug you found, will try have it fixed today.

Currently there is no option to disabled the drag/resize outside the grid.
You can limit the number of maxCols & maxRows the grid can have. That will limit the drag I think. Not sure if it will work.

**Comment by Onyphlax** [comment]
Well in the example i send, maxCols was at 7 and the number of item cols in the grid was 7 too, so it doesn't seem to work.

**Comment by tiberiuzuld** [comment]
Hi @Onyphlax ,
Fixed in v2.10.2
Limited the drag to the max sizes of the grid.
Unfortunately the drag is limited when the item will change position, tried it with limiting it right when passes the limit but was blocking normal user drag near the edge.

**Comment by viethien** [comment]
I fixed this issue by this setting

this.options.maxCols = this.gridster.gridColumns.length;
this.options.maxRows = this.gridster.gridRows.length;
this.options.api.optionsChanged();
