### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by dzhavat** [tiberiuzuld/angular-gridster2#55]
When I try to load the demo in IE11, I get the following error: 

![capture](https://cloud.githubusercontent.com/assets/1096332/26684885/c7cd38ba-46e8-11e7-8bdb-83b81b2a2543.PNG)

Any suggestions on why that happens?

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,
Appears to be an issue from angular, will try to track down the issue.

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,
Polyfils from angular-cli were not enabled for IE versions.
Also fixed a small issue with grid columns in IE.
Fixed in v2.10.4.

Thank you

**Comment by dzhavat** [comment]
Works amazingly. Thank for the quick fix and response.
