### ISSUE TITLE
No provider for GridsterComponent

### ISSUE THREAD

**Issue by Onyphlax** [tiberiuzuld/angular-gridster2#56]
Hi @tiberiuzuld,

I'm trying to dynamically add a component to a gridster grid with a ComponentFactoryResolver. 
I can load perfectly components but i can't add grister-item.
Everytime i add grister-item to the template i have an error:
Unhandled Promise rejection: Template parse errors:
```
No provider for GridsterComponent ("[ERROR ->]<gridster-item [item]="data">
    <div>
        <h1>{{data["title"]}}</h1>
"): ng:///AppModule/DefaultButtonComponent.html@0:0 ; Zone: <root> ; Task: Promise.then ; Value: Error: Template parse errors:
```
I already tried to add GridsterComponent to providers but without success.
I'm wondering if `<gridster-item>` should be in the same template as `<gridster>`

dashboard/dashboard.component.html:
```
<gridster [options]="options">
    <ng-template dashboard-host></ng-template>
</gridster>
```
dashboard/default-button/default-button.component.html:
```
<gridster-item [item]="data">
    <div>
        <h1>{{data["title"]}}</h1>
        <p>{{data["description"]}}</p>
        <a routerLink="{{data['componentLink']}}">{{data["componentLink"]}}</a>
    </div>
</gridster-item>
```
And if i remove `<gridster-item>` i can display the template.
The data value : `{cols: 1, rows: 1, y: 1, x: 2, componentLink: "catalogue", title: "Catalogues", description: "Je consulte les catalogues fournisseurs", component:
function DefaultButtonComponent()}`

**Comment by tiberiuzuld** [comment]
Hi @Onyphlax ,
I think you should have the template like this:
```
<gridster [options]="options">
   <gridster-item [item]="item" *ngFor="let item of dashboard">
      <ng-template dashboard-host></ng-template>
    </gridster-item>
</gridster>
```
You need to initialize different component inside the `gridster-item` depending of `componentLink`

**Comment by Onyphlax** [comment]
I already tried this but this defined all my components in only one gridster-item.
That's why i tried to use gridster-item in an other template

**Comment by tiberiuzuld** [comment]
Well your `ComponentFactoryResolver` needs to define only one of your components not all of them.
Since you can have different components in different `gridster-item`

**Comment by Onyphlax** [comment]
Well i don't succeed with your methode.
But the thing that i don't understand, is why i can't have a `<gridster-item>` on an other template.

**Comment by tiberiuzuld** [comment]
`<gridster-item>` requires `<gridster>` as Host see [here](https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridsterItem.component.ts)

And maybe thats why you get that error.

I never tried to use the `ComponentFactoryResolver` so I don't know why is not working for you inside the `<gridster-item>`

**Comment by tiberiuzuld** [comment]
Hi @Onyphlax ,

Did you made it work ?

Try [this](https://www.npmjs.com/package/ng-dynamic-component) maybe it will work.

Same issue [here](https://github.com/tiberiuzuld/angular-gridster2/issues/51) will close this one to keep the conversation in one place about dynamic components.
