### ISSUE TITLE
Not able to access/update class/member/instance member variables on GridsterConfig ( GridsterConfigOptions ) static callback methods/events.

### ISSUE THREAD

**Issue by 9561690684** [tiberiuzuld/angular-gridster2#568]
Hi,
         As GridsterConfig ( GridsterConfigOptions ) provide us all the events handling as static methods. In this method we are not able to access/update the class ( which uses gridster ) member/instance variable. As per my current requirement I have to update my class/member/instance level variables inside these callback methods ( ex.- itemChange( item: GridSterItem, itemComponent: GridsterItemComponent )). Please let me know any suitable approach.

Thanks

**Comment by Subbup101** [comment]
I am also looking for the similar solution, any alternatives that you have?

**Comment by hathawayjess** [comment]
I used .bind(this) to solve this problem.

In the options object, do something like this:

```
this.options = {
      [...other options here...]
      itemChangeCallback: this.itemChange.bind(this),
      itemResizeCallBack: this.itemResize.bind(this)
}
```

**Comment by 9561690684** [comment]
Thanks hathawayjess. It works.
