### ISSUE TITLE
Getting maximum call stack size exceed error, when set maxgridcols to 5 in angular 4

### ISSUE THREAD

**Issue by kirtiesl** [tiberiuzuld/angular-gridster2#57]
Hi,

Set maxgridcols to 5 in vertical scroll layout, getting maximum call stack size exceed error while dragging griditem.
![gridster](https://cloud.githubusercontent.com/assets/27264221/26725751/a1642564-47bd-11e7-8be2-e592b529a5e2.png)

Please provide solution.

**Comment by tiberiuzuld** [comment]
Hi @kirtiesl ,
Well is probably because you set max cold less than what you have in the grid.
Not near a PC today. Will look at it soon.

**Comment by tiberiuzuld** [comment]
Hi @kirtiesl ,

Looked a bit into it, is how the `Push Items` works and calculates how to push the items.
There is a recursively function which passes through all items needs to move.
Will try to solve the issue as soon as possible.

**Comment by kirtiesl** [comment]
Hi tiberiuzuld ,
Could you please solve above issue as soon as possible and update me the same.

**Comment by tiberiuzuld** [comment]
Hi @kirtiesl ,
Yes will try to solve it as soon as possible. Will let you know.

**Comment by kirtiesl** [comment]
Hi tiberiuzuld,
Is there any function to get sequence of grid item??

**Comment by tiberiuzuld** [comment]
Hi @kirtiesl ,
What do you mean by sequence of grid item ? There is no sequence used internally.

**Comment by tiberiuzuld** [comment]
Hi @kirtiesl ,
Fixed the issue in v2.10.5
Please have a look and let me know if you find anymore problems.
