### ISSUE TITLE
Gridster2 items displayed in one column and only remove item button works

### ISSUE THREAD

**Issue by bcebova** [tiberiuzuld/angular-gridster2#58]
Hi, 

I've implemented angular-gridster2 from the demo application ANGULAR-GRIDSTER2-MASTER.

These are the changes that I've made:
//import { GridsterConfig } from 'angular-gridster2'; - FIRST ATTEMPT
import { GridsterConfig } from 'angular-gridster2/dist/gridsterConfig.interface'; //- SECOND ATTEMPT
import "../app.component.css"; // from the demo
import "../../../../node_modules/@angular/material/prebuilt-themes/deeppurple-amber.css"

I've copied the ngOnInit() function with the same dashboard and the options from the demo.
I've also copied the events: eventStop, itemChange, itemResize, itemInit, changedOptions, removeItem, addItem in app.component.ts from the demo.

I've copied the html from the demo and the css also.

Imported necessary modules in app.module.ts.
//import { GridsterModule } from 'angular-gridster2';
import { GridsterModule } from 'angular-gridster2/dist/gridster.module';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import {
    MdIconModule,
    MdButtonModule,
    MdSelectModule,
    MdSliderModule,
    MdInputModule,
    MdTooltipModule,
    MdCheckboxModule
} from '@angular/material';

import 'hammerjs';
...

Added all packages in package.json I didn't had and included gridster-angular2 in vendor.ts.

And I got this:
![gridster2](https://cloud.githubusercontent.com/assets/29229405/26830383/087197c4-4ac9-11e7-808d-16f87e678b7f.png)

What could be the problem?

Thanks in advance,
bcebova

**Comment by tiberiuzuld** [comment]
Hi @bcebova ,
It may be the problem of the width you give to the `gridster`. since the option `mobileBreakpoint` is greater than the width size it has there.

And for the other problems you had importing stuff will investigate.

**Comment by bcebova** [comment]
Hi @tiberiuzuld,

I've found that if I overwrite the following css I've found:
gridster.css
:host {
        position: relative;
        display: flex;
        overflow: auto;
        flex: 1 auto;
        background: grey;
        width: 100%;
        height: 100%;
    }
in my component css as:
gridster {
    position: absolute !important;
    display: flex;
    overflow: auto;
    flex: 1 auto;
    background: grey;
    width: 100%;
    height: 100%;
}
the gridster gets the same as in the demo.

Thanks!
Regards.
bcebova

**Comment by tiberiuzuld** [comment]
Hi @bcebova ,
So I just tried a test app with `angular-cli` and imported the `angular-gridster2` just fine.
```typescript
// app.module.ts
import {BrowserModule} from '@angular/platform-browser';
import {NgModule} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {HttpModule} from '@angular/http';
import {GridsterModule} from 'angular-gridster2';

import {AppComponent} from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    GridsterModule,
    HttpModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {
}

```

```typescript
// app.component.ts
import {Component, OnInit} from '@angular/core';
import {GridsterConfig} from 'angular-gridster2';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  options: GridsterConfig;
  dashboard: Array<Object>;

  static eventStop(item, scope) {
    console.info('eventStop', item, scope);
  }

  static itemChange(item, scope) {
    console.info('itemChanged', item, scope);
  }

  static itemResize(item, scope) {
    console.info('itemResized', item, scope);
  }

  static itemInit(item) {
    console.info('itemInitialized', item);
  }

  ngOnInit() {
    this.options = {
      gridType: 'fit',
      compactUp: false,
      compactLeft: false,
      itemChangeCallback: AppComponent.itemChange,
      itemResizeCallback: AppComponent.itemResize,
      margin: 10,
      outerMargin: true,
      maxItemCols: 50,
      minItemCols: 1,
      maxItemRows: 50,
      minItemRows: 1,
      defaultItemCols: 1,
      defaultItemRows: 1,
      fixedColWidth: 250,
      fixedRowHeight: 250,
      draggable: {
        enabled: true,
        stop: AppComponent.eventStop
      },
      resizable: {
        enabled: true,
        stop: AppComponent.eventStop
      },
      swap: false
    };

    this.dashboard = [
      {cols: 2, rows: 1, y: 0, x: 0},
      {cols: 2, rows: 2, y: 0, x: 2},
      {cols: 1, rows: 1, y: 0, x: 4},
      {cols: 1, rows: 1, y: 0, x: 5},
      {cols: undefined, rows: undefined, y: 1, x: 0},
      {cols: 1, rows: 1, y: undefined, x: undefined},
      {cols: 2, rows: 2, y: 1, x: 5, minItemRows: 2, minItemCols: 2, label: 'Min rows & cols = 2'},
      {cols: 2, rows: 2, y: 2, x: 0, maxItemRows: 2, maxItemCols: 2, label: 'Max rows & cols = 2'},
      {cols: 2, rows: 1, y: 2, x: 2, dragEnabled: true, resizeEnabled: true, label: 'Drag&Resize Enabled'},
      {cols: 1, rows: 1, y: 2, x: 4, dragEnabled: false, resizeEnabled: false, label: 'Drag&Resize Disabled'},
      {cols: 1, rows: 1, y: 0, x: 6, initCallback: AppComponent.itemInit}
    ];
  }

  changedOptions() {
    this.options.optionsChanged();
  }

  removeItem(item) {
    this.dashboard.splice(this.dashboard.indexOf(item), 1);
  };

  addItem() {
    this.dashboard.push({});
  };
}
```

```css
// app.component.css
:host {
  display: block;
  width: 100%;
  height: 100%;
}
```

```html
<!-- app.component.html -->
<gridster [options]="options">
  <gridster-item [item]="item" *ngFor="let item of dashboard">
    <!-- your content here -->
  </gridster-item>
</gridster>
```
![image](https://user-images.githubusercontent.com/15310395/26988134-c77ecf3a-4d56-11e7-9f1c-f8cefa8db96c.png)
