### ISSUE TITLE
Cannot read property 'renderer' of undefined

### ISSUE THREAD

**Issue by iturn** [tiberiuzuld/angular-gridster2#587]
On resize of tile, this error gets thrown, started happening after updating the library.

 "angular-gridster2": "8.3.*",
"@angular/common": "~8.1.1",

![1](https://user-images.githubusercontent.com/12299090/73931550-cd234d00-48d8-11ea-9d20-a76ad7f7e900.png)
![2](https://user-images.githubusercontent.com/12299090/73931656-f17f2980-48d8-11ea-94b8-58b6cc918d8c.png)

**Comment by tiberiuzuld** [comment]
Hi @iturn ,
Tested on the demo page and couldn't reproduce.
Can you give more info about the configuration of the gridster?
Is it possible the item is removed right after resize end?
From what I see from error all signs indicate that the item was removed on resize end.

**Comment by iturn** [comment]
Thanks for your quick reply and the great package!

Your input brought me the idea to delay the ngrx action that updates the tile config with a set timeout. This seems to have fixed the issue as i now assume the time config was updated while still rerendering.
