### ISSUE TITLE
Angular 9 Support

### ISSUE THREAD

**Issue by ashish-sharma91** [tiberiuzuld/angular-gridster2#597]
Please update the code, so that it can be used with Angular 9.

**Comment by tiberiuzuld** [comment]
Hi @ashish-sharma91 ,
The demo is working with angular 9
https://tiberiuzuld.github.io/angular-gridster2/
What is not working for you in angular 9?

**Comment by tmtron** [comment]
We've already updated to ng-9 and it works fine in our app.

**Comment by jmacaluso711** [comment]
I'm getting this error in Angular 9.0.2 and Gridster 9.0.1

```
This likely means that the library (angular-gridster2) which declares GridsterModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
```

**Comment by jmacaluso711** [comment]
This appears to only happen when adding the import while the Angular app is running.
To resolve I just stopped the local server and re-ran `npm start`
