### ISSUE TITLE
can't run the demo project with latest commit

### ISSUE THREAD

**Issue by dedalusmax** [tiberiuzuld/angular-gridster2#6]
when cloning the project, npm install throws me:
-- UNMET PEER DEPENDENCY zone.js@0.8.4
(maybe it's not a problem)

BUT, when I npm start, this is what I get:

ERROR in D:/angular-gridster2/src/app/app.component.ts (5,13): Cannot find name 'module'.)

ERROR in D:/angular-gridster2/lib/gridster.component.ts (9,13): Cannot find name 'module'.)

ERROR in D:/angular-gridster2/lib/gridsterItem.component.ts (9,13): Cannot find name 'module'.)

P.S. what is strange, is that it worked this weekend (yesterday)!

**Comment by tiberiuzuld** [comment]
Fixed now.

**Comment by dedalusmax** [comment]
thank you very much. 
I have only one problem - unfortunatelly, our project's package.json is currently fixed to angular libraries fixed to 2.4.0. is it possible to make the dependencies go from then?
