### ISSUE TITLE
priorities for compactUp and compactLeft

### ISSUE THREAD

**Issue by jtushar53** [tiberiuzuld/angular-gridster2#61]
Hi,
i need both compactup and compactLeft for gridster item but the problem is when we remove top left gridster item, the bottom widget goes up.  I need the right item next to it should get aligned to left.

 if i use only compactLeft, item shifts to left but at the end the when first row is empty the second row should slide up.

![gridsterremoveitem](https://user-images.githubusercontent.com/5780117/27216557-ddaaaeae-5293-11e7-98d1-d6eecd103f88.gif)

**Comment by tiberiuzuld** [comment]
Hi @jtushar53 ,
Will put in a different option over the weekend.

**Comment by tiberiuzuld** [comment]
Hi @jtushar53 ,
Changed how `compact` options work in v3.0.0.
Now you can choose to compact left and then up by using `compactType` option.

I don't think it will work how you want it to work.

If you want to move up the items only after all the row is empty then you will have to change options at run time.

```typescript
//initialize grid with `this.options.compactType` to `compactLeft`

// user removes item
// check item removed row is empty
// if yes
// change `this.options.compactType` to 'compactUp'
// call `this.options.api.optionsChanged()`
// switch back  `this.options.compactType` to 'compactLeft'
// call `this.options.api.optionsChanged()`
```

Let me know if this helps you.

**Comment by jtushar53** [comment]
Thanks, its working now.
