### ISSUE TITLE
Resize Works In Opposite Direction If Direction is RTL

### ISSUE THREAD

**Issue by Ibrahimrahhal** [tiberiuzuld/angular-gridster2#610]
**My App Supports Both Multi Languages, every thing goes well when I switch directions except for the resizing.**
It works in the **opposite direction of dragging** if the direction is in **rtl**. 
here's my configs.
 this.options = {
      gridType: GridType.Fixed,
      compactType: CompactType.None,
      margin: 10,
      outerMargin: true,
      outerMarginTop: null,
      outerMarginRight: null,
      outerMarginBottom: null,
      outerMarginLeft: null,
      useTransformPositioning: true,
      mobileBreakpoint: 640,
      minCols: 11,
      maxCols: 11,
      minRows: 7,
      maxRows: 30,
      defaultItemCols: 1,
      defaultItemRows: 1,
      fixedColWidth: 105,
      fixedRowHeight: 105,
      keepFixedHeightInMobile: false,
      keepFixedWidthInMobile: false,
      scrollSensitivity: 10,
      scrollSpeed: 20,
      enableEmptyCellClick: false,
      enableEmptyCellContextMenu: false,
      enableEmptyCellDrop: false,
      enableEmptyCellDrag: false,
      enableOccupiedCellDrop: false,
      emptyCellDragMaxCols: 50,
      emptyCellDragMaxRows: 50,
      ignoreMarginInRow: false,
      dirType: this.translate.currentLang == 'ar' ? 'rtl' :'ltr',
      draggable: {
        enabled: false,
        stop:(a,b,x)=>{
          setTimeout(()=>{
            this.calculateWidgetsHeight();
          },100)
        },
      },
      resizable: {
        enabled: false,
      },
      swap: false,
      pushItems: true,
      disablePushOnDrag: false,
      disablePushOnResize: false,
      pushDirections: {north: true, east: true, south: true, west: true},
      pushResizeItems: false,
      displayGrid: DisplayGrid.OnDragAndResize,
      disableWindowResize: false,
      disableWarnings: false,
      scrollToNewItems: false
    };

thank you.

**Comment by EitanD1** [comment]
it happens even on [demo](https://tiberiuzuld.github.io/angular-gridster2/rtl)
