### ISSUE TITLE
[bug] declaration for GridsterConfig still contains optionsChanged

### ISSUE THREAD

**Issue by reppners** [tiberiuzuld/angular-gridster2#62]
The api changed with 3.0.0 and an exception is thrown at runtime but in the typings of `GridsterConfig` the `optionsChanged` function is still declared.

https://github.com/tiberiuzuld/angular-gridster2/blob/562002a8aacd0d9558fca21e29f239b2bd9cced8/dist/gridsterConfig.interface.d.ts#L27

**Comment by tiberiuzuld** [comment]
Hi @reppners ,
Ops forgot to remove it. Will make the fix today. 

Thank you,

**Comment by tiberiuzuld** [comment]
Hi @reppners ,
Fixed the issue in v3.0.1.
Thank you,
