### ISSUE TITLE
Getting an items position in dropOverItemsCallback

### ISSUE THREAD

**Issue by JeffersonBledsoe** [tiberiuzuld/angular-gridster2#633]
`dropOverItemsCallback` works great for situations where I want custom drop behaviour based on what source item was dragged onto what target item, however I would like to be able to further fine-tune some behaviour based on where the item was dropped. Is there either a way to access the widget used to render the source and/ or target item, or for me to know the x and y positions of where the source item was dropped inside the callback?

I realise I can handle this manually by keeping a reference to the gridster items and using `draggable.stop` to work out which item the drag was dropped on, but having that little bit of help from angular-gridster to reduce that unnecessary code would go a long way!

This could be achieved by adding an optional callback parameter to [where the `dropOverItems` callback is called](https://github.com/tiberiuzuld/angular-gridster2/blob/c2df0fb9622dc664f05c9692c76b6f9e974d5635/projects/angular-gridster2/src/lib/gridsterDraggable.service.ts#L223). I'll get a PR with this for you to comment on :)

**Comment by tiberiuzuld** [comment]
Hi @JeffersonBledsoe ,
Maybe I didn't understood your whole question or what extra information you need.
But the callback is called with the fallowing parameters: item that is dragged, item that is dragged over, gridster instance.
Item that is dragged should have the new coordinated.
Item that is dragged over could make you get what item is for you, in your context.

If you make a PR I will Review and merge.

**Comment by JeffersonBledsoe** [comment]
Thanks for responding @tiberiuzuld :)
I think what I actually need is a function to get an item's component based on the item that is being rendered. I know this is internally available, but is there a public API for this?

**Comment by tiberiuzuld** [comment]
So then in that scenario you want 
`this.gridsterItem` (source) and `this.collision` (target) the internal item components ?

**Comment by tiberiuzuld** [comment]
I can add an api callback to give you the internal component based on the item from that callback.

**Comment by JeffersonBledsoe** [comment]
> So then in that scenario you want 
> `this.gridsterItem` (source) and `this.collision` (target) the internal item components ?

Exactly what I'm after!

**Comment by tiberiuzuld** [comment]
Let me know if this fits your needs:
https://github.com/tiberiuzuld/angular-gridster2/commit/f213e2c0c78d8795b81dd07bf20fad54f2296185
you give it the item you get in `dropOverItemsCallback` and returns the component if it is found.

**Comment by tiberiuzuld** [comment]
Hmm but now I remembered there is this option `initCallback` which gives you the GridsterComponent.
You save it on a property and use it when you get `dropOverItemsCallback` items.
And from that you can do what I did in the code to find the GridsterItemComponent:
```
gridster.grid.find(c => c.item === item);
```

Hmm maybe I should revert the last commit and you can use the existing API to get your component.
What do you think, it is ok for your use case?

**Comment by JeffersonBledsoe** [comment]
The existing API works great @tiberiuzuld! Although I do like having the API function around, makes it quite clear what's going on :) Thanks for doing this either way!

**Comment by tiberiuzuld** [comment]
Added the api method in v10.1.0
