### ISSUE TITLE
Bug: Mobile Gridster Height for ScrollVertical and setGridSize: true

### ISSUE THREAD

**Issue by ea20140129** [tiberiuzuld/angular-gridster2#637]
Hello Tiberiu:

I am having an issue with Mobile Gridster Height for ScrollVertical and setGridSize: true.  The Gridster height shrinks down to a small square area.  I've tried to manually override it in Chrome but always gets reset.

I have the height of gridster at 100vh as follows:
gridster {
height: 100vh;
margin: 0 auto;
}

I started to experience this with the following setting: 
setGridSize: true

I also get the same result on your Demo site.  Choose Grid Type "Scroll Vertical" and check the "Set Grid Size" checkbox.  Then go into Mobile in the browser (F12).

Appreciate your help with this.

**Comment by tiberiuzuld** [comment]
Fixed in v.10.0.2 , please let me know if it is now working correctly for you.

**Comment by tiberiuzuld** [comment]
The issue with double scrollbar should be fixed now in v10.1.2

**Comment by VinodLouis** [comment]
@tiberiuzuld is this fix available for v8.x.x?

**Comment by VinodLouis** [comment]
@tiberiuzuld seems still a bug for V8 missing the changes. Please consider [MR](https://github.com/tiberiuzuld/angular-gridster2/pull/690)
