### ISSUE TITLE
Auto resize doesn't fire any events

### ISSUE THREAD

**Issue by samarsiraj** [tiberiuzuld/angular-gridster2#64]
Hello,
When Auto resize occurs no events are fired. My use case involves storing the x and y position so that the grid positions are retained. But there is no way of knowing if auto resize has occurred apart from the console message. Is this the expected behaviour?
Thanks in advance.

**Comment by tiberiuzuld** [comment]
Hi @samarsiraj ,
The auto resize only changes the size of the items in width and height not the x, y , cols, rows.

The resize callback should be used when the content of the widget needs to resize also, like a chart.

**Comment by samarsiraj** [comment]
Thanks for clarifying.
