### ISSUE TITLE
trackBy reset issue

### ISSUE THREAD

**Issue by tmtron** [tiberiuzuld/angular-gridster2#644]
when a new item collection is assigned to ngFor, the layout does not work as expected.

Here is a [Stackblitz example](https://stackblitz.com/edit/angular-gridster-track-by) to reproduce the issue.  
* The dashboard is basically the same as in the [trackBy example](https://tiberiuzuld.github.io/angular-gridster2/trackBy)
  * the only difference is that you can delete elements when you click the `ID`-div

Make sure to make the browser window is wide enough so that you don't see the mobile layout!

The issue happens when you 
* delete the item with `ID: 0` (click on the id)
* then move the item with `ID: 1` to the left
* click `Reset`

The reset function assigns the initial dashboard to gridster, but thistime, the tile with `ID: 0` is in another position.
It seems that the previous position is somehow remembered when we use `trackBy`.

Here's a gif to show the issue
![2020-07-13_19h07_54](https://user-images.githubusercontent.com/20422904/87332654-30767280-c53c-11ea-85ed-a847f72641d3.gif)

Gridster version: 
* 10.0.2
* I also saw this in version 9.3.2

Workaround is not to use `trackBy` for now..

**Comment by tiberiuzuld** [comment]
Hi @tmtron ,
It is working as expected.
You are resetting to original positions.
When doing this:
```
   this.dashboardOriginal = this.dashboard.map(x => ({ ...x }));
```
the object reference is not kept so any changes you do are lost.
If you want to keep the changes you need to update `dashboardOriginal`

**Comment by tmtron** [comment]
@tiberiuzuld 
thanks for the answer.
However, there seems to be a misunderstanding: I think I did not explain the issue good enough.

> When doing this:
> 
>    this.dashboardOriginal = this.dashboard.map(x => ({ ...x }));
> the object reference is not kept so any changes you do are lost.

Yes: that is exactly what I want: after calling `reset()` I always expect the dashboard to look exactly the same as the initial dashboard.

**Details**

When the component is initialized, we take a copy of the initial dashboard `dashboardOriginal`:
` this.dashboardOriginal = this.dashboard.map(x => ({ ...x }));`

The initial dashboard looks like this:
![image](https://user-images.githubusercontent.com/20422904/88037033-ac784800-cb44-11ea-82f6-954b0c493793.png)

In the `reset()` function, we change the current dashboard (`this.dashboard`) back to the original dashboard:

```typescript
  reset() {
    this.dashboard = this.dashboardOriginal.map(x => ({ ...x }));
  }
```

So: after every `reset()` call, the dashboard should look exactly the same as the original dashboard, right?  
But it does not (in the case that I described in this issue). `ID: 0` is not in the original position (after calling `reset()`):
![image](https://user-images.githubusercontent.com/20422904/88037092-c154db80-cb44-11ea-95a9-cc474fc495f5.png)

**Comment by tiberiuzuld** [comment]
Oh ok, I found the issue now, but don't know how to resolve it.
Because you are removing the item 0 and moving item 1 to be over the position of item 0 original position, when resetting the item 0 is recreated before item 1 is updated. The grid will detect a conflict and move item 0 first to a new position and only after that update item 1
This happens because of id 0 is before id 1 in array ngFor just loops over them in order.
if you do this in reverse you will not notice this issue.
There are 2 workarounds for this:
1. Reset the grid a second time.
2. Don't use trackBy

I don't know a way on how to resolve this issue at the moment.

**Comment by tmtron** [comment]
Thanks for the answer.

I can live with the double reset workaround. This code seems to work:

```typescript
  private resetGrid() {
    this.dashboard = this.dashboardOriginal.map(x => ({ ...x }));
  }

  reset() {
    this.resetGrid();
    this.cdr.detectChanges();
    this.resetGrid();
  }
```
