### ISSUE TITLE
Items are stacked when the grid is full

### ISSUE THREAD

**Issue by dions00** [tiberiuzuld/angular-gridster2#65]
I don't know if it is normal or not,  when the grid is full, the new items are stacked on top of each other.

![grid_full](https://user-images.githubusercontent.com/5869871/27593461-3f04f6d4-5b25-11e7-8936-53bc041273df.png)

With the api,  is it possible to know if adding a new item has been successful or not?

In my application, we have a concept of floating tile and docked tile,  the floating tile can be docked in the grid if there is enough space, otherwise, a error message is displayed and the tile remains floating.

Thanks,
Stephane

**Comment by tiberiuzuld** [comment]
Hi @dions00 ,
Will have a look today with the issue about adding.
Currently there is no way of knowing beforehand if the new item has room. 
Will look to see how easy it is to add the functionality.

**Comment by tiberiuzuld** [comment]
Hi @dions00 ,

Fixed the issue in v3.1.0
And added feature `this.options.api.getNextPossiblePosition(item: GridsterItem);` to get the next viable position of a new item before adding to grid.

Let me know if this will be ok for you.
