### ISSUE TITLE
Bug: double scroll bar

### ISSUE THREAD

**Issue by otsybulsky** [tiberiuzuld/angular-gridster2#660]
Hi! I want to implement a dashboard that can automatically expand to the right and down.
For a maximized browser window, everything works fine. But when I switch the browser window to normal mode, the dashboard behaves incorrectly. When i increase the element vertically, a double scroll bar appears, and the elements change their location. This is clearly seen in the screenshot. Please help solve this problem.

![gridster - double scroll bar](https://user-images.githubusercontent.com/34866613/90229223-381d8580-de20-11ea-9e44-fe1479fb2a03.gif)

```
 this.options = {
      gridType: GridType.Fixed,
      displayGrid: 'none',
      outerMargin: true,
      outerMarginTop: 2,
      outerMarginRight: 2,
      outerMarginBottom: 2,
      outerMarginLeft: 2,
      margin: 2,
      fixedColWidth: 10,
      fixedRowHeight: 10,
      maxItemCols: 1000,
      maxItemRows: 1000,
      maxItemArea: 1000000,
      maxCols: 1000000,
      maxRows: 1000000,
      disableWindowResize: true,
      swap: false,
      swapWhileDragging: false,
      scale: 1,
      setGridSize: false,
      resizable: {
        enabled: true,
      },
      draggable: {
        enabled: true,
      },

      itemChangeCallback: LayoutComponent.itemChange,
      itemResizeCallback: LayoutComponent.itemResize,
    };
```

**Comment by tiberiuzuld** [comment]
Hi @otsybulsky ,
After investigation and a bit of trial and error, I found what is the issue, is related to mobile size.
Event if you have `disableWindowResize` set to true, the problem seems that the grid seems to calculate is in mobile mode.
I suggest setting the `mobileBreakpoint` to 0 that seems to solve your issue.

**Comment by otsybulsky** [comment]
mobileBreakpoint with 0 works great. Thanks for the help!
