### ISSUE TITLE
Is there a way to change 4 corners of an item?

### ISSUE THREAD

**Issue by jmalkan** [tiberiuzuld/angular-gridster2#661]
I'd like to have rounded edges for the items.
What are my options & best practices to achieve this?

**Comment by jmalkan** [comment]
one option i found is 
`
gridster gridster-item {
	border-radius: 15px;
}
`

set the component with 
`encapsulation: ViewEncapsulation.None`

**Comment by tiberiuzuld** [comment]
you are right, or you can use `::ng-deep`
