### ISSUE TITLE
Jumpy continuous scroll to top

### ISSUE THREAD

**Issue by phynweb** [tiberiuzuld/angular-gridster2#663]
I have a weird issue here.

When I load a dashboard I can't scroll down. There's a quick scroll down response, but the page automatically scrolls back up every time. Once i click on any dashboard item `drag-handle`, everything is find and I can scroll like normal. However, once I resize/drag an item that causes the existing grid to expand, I get the same issue all over again.

I just upgraded to version 10 of gridster which involved upgrading my project from angular v8 to v10 (and several libraries in the process). However, this only happens on gridster pages and is only fixed by clicking specifically on the drag handle (nowhere else). I have a non-trivial app, and can't re-create this issue in a minimal example. Just checking to see if this rings any bells or if anyone has any ideas/pointers/suggestions?

If it helps, i've noticed that unchecking the CSS attributes (position: relative & top/right/bottom/left = 0) that come with `fullscreen` attribute on my page's `mat-sidenav-container` allows normal scrolling to resume. Also, this happens on every grid type, but when i set `setGridSize` to false while the type is `verticalFixed` and set the height of the `gridster` element manually within the `gridSizeChangedCallback`, the scrolling issue disappears. The problem is that each of these workarounds come with different UI/UX problems....just mentioning them in case it highlights the root issue to someone who has experienced this.

**Comment by tiberiuzuld** [comment]
Hi @phynweb ,
This issue was able to reproduce in #665
Will track this issue there from now on.
Thank you for your info.
