### ISSUE TITLE
Unexpected Jumpy scrolling

### ISSUE THREAD

**Issue by wessamyaacob** [tiberiuzuld/angular-gridster2#666]
Hi , I've a problem when using `setGridSize:true `with `GridType.ScrollVertical` and wrapping gridster inside bootstrap div `container-fluid` , when you try to drag item down the bottom of the screen a jumpy scrolling recursive behaviour happens and only stop when you press one click on the item itself, here is the link to reproduce the issue

https://angular-k4uhx9.stackblitz.io/
https://stackblitz.com/edit/angular-k4uhx9

**Comment by ea20140129** [comment]
Confirmed.  With settings setGridSize:true with GridType.ScrollVertical when scrolling to the absolute bottom and try to hold the scroll at the bottom the jumpiness starts to happen.

**Comment by wessamyaacob** [comment]
any update on this issue ?

**Comment by derekparsons718** [comment]
I'm having a very similar issue. As the author described, the issue disappears after a single click on an item. Some minor differences in my scenario:
- I'm using `VerticalFixed`, not `ScrollVertical`
- I'm not using `container-fluid`
- The scroll position jumps up as soon as I attempt to scroll down past the top of the grid. This effectively prevents me from scrolling to the bottom; I can only view the top portion of the grid.

**Comment by derekparsons718** [comment]
I just proposed a fix for this in #681. I explain why it is happening in the opening comment.

**Comment by derekparsons718** [comment]
Just submitted a fix for this: #681 

I explained why it was happening in the opening comment.

**Comment by tiberiuzuld** [comment]
fix in v10.1.7
Thank you @derekparsons718
