### ISSUE TITLE
Does gridster support push all gridster upwards when the top gridster is resized to a smaller size.

### ISSUE THREAD

**Issue by neoccccc** [tiberiuzuld/angular-gridster2#668]
in the example here https://tiberiuzuld.github.io/angular-gridster2/api, the gridster is pushed down then the first gridster is resized to a bigger size. 

How can I achieve the opposite effect? ie. when the top gridster is changed to a smaller size, all the gridster beneath it should push it up to fill the empty space.

**Comment by tiberiuzuld** [comment]
Try compact up
