### ISSUE TITLE
Hide scrollbars on overflow?

### ISSUE THREAD

**Issue by Blunderchips** [tiberiuzuld/angular-gridster2#670]
Is it possible to completely hide both scrollbars on overflow? So if the grid item is too small to display the content within the content is hidden.

**Comment by tiberiuzuld** [comment]
css

**Comment by Blunderchips** [comment]
A fine theory @tiberiuzuld, however, setting overflow to hidden does not appear to have any effect.

**Comment by tiberiuzuld** [comment]
So you want to not have scrollbars in a item when the content is to big ? 
well you can use css:
```
::ng-deep .gridster-item {
 overflow: hidden
}
```
or maybe I understood incorrectly a image with the problem would help
