### ISSUE TITLE
Issue with setGridSize: true and GridType: VerticalFixed

### ISSUE THREAD

**Issue by animesh84** [tiberiuzuld/angular-gridster2#675]
Hi Team,

I have page which has sidebar which is collapsible and expandable at left side and right side i have dashboard showing gridster tile which contains highcharts. Issue is that when i collapse/expand side bar, i call this.options.api.resize(); which re-adjust tile but it fluctuate while resizing the tile. i am sharing the video also but working fine when i set GridType.Fit

[7a7461f1-aefa-4b73-b8ca-2d9f87d9c24b.zip](https://github.com/tiberiuzuld/angular-gridster2/files/5290767/7a7461f1-aefa-4b73-b8ca-2d9f87d9c24b.zip)

**Comment by tiberiuzuld** [comment]
HI @animesh84 ,
When do you call that resize?
Before or after your sidebar transition?
You should call it after the transition of the sidebar is over.
Maybe that is why you see a flicker or something.
If you have CSS transition look into `ontransitionend` https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ontransitionend

**Comment by animesh84** [comment]
@tiberiuzuld I have called resize after transition finished.
this.toggleSidebarSubscription = this.dashboardService.getToggleMenuSidebarStatus().subscribe((status) => {
      setTimeout(() => {
        this.options.api.resize();
      }, 500);
    });

but the handler of **options** itemResizeCallback call 4 times of total tiles e.g. when i expand/collapse sidebar first Item resize call 16 times which is ok then after expand/collapse again it calls 32 times and then 64 times. thats why it is flickering.
For your reference i am pasting the ts and html code
ts code 
------------------------------------
import {
  ChangeDetectionStrategy,
  Component,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  SimpleChanges,
  ViewEncapsulation,
} from '@angular/core';

import * as Highcharts from 'highcharts';

import {
  CompactType,
  DisplayGrid,
  Draggable,
  GridsterConfig,
  GridsterItem,
  GridType,
  PushDirections,
  Resizable,
} from 'angular-gridster2';
import { DashboardService } from 'src/app/views/dashboard/services/dashboard.service';
import { Subscription } from 'rxjs';

export interface Safe extends GridsterConfig {
  draggable: Draggable;
  resizable: Resizable;
  pushDirections: PushDirections;
}

@Component({
  selector: 'app-practitioners-tile',
  templateUrl: './practitioners-tile.component.html',
  styleUrls: ['./practitioners-tile.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
})
export class PractitionersTileComponent implements OnInit, OnDestroy, OnChanges {
  @Input() selectedclients: any;
  previousSelectedClients: any[];
  previousSelectedWidgetDimension = [];
  options: Safe;
  dashboard: Array<GridsterItem>;

  highcharts = Highcharts;
  toggleSidebarSubscription: Subscription;

  constructor(private dashboardService: DashboardService) {}

  ngOnInit(): void {
    this.options = {
      gridType: GridType.VerticalFixed,
      compactType: CompactType.None,
      margin: 10,
      outerMargin: true,
      outerMarginTop: null,
      outerMarginRight: null,
      outerMarginBottom: null,
      outerMarginLeft: null,
      useTransformPositioning: true,
      mobileBreakpoint: 640,
      minCols: 1,
      maxCols: 4,
      minRows: 1,
      maxRows: 5,
      maxItemCols: 4,
      minItemCols: 1,
      maxItemRows: 5,
      minItemRows: 1,
      maxItemArea: 2500,
      minItemArea: 1,
      defaultItemCols: 1,
      defaultItemRows: 100,
      fixedColWidth: 285,
      fixedRowHeight: 165,
      keepFixedHeightInMobile: false,
      keepFixedWidthInMobile: false,
      scrollSensitivity: 10,
      scrollSpeed: 20,
      enableEmptyCellClick: false,
      enableEmptyCellContextMenu: false,
      enableEmptyCellDrop: false,
      enableEmptyCellDrag: false,
      enableOccupiedCellDrop: false,
      emptyCellDragMaxCols: 50,
      emptyCellDragMaxRows: 50,
      ignoreMarginInRow: false,
      draggable: {
        enabled: true,
      },
      resizable: {
        enabled: false,
      },
      swap: true,
      pushItems: false,
      disablePushOnDrag: false,
      disablePushOnResize: false,
      pushDirections: { north: true, east: true, south: true, west: true },
      pushResizeItems: false,
      displayGrid: DisplayGrid.None,
      disableWindowResize: false,
      disableWarnings: false,
      scrollToNewItems: false,
      setGridSize: true,
      itemInitCallback: () => {
        console.log('itemInitCallback');
      },
      itemChangeCallback: (gridsterItem, gridsterItemComponent) => {
        console.log('itemChangeCallback');
        if (this.previousSelectedWidgetDimension.length !== this.selectedclients.length) {
          this.selectedclients.forEach(item => {
            if (item === gridsterItem.widgetTitle) {
              this.previousSelectedWidgetDimension.push(Object.assign({}, gridsterItem));
            }
          });
        }
      },
      itemResizeCallback: (gridsterItem, gridsterItemComponent) => {
        console.log('itemResizeCallback');
        if (gridsterItem && gridsterItem.chartOptions) {
          gridsterItem.chartOptions.chart.height = gridsterItemComponent.height - 60;
          gridsterItem.chartOptions.chart.width = gridsterItemComponent.width - 26;
          gridsterItem.chartOptions = Object.assign({}, gridsterItem.chartOptions);
        }
      },
    };

    this.dashboard = [
      {
        cols: 1,
        rows: 1,
        y: 0,
        x: 0,
        widgetType: 'line',
        widgetName: 'PhysicalHealth',
        widgetTitle: 'Physical Health',
        widgetColor: '#665eff',
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        data: [
          7.0,
          6.9,
          9.5,
          14.5,
          18.2,
          21.5,
          25.2,
          26.5,
          23.3,
          18.3,
          13.9,
          9.6,
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 0,
        x: 1,
        widgetType: 'line',
        widgetName: 'LivingHealth',
        widgetTitle: 'Living Health',
        widgetColor: '#2cd443',
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        data: [
          7.0,
          6.9,
          9.5,
          14.5,
          18.2,
          21.5,
          25.2,
          26.5,
          23.3,
          18.3,
          13.9,
          9.6,
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 0,
        x: 2,
        widgetType: 'line',
        widgetName: 'HealthPractices',
        widgetTitle: 'Health Practices',
        widgetColor: '#3acce1',
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        data: [
          7.0,
          6.9,
          9.5,
          14.5,
          18.2,
          21.5,
          25.2,
          26.5,
          23.3,
          18.3,
          13.9,
          9.6,
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 0,
        x: 3,
        widgetType: 'line',
        widgetName: 'VitalityIndex',
        widgetTitle: 'Vitality Index',
        widgetColor: '#ff4f9a',
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        data: [
          7.0,
          6.9,
          9.5,
          14.5,
          18.2,
          21.5,
          25.2,
          26.5,
          23.3,
          18.3,
          13.9,
          9.6,
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 1,
        x: 0,
        widgetType: 'line',
        widgetName: 'VitalityIndexBaseline',
        widgetTitle: 'Vitality Index % Change from Baseline',
        widgetColor: '#ff4f9a',
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        data: [
          7.0,
          6.9,
          9.5,
          14.5,
          18.2,
          21.5,
          25.2,
          26.5,
          23.3,
          18.3,
          13.9,
          9.6,
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 1,
        x: 1,
        widgetType: 'line',
        widgetName: 'Wellbeing',
        widgetTitle: 'Wellbeing',
        widgetColor: '#78849e',
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        data: [
          7.0,
          6.9,
          9.5,
          14.5,
          18.2,
          21.5,
          25.2,
          26.5,
          23.3,
          18.3,
          13.9,
          9.6,
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 1,
        x: 2,
        widgetType: 'pie',
        widgetName: 'HealthStatus',
        widgetTitle: 'Health Status',
        widgetColor: '#665eff',
        data: [
          {
            name: 'Total',
            value: 10,
          },
          {
            name: 'Health Status',
            value: 9.3,
          },
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 1,
        x: 3,
        widgetType: 'pie',
        widgetName: 'EmotionalHealth',
        widgetTitle: 'Emotional Health',
        widgetColor: '#2cd443',
        data: [
          {
            name: 'Total',
            value: 10,
          },
          {
            name: 'Emotional Health',
            value: 6.2,
          },
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 2,
        x: 0,
        widgetType: 'progress-bar',
        widgetName: 'InternalWorld',
        widgetTitle: 'Internal World',
        widgetColor: '#3acce1',
        images: [
          {
            name: 'soothe.png',
          },
          {
            name: 'think.png',
          },
          {
            name: 'rest.png',
          },
        ],
        value: 7.3,
      },
      {
        cols: 1,
        rows: 1,
        y: 2,
        x: 1,
        widgetType: 'progress-bar',
        widgetName: 'PhysicalWorld',
        widgetTitle: 'Physical World',
        widgetColor: '#665eff',
        images: [
          {
            name: 'hydrate.png',
          },
          {
            name: 'move.png',
          },
          {
            name: 'nourish.png',
          },
        ],
        value: 8.0,
      },
      {
        cols: 1,
        rows: 1,
        y: 2,
        x: 2,
        widgetType: 'progress-bar',
        widgetName: 'ExternalWorld',
        widgetTitle: 'External World',
        widgetColor: '#3497fd',
        images: [
          {
            name: 'express.png',
          },
          {
            name: 'connect.png',
          },
          {
            name: 'activate.png',
          },
        ],
        value: 9.3,
      },
      {
        cols: 1,
        rows: 1,
        y: 2,
        x: 3,
        widgetType: 'progress-bar',
        widgetName: 'SpiritualWorld',
        widgetTitle: 'Spiritual World',
        widgetColor: '#2cd443',
        images: [
          {
            name: 'observe.png',
          },
          {
            name: 'seek.png',
          },
          {
            name: 'believe.png',
          },
        ],
        value: 9.1,
      },
      {
        cols: 1,
        rows: 1,
        y: 3,
        x: 0,
        widgetType: 'line',
        widgetName: 'Readiness',
        widgetTitle: 'Readiness',
        widgetColor: '#665eff',
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        data: [
          7.0,
          6.9,
          9.5,
          14.5,
          18.2,
          21.5,
          25.2,
          26.5,
          23.3,
          18.3,
          13.9,
          9.6,
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 3,
        x: 1,
        widgetType: 'line',
        widgetName: 'Depression',
        widgetTitle: 'Depression',
        widgetColor: '#2cd443',
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        data: [
          7.0,
          6.9,
          9.5,
          14.5,
          18.2,
          21.5,
          25.2,
          26.5,
          23.3,
          18.3,
          13.9,
          9.6,
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 3,
        x: 2,
        widgetType: 'line',
        widgetName: 'Anxiety',
        widgetTitle: 'Anxiety',
        widgetColor: '#3acce1',
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        data: [
          7.0,
          6.9,
          9.5,
          14.5,
          18.2,
          21.5,
          25.2,
          26.5,
          23.3,
          18.3,
          13.9,
          9.6,
        ],
      },
      {
        cols: 1,
        rows: 1,
        y: 3,
        x: 3,
        widgetType: 'line',
        widgetName: 'DistressIndex',
        widgetTitle: 'Distress Index',
        widgetColor: '#78849e',
        categories: [
          'Jan',
          'Feb',
          'Mar',
          'Apr',
          'May',
          'Jun',
          'Jul',
          'Aug',
          'Sep',
          'Oct',
          'Nov',
          'Dec',
        ],
        data: [
          7.0,
          6.9,
          9.5,
          14.5,
          18.2,
          21.5,
          25.2,
          26.5,
          23.3,
          18.3,
          13.9,
          9.6,
        ],
      },
    ];

    this.configureChartOptions();

    this.toggleSidebarSubscription = this.dashboardService.getToggleMenuSidebarStatus().subscribe((status) => {
      setTimeout(() => {
        this.options.api.resize();
      }, 500);
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    let selectedClientsChanges = changes['selectedclients'];
    if (!selectedClientsChanges.isFirstChange()) {
      this.addItem();
      this.previousSelectedClients = selectedClientsChanges.previousValue;
    }
  }

  removeItem($event: MouseEvent | TouchEvent, item): void {
    $event.preventDefault();
    $event.stopPropagation();
    this.dashboard.splice(this.dashboard.indexOf(item), 1);
  }

  addItem(): void {
    let addTileJson = {
      cols: 1,
      rows: 1,
      y: 0,
      x: 0,
      widgetType: 'pie',
      widgetName: 'HealthStatus',
      widgetTitle: 'Health Status',
      widgetColor: '#665eff',
      data: [
        {
          name: 'Total',
          value: 10,
        },
        {
          name: 'Health Status',
          value: 9.3,
        },
      ],
    };

    // Addition of tile
    this.selectedclients.forEach(selectedItem => {
      const idx = this.dashboard.findIndex(dashboardTile => dashboardTile.widgetName.toLowerCase() === selectedItem.toLowerCase());
      if (idx === -1) {
        addTileJson = Object.assign({}, addTileJson);
        const pieChartOptions = Object.assign({}, this.dashboardService.getPieChartOptions());
        addTileJson.widgetName = selectedItem;
        addTileJson.widgetTitle = selectedItem;

        pieChartOptions.subtitle.text = addTileJson.data[1].value;
        pieChartOptions.series[0].data[1].borderColor = addTileJson.widgetColor;
        pieChartOptions.series[0].data[1].color = addTileJson.widgetColor;
        pieChartOptions.series[0].data[1].name = addTileJson.data[1].name;
        pieChartOptions.series[0].data[1].y = addTileJson.data[1].value;
        pieChartOptions.series[0].data[0].name = addTileJson.data[0].name;
        pieChartOptions.series[0].data[0].y = addTileJson.data[0].value - addTileJson.data[1].value;
        addTileJson['chartOptions'] = pieChartOptions;
        this.dashboard.push(addTileJson);
        this.options.api.optionsChanged();
      }
    });

    // Remove tile if previousSelected and Selected has different item
    if (this.previousSelectedClients && this.previousSelectedClients.length) {
      const diff: any[] = this.previousSelectedClients.filter(item => !this.selectedclients.includes(item));
      if (diff && diff.length) {
        diff.forEach(selectedItem => {
          const idx = this.dashboard.findIndex(dashboardTile => dashboardTile.widgetName.toLowerCase() === selectedItem.toLowerCase());
          if (idx > -1) {
            const deleteItem = this.dashboard.splice(idx, 1);
            const previndex = this.previousSelectedWidgetDimension.findIndex(item => item.widgetTitle === selectedItem);
            const deleteItemFirstDimension = this.previousSelectedWidgetDimension.splice(previndex, 1);
            if (deleteItemFirstDimension[0].x !== deleteItem[0]['x'] || deleteItemFirstDimension[0].y !== deleteItem[0]['y'] || 
            deleteItemFirstDimension[0].rows !== deleteItem[0]['rows'] || deleteItemFirstDimension[0].cols !== deleteItem[0]['cols']) {
              this.dashboard[this.dashboard.length - this.selectedclients.length - 1].x = deleteItem[0]['x'];
              this.dashboard[this.dashboard.length - this.selectedclients.length - 1].y = deleteItem[0]['y'];
              this.dashboard[this.dashboard.length - this.selectedclients.length - 1].rows = deleteItem[0]['rows'];
              this.dashboard[this.dashboard.length - this.selectedclients.length - 1].cols = deleteItem[0]['cols'];
              this.options.api.optionsChanged();
            }
          }
        });
      }
    }
  }

  tileClickHandler($event: MouseEvent | TouchEvent, title: string): void {
    this.dashboardService.setSelectedTileTitle(title);
  }

  configureChartOptions(): void {
    this.dashboard.forEach((item) => {
      if (item.widgetType === 'pie') {
        const pieChartOptions = Object.assign(
          {},
          this.dashboardService.getPieChartOptions()
        );
        pieChartOptions.subtitle.text = item.data[1].value;
        pieChartOptions.series[0].data[1].borderColor = item.widgetColor;
        pieChartOptions.series[0].data[1].color = item.widgetColor;
        pieChartOptions.series[0].data[1].name = item.data[1].name;
        pieChartOptions.series[0].data[1].y = item.data[1].value;
        pieChartOptions.series[0].data[0].name = item.data[0].name;
        pieChartOptions.series[0].data[0].y =
          item.data[0].value - item.data[1].value;
        item['chartOptions'] = pieChartOptions;
      } else if (item.widgetType === 'line') {
        const lineChartOptions = Object.assign(
          {},
          this.dashboardService.getLineChartOptions()
        );
        lineChartOptions.xAxis.categories = item.categories;
        lineChartOptions.series[0].name = item.widgetTitle;
        lineChartOptions.series[0].color = item.widgetColor;
        lineChartOptions.series[0].data = item.data;
        item['chartOptions'] = lineChartOptions;
      }
    });
  }

  ngOnDestroy(): void {
    this.toggleSidebarSubscription.unsubscribe();
  }
}
------------End of TS code--------------------
html Code
___________________________

<gridster [options]="options">
  <gridster-item [item]="item" *ngFor="let item of dashboard; let i = index" (click)="tileClickHandler($event, item.widgetTitle)">

    <app-line-chart-tile
      *ngIf="item.widgetType === 'line'"
      [title]="item.widgetTitle"
      [color]="item.widgetColor"
      [highcharts]="highcharts"
      [options]="item.chartOptions"
    ></app-line-chart-tile>

    <app-circular-progress-bar-tile
      *ngIf="item.widgetType === 'pie'"
      [title]="item.widgetTitle"
      [color]="item.widgetColor"
      [highcharts]="highcharts"
      [options]="item.chartOptions"
    ></app-circular-progress-bar-tile>

    <app-progress-bar-tile
      *ngIf="item.widgetType === 'progress-bar'"
      [title]="item.widgetTitle"
      [color]="item.widgetColor"
      [images]="item.images"
      [minValue]="0"
      [maxValue]="10"
      [currentValue]="item.value"
    ></app-progress-bar-tile>

  </gridster-item>
</gridster>

**Comment by animesh84** [comment]
@tiberiuzuld did you checked my code or understood my problem?

**Comment by animesh84** [comment]
@tiberiuzuld did you get time to look into my issue?

**Comment by tiberiuzuld** [comment]
Hi @animesh84 
Checkout v10.1.7 I think fixes your issue also.

**Comment by animesh84** [comment]
Thanks for your reply, will check on latest version
