### ISSUE TITLE
Compatibility with Angular 11?

### ISSUE THREAD

**Issue by ddegasperi** [tiberiuzuld/angular-gridster2#697]
Is this library compatible with Angular 11?

**Comment by matusko89** [comment]
I am also interested when Angular 11 will be supported

**Comment by tiberiuzuld** [comment]
I will try to have it done this weekend.

**Comment by ddegasperi** [comment]
Thank you very much

**Comment by tiberiuzuld** [comment]
released v11.0.0 with angular v11
