### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by IvanBaskov** [tiberiuzuld/angular-gridster2#70]
![screenshot_20170705_122611](https://user-images.githubusercontent.com/10289070/27858240-2bd20b34-617d-11e7-8af3-b5e6400ad6b0.png)

If you enable "push items" option and you have many items, when you moving item you get this errors.

**Comment by tiberiuzuld** [comment]
Hi @IvanBaskov ,
Was not able to reproduce this issue. Added like 50 items and never got the error.

Let me know if you are able to reproduce it and how.

Thanks
