### ISSUE TITLE
Widgets resize on mobile view

### ISSUE THREAD

**Issue by dzhavat** [tiberiuzuld/angular-gridster2#71]
I have a grid that is `fixed` but when I go to mobile view, the widgets resize not only in width but in height as well making them look tiny. Aren't they supposed to preserve their height since I have a `fixed` grid?

Here's a gif that illustrates my point.

![problem](https://user-images.githubusercontent.com/1096332/27905705-1289f55a-6241-11e7-91db-e010e60d7b89.gif)

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,
The mobile view behaves like `verticalScroll` but puts the widgets one after the other.
If you want to keep the the fixed mode then lower the mobile breakpoint to 0.

**Comment by dzhavat** [comment]
The order is fine. I just want to keep the height the same since I'm using a `fixed` grid. 

Unfortunately it's not possible to set the mobile breakpoint to 0, since that wont put the widgets one after the other on mobile view.

In order to achieve what I want I edited the package itself by replacing this line:

`this.height = this.width / 2;`

with this one:

`this.height = this.$item.rows * this.gridster.$options.fixedRowHeight;` 

in [gridsterItem.component.ts#L72](https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridsterItem.component.ts#L72).

I'm aware that this should not be done because it will be overwritten once I update the package, but I need this fix urgently.

Wouldn't it be possible to add support for this natively?

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,
If you only need the height to be the same and the width to be the width of the parent. 
Then it is possible to add an option like `keepFixedHeightInMobile` : boolean default false.
And then the height will be taken how you calculated.
Is ok if I implement this weekend ? Do you need it faster than this ?

**Comment by dzhavat** [comment]
Yes, I need it by tomorrow. It will be awesome if you can add it. 

Well, if it's just adding the new option and changing that line above, I can also make a PR.

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,
Added the option in v3.3.0
Let me know if it works as expected.

Thanks,

**Comment by dzhavat** [comment]
Awesome! Thanks for your quick fix. I'm about to install this new version and try it.

One question though. Wouldn't it be better if you also check for `gridType`'s value in that `if`?

`if (this.gridster.$options.keepFixedHeightInMobile) {`

Right now it will work with any `gridType` as long as it has `keepFixedHeightInMobile: true`. Otherwise everything else should be working just fine.

**Comment by tiberiuzuld** [comment]
Hi @dzhavat ,
Yes I thought about that also. But maybe someone wants to use that on other `gridType`'s.

**Comment by dzhavat** [comment]
That's fine. Thanks again for your efforts.
