### ISSUE TITLE
TrackBy Demo not working

### ISSUE THREAD

**Issue by danwhite-ipc** [tiberiuzuld/angular-gridster2#716]
If you drag an item and then attempt to reset, the item does not move back to its original position unless you add another item. Currently this is affecting my implementation using trackby and dynamic items.

https://user-images.githubusercontent.com/40389335/107972258-7e0ffd80-6fab-11eb-85b4-6286331a8f2d.mp4

**Comment by tiberiuzuld** [comment]
Fixed in v11.1.2

**Comment by danwhite-ipc** [comment]
@tiberiuzuld great work!

**Comment by danwhite-ipc** [comment]
@tiberiuzuld only undesired behaviour the fix has caused is that now whenever you add a new item it always animates from position 0,0 to its required position

**Comment by danwhite-ipc** [comment]
A work around I have implemented atm the moment is to always insert a new item at `{x: -1, y: -1}` and then updated the fix to be

```
if (this.$item.x !== -1 || this.$item.y !== -1) {
     this.setSize();
}
```

**Comment by tiberiuzuld** [comment]
Hi @danwhite-ipc 
Will have a look later today to fix this side effect.

**Comment by tiberiuzuld** [comment]
ok made the fix to the side effect and also tested the original issue in 11.1.3
Please have a look at it and let me know.

Thanks

**Comment by danwhite-ipc** [comment]
@tiberiuzuld looks good to me, thanks for you work!
