### ISSUE TITLE
Landscape - Portrait

### ISSUE THREAD

**Issue by tobias-kruegel** [tiberiuzuld/angular-gridster2#719]
First of all, I would like to thank you very much for this great component!
But there seems to be a problem with adjusting the width of the grid.
If you switch from landscape to portrait mode on a tablet, the size of the grid is not adapted to the new screen width.
This occurs when the mobile breakpoint is smaller than the screen width and the grid does not switch to mobile view.
The problem is reproducible with the Gridster demo application on an iPad, both under Safari and Chrome.

Is there a way to work around this problem?
Thanks a lot !!!

**Comment by tiberiuzuld** [comment]
Hi @tobias-kruegel ,
You could listen to the event of landscape change and try to call the API to resize

**Comment by tobias-kruegel** [comment]
Thanks for the fast response! I will try this ;-)
Gridster is really great. Thanks for making it available to the community.

**Comment by tobias-kruegel** [comment]
Here is a solution that works for all Browsers (except IE, which does not support addEventListener on MediaQueryList):

```
const mediaQueryList: MediaQueryList = window.matchMedia('(orientation: portrait)');
mediaQueryList.addEventListener('change', (event: MediaQueryListEvent) => {
    setTimeout(() => this.options.api.resize(), 0);
});
```

There seems to be a timing problem (maybe caused by the implementation in combination with Angulars change detection lifecycle). The width for the grid seems to be calculated BEFORE the page is fully rendered. This results in a grid width that does not fit with the sceen width of the iOS device.
To prevent this, we now use the additional setTimeout(). This causes angular to run the resize() function of gridster in a later change detection cycle. And it works... ;-)
