### ISSUE TITLE
add new item as first item to display

### ISSUE THREAD

**Issue by jasonhue8183** [tiberiuzuld/angular-gridster2#72]
Hi,

May i know how add new item as first item to display, configured {x:0, y:0}, but console print message "Can't be placed in the bounds of the dashboard, trying to auto position!/n{"cols":2,"rows":1,"x":0,"y":0}"

Thanks.

**Comment by tiberiuzuld** [comment]
Hi @jasonhue8183 ,
Have a look over #26 .
It explains there how you can obtain that. The grid will not support that directly.
Let me know if you need any more help.

**Comment by jasonhue8183** [comment]
Hi @tiberiuzuld ,
very appreciate for the quick response. 
i modify the code as below for the existing addItem().
```
addItem() {
    this.dashboard.forEach(element => {
      if(element.x == 0){
        element.x +=1
      }
      this.options.api.optionsChanged();
    });
    
    this.dashboard.push({cols: 1, rows: 1, y: 0, x: 0,dragEnabled: true, resizeEnabled: true});
  }
```

it only work for first add, subsequent added item will be overlapped. any idea for it ?
appreciate for the reply.
