### ISSUE TITLE
Type of first argument of emptyCellDropCallback should be changed

### ISSUE THREAD

**Issue by JuPfu** [tiberiuzuld/angular-gridster2#722]
Hi Tiberiu,

it may be that the signature for 

`emptyCellDropCallback?: (event: MouseEvent, item: GridsterItem) => void;`

should be changed to 

`emptyCellDropCallback?: (event: DragEvent, item: GridsterItem) => void;`

Kind regards
Jürgen

**Comment by tiberiuzuld** [comment]
Hi @JuPfu ,
The type is fixed in v11.1.4

**Comment by JuPfu** [comment]
Hi Tiberiu,

thank you for your efforts!

Kind regards,

Jürgen
