### ISSUE TITLE
All items on each other after refreshing

### ISSUE THREAD

**Issue by ArinaWik** [tiberiuzuld/angular-gridster2#732]
Hey,

I am having an issue when I refresh the app all grid items are going to the same place. Several time refresh helps to have a normal view, but sometimes when I am refreshing the page the problem occurs again.
Below is my GridsterOption

```
  getGridsterOptions() {
    const options = {
      itemChangeCallback: AppComponent.itemChange,
      itemResizeCallback: AppComponent.itemResize,
      gridType: GridType.Fit,
      displayGrid: DisplayGrid.OnDragAndResize,
      mobileBreakpoint: 0,
      disableScrollHorizontal: true,
      disableScrollVertical: true
    };

    return options;
  }
```
**Below are two screenshots (with normal view) :** 
![image](https://user-images.githubusercontent.com/29709450/114170216-e12a6a80-9932-11eb-907d-c6a42087f624.png)

**Screenshot with issue:**  

![image](https://user-images.githubusercontent.com/29709450/114170287-fef7cf80-9932-11eb-8253-009a3fe990fd.png)

Any help or ideas will be appreciated.

Framework: Ionic + Capacitor

Thanks in advance.

**Comment by gtteamamxx** [comment]
Same problem after refreshing...

**Comment by ArinaWik** [comment]
yeah exactly...  and no solution... it's really annoying

**Comment by ArinaWik** [comment]
Do not load the dashboard(gridster-item) from ngOnInit. My problem was coming from that... Good luck!

**Comment by Tyler-V** [comment]
Old thread but so true for anyone else looking, you HAVE to initialize the GridsterConfig in the constructor

i.e.

```
    options: GridsterConfig;

    dashboard: Array<GridsterItem>;

    constructor() {
        this.options = {
            margin: 20,
            gridType: GridType.Fit,
            compactType: CompactType.None,
            maxCols: 10,
            maxRows: 10,
            pushItems: false,
            draggable: {
                enabled: true
            },
            resizable: {
                enabled: true
            },
            itemResizeCallback: (item) => {
                this.resizeEvent.emit(item);
            }
        };

        this.dashboard = [
            { cols: 6, rows: 10, y: 0, x: 0, type: 'check-in-list' },
            { cols: 4, rows: 6, y: 0, x: 5, type: 'projects-chart' },
            { cols: 4, rows: 4, y: 5, x: 5, type: 'location-chart' }
        ];
    }
```
