### ISSUE TITLE
last row item auto moved to next row if exceed max allowed col item for multiple added

### ISSUE THREAD

**Issue by jasonhue8183** [tiberiuzuld/angular-gridster2#74]
Hi @tiberiuzuld ,

may i know what is the correct configuration for every last item in every row auto drag to next row if exceed max col item ? 

every row allowed for 3 items, every col allowed for 4 items.

my current configuration as below 
`{maxCols: 3,maxRows: 4,maxItemRows: 4,maxItemCols: 3}`

my addItem function as below : 
```
addItem() {
    this.dashboard.forEach(element => {
      element.x +=1;
      this.options.api.optionsChanged();
    });
    
    this.dashboard.push({cols: 1, rows: 1, y: 0, x: 0,dragEnabled: true, resizeEnabled: true});
  }
```

above behavior will push all row item to the right even exceed my max col setting for multiple added item. 
how to determine the item is actually the first row item ? and the last row item drag to next row if new item added ( assumed exceed configuration max allow col item).

**Comment by tiberiuzuld** [comment]
Hi @jasonhue8183 ,

If I understand correctly you want that when you add a new item all items move to right and to the next row when they reach end of cols.

You can check a item position and right side length with:
`element.x + element.cols < this.options.maxCols`

Keep in mind that the items in array may not be in the order of 'y, x'.

So to achieve the desired effect this may work:
```javascript
if(element.x + element.cols < this.options.maxCols){
 element.x +=1;
} else {
 element.x = 0;
 element.y +=1;
}
```
I am not sure this will cover all edge cases but you can start from there and test things out.
Let me know if I answered your question.

Thanks,

**Comment by jasonhue8183** [comment]
Thank you for the guide ! working perfect now  :)
