### ISSUE TITLE
Building a library using angular-gridster2@12.0.2 with Angular12 fails

### ISSUE THREAD

**Issue by slavede** [tiberiuzuld/angular-gridster2#741]
If I'm trying to build a library using angular-gridster2@12.0.2 it fails without much explanation:

× Compiling TypeScript sources through NGC
ERROR: Maximum call stack size exceeded
An unhandled exception occurred: Maximum call stack size exceeded

When I downgrade angular-gridster to 11.2.0 it works fine.

**Comment by tiberiuzuld** [comment]
Hi @slavede ,
Seems like an angular issue.
I updated angular and made a new build in 12.0.1
Please try the new version and let me know if the issue persists.
Angular changed how the libraries are built in v12 , probably similar issue with #740

**Comment by slavede** [comment]
Unfortunatelly, still fails....with the same error

[error] RangeError: Maximum call stack size exceeded
    at parseUnionTypeOrHigher (<path>\node_modules\typescript\lib\typescript.js:31416:20)
    at parseTypeWorker (<path>\node_modules\typescript\lib\typescript.js:31512:24)
    at doOutsideOfContext (<path>\node_modules\typescript\lib\typescript.js:29324:30)
    at parseType (<path>\node_modules\typescript\lib\typescript.js:31505:20)
    at parseTypeOrTypePredicate (<path>\node_modules\typescript\lib\typescript.js:31480:24)
    at parseReturnType (<path>\node_modules\typescript\lib\typescript.js:30784:24)
    at parseMethodDeclaration (<path>\node_modules\typescript\lib\typescript.js:33805:24)
    at parsePropertyOrMethodDeclaration (<path>\node_modules\typescript\lib\typescript.js:33827:24)
    at parseClassElement (<path>\node_modules\typescript\lib\typescript.js:34015:28)
    at parseListElement (<path>\node_modules\typescript\lib\typescript.js:30054:20)

**Comment by tiberiuzuld** [comment]
I have no idea why is not working for you.
Do you have typescript 4.2.x ?
Do you use ng-packar ?

**Comment by slavede** [comment]
Yes to both

"typescript": "4.2.4",
"ng-packagr": "12.0.2",
"angular-gridster2":"12.0.1"

And build defined in angular.json:

{
      "projectType": "library",
      "root": "",
      "sourceRoot": "src",
      "prefix": "lib",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:ng-packagr",
          "options": {
            "tsConfig": "tsconfig.app.json",
            "project": "ng-package.json"
          },
          "configurations": {
            "production": {
              "tsConfig": "tsconfig.lib.prod.json"
            }
          }
        }
      }
    }

Again when I downgrade version, it builds correctly...

**Comment by liesahead** [comment]
Works fine here with angular `12.0.3`.

**Comment by slavede** [comment]
@liesahead How do you have your lib build set up?

**Comment by liesahead** [comment]
@slavede , my bad, I missed the `building library` part. We're just started using `angular-gridster2` in the usual application.

**Comment by slavede** [comment]
Right....so yeah, the regular app works for me as well, but the library, it doesn't :/

**Comment by slavede** [comment]
Just to keep this up to date. Tried it with latest angular release 12.1.0, still the same issue...

**Comment by tiberiuzuld** [comment]
hey guys,
made a new release 12.1.0 with changed configuration for angular build of the library.
on short, I just added back the config which was before the release of angular 12.
Let me know if it works for you.

**Comment by slavede** [comment]
I did not help unfortunately....

× Compiling TypeScript sources through NGC
ERROR: Maximum call stack size exceeded
Maximum call stack size exceeded

**Comment by slavede** [comment]
I have looked into your dependencies and it seems gridster is using non valid typescript version for Angular 12...

From https://angular.io/guide/updating-to-version-12

`The supported range of TypeScript versions is 4.2.3 to 4.2.x`

It doesn't have to fix this, but it may...

**Comment by slavede** [comment]
Also, what I've noticed is compilationMode, it seems it's because of and that angular-gridster2 requires

  "angularCompilerOptions": {
    "compilationMode": "partial"
  }


I had this

**Comment by ursmeili** [comment]
> 
> 
> I have looked into your dependencies and it seems gridster is using non valid typescript version for Angular 12...
> 
> From https://angular.io/guide/updating-to-version-12
> 
> `The supported range of TypeScript versions is 4.2.3 to 4.2.x`
> 
> It doesn't have to fix this, but it may...

The upgrade guide is wrong. Actually Angular 12.1 supports typescript Version 4.3.x also.

**Comment by slavede** [comment]
@tiberiuzuld So I found why gridster12 stopped working as it did. The thing is that I had to start using partial compilation mode for lib build as well...then it was built correctly. I believe we can close the ticket, and maybe you could consider putting that somewhere in changelog/readme...

Thanks for the effort!
