### ISSUE TITLE
Adding new tile gets added at the wrong place (outside of grid)

### ISSUE THREAD

**Issue by jsthivierge** [tiberiuzuld/angular-gridster2#75]
Hi,

As you can see on the gif below, I have a grid of 8 rows / 12 cols. I already have 2 widgets on it (2 rows / 3 cols and beside it a 6 rows / 6 cols). I'm adding a (4 rows / 6 cols) tile and it gets added underneath my tiles (outside of grid) instead of beside them.

![gridsterissue](https://user-images.githubusercontent.com/5862851/27970167-c7c42b54-631b-11e7-91f6-ffdda7f0cca0.gif)

Thanks for your support
Jean-Sebastien

**Comment by tiberiuzuld** [comment]
Hi @jsthivierge ,

In your example the 3rd item will be outside of grid limits.
Yes there was a bug that allowed items to be added outside of grid limits.

Fixed in v3.3.1

Let me know if you find any more issues.

Thanks,

**Comment by jsthivierge** [comment]
Perfect, thanks !
