### ISSUE TITLE
Can't save the layout of Gridster

### ISSUE THREAD

**Issue by Ghonimy** [tiberiuzuld/angular-gridster2#762]
I'm trying to save the location of the layout after arranging the widgets in a specific order but when I reload I lose order, the items stays the same but the order is messed up, I have tried everything like itemChangeCallback to get the x and y coordinates, but I need a way to be able to save the layout style when the user arrange widgets as he likes

**Comment by gitalvininfo** [comment]
@Ghonimy you need to save it somewhere like a database or localstorage in order for you to access the saved positions of grids.

**Comment by Ghonimy** [comment]
@gitalvininfo  Thank you. I saved it on local storage using ngOnInit to save the entire object and luckily it worked.

**Comment by EnricoVogt** [comment]
@tiberiuzuld I think this issue can be closed.
