### ISSUE TITLE
Unable to drag add on mobile

### ISSUE THREAD

**Issue by Blunderchips** [tiberiuzuld/angular-gridster2#767]
Item creation works but not drag to add. However, I am able to click add. I have try at your [demo](https://tiberiuzuld.github.io/angular-gridster2/angular/), just to make sure that is not my configuration, and is working in the same way.

I suspect it is similar to this issue: https://github.com/tiberiuzuld/angular-gridster2/issues/169

Looking at that ticket, these.boxes are ticked. 

![Screenshot_20210910-204944_Chrome](https://user-images.githubusercontent.com/7081037/132903032-8f8bee36-df42-43de-be22-d646a02baed3.jpg)

I'm able to reproduce this on my phone (Android device using Google Chrome) and on my desktop when I enable touch simulation.

**Comment by paulstelzer** [comment]
I have created a PR (#782). Hopefully it will be merged soon :)

**Comment by Blunderchips** [comment]
Just tested out and all is working great!
