### ISSUE TITLE
how to shrink gridster width

### ISSUE THREAD

**Issue by jasonhue8183** [tiberiuzuld/angular-gridster2#77]
Hi,
1 ) May i know how to shrink the gridster width ? i got right panel able to expand and shrink, i expect the gridster able to shrink if right panel expanded. 

2 ) anyway to change the background color ?

Thanks.
Jason

**Comment by tiberiuzuld** [comment]
Hi @jasonhue8183 
1) call this.options.api.resize();  after you opened the sidebar.
2) override the css to change any style

**Comment by jasonhue8183** [comment]
Hi @tiberiuzuld 

I hit this.options.api is undefined when call it.

**Comment by tiberiuzuld** [comment]
Hi @jasonhue8183 ,
The `this.options.api` is set on initialization.
 If is undefined then you don't need to call it yet.

**Comment by jasonhue8183** [comment]
Hi @tiberiuzuld ,

![shrink gridster](https://user-images.githubusercontent.com/8756745/28042456-e6b00d44-65ff-11e7-8666-1baf6c0e55a6.png)

below is the this.options.api.resize() call in ngOnChanges method
```
if(changes['isEditorVisible'] && this.options){
      console.info('editor toggle');
      this.options.api.resize(); 
   }
```
after toggle , resize() still not working. 
![after-toggle](https://user-images.githubusercontent.com/8756745/28042617-aaabb4f0-6600-11e7-904d-562a359c9c3c.png)

**Comment by tiberiuzuld** [comment]
Hi @jasonhue8183 ,
Do you have css transition on the sidebar ? If yes the you need to call resize `ontransitionend` event.
