### ISSUE TITLE
change gridster-item background-color when active

### ISSUE THREAD

**Issue by saidAdservio** [tiberiuzuld/angular-gridster2#775]
Hi, how can l change the background color of the area behind the widget when the widget is dragged
![Capture](https://user-images.githubusercontent.com/89802776/143250460-a7fb44ad-ebda-4598-89bf-584b91f1ffa8.PNG)

**Comment by saidAdservio** [comment]
this fixed the problem for me: 
`:host gridster /deep/ gridster-preview {
  background: white;
}`

**Comment by fjh352** [comment]
@saidAdservio directly to use it in css file?
