### ISSUE TITLE
how to call EventEmitter from static itemChange function

### ISSUE THREAD

**Issue by jasonhue8183** [tiberiuzuld/angular-gridster2#78]
Hi,

`itemChangeCallback: AppComponent.itemChange`

expecting static function itemChange but i not able to call EventEmitter from static function. 
Any workaround ?

Thanks.
Jason

**Comment by tiberiuzuld** [comment]
Hi @jasonhue8183 ,
Don't make your method static then.

**Comment by jasonhue8183** [comment]
hi @tiberiuzuld ,

if my itemChange function as below :  

```
itemChange(item, scope) {
      console.info('itemChanged', item, scope);
      this.emitUpdateGrid.emit(item);
   }
```

`itemChangeCallback: this.itemChange`

I having "this.emitUpdateGrid is undefined" error. 
Thanks.

**Comment by jasonhue8183** [comment]
i found the bug on my side, thank you very much for the support

**Comment by jasonhue8183** [comment]
Hi @tiberiuzuld ,

the itemChange call back function called but never trigger emitter.

```
itemChange(item, scope) {
      console.info('before emit');
      if(this.emitEditGrid){
          console.info('emitting');
          this.emitEditGrid.emit(item);
        }
   }
```

`@Output() emitEditGrid: EventEmitter<any> = new EventEmitter();`

I tested the emitter working in ngOnChanges 

```
if(changes['isEditorVisible'] && this.options){
      this.emitEditGrid.emit("test emit in editor toggle");
      console.info('editor toggle');
      this.options.api.resize(); 
   }
```

my ngOnInit methode as below :  

```
ngOnInit() {

      this.options = {
        gridType: 'fixed',
        compactType: 'none',
        itemChangeCallback: this.itemChange,
        itemResizeCallback: this.itemResize,
        margin: 10,
        outerMargin: true,
        ...
}
```

**Comment by tiberiuzuld** [comment]
Hi @jasonhue8183 ,

The event emitters from `gridsterItem` don't work or your event emitter is not working ? 
Don't understand what is not working.

**Comment by jasonhue8183** [comment]
Hi @tiberiuzuld 

the event emmitter not working in itemChangeCallback function

**Comment by jasonhue8183** [comment]
the emitter not working in itemChangeCallback but working in other function

**Comment by tiberiuzuld** [comment]
Hi @jasonhue8183 ,
In your code `this` is the `gridsterController`
```typescript
itemChange(item, scope) {
      console.info('before emit');
      if(this.emitEditGrid){
          console.info('emitting');
          this.emitEditGrid.emit(item);
        }
   }
```

try 
```typescript
const vm = this;
itemChange(item, scope) {
      console.info('before emit');
      if(vm .emitEditGrid){
          console.info('emitting');
          vm .emitEditGrid.emit(item);
        }
   }
```

**Comment by jasonhue8183** [comment]
thanks. it working now :)
