### ISSUE TITLE
How to get all item scope value ?

### ISSUE THREAD

**Issue by jasonhue8183** [tiberiuzuld/angular-gridster2#79]
-

**Comment by tiberiuzuld** [comment]
Hi @jasonhue8183 ,

Angular 2-4 doesn't have `$scope`.

You have the `item`'s from `*ngFor`  how do you bind them and use them is a angular 2 question.

Please be more specific in your questions. And if is not a library issue/question then google it.

Thanks,

**Comment by jasonhue8183** [comment]
Hi @tiberiuzuld ,

sorry for misleading, i actually mean all the gridster dom element.

**Comment by tiberiuzuld** [comment]
Hi @jasonhue8183 ,

How to get a DOM element: `document.querySelector('gridster')`
https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector
If you want the element from a parent component of gridster.

How do you get a DOM element in angular. 
https://stackoverflow.com/questions/32693061/angular-2-typescript-get-hold-of-an-element-in-the-template
If you do that in a child component inside the widget, you can go to it with the parent reference.

All of them is the first result in google.

**Comment by jasonhue8183** [comment]
sorry to disturb you
