### ISSUE TITLE
Relative column width

### ISSUE THREAD

**Issue by Rugy2000** [tiberiuzuld/angular-gridster2#81]
Hello,

First of all, thanks for the awesome component!

The problem I have is that I want the columns to share the 100% of the width space but to have a fixed height for each row, so the GridsterItem won't need to be allways squared.
Is there a way to achive that whitout having to change to 'fixed' position and recalculate the width of each column in every window resize?

**Comment by tiberiuzuld** [comment]
Hi @Rugy2000 ,

So you want a mix between `gridType:` `verticalScroll` and `fixed`. 

Currently that is not possible. 

It needs a new `gridType`: `verticalFixed` or something like that. 
That needs to apply the `fixedHeight` option and calculate the width depending on `gridster` width and number of columns.

Maybe I will implement it over the weekend.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @Rugy2000 ,
Made the option `gridType`: `verticalFixed` and `horizontalFixed` in v3.5.0.

Thanks,

**Comment by Rugy2000** [comment]
Thanks for the new feature!

**Comment by Rugy2000** [comment]
Hello again,

I've just tried the new version of the gridster and i can't find out how to solve the error is showing me:

src/app/cardgrid/card-grid.component.ts(36,9): error TS2322: Type '{ gridType: "verticalFixed"; compactType: "none"; itemChangeCallback: (item: any, scope: any) => ...' is no
t assignable to type 'GridsterConfig'.
  Types of property 'gridType' are incompatible.
    Type '"verticalFixed"' is not assignable to type 'GridType'.
src/app/cardgrid/card-grid.component.ts(82,9): error TS2322: Type '"verticalFixed"' is not assignable to type 'GridType'.

Isn't gridType a simple string? Am I missing something? Cause if I put any of the originals gridTypes it works perfectly.

Thanks!

**Comment by tiberiuzuld** [comment]
Hi @Rugy2000 ,
The code [here](https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridsterConfig.interface.ts) has the correct type accepting `verticalFixed` 
In earlier version it didn't had that type available. The error seems to indicate that problem.
Check in `node_modules` what version you have.
If you use npm v5.0.x update to v5.3.0.
 First versions of npm 5.x where having a small issue to update a package. To overcome the issue you also can delete `package-lock.json` and do `npm install` again.

Let me know if any of the options above worked.
Thanks,

**Comment by Rugy2000** [comment]
Hi,

Thanks for the fast answer.

I have npm version up to 5.3.0 and the code file in node_modules is exactly the one you linked me. 
But still got the error.. maybe you are missing some other validator function?

Thanks

**Comment by Rugy2000** [comment]
Hello again!

I've found the mistake, I was using a copy of your previous gridsterConfig.interface.ts instead the new updated in node_modules package. 

Thanks for everything!
