### ISSUE TITLE
error TS2341: Property 'resize' is private and only accessible within class 'GridsterComponent'

### ISSUE THREAD

**Issue by ciukstar** [tiberiuzuld/angular-gridster2#819]
After updating from `angular-gridster2 @ "13.2.1"` to `angular-gridster2 @ "14.0.1"`, I am getting the error "_Property 'resize' is private and only accessible within class 'GridsterComponent'_"

This is a bug or a change in the API?
Thanks!

Env:
```
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.0
Node: 14.17.0
Package Manager: npm 7.20.5 
OS: linux x64

Angular: 14.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@angular/flex-layout            13.0.0-beta.38
@schematics/angular             14.0.0
rxjs                            7.5.5
typescript                      4.7.3
```

**Comment by tiberiuzuld** [comment]
Hi @ciukstar ,
I am not able to reproduce the error.
`GridsterComponent` doesn't have `resize` property.

**Comment by ciukstar** [comment]
There was a method `resize()` in `angular-gridster2 @ "13.2.1"` as below:

`$ more node_modules/angular-gridster2/lib/gridster.component.d.ts`
```
....
import { GridsterRenderer } from './gridsterRenderer.service';
import * as i0 from "@angular/core";
export declare class GridsterComponent implements OnInit, OnChanges, OnDestroy, GridsterComponentInterface {
    renderer: Renderer2;
    cdRef: ChangeDetectorRef;
    zone: NgZone;
   ....
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    resize(): void;
    setOptions(): void;
    optionsChanged(): void;
    ....
}
```
Now, in version `angular-gridster2 @ "14.0.1"`, it looks like below:
`$ more node_modules/angular-gridster2/lib/gridster.component.d.ts`
```
....
import * as i0 from "@angular/core";
export declare class GridsterComponent implements OnInit, OnChanges, OnDestroy, GridsterComponentInterface {
    renderer: Renderer2;
    ....
    previewStyle$: EventEmitter<GridsterItem | null>;
    calculateLayout$: Subject<void>;
    private resize$;
    private destroy$;
    constructor(el: ElementRef, renderer: Renderer2, cdRef: ChangeDetectorRef, zone: NgZone);
    ....
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    private resize;
    setOptions(): void;
    optionsChanged: () => void;
    ngOnDestroy(): void;
    onResize: () => void;
    ....
}
```

My application uses "GridsterComponent" with a toggleable material "Sidenav" component and it was able to call resize() on gridster component when sidenav toggle event happened.
Now, in version `angular-gridster2 @ "14.0.1"`, it doesn't compile, and without a call to resize() , the grid doesn't resize when hiding or showing the sidenav. 
Thanks.

**Comment by tiberiuzuld** [comment]
oh ok,

But you should call the `gridsterOptions.api.resize()` when that is the case:
https://tiberiuzuld.github.io/angular-gridster2/api
https://github.com/tiberiuzuld/angular-gridster2/blob/master/projects/angular-gridster2/src/lib/gridster.component.ts#L152

Let me know if this option works for you.

**Comment by ciukstar** [comment]
> oh ok,
> 
> But you should call the `gridsterOptions.api.resize()` when that is the case: https://tiberiuzuld.github.io/angular-gridster2/api https://github.com/tiberiuzuld/angular-gridster2/blob/master/projects/angular-gridster2/src/lib/gridster.component.ts#L152
> 
> Let me know if this option works for you.

Indeed, it compiles and runs when calling
`this.grid.options.api.resize() on @ViewChild('grid') grid: GridsterComponent;`

instead of
`this.grid.resize() on @ViewChild('grid') grid: GridsterComponent;`

Thank you.
