### ISSUE TITLE
Disable swap/push for individual GridsterItem tiles

### ISSUE THREAD

**Issue by jsthivierge** [tiberiuzuld/angular-gridster2#82]
Hi,

I was wondering if it could be possible to disable swap/push for individual gridster tiles. I would like my tile to be not movable (locked on grid), but currently other tiles are able to push or swap my locked tile. 

![gridsteritemlock](https://user-images.githubusercontent.com/5862851/28228956-b38d33ea-68ae-11e7-9075-599eaa186be9.gif)

I would like my tile "Drag&Resize Disabled" to remain where it stands instead of being swapped around.

Thanks !
JS

**Comment by tiberiuzuld** [comment]
Hi @jsthivierge ,
Yes current option to disableDrag of an item should also stop other items to move it.

Will see what I can do to make it work.

**Comment by tiberiuzuld** [comment]
Hi @jsthivierge ,
Made the improvements in v3.5.0.

Thanks,

**Comment by jsthivierge** [comment]
Thanks a lot!
