### ISSUE TITLE
Ng build errors after updating to version 13.3.0 or 14.0.1

### ISSUE THREAD

**Issue by csjasonwong** [tiberiuzuld/angular-gridster2#820]
Dear Sir,

I am using Angular 13/14 and angular-gridster2 13.2.1 works fine on them. However, after updating angular-gridster2 to 13.3.0 in Angular 13/14 or updating angular-gridster2 to 14.0.1 in Angular 14. I got these errors when doing ng build. Is there something I am missing? Please help. It would be much appreciated. 

./node_modules/angular-gridster2/fesm2020/angular-gridster2.mjs:1248:31-43 - Error: export 'debounceTime' (imported as 'debounceTime') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, 
BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, 
range, scheduled, throwError, timer, using, zip)

./node_modules/angular-gridster2/fesm2020/angular-gridster2.mjs:1248:48-57 - Error: export 'takeUntil' (imported as 'takeUntil') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

./node_modules/angular-gridster2/fesm2020/angular-gridster2.mjs:1251:4-13 - Error: export 'switchMap' (imported as 'switchMap') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, 
scheduled, throwError, timer, using, zip)

./node_modules/angular-gridster2/fesm2020/angular-gridster2.mjs:1251:33-42 - Error: export 'takeUntil' (imported as 'takeUntil') was not found in 'rxjs' (possible exports: ArgumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsubscribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animationFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin, from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, queue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)

**Comment by dogukan10** [comment]
Hi,
I encountered the same problem while upgrading angular-gridster2 to 13.3.0 from 13.2.0 in my Angular 13 project.
Upgrading rxjs from 6.6.7 to 7.5.5 in my project solved the problem.

**Comment by symonfly82** [comment]
Same problem for me. I'll try to upgrade rxjs to 7.5.5...hoping not to break other packages X-)

**Comment by csjasonwong** [comment]
Thanks, I was thinking upgrading rxjs to 7.5.5 could be the solution. I did try to rxjs to 7.5.5 but it did break TOSWebApiServiceClient.Generated.ts generated from swagger and .next() in rxjs now requires an argument. Anyway, it is something I need to look into upgrading rxjs, so it is still a good news to know that upgrading rxjs will solve the angular-gridster2 upgrade issue. Thank you so much for your answer! Much appreciated!

**Comment by titobf** [comment]
I confirm that upgrading rxjs to version 7 solves the problem. About Nswag, you need to set "rxJsVersion": 7.0. And about next(), you need to use Subject<void>. Then it's mostly fixing the imports.

**Comment by tiberiuzuld** [comment]
Done in v14.1.2
