### ISSUE TITLE
Option to disable auto-resize?

### ISSUE THREAD

**Issue by jasonhendee** [tiberiuzuld/angular-gridster2#83]
Thanks for this awesome library! After experimenting with several Angular grids, this is the best one I've come across yet.

I wondered if you might consider adding an option to completely disable the grid's hook into the window resize event. I have an application where I'm already performing several operations upon window resize, and noticed that you've provided a gridsterOptions.api.resize() call, to explicitly resize the grid when I'm ready to do so; I would rather the grid not try to auto-resize on its own if possible.

**Comment by tiberiuzuld** [comment]
Hi @jasonhendee ,

I will add an option to disable window resize event.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @jasonhendee ,
Released the new option in v3.5.0

Thanks,

**Comment by jasonhendee** [comment]
Thank you! Amazing turnaround time for feature requests btw!
