### ISSUE TITLE
List RxJS as peer dependency

### ISSUE THREAD

**Issue by HanMoeHtet** [tiberiuzuld/angular-gridster2#839]
Following [#835](https://github.com/tiberiuzuld/angular-gridster2/issues/835) and [#820](https://github.com/tiberiuzuld/angular-gridster2/issues/820) and checking the build, seems that RxJS is intenally used. Please list it in the peer dependencies to avoid versions mismatch.

**Comment by tiberiuzuld** [comment]
Done in v14.1.2
