### ISSUE TITLE
Placing gridster as a component

### ISSUE THREAD

**Issue by EnumC** [tiberiuzuld/angular-gridster2#84]
Hello! I'm encountering a very strange issue on an app. The demo itself work fine, but when I attempt to use the basic code as a separate component in my single-page app, the dashboard stops showing. The module is correctly loaded evident by the debug messages in the console, but nothing is showing up, and as you can see, the demo code's adjustment settings are also incorrectly formatted. 
![screen shot 2017-07-15 at 3 07 21 pm](https://user-images.githubusercontent.com/5799869/28237592-7130ae92-6975-11e7-9680-edfadc0abc37.png)

This might be due to the same issue as documented in #45. Do you have any clue on why this might be occurring? Thanks for your help!

**Comment by tiberiuzuld** [comment]
Hi @EnumC ,
Short answer: yes.
Long answer: the gridster will take all the available space from the parent. It will not size depending on content.
The parent of the component needs to have a size.
From the demo you miss the demo styles.

**Comment by EnumC** [comment]
Thanks for pointing that out. You should consider putting that in readme :). I was under the impression that it will scale automatically, so in this case, any div tags without height/width will cause it to not display at all.

**Comment by tiberiuzuld** [comment]
Will do.
Thanks,

**Comment by tiberiuzuld** [comment]
Added [here](https://github.com/tiberiuzuld/angular-gridster2#note-the-gridster-will-take-all-the-available-space-from-the-parent-it-will-not-size-depending-on-content-the-parent-of-the-component-needs-to-have-a-size)

**Comment by EnumC** [comment]
Nice 👍
