### ISSUE TITLE
initCallback provide undefined item

### ISSUE THREAD

**Issue by khaled-ansary** [tiberiuzuld/angular-gridster2#86]
Hi @tiberiuzuld,

I tried to initialize using  initCallback where I set a function like
   ```
 itemInit(item) {
        console.info('itemInitialized', item);
 }
```
but getting `undefined` message.  I am getting item value for other callbacks (i.e. `itemChangeCallback`, `itemResizeCallback`,  `draggable.stop`,  `resizable.stop ` and saved my widget  `cols, rows, x, y`   in json format using drag and resize. Now I would like to initialize using` itemInit ` function when page again reload. Could you please see why I am getting `undefined` item? Thanks.

**Comment by tiberiuzuld** [comment]
Hi @khaled-ansary ,
Will investigate today.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @khaled-ansary ,
Was not able to reproduce the issue on the demo. The init callback is called with `GridsterItemComponent`
The argument received is not exactly as resize and drag but is present and includes the `GridsterItem`.

![image](https://user-images.githubusercontent.com/15310395/28432451-9b8d5018-6d90-11e7-9593-29d34805080c.png)

**Comment by khaled-ansary** [comment]
Hi @tiberiuzuld,

It works when I set `initCallback` function for `GridsterItem `  for example, 
` {cols: 1, rows: 1, y: 0, x: 6, initCallback: AppComponent.itemInit}`

But its not working when I set it for `GridsterConfigService`  for example,

```
this.options = {
       gridType: 'fit',
       compactUp: false,
       compactLeft: false,
       itemChangeCallback: AppComponent.itemChange,
       itemResizeCallback: AppComponent.itemResize,
       **initCallback: AppComponent.itemInit**
       margin: 10,
       outerMargin: true,
       maxItemCols: 50,
       minItemCols: 1,
       maxItemRows: 50,
       minItemRows: 1,
       defaultItemCols: 1,
       defaultItemRows: 1,
       fixedColWidth: 250,
       fixedRowHeight: 250,
       draggable: {
         enabled: true,
         stop: AppComponent.eventStop
       },
       resizable: {
         enabled: true,
         stop: AppComponent.eventStop
       },
       swap: false
     };

```
I would like set `initCallback` using `options`  . Thanks

**Comment by tiberiuzuld** [comment]
Hi @khaled-ansary ,
The one in `GridsterConfigService` is for the grid init not item init.

I could add an itemInit callback in the `GridsterConfigService`.

Maybe this weekend.

**Comment by khaled-ansary** [comment]
Thank you  :)

**Comment by tiberiuzuld** [comment]
Hi @khaled-ansary ,
Added in v3.6.0.

Thanks,
