### ISSUE TITLE
Item returned from events missing id

### ISSUE THREAD

**Issue by Rugy2000** [tiberiuzuld/angular-gridster2#88]
Hi again,

I'm filling your gridster with items and my idea is to save the changes that the user makes. 
I'm having problems because the item i'm introducing to your gridster has an id propertie called "position" but in the resize and dragging events I just got the item retuned with propierties "cols, rows, x, y". No trace of "position" attribute so I'm losing the reference of the item being modified.

Is there another way to update the item's position data cause gridster doesn't seem to have automatic binding.

Thanks!

**Comment by tiberiuzuld** [comment]
Hi @Rugy2000 ,
The callback is called with the same object [here](https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridsterItem.component.ts#L113)

In previous versions that was the case maybe. 
Please update to latest version.

Thanks,

**Comment by Rugy2000** [comment]
It worked with the version update.

Thanks!

**Comment by tiberiuzuld** [comment]
👍
