### ISSUE TITLE
angular v17 has been released

### ISSUE THREAD

**Issue by HCenggel** [tiberiuzuld/angular-gridster2#896]
Waiting for update...

**Comment by tiberiuzuld** [comment]
Hello,
Sorry for the delay.
Had a busy weekend...
Will do the update this week.

**Comment by HCenggel** [comment]
> Hello, Sorry for the delay. Had a busy weekend... Will do the update this week.

Hooray! Can't wait!

**Comment by MPruntel** [comment]
Made changes to support Angular 17 #898

**Comment by HCenggel** [comment]
> Made changes to support Angular 17 #898

Like you

**Comment by tiberiuzuld** [comment]
v17 is published.

**Comment by HCenggel** [comment]
> v17 is published.

coooooool
