### ISSUE TITLE
mobileBreakpoint doesn't work

### ISSUE THREAD

**Issue by nghiado** [tiberiuzuld/angular-gridster2#9]
Try to resize the browser to mobile size on this demo https://tiberiuzuld.github.io/angular-gridster2/angular/
The grid is not stacked as expected, all tiles are showing at the same position
![screen shot 2017-03-23 at 3 28 47 pm](https://cloud.githubusercontent.com/assets/1259031/24268952/80d59570-0fdd-11e7-88e8-232dcf14eee6.png)

**Comment by tiberiuzuld** [comment]
fixed in v2.0.7

**Comment by nghiado** [comment]
thank you very much for your quick fix @tiberiuzuld.
