### ISSUE TITLE
Mouse events disabled on the right side of the grid

### ISSUE THREAD

**Issue by HoplaGeiss** [tiberiuzuld/angular-gridster2#90]
Hello - awesome work with this library.

I just have a little issue with mouse events when my mouse is on the right side of the grid. ( I would say a 200px area on the right side of the grid).
I can't drag / resize elements when my mouse is there. Actually, I can't even scroll when my mouse is in this area. Any idea of what this could be?

**Comment by tiberiuzuld** [comment]
Hi @HoplaGeiss ,
Thank you!

I just tested on demo page and works for me.
Maybe you have some element on top there. At least what you say seems to indicate that.
Try do a inspect with the select tool from dev tools.

Let me know if it works/find out why.

**Comment by HoplaGeiss** [comment]
You are right.. Had a hidden element on top of the grid! Can't believe I missed that. Thanks!
