### ISSUE TITLE
Styling grid-item

### ISSUE THREAD

**Issue by mcrodriguezb** [tiberiuzuld/angular-gridster2#906]
Hi,
I'm trying to apply a box to the grid item element, but I just got the left and top as shown in the image. Any reason for that?
![image](https://github.com/tiberiuzuld/angular-gridster2/assets/149514755/2866f722-8a4f-4886-bba3-7ffdd4af2a0a)

My component code is: 
```
<div style="height: 100%; width: 100%;display: flex;flex-direction: column;border-radius: 15px;border: 1px solid #E7E8F2;background: #FFF;">
<div style="display: flex;height: 45px;flex-shrink: 0;border-bottom: 1px solid #E7E8F2;align-items: center;padding-left: 20px;">
  Widget A
</div>
<div>
  test widget
</div>
</div>
```

**Comment by HCenggel** [comment]
It seems that this is not a problem with angular-gridster2
