### ISSUE TITLE
Dragging gridster-item pushes untouched adjacent gridster-item

### ISSUE THREAD

**Issue by FrozenGenis** [tiberiuzuld/angular-gridster2#91]
1. Open demo
2. Tick 'Push Items'
3. Drag the first gridster-item (top left) from row 1 to row 3 then back to row 1.
4. Gridster-item with label 'Some content to select and click without dragging the widget' gets pushed

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,
Yes was able to reproduce.
Will try to fix it this week.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @FrozenGenis ,

Fixed in v3.7.0

Thanks
