### ISSUE TITLE
v18 - Warning NG0955 - Track expression resulted in duplicated keys

### ISSUE THREAD

**Issue by MichaelCPGordon** [tiberiuzuld/angular-gridster2#914]
Since upgrading to v18 I keep getting a warning from Angular printed to the console anywhere that I'm using angular-gridster2.
https://angular.dev/errors/NG0955

From what I can determine, this seems to be a result of `gridColumns` and `gridRows` being declared in `gridster.component.ts` as arrays with non-unique values. 

I'm expecting that in `gridster.html` updating the `@for` loops to track $index instead of the array values should resolve this?

**Comment by tiberiuzuld** [comment]
Hello @MichaelCPGordon ,
Issue is fixed in v18.0.1

Thank you for the report.
