### ISSUE TITLE
Question: Create item while dragging in empty cell.

### ISSUE THREAD

**Issue by leandroz** [tiberiuzuld/angular-gridster2#92]
Hi @tiberiuzuld , first of all, thanks for this awesome library!

My question is if is it possible to listen for drag or click events over empty cells, the idea is to let the user create an event by selecting empty cells. Is there a way to accomplish it with the current functionality?

Thanks!

**Comment by tiberiuzuld** [comment]
Hi @leandroz ,
Thanks!

Yes it is possible for drag/click events to call a callback from options, with the event and position in grid.

This will accomplish what you need ?

**Comment by leandroz** [comment]
Hi @tiberiuzuld, thanks for the quick reply.

Yes definitely, I will be able to create the new item from there.

**Comment by tiberiuzuld** [comment]
Hi @leandroz ,
Ok, will try to add the feature this weekend.

Thanks

**Comment by leandroz** [comment]
Cool awesome @tiberiuzuld , I will be using the component a lot so hopefully I will get more familiar with it to help :)

**Comment by tiberiuzuld** [comment]
Hi @leandroz ,

Added in v3.7.0

Thanks

**Comment by leandroz** [comment]
Thanks for the quick implementation @tiberiuzuld !

I found a bug, is easy to replicate in the demo page. If you start dragging an item over a cell and drop it in less than the middle of it, the click handler will be called for that cell, adding a new item:

![bug-click-handler](https://user-images.githubusercontent.com/4624850/28748510-21134638-7490-11e7-92c0-47d88bdec69a.gif)

**Comment by leandroz** [comment]
Basically, the idea is to be able to accomplish something like this:
![use-case](https://user-images.githubusercontent.com/4624850/28749485-53db39d6-749f-11e7-9fbd-ceed64714f74.gif)

I believe a drag start event will be required as well apart from click and drop.

**Comment by tiberiuzuld** [comment]
Hi @leandroz ,
Will have the bug fixed soon.

Drag start is from outside the grid.
For example `<div draggable="true">Drag me</div` and if you drop the element on to the grid the callback will be called.

Thanks

**Comment by tiberiuzuld** [comment]
Hi @leandroz ,

Fixed in v3.7.1

Thanks

**Comment by leandroz** [comment]
You are the best @tiberiuzuld , bug is fixed and no longer happening :)

I think I won't be able to implement what I need with the current events.
Basically is like selecting a part of the grid, like a spreadsheet. I will take a look at the code and see if I can do it myself, it would be a mouse down listener, store the grid position until a mouse up, check where the mouse up happened and emit an event with the grid item where the movement started and the grid item where the selection finished, then the user can do whatever they need to with the event.

There should be a flag to enable or disable it for sure.

**Comment by tiberiuzuld** [comment]
Hi @leandroz ,
I see so on mouse down to register position and on mouse up to calculate the size of it.
Like selecting multiple cells in excel.
That will be a bit more complicate to make but it is possible.
Will think about this week and if I have time in the weekend maybe will implement it.

Thanks

**Comment by leandroz** [comment]
All good @tiberiuzuld , I was thinking about the API, it needs to allow setting a maxRows and maxCols to allow for example selecting only a row, this may be accomplished the same as the resizable option too.
I believe that using RxJS would be a good option, let me know how I can help :)

**Comment by tiberiuzuld** [comment]
Hi @leandroz ,
Added in v3.9.0.

Hmm forgot to add maxRows and maxCols for it ... 
It will respect the maxItemRows and maxItemCols from gridster options.
But this I don't think it will satisfy your needs ... 
Will try to add the options this week.

Thanks

**Comment by leandroz** [comment]
Hi @tiberiuzuld , thanks for the implementation!, once you add those options it will be perfect!

I found a bug in the implementation of `getValidItemFromEvent`, basically this part:

```
var x = e.pageX - this.el.scrollLeft - this.el.offsetLeft;
 var y = e.pageY - this.el.scrollTop - this.el.offsetTop;
```

You are using pageX and pageY, so if the user has fixed content like a navbar and then using margin or padding over the parent element the coordinates are wrong because are taken from the top left of the document and not from the Gridster component.

I changed the implementation to use `getBoundingClientRect ` and works ok.

```
var bounds = this.el.getBoundingClientRect();
var x = e.clientX - this.el.scrollLeft - bounds.left;
var y = e.clientY - this.el.scrollTop - bounds.top;
```

**Comment by tiberiuzuld** [comment]
Hi @leandroz ,
Added the max options in v3.10.0
Fixed the issue with position in scrolled content. 
Let me know if you find any more issues :)
Thanks,

**Comment by leandroz** [comment]
Hi @tiberiuzuld !, it works great!, thanks again for adding it :)

**Comment by viethien** [comment]
@leandroz @tiberiuzuld 

How can I get position (x,y) of mouse when I drag component to dashboard?
I am stuck in how to call method getValidItemFromEvent.

Thanks

**Comment by CollinGraf314** [comment]
You can get the x, y coordinates of the item (in rows and columns) from one of the emptyCell callback functions:
https://tiberiuzuld.github.io/angular-gridster2/emptyCell


If you want to get the x, y coordinates of the mouse itself, you can get them from any MouseEvent:
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX
https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientY
