### ISSUE TITLE
Recalculate position after item size programmatically changed

### ISSUE THREAD

**Issue by rychagov** [tiberiuzuld/angular-gridster2#921]
Dear developers,
we have some problems with positioning items if we change their sizes.
Example:
We have toggleable widgets - each widget contains button for minimizing widget to 1 row height and restoring to previous height after next click.

After minimizing widget next widgets moved top (we set appropriate compactType).

Problem:
After restoring widgets default size next widgets don’t move and overlay expanded widgets. But if I resize widget then grid recalculates.

Possible solution:
Add api method to recalculate overlapping widgets as it works if user change item by resizing.

**Comment by rychagov** [comment]
Solution found here: https://tiberiuzuld.github.io/angular-gridster2/api
There is GridsterPush service to help with pushing items.

**Comment by navneetagrwl** [comment]
I am dynamically changing cols from 1 to 2 for particular item, but it not pushing the adjacent item to next row, instead the first item is hiding below the 2. Do you have any suggestion how to fix this?
