### ISSUE TITLE
Emit event after the grid is loaded.

### ISSUE THREAD

**Issue by NoMercy235** [tiberiuzuld/angular-gridster2#95]
The `initCallback` property of the gridster options is currently firing when the grid is initialized. Would it be possible to emit another event (e.g. similar to `ngAfterContentInit`) after the items are also initialized? 

The context in which I require this is the following:
- The grid itself needs to have a fixed height and cannot resize based on it's content
- I'm binding the `height` attribute of the host element and update it on content initialization and item resize. I will always be using a `fixed` grid type so the binding shouldn't make any issues.

I've had a look in the implementation and couldn't come up with a way to do this, since the `GridsterComponent` doesn't seem to know about the number of `GridsterItemComponent`s. If it's not possible, please close this.

**Comment by tiberiuzuld** [comment]
Hi @NoMercy235 ,
If you have a fixed height for the grid then why not limit it from the css from the start ?
Maybe I don't understand the issue.

Yes the `GridsterComponent` doesn't know how many it has since some user may lazy load them. So then it does not know when to fire the init after all loaded.
You could use the `initCallback` from the `GridsterItem` with a `_.debounce` and you will get notified when all are initialized.

Let me know if this solves your issue.

Thanks

**Comment by NoMercy235** [comment]
Hello @tiberiuzuld !

Let's consider the following example: we have 3 widgets on the dashboard: A (needs 570px height) on the first row, B (needs 190px height) again on the first row and C (needs 500px height) on the second row. currently I am suming the height of all widgets and bind the result to the parent element 
```
<div [style.height.px]='computedHeight'> 
   gridster
</div>
```
But I don't need is the extra 190px from widget B since it's on the same row with widget A and it's smaller than it.

What I currently do is something among those lines:
```javascript
// after I compute how many rows and columns an item should have
let height = 0;
elements.map(el => {
    height += el.rows * options.fixedRowHeight;
});
```

If I use the `itemInitCallback` function, I can compute the height based on the widgets added, but this seems to trigger the `expression has changed after it was checked` error, perhaps because after extracting the result, I immediately bind it to the parent element. If there was a way to get the first `onContentInit` event, I thought that I could use that to find out the initial height and then update it whenever there is a resize or add/remove action.

Another thing I've tried was to create a `Subject` object and subscribe to it on `ngInit` method in the component. And then, on `itemInitCallback`, have the height of the item pushed to the stream. But again, this triggers the `expression has changed...` error.

Also, I've tried extending the `*ngFor` directive to send an event using the `EventEmitter` when it reaches the last element, but i still don't have a way to get the height of the items unless I use jQuery or something similar and reference each object so that I can access them from the component. This adds a lot of overhead so I'm thinking that it's not worth the trouble.

The first method (the one where I get the height of all widgets and bind it to the parent element) currently works. It's just that if the user has many widgets on a single row, there'll be extra height added for no reason. However, this is not that much of a problem, since we'll have a limit on how many widgets per row one can use. Therefore, it's not a problem if the `onContentInit` event thing can't be done. I just thought it'd be worth asking. ^.^

**Comment by tiberiuzuld** [comment]
Hi @NoMercy235 ,
So if I understand correctly you want the height of the gridster to be 
`gridster.rows * options.fixedRowHeight`

You can obtain that by doing some creative css. Look [here](https://github.com/tiberiuzuld/angular-gridster2/issues/80) for some inspiration on how you can do that.

Or from the `this.options.initCallback(this)`. `this` is the gridster component which has a property rows.
Will have the total number of rows from the grid. You need to update when it changes somehow.

Let me know if this helps you.

Thanks

**Comment by NoMercy235** [comment]
Hey @tiberiuzuld ,

Yes, that would be the functionality I'd need. And I'd like to update it dynamically. I'm not sure if Angular provides something like the `$watch` function of AngularJs. I might try making an observable out of it and see if I can react to changes somehow. 

Sadly, I don't have the code in front of me right now, but I will take a look tomorrow morning  (also try the CSS method) and let you know what's the result.

Thank you for your time!

**Comment by NoMercy235** [comment]
Morning @tiberiuzuld !

The CSS solution you've provided worked for me as well. ^.^ Thank you for pointing it out.

Have a nice day!
