### ISSUE TITLE
Display Grid lines & outerMargin = false

### ISSUE THREAD

**Issue by nlgi** [tiberiuzuld/angular-gridster2#96]
Hi,

It seems that grid lines don't fit to outerMargin = false.

With outerMargin : OK
![Image of outerMargin true](https://img4.hostingpics.net/pics/47179624ok.png)

Without outerMargin : Still margin
![Image of outerMargin false](https://img4.hostingpics.net/pics/58308277ko.png)

You can see it on https://tiberiuzuld.github.io/angular-gridster2/angular/ 

Many thanks for your work!

**Comment by tiberiuzuld** [comment]
Hi @nlgi ,
Yep bug, will fix it this week.

Thanks,

**Comment by tiberiuzuld** [comment]
Hi @nlgi ,
Fixed in v3.9.0

Thanks
