### ISSUE TITLE
Transclusion using ng-content

### ISSUE THREAD

**Issue by HoplaGeiss** [tiberiuzuld/angular-gridster2#97]
I would like to pass components to each widget of my dashboard. To do this I thought I would use ng-content. Please look at the example bellow:

```
// app.component.ts
<app-dashboard [widgets]='widgets'>
  <div class='widget0'>0</div>
  <div class='widget1'>1</div>
</app-dashboard>
```

```
// dashboard.component.ts
<gridster [options]='options'>
  <div *ngFor='let widget of widgets'>
    <gridster-item [item]='widget'>
      <ng-content></ng-content>
    </gridster-item>
  </div>
</gridster>
```

With this code I would expect both widgets to have `0` and `1` as content.. However only the last widget has content. See attached screenshot.
![screenshot from 2017-08-02 14-51-13](https://user-images.githubusercontent.com/5755785/28876729-0da63632-7792-11e7-9a8d-2e6efb75b5c1.png)

Is that a bug from gridster ?

**Comment by tiberiuzuld** [comment]
Hi @HoplaGeiss ,
The `<gridster-item>` already has `<ng-content>` see [here](https://github.com/tiberiuzuld/angular-gridster2/blob/master/src/lib/gridsterItem.html)
You just put your component in:
```html
<gridster-item>
     <my-component></my-component>
</gridster-item>
```

**Comment by HoplaGeiss** [comment]
You can close the issue! Thanks :)
