### ISSUE TITLE
api resize callback

### ISSUE THREAD

**Issue by jasonhendee** [tiberiuzuld/angular-gridster2#98]
Can you provide a callback hook for the **this.options.api.resize()** function, to be called after all debounced activities take place?

**Comment by tiberiuzuld** [comment]
Hi @jasonhendee ,
You have `this.options.itemReisizeCallback` you can set.
You will get called every time a item resized.
Or  have a debounce in it to do your thing after the whole dashboard has resized.

To add a callback directly in the api call is tricky.

Let me know if you really need that.

Thanks

**Comment by jasonhendee** [comment]
@tiberiuzuld, understand. Thanks for your quick reply. I'll play around with a couple of alternative approaches, and let you know.

**Comment by jasonhendee** [comment]
@tiberiuzuld, I found a workaround for my issue. Thanks!
