### ISSUE TITLE
Handlebars between blocks

### ISSUE THREAD

**Issue by StephenPaul** [tiberiuzuld/angular-gridster2#99]
Hi, I think this library is superb and feels really solid. Fantastic job.
I hope I'm not missing something in your API, but would it be too much effort to add the following: 

I would like to hover my cursor over a margin between tiles. If I drag into the space another tile occupies, that tile will try to shrink as much as possible

![image](https://user-images.githubusercontent.com/17923511/28957663-2e908d22-78f3-11e7-988a-ef7ce1045495.png)

From a code perspective, its as if you're resizing two (or more) adjacent tiles simultaneously.

From an API perspective, perhaps you can add a `sharedEdgesAdjustable: boolean` option (or something more eloquent)

**Comment by tiberiuzuld** [comment]
Hi @StephenPaul ,
Thanks :)

There is no such thing in the current API.
Only thing similar is push but will push the adjacent tile not resize it.
It can be added, a bit complicated but possible.

Will try to add it this month.

Thanks

**Comment by StephenPaul** [comment]
Awesome, no pressure :) I really appreciate the effort put into this.

**Comment by tiberiuzuld** [comment]
Hi @StephenPaul ,
Implemented the feature in v3.11.0
Had some spare time :)

Wish all issues are so detailed. 

Thanks

**Comment by StephenPaul** [comment]
Wow that was faster than I expected :) thanks so much, exactly what I needed
